import type { Industry } from '../experience-data';

export const autoIndustries: Industry[] = [
  /* ------------------------------------------------------------------ */
  /* 1. AUTO DEALERSHIP                                                  */
  /* ------------------------------------------------------------------ */
  {
    id: 'dealership',
    label: 'Auto Dealership',
    emoji: '\u{1F697}',
    category: 'Auto',
    tagline: 'Every lead captured, every test drive booked, every follow-up relentless.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Overnight lead digest',
        description: 'AI compiles all leads from AutoTrader, Cars.com, website forms, and Facebook Marketplace that came in after hours.',
        aiResponse: 'Overnight leads: 7 new inquiries. 3 from AutoTrader (2 SUVs, 1 truck), 2 from your website (sedan and EV), 1 Facebook Marketplace (used Civic), 1 walk-in who left a card. I\'ve scored them by urgency: 2 are hot (actively comparing dealers), 3 warm, 2 cold. First responses sent to all 7.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 7 },
      },
      {
        time: '7:30 AM',
        title: 'Morning briefing for sales team',
        description: 'AI sends each salesperson their daily agenda: scheduled test drives, follow-up calls, and hot leads assigned to them.',
        aiResponse: 'Good morning, team! Today\'s schedule: Jake \u2014 2 test drives (10 AM RAV4, 2 PM F-150) + follow up with the Hendersons (financing approved yesterday). Maria \u2014 3 hot leads assigned, delivery prep for the Garcia family\'s new Accord. Tom \u2014 2 trade-in appraisals + Saturday event prep. Lot inventory: 142 vehicles.',
        channel: 'whatsapp',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:45 AM',
        title: 'Facebook lead responds \u2014 test drive booked',
        description: 'The Civic lead from Facebook replies asking to see the car. AI qualifies them and books a test drive.',
        aiResponse: 'Hi Mike! Great news \u2014 the 2022 Honda Civic EX (Silver, 18K miles, $22,900) is still available. I can have it washed and ready for you to test drive. How about today at 11 AM or 1 PM? We\'re at 4500 Auto Mall Drive. Also, if you have a trade-in, feel free to bring it and we\'ll give you a free appraisal on the spot.',
        channel: 'facebook',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Test drive follow-up with personalized recap',
        description: 'Customer test-drove a RAV4 yesterday but didn\'t commit. AI sends a tailored follow-up with the details they discussed.',
        aiResponse: 'Hi Sarah! It was great meeting you yesterday. I know the 2024 RAV4 XLE in Cavalry Blue checked a lot of boxes \u2014 especially the cargo space for your hiking gear and the fuel efficiency you asked about (35 MPG combined). The out-the-door price we discussed was $34,200 with your trade-in. I can hold that price through Friday. Any questions I can answer?',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Trade-in valuation completed',
        description: 'Customer brings in their car for trade-in. AI pulls market data from KBB, Edmunds, and auction results.',
        aiResponse: 'Trade-in assessment for 2020 Toyota Camry SE (42K miles, Clean title, Good condition): KBB trade-in: $19,200\u2013$20,800. Edmunds: $19,500. Recent auction comparables: $19,800 avg. Recommended offer: $19,500 (leaves $2,100 margin on resale at $21,600). Vehicle history clean \u2014 one owner, all service records.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 400 },
      },
      {
        time: '1:00 PM',
        title: 'Financing application assisted',
        description: 'Customer wants to finance their purchase. AI helps gather documents and pre-qualifies them.',
        aiResponse: 'Hi Carlos! Great \u2014 let\'s get your financing started. I\'ve sent you our secure application link. Based on the info you\'ve shared (credit score 720+, $5K down payment on a $32,000 vehicle), you\'ll likely qualify for rates around 4.9\u20135.9% APR over 60 months. That puts your estimated payment at $512\u2013$528/month. I\'ll have final numbers once the application is submitted.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Competitor inventory scan',
        description: 'AI browses competing dealership websites to compare pricing on similar vehicles in your market.',
        aiResponse: 'Competitor check on 2024 RAV4 XLE: Your price $34,200 vs. Lakeside Toyota $34,800 vs. Metro Auto $33,900 (but higher mileage demo). You\'re competitively positioned. Also spotted: Metro is running a "0% for 48 months" promo on Camrys \u2014 might pull traffic. Consider matching or offering a value-add (free maintenance package).',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '3:45 PM',
        title: 'Service reminder upsell',
        description: 'AI identifies 45 customers due for service and sends reminders with a special offer to drive them back to the dealership.',
        aiResponse: 'Batch sent: 45 service reminders to customers due for oil change / tire rotation. Each one personalized with their vehicle details and mileage estimate. Included a "$49.95 Express Service Special" coupon. Added: "While you wait, check out the latest models \u2014 your current vehicle\'s trade-in value has never been higher." Last campaign brought 3 trade-in conversations.',
        channel: 'sms',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 600 },
      },
      {
        time: '5:00 PM',
        title: 'Google review response',
        description: 'A customer left a 5-star review praising the no-pressure sales experience. AI responds warmly.',
        aiResponse: 'Thank you so much, Henderson family! We\'re thrilled you had a great experience with Jake. Enjoy your new Accord \u2014 it\'s a fantastic choice for your growing family. Don\'t forget, your first oil change is on us! We look forward to seeing you for your 5,000-mile service. Welcome to the family!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '6:30 PM',
        title: 'Weekend sale event promoted',
        description: 'AI creates and schedules social media ads for Saturday\'s sales event with inventory highlights.',
        aiResponse: 'Weekend event content ready: "Spring Sales Spectacular" \u2014 Facebook ad carousel with 6 featured vehicles (priced from $18,900), Instagram story countdown, and email blast to 2,800 past customers and leads. Targeting: 25\u201355, within 30 miles, auto intenders. Budget: $350 across platforms. Last event drove 34 showroom visits.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '8:00 PM',
        title: 'Daily sales dashboard',
        description: 'AI compiles the day\'s performance: units sold, leads generated, test drives, and pipeline value.',
        aiResponse: 'Today\'s scorecard: 2 units sold ($67,100 total, $4,200 gross profit). 7 new leads (all contacted). 4 test drives conducted. Pipeline: 12 active deals worth $385,000. Trade-ins: 1 acquired ($19,500 Camry). Financing: 1 application submitted. Saturday event: 62 RSVPs so far. Strong day!',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 PM',
        title: 'After-hours lead captured and nurtured',
        description: 'Someone fills out a "Get a Quote" form on your website at 9 PM. AI responds instantly instead of waiting until morning.',
        aiResponse: 'Hi Amanda! Thanks for your interest in the 2024 Honda CR-V Hybrid. Great choice \u2014 it\'s our most popular model right now. The Sport trim you selected is $36,800 MSRP. With current incentives, I can offer $35,200 plus tax and fees. We have 3 in stock in the colors you\'d love. Can I schedule a test drive? We\'re open tomorrow 9 AM\u20138 PM.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Answers vehicle questions with full spec knowledge, pricing, and availability across every channel instantly.',
      memory: 'Remembers what each customer test-drove, their budget, trade-in details, financing preferences, and family needs.',
      proactive: 'Morning briefings with lead assignments, test drive schedules, and pipeline updates for each salesperson.',
      bookings: 'Schedules test drives, trade-in appraisals, delivery appointments, and service visits automatically.',
      leads: 'Captures leads from AutoTrader, Cars.com, Facebook, website \u2014 scores by urgency and assigns to sales team.',
      revenue: 'Service reminder campaigns with trade-in upsell, lapsed customer re-engagement, and financing follow-ups.',
      reputation: 'Responds to every Google and Facebook review within the hour with personalized, on-brand messaging.',
      content: 'Creates sales event promotions, new arrival spotlights, and customer delivery celebration posts.',
      reporting: 'Daily sales dashboards, pipeline tracking, lead conversion rates, and gross profit analysis.',
      browser: 'Scans competitor pricing daily, pulls trade-in valuations from KBB/Edmunds, and monitors auction results.',
    },
    stats: {
      messagesPerDay: 95,
      bookingsPerWeek: 28,
      monthlySavings: 6500,
      responseTime: '< 1 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Auto dealerships need instant lead response, competitive intelligence, and relentless follow-up. The Executive tier adds real-time competitor browsing, trade-in market analysis, and after-hours voice/lead handling.',
  },

  /* ------------------------------------------------------------------ */
  /* 2. AUTO REPAIR / BODY SHOP                                          */
  /* ------------------------------------------------------------------ */
  {
    id: 'autorepair',
    label: 'Auto Repair / Body Shop',
    emoji: '\u{1F529}',
    category: 'Auto',
    tagline: 'Every estimate instant, every repair tracked, every customer updated automatically.',
    dayEvents: [
      {
        time: '6:30 AM',
        title: 'Daily bay schedule and parts check',
        description: 'AI reviews today\'s repair appointments, checks if all ordered parts have arrived, and flags any delays.',
        aiResponse: 'Good morning! Today: 6 vehicles in bays. Bay 1: Brake job (2018 Camry, parts ready). Bay 2: Transmission flush (2020 F-150). Bay 3: AC repair (2019 Civic, compressor arrived yesterday). Bay 4: Body work (2022 Accord, insurance approved). Bays 5\u20136: Open for walk-ins. One delay: CV axle for the 2017 Subaru backordered \u2014 ETA Thursday.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:45 AM',
        title: 'Customer texts photo of warning light',
        description: 'A worried customer sends a photo of their dashboard with a check engine light and asks what to do.',
        aiResponse: 'Hi Rosa! Thanks for sending the photo. That\'s a check engine light \u2014 it could be anything from a loose gas cap to a sensor issue. It\'s not an emergency, but I\'d recommend bringing it in for a diagnostic scan ($49.95, applied toward any repair). We have an opening today at 2 PM or tomorrow at 9 AM. The scan takes about 30 minutes. Which works better for you?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 AM',
        title: 'Insurance estimate submitted',
        description: 'Body shop estimate for a fender-bender is completed. AI formats it and submits to the insurance company.',
        aiResponse: 'Estimate for 2022 Honda Accord (Claim #INS-44821) submitted to State Farm: Front bumper replacement ($890), fender repair and paint ($620), headlight assembly ($340), labor ($480). Total: $2,330. Photos attached showing all damage points. I\'ve also sent the customer a copy and scheduled the repair for next Monday pending approval.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Repair status update sent to customer',
        description: 'Brake job is halfway done. AI proactively updates the customer so they\'re not wondering.',
        aiResponse: 'Hi James! Quick update on your Camry \u2014 we\'re halfway through the brake job. Front pads and rotors are replaced, now working on the rears. Everything looks good so far \u2014 no surprises. Estimated completion: 1:30 PM today. Total remains $485 as quoted. I\'ll text you the moment it\'s ready for pickup.',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:45 AM',
        title: 'Walk-in customer estimate',
        description: 'Someone walks in with a squealing belt. AI helps the front desk generate an instant estimate.',
        aiResponse: 'Serpentine belt replacement for 2016 Toyota Highlander: Part cost $42, labor $95 (approximately 45 minutes). Total: $137. If you\'d like, we can inspect the tensioner too \u2014 if it\'s worn, replacing it now saves a repeat visit ($65 additional). We can start in about an hour if you can wait, or schedule for tomorrow morning. What would you prefer?',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '1:00 PM',
        title: 'Parts sourced and price compared',
        description: 'AI searches multiple parts suppliers to find the best price on a transmission solenoid needed for tomorrow\'s job.',
        aiResponse: 'Transmission solenoid pack for 2019 Ford F-150: AutoZone $189 (in stock, pickup today), O\'Reilly $195 (in stock), RockAuto $142 (ships tomorrow, arrives Friday). OEM from Ford: $267 (2-day delivery). Recommendation: AutoZone at $189 for same-day availability since the customer is scheduled tomorrow. Shall I order it?',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 78 },
      },
      {
        time: '2:30 PM',
        title: 'Diagnostic results explained to customer',
        description: 'Rosa\'s check engine scan is complete. AI explains the results in plain language and provides options.',
        aiResponse: 'Hi Rosa! Diagnostic results: Code P0420 \u2014 your catalytic converter efficiency is below threshold. Two options: 1) Replace the catalytic converter ($1,100 parts + labor, fixes it permanently) or 2) Try a catalytic converter cleaner first ($35, works about 40% of the time for early-stage issues). Your car is safe to drive in the meantime. What would you prefer?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:45 PM',
        title: 'Service reminder batch sent',
        description: 'AI identifies 30 customers overdue for oil changes or scheduled maintenance and sends reminders.',
        aiResponse: 'Service reminders sent to 30 customers overdue for maintenance. Each message personalized with their vehicle, last service date, and mileage estimate. Example: "Hi Tom, your 2021 RAV4 is likely at 45,000 miles \u2014 time for a transmission fluid exchange and tire rotation. Book this week and get a free multi-point inspection." 15% of last month\'s batch converted to appointments.',
        channel: 'sms',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 340 },
      },
      {
        time: '4:30 PM',
        title: 'Vehicle ready \u2014 pickup notification',
        description: 'Brake job complete, quality-checked. AI notifies the customer with the final invoice.',
        aiResponse: 'Hi James! Great news \u2014 your Camry is ready! Brake job complete on all four wheels: new pads and rotors, brake fluid flushed, all torqued to spec. Total: $485 as quoted (no surprises). We\'re open until 6 PM today, or you can pick up tomorrow 7:30 AM\u20136 PM. We accept card, cash, or financing if preferred. Drive safely!',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:30 PM',
        title: 'Google review request sent',
        description: 'AI sends a review request to today\'s completed customers with a direct link to Google.',
        aiResponse: 'Review requests sent to 3 completed customers: James (brake job), Rosa (diagnostic), and the walk-in belt replacement. Each message is personalized: "Hi James, thanks for trusting us with your Camry\'s brakes! If you have 30 seconds, a quick Google review helps us a lot. [Direct link]." Last month\'s review campaign generated 14 new 5-star reviews.',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '6:30 PM',
        title: 'End-of-day shop report',
        description: 'AI compiles daily revenue, completed jobs, and tomorrow\'s schedule.',
        aiResponse: 'Shop report: 5 jobs completed ($2,840 revenue). Parts cost: $620, labor billed: $1,480. Gross margin: 62%. Tomorrow: 4 scheduled appointments (transmission job, body work continuation, 2 oil changes). Parts status: all in stock. One pending insurance approval (State Farm estimate). Walk-in belt job was a same-day win \u2014 $137 incremental.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'After-hours emergency call handled',
        description: 'A stranded motorist calls after hours asking if you can tow and fix their car tomorrow.',
        aiResponse: 'I\'m sorry to hear you\'re stranded! We open at 7:30 AM tomorrow and I\'ve reserved Bay 5 for your vehicle. For towing, I\'d recommend ABC Towing at (555) 234-5678 \u2014 they work with us regularly and offer our customers a $20 discount. Just tell them you\'re having it towed to our shop. I\'ll have a technician ready to diagnose first thing. What\'s the make and model so I can prep?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'bookings', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Explains diagnostic codes in plain language, provides transparent estimates, and sends proactive repair status updates.',
      memory: 'Tracks every vehicle\'s complete service history, recalls, maintenance schedule, and customer preferences.',
      proactive: 'Morning bay schedules with parts status, maintenance reminders for overdue customers, and warranty expiration alerts.',
      bookings: 'Schedules repair appointments, manages bay allocation, and sends pickup notifications when vehicles are ready.',
      leads: 'Converts walk-in estimates into booked jobs, follows up on pending approvals, and captures emergency after-hours leads.',
      revenue: 'Service reminder campaigns, seasonal maintenance offers, and fleet account management.',
      reputation: 'Requests reviews after every completed job, responds to feedback, and tracks rating trends.',
      reporting: 'Daily shop reports with revenue, margins, bay utilization, and parts cost analysis.',
      browser: 'Compares parts pricing across suppliers, checks OEM part numbers, and monitors availability.',
      voice: 'Handles after-hours emergency calls, provides towing recommendations, and books next-day appointments.',
      workflow: 'Submits insurance estimates, tracks claim approvals, and manages the repair-to-payment pipeline.',
    },
    stats: {
      messagesPerDay: 55,
      bookingsPerWeek: 24,
      monthlySavings: 3800,
      responseTime: '< 2 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Auto repair shops thrive on trust and repeat business. The Manager tier handles reputation management, service reminder campaigns, and reporting that keeps bays full and margins healthy.',
  },

  /* ------------------------------------------------------------------ */
  /* 3. CAR RENTAL / DETAILING                                           */
  /* ------------------------------------------------------------------ */
  {
    id: 'carrental',
    label: 'Car Rental / Detailing',
    emoji: '\u{1F699}',
    category: 'Auto',
    tagline: 'Every vehicle tracked, every booking optimized, every return seamless.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Fleet status and availability report',
        description: 'AI scans the entire fleet: which cars are out, which are due back, which need cleaning or maintenance.',
        aiResponse: 'Fleet status: 18 of 25 vehicles rented. 3 returns expected today (10 AM, 2 PM, 5 PM). 4 vehicles ready for new rentals. 2 in detailing bay (ready by 9 AM). 1 due for oil change (Civic #12, 4,800 miles since last). Today\'s reservations: 5 pickups scheduled. No conflicts \u2014 fleet allocation is clean.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Detailing appointments confirmed',
        description: 'AI sends reminders to today\'s detailing customers with drop-off instructions and estimated completion times.',
        aiResponse: 'Good morning! Reminders sent to 4 detailing clients: 1) Mike T. \u2014 Full detail, 8 AM drop-off, ready by 3 PM. 2) Sarah L. \u2014 Interior only, 9 AM, ready by noon. 3) Corporate fleet \u2014 3 vehicles, noon drop-off, next-day pickup. 4) Linda K. \u2014 Ceramic coating, 10 AM, 2-day turnaround. All confirmed via SMS.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 4 },
      },
      {
        time: '8:45 AM',
        title: 'Walk-in rental inquiry handled',
        description: 'Someone walks in needing a car for the weekend. AI checks availability and provides options instantly.',
        aiResponse: 'Welcome! For this weekend (Friday\u2013Sunday), here are your options: Economy (Nissan Versa) $39/day, Mid-size (Toyota Camry) $55/day, SUV (Honda CR-V) $72/day. All include 200 miles/day, insurance available at $18/day. The Camry is our most popular weekend rental. I just need a valid license and credit card to get you started. Which one interests you?',
        channel: 'system',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Vehicle return processed',
        description: 'Customer returns a rental. AI generates the final invoice with mileage, fuel, and damage inspection checklist.',
        aiResponse: 'Return processed for Rental #R-2847 (2024 Camry, John P.): Rented 3 days, 342 miles driven (within 600-mile allowance). Fuel: returned at 3/4 tank (rented full) \u2014 fuel charge $18. No damage noted. Total: $165 (3 days) + $54 (insurance) + $18 (fuel) = $237. Charged to Visa ending 4421. Receipt emailed. Vehicle queued for cleaning.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Corporate fleet inquiry',
        description: 'A local company emails asking about monthly fleet rental rates for their sales team.',
        aiResponse: 'Hi Patricia! Thank you for the inquiry. For a fleet of 8 vehicles (mid-size sedans) on a monthly basis, we offer: $1,200/vehicle/month with unlimited mileage, insurance included, and free monthly detailing. That\'s $9,600/month total. We also include roadside assistance and same-day vehicle swaps if one needs maintenance. Shall I prepare a formal proposal with delivery and pickup logistics?',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:45 PM',
        title: 'Detailing before-and-after posted',
        description: 'AI photographs a completed full detail and posts a before/after carousel on Instagram.',
        aiResponse: 'Posted! Before/after carousel of Mike\'s 2021 BMW X5 full detail: swirl marks removed, leather conditioned, engine bay cleaned, ceramic sealant applied. 6-photo carousel with close-up comparisons. Caption: "From daily driver to showroom shine. Book your transformation \u2014 link in bio." Hashtags: #AutoDetailing #CeramicCoating #Satisfying. Last detail post got 890 views.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '2:00 PM',
        title: 'Rental extension request',
        description: 'A customer calls wanting to extend their rental by 3 days. AI checks availability and processes the extension.',
        aiResponse: 'Hi Lisa! No problem \u2014 I can extend your Nissan Rogue rental through Friday. Your daily rate stays at $62. Updated total for the extension: $186 (3 days). I\'ll charge the same card on file. Your new return date is Friday, March 20th by 5 PM. If plans change, just let me know at least 24 hours in advance. Enjoy the rest of your trip!',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Seasonal pricing optimization',
        description: 'AI analyzes booking patterns and recommends pricing adjustments for the upcoming spring break period.',
        aiResponse: 'Spring break analysis (March 21\u2013April 5): Last year, fleet was 100% booked by March 15th. Current bookings: 65% reserved. Recommendation: Increase rates 20% starting next week (economy $47/day, mid-size $66, SUV $86). This matches market rates \u2014 Enterprise is already at $72 for mid-size. Projected additional revenue: $3,400 over the 2-week period.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 3400 },
      },
      {
        time: '4:30 PM',
        title: 'Vehicle maintenance scheduled',
        description: 'AI flags vehicles due for scheduled maintenance and coordinates with the mechanic.',
        aiResponse: 'Maintenance due: Civic #12 needs oil change (4,800 miles). Corolla #8 tire rotation at 10,000 miles. Camry #3 brake inspection recommended (slight squeal noted in return inspection). I\'ve scheduled all three for tomorrow morning when they\'re not reserved. Estimated downtime: 3 hours total. No impact on bookings.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
      },
      {
        time: '5:30 PM',
        title: 'Google review from detailing customer',
        description: 'Mike leaves a 5-star review about his BMW detail. AI responds and thanks him.',
        aiResponse: 'Thank you, Mike! We\'re so glad the X5 looks showroom-fresh again. The ceramic coating will keep that shine for months \u2014 just remember to hand wash only for the first two weeks. We\'d love to see you again for a maintenance wash in a few months. Enjoy driving that beautiful ride!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Daily revenue and fleet utilization report',
        description: 'AI compiles rental revenue, detailing income, and fleet utilization metrics.',
        aiResponse: 'Daily report: Rental revenue: $1,420 (5 active rentals billed). Detailing revenue: $680 (3 details completed + 1 ceramic coating). Fleet utilization: 72% (18/25 vehicles). Average daily rate: $58. Detailing queue tomorrow: 4 vehicles. Corporate proposal pending ($9,600/month potential). Spring break bookings on track.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Online booking confirmed after hours',
        description: 'A traveler landing tomorrow morning books a rental through your website at 10 PM. AI confirms instantly.',
        aiResponse: 'Hi Derek! Your reservation is confirmed: 2024 Toyota Camry, pickup March 12th at 8 AM, return March 16th at 5 PM. 4 days at $55/day = $220 + optional insurance ($18/day). Our office is at 1200 Airport Blvd \u2014 5 minutes from the terminal. I\'ll have the car washed and waiting. Bring your driver\'s license and the credit card used for booking. Safe travels!',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles rental inquiries, extension requests, and pricing questions across phone, email, and WhatsApp.',
      memory: 'Tracks every renter\'s history, preferences (car type, insurance choices), and corporate account details.',
      proactive: 'Morning fleet status with returns, maintenance needs, and reservation conflicts. Alerts when vehicles are overdue.',
      bookings: 'Manages reservations, returns, extensions, and detailing schedules with automatic confirmations.',
      leads: 'Captures corporate fleet inquiries, event rental requests, and converts walk-ins into bookings.',
      revenue: 'Dynamic seasonal pricing, corporate rate negotiations, and upsell recommendations (insurance, upgrades).',
      reputation: 'Responds to Google and Yelp reviews, sends post-rental review requests, and tracks satisfaction trends.',
      content: 'Creates detailing before/after posts, fleet showcase videos, and seasonal promotion graphics.',
      reporting: 'Daily fleet utilization, revenue per vehicle, detailing throughput, and seasonal demand forecasting.',
      voice: 'Handles phone calls for extensions, roadside issues, and after-hours booking confirmations.',
      workflow: 'Coordinates maintenance schedules with bookings to minimize fleet downtime.',
    },
    stats: {
      messagesPerDay: 60,
      bookingsPerWeek: 32,
      monthlySavings: 4200,
      responseTime: '< 2 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Car rental and detailing businesses need tight scheduling, dynamic pricing, and visual marketing. The Manager tier handles seasonal optimization, content that showcases quality, and reputation management.',
  },
];
