/* ================================================================
   EDUCATION & CHILDCARE INDUSTRIES
   4 industries, 12 unique day-events each (6 AM – 10 PM)
   ================================================================ */

import type { Industry } from '../experience-data';

/* ------------------------------------------------------------------ */
/* 1. DAYCARE / AFTER SCHOOL                                           */
/* ------------------------------------------------------------------ */

const daycare: Industry = {
  id: 'daycare',
  label: 'Daycare / After School',
  emoji: '👶',
  category: 'Education & Childcare',
  tagline: 'Every parent informed, every child accounted for, every spot filled — while you focus on the kids.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning Briefing Delivered',
      description: 'System wake-up: 34 children expected today, 2 absent notifications received overnight, 1 new enrollment inquiry, medication reminder for Lily R. at 10 AM.',
      aiResponse: 'Sent the director a briefing with today\'s headcount, flagged the medication schedule for Lily, confirmed the 2 absences with parents, and noted the open spot in the toddler room from a last-minute cancellation.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:15 AM',
      title: 'Parent Drop-Off Questions',
      description: 'WhatsApp from Amanda G.: "Hi, is there nut-free snack today? Oliver has his allergy appointment at 3 PM so I\'ll need early pickup. Also, did you get the updated emergency contact form I sent?"',
      aiResponse: 'Confirmed today\'s snack is nut-free (apple slices and cheese crackers), noted Oliver\'s 3 PM early pickup in the system, and verified the emergency contact form was received and filed. Sent Amanda a confirmation with the day\'s activity schedule.',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'New Enrollment Inquiry',
      description: 'Email from Jennifer W.: "We just moved to the area and are looking for full-time daycare for our 2-year-old starting next month. Do you have openings? What are your rates?"',
      aiResponse: 'Checked availability: 2 spots open in the toddler room. Sent Jennifer a welcome packet with rates ($1,450/month full-time), daily schedule, curriculum overview, and licensing info. Offered a tour this Thursday at 10 AM and added her to the CRM with a Day 3 follow-up.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Instagram Photo Day Promo',
      description: 'Scheduled content: Photo day is next Friday and 8 parents haven\'t signed consent forms yet.',
      aiResponse: 'Created an Instagram post announcing photo day with a carousel of last year\'s adorable shots. Sent personalized WhatsApp reminders to the 8 parents missing consent forms with a direct link to the digital form. 5 forms returned within the hour.',
      channel: 'instagram',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'messages', increment: 8 },
    },
    {
      time: '10:30 AM',
      title: 'Sick Child Pickup Coordination',
      description: 'Toddler room reports that Emma S. has a low-grade fever. Both parents are listed as emergency contacts.',
      aiResponse: 'Called mom (Sarah S.) first — went to voicemail. Immediately texted dad (Kevin S.) who confirmed pickup in 20 minutes. Sent a summary of Emma\'s symptoms, temperature readings, and the center\'s return policy (24 hours fever-free). Updated the room roster.',
      channel: 'phone',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 3 },
    },
    {
      time: '12:00 PM',
      title: 'Google Review Response',
      description: 'New 5-star Google review from "Rachel T.": "Best daycare in town! My daughter loves Ms. Maria and the activities are so creative. Worth every penny."',
      aiResponse: 'Responded within 15 minutes: "Thank you so much, Rachel! We adore having little Sophia with us — Ms. Maria says she\'s become quite the artist! We love creating memorable experiences for our kiddos." Flagged the review to the director as a morale booster.',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:30 PM',
      title: 'After-School Program Waitlist',
      description: 'SMS from David L.: "Any spots open in the after-school program for my 7-year-old? He needs pickup from Lincoln Elementary at 3:15."',
      aiResponse: 'Checked the after-school roster: currently full with 20 kids but 1 family gave notice for end of month. Added David\'s son to the waitlist at position 2, sent the program details and pricing ($650/month), and set a reminder to notify him when the spot opens.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '3:00 PM',
      title: 'Pickup Time Parent Updates',
      description: 'Afternoon pickup rush: 18 parents arriving between 3–5 PM. Three parents haven\'t confirmed who is picking up today.',
      aiResponse: 'Sent automated pickup confirmations to all parents with today\'s activity summary and photos. Individually messaged the 3 unconfirmed parents to verify authorized pickup persons. All confirmed within 15 minutes — one sent Grandma with the correct PIN.',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 18 },
    },
    {
      time: '4:30 PM',
      title: 'Overdue Tuition Follow-Up',
      description: 'Three families are past due on monthly tuition — one at 7 days, one at 14 days, one at 30 days.',
      aiResponse: 'Sent tiered reminders: friendly first notice to the 7-day family, firmer reminder with payment link to the 14-day family, and flagged the 30-day account to the director with a suggested phone conversation. Total outstanding: $4,150.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 4150 },
    },
    {
      time: '6:00 PM',
      title: 'Summer Camp Registration Launch',
      description: 'Summer camp registration opens tomorrow. Need to notify 120 current and former families.',
      aiResponse: 'Drafted and scheduled an email blast with the summer camp brochure, weekly themes, pricing, and early-bird discount deadline. Created matching Instagram stories and a WhatsApp broadcast for current parents. Set up an auto-responder for registration questions.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:00 PM',
      title: 'Staff Schedule Coordination',
      description: 'Lead teacher Ms. Maria requests Friday off. Need coverage for the pre-K room with proper ratios.',
      aiResponse: 'Checked staff availability: Ms. Janet can cover the pre-K room Friday, maintaining the required 1:10 ratio. Sent Janet a shift offer via text, she confirmed in 8 minutes. Updated the staff schedule and notified the director. Sent parents a heads-up about the substitute.',
      channel: 'sms',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'messages', increment: 2 },
    },
    {
      time: '9:30 PM',
      title: 'End-of-Day Summary Report',
      description: 'All children picked up, facility locked. Time for the daily wrap-up.',
      aiResponse: 'Daily report sent: 34 children attended, 0 incidents, 1 new enrollment inquiry (Jennifer W.), 5 consent forms collected, $4,150 in outstanding tuition flagged, and 1 waitlist addition. Tomorrow\'s headcount: 33 (Oliver absent for doctor). Morning staff: confirmed.',
      channel: 'whatsapp',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
  ],
  capabilityExamples: {
    communication: 'Answers parent questions about snacks, schedules, and policies across WhatsApp, SMS, and email simultaneously',
    memory: 'Remembers every child\'s allergies, emergency contacts, authorized pickup persons, and behavioral notes',
    proactive: 'Morning briefing with headcount, medication schedules, absences, and open enrollment spots',
    bookings: 'Manages enrollment waitlists, tour scheduling, and after-school program registrations',
    leads: 'Pre-qualifies new enrollment inquiries with age, schedule needs, and budget before tours',
    revenue: 'Chases overdue tuition with tiered reminders at 7, 14, and 30 days automatically',
    reputation: 'Responds to every Google and Facebook review within the hour with warm, personalized replies',
    content: 'Creates photo-day announcements, summer camp promotions, and weekly activity highlights for social media',
    reporting: 'Nightly report with attendance, incidents, financials, and next-day prep summary',
    team: 'Coordinates staff substitutions and shift swaps while maintaining required child-to-teacher ratios',
  },
  stats: {
    messagesPerDay: 72,
    bookingsPerWeek: 8,
    monthlySavings: 4200,
    responseTime: '< 45 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Daycares need proactive parent communication plus revenue recovery and reputation management — the Manager tier automates tuition follow-ups, review responses, and content creation on top of daily operations.',
};

/* ------------------------------------------------------------------ */
/* 2. TUTORING / LEARNING CENTER                                       */
/* ------------------------------------------------------------------ */

const tutoring: Industry = {
  id: 'tutoring',
  label: 'Tutoring / Learning Center',
  emoji: '🎓',
  category: 'Education & Childcare',
  tagline: 'Every session booked, every parent updated, every student matched — so you can focus on teaching.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning Schedule Briefing',
      description: 'System wake-up: 18 sessions scheduled today across 6 tutors, 2 students requested subject changes, SAT prep bootcamp starts Saturday with 4 spots left.',
      aiResponse: 'Sent the center director today\'s session grid by room and tutor, flagged the 2 subject-change requests with tutor availability, and noted the SAT bootcamp needs a marketing push to fill the last 4 seats.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Parent Progress Inquiry',
      description: 'WhatsApp from Mrs. Chen: "Hi, how is Lucas doing in math? His report card comes out next week and we\'re worried about algebra. Is he improving?"',
      aiResponse: 'Pulled Lucas\'s session history: attended 8 algebra sessions, quiz scores improved from 62% to 78% over 6 weeks. Sent Mrs. Chen a summary with the upward trend, tutor notes from his last session, and recommended 2 extra sessions before the exam. Offered to book them.',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'New Student Assessment Booking',
      description: 'Email from Mark D.: "My daughter is in 9th grade and struggling with chemistry and essay writing. How do I get started? What\'s the process?"',
      aiResponse: 'Explained the 3-step onboarding: free diagnostic assessment, personalized learning plan, then matched tutoring sessions. Booked a chemistry and writing assessment for Saturday at 11 AM. Sent Mark the intake form, pricing sheet ($55/hr individual, $35/hr group), and parking info.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Session Cancellation and Backfill',
      description: 'SMS from Tyler\'s mom: "Tyler can\'t make his 4 PM math session today — basketball practice moved up. Can we reschedule to Wednesday?"',
      aiResponse: 'Rescheduled Tyler to Wednesday 4 PM with the same tutor (Mr. Davis). Checked the waitlist for the now-open Tuesday 4 PM slot — offered it to Aisha K. who\'s been requesting extra math time. Aisha\'s mom confirmed within 10 minutes. Slot filled.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '11:30 AM',
      title: 'Facebook Inquiry About Group Rates',
      description: 'Facebook message from a homeschool co-op organizer: "We have 6 kids ages 10-13 who need weekly science tutoring. Do you offer group discounts?"',
      aiResponse: 'Quoted the group rate: $35/student/session for groups of 4+, saving $120/week vs. individual sessions. Proposed a Wednesday 1 PM recurring slot in the large classroom. Sent the co-op a course outline for middle-school science and a registration link for all 6 students.',
      channel: 'facebook',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:00 PM',
      title: 'SAT Bootcamp Promotion Push',
      description: 'Only 4 spots remaining in Saturday\'s SAT prep bootcamp. Need to fill them before Friday cutoff.',
      aiResponse: 'Sent targeted emails to 23 parents of 10th and 11th graders who previously inquired about test prep. Created an Instagram story with a countdown timer and student testimonials. Texted 8 current students\' parents who hadn\'t signed up yet. 2 spots booked within 2 hours.',
      channel: 'email',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'bookings', increment: 2 },
    },
    {
      time: '2:30 PM',
      title: 'Tutor Absence Coordination',
      description: 'Tutor Jessica L. messages that she has a flat tire and can\'t make her 3 PM and 4 PM reading sessions.',
      aiResponse: 'Cross-referenced tutor availability: Ms. Patel is free and qualified for reading. Texted Ms. Patel who confirmed in 5 minutes. Notified both students\' parents about the substitute tutor with her credentials. Updated the session board and room assignments.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '4:00 PM',
      title: 'Post-Session Parent Updates',
      description: 'Four tutoring sessions just ended. Parents expect progress notes after every session.',
      aiResponse: 'Collected session notes from each tutor and sent personalized summaries to all 4 parents: topics covered, homework assigned, areas of improvement, and what\'s planned for next session. Included each student\'s running progress score.',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '5:30 PM',
      title: 'Google Review — Negative',
      description: 'New 2-star Google review from "Karen P.": "My son has been going for 3 months and his grades haven\'t improved. We expected better results for the price."',
      aiResponse: 'Flagged to the director with context: Karen\'s son Jake attended only 6 of 12 scheduled sessions (50% attendance). Drafted a professional response acknowledging the concern, noting the attendance gap gently, and offering a free reassessment to adjust his learning plan. Posted within 20 minutes.',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:00 PM',
      title: 'Re-Engagement of Lapsed Students',
      description: 'AI identifies 14 students who completed their initial package but haven\'t re-enrolled in 30+ days.',
      aiResponse: 'Sent personalized re-engagement messages to all 14 families: referenced each student\'s last progress snapshot, highlighted upcoming exam seasons, and offered a "welcome back" 10% discount on the next 8-session package. 3 parents responded same evening.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 1650 },
    },
    {
      time: '8:30 PM',
      title: 'Competitor Program Research',
      description: 'A new Kumon center opened 2 miles away. Director wants to understand their offering.',
      aiResponse: 'Browsed the competitor\'s website: they offer math and reading only, $150/month unlimited worksheets, no 1-on-1 tutoring. Compiled a comparison sheet highlighting our advantages — personalized instruction, broader subjects, qualified tutors with degrees. Suggested a "Why Choose Us" social media campaign.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:45 PM',
      title: 'Weekly Analytics Report',
      description: 'End of day Wednesday — midweek analytics due.',
      aiResponse: 'Midweek report: 42 sessions delivered (vs. 38 last week), 92% attendance rate, 3 new student enrollments, $4,620 revenue booked, 1 negative review handled, SAT bootcamp at 80% capacity. Recommended: push SAT promo one more day and add a Friday makeup session block.',
      channel: 'whatsapp',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
  ],
  capabilityExamples: {
    communication: 'Answers parent questions about subjects, pricing, and schedules across WhatsApp, Facebook, and email instantly',
    memory: 'Tracks every student\'s progress, quiz scores, attendance history, and tutor notes across all sessions',
    proactive: 'Morning briefing with session grid, tutor assignments, cancellations, and enrollment pipeline',
    bookings: 'Books assessments, reschedules sessions, fills cancelled slots from the waitlist automatically',
    leads: 'Pre-qualifies new inquiries with grade level, subjects, and goals before scheduling diagnostic assessments',
    revenue: 'Re-engages lapsed students with personalized messages referencing their last progress snapshot',
    reputation: 'Responds to every review with context — knows attendance rates and progress data for informed replies',
    content: 'Creates test-prep promotions, student success spotlights, and seasonal enrollment campaigns',
    reporting: 'Midweek and end-of-week reports with session counts, revenue, attendance rates, and enrollment pipeline',
    browser: 'Researches competitor programs, pricing, and reviews to inform positioning and marketing strategy',
  },
  stats: {
    messagesPerDay: 58,
    bookingsPerWeek: 24,
    monthlySavings: 2800,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'operator',
  recommendationReason: 'Tutoring centers thrive on fast booking responses and session management — the Operator tier handles scheduling, parent updates, and lead capture, which covers the core daily workflow.',
};

/* ------------------------------------------------------------------ */
/* 3. MUSIC / DANCE SCHOOL                                             */
/* ------------------------------------------------------------------ */

const musicSchool: Industry = {
  id: 'music-school',
  label: 'Music / Dance School',
  emoji: '🎵',
  category: 'Education & Childcare',
  tagline: 'Every recital organized, every lesson filled, every student inspired — while you focus on the music.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Daily Studio Briefing',
      description: 'System wake-up: 22 lessons scheduled today, Studio B reserved for dance rehearsal 4–7 PM, piano recital in 9 days — 3 students haven\'t confirmed attendance.',
      aiResponse: 'Sent the school director today\'s lesson schedule by room and instructor, flagged the recital no-confirms for follow-up, and noted that guitar instructor Ryan is out tomorrow so 4 lessons need rescheduling.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Trial Lesson Inquiry',
      description: 'Instagram DM from @proud_mama_jessica: "My 6-year-old loves singing along to everything! Do you offer voice lessons for young kids? She\'s never had formal training."',
      aiResponse: 'Explained the junior voice program for ages 5–8: starts with rhythm, pitch matching, and fun song repertoire. Offered a free 30-minute trial lesson this Saturday at 10 AM with Miss Rachel, the children\'s vocal coach. Sent a link to the registration form and a short video of a kids\' recital.',
      channel: 'instagram',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:00 AM',
      title: 'Lesson Rescheduling Cascade',
      description: 'Guitar instructor Ryan confirmed he\'ll be absent tomorrow. 4 students need rescheduling: 2 beginners, 1 intermediate, 1 advanced.',
      aiResponse: 'Checked substitute availability: Mr. Torres can take the 2 beginners and the intermediate student. The advanced student (Alex, grade 8 prep) needs Ryan specifically — offered Alex a Thursday makeup slot. Texted all 4 families with new times, 3 confirmed within 30 minutes.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '10:30 AM',
      title: 'Recital RSVP Chase',
      description: 'Piano recital is in 9 days. 3 performing students haven\'t confirmed attendance, and 12 family RSVP forms are still outstanding.',
      aiResponse: 'Called the 3 unconfirmed students\' parents — 2 confirmed, 1 has a conflict and will perform in the makeup recital. Sent the 12 outstanding families a personalized RSVP reminder with the recital program, parking info, and a note about their child\'s piece. 8 RSVPs received by noon.',
      channel: 'phone',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 12 },
    },
    {
      time: '12:00 PM',
      title: 'Facebook Review Response',
      description: 'New 5-star Facebook review from "The Nguyen Family": "Our twins have been taking piano for 6 months and they can already play simple songs! The teachers are patient and the recitals are so well organized."',
      aiResponse: 'Replied within 10 minutes: "We love watching Lily and James grow as pianists! Their teacher Mrs. Kim says they\'re naturals — especially their duet at last month\'s recital. Thank you for being part of our music family!" Shared the review on the school\'s Instagram story.',
      channel: 'facebook',
      capability: 'reputation',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:30 PM',
      title: 'Summer Intensive Registration Opens',
      description: 'Summer dance and music intensives start registration today. Need to notify current families and promote externally.',
      aiResponse: 'Sent early-access registration emails to all 85 current families with a 48-hour priority window before public enrollment. Created an Instagram carousel with workshop descriptions, instructor bios, and last summer\'s highlight reel. Scheduled a Facebook event and a WhatsApp broadcast for current parents.',
      channel: 'email',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'messages', increment: 85 },
    },
    {
      time: '3:00 PM',
      title: 'Makeup Lesson Coordination',
      description: 'WhatsApp from Tom P.: "Hey, Mia missed her ballet class last week due to the flu. Can she do a makeup class? She doesn\'t want to fall behind for the spring show."',
      aiResponse: 'Checked the ballet makeup schedule: open slot in Saturday\'s 11 AM class with Miss Devane, same level as Mia\'s regular class. Booked it and sent Tom a confirmation with the spring show rehearsal schedule so Mia stays on track. Noted the absence was illness-related — no charge for the makeup.',
      channel: 'whatsapp',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '4:30 PM',
      title: 'Student Progress Milestone',
      description: 'System detects that violin student Sarah M. has completed her Grade 5 ABRSM prep — all practice logs and mock exams show ready status.',
      aiResponse: 'Notified Sarah\'s parents with a congratulatory message and her progress trajectory. Recommended registering for the June ABRSM exam (deadline in 3 weeks). Sent the exam registration link, fee breakdown, and offered 2 extra mock-exam sessions at no charge. Parents registered the same day.',
      channel: 'email',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '6:00 PM',
      title: 'Dance Rehearsal Room Conflict',
      description: 'Hip-hop class and contemporary rehearsal both need Studio B at 6 PM. Double booking detected.',
      aiResponse: 'Checked room availability: moved hip-hop to Studio A (slightly smaller but adequate for the 8-student class). Notified hip-hop instructor DeShawn and the students via group text. Updated the room booking board and added a note to prevent future conflicts on Tuesdays.',
      channel: 'system',
      capability: 'workflow',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 PM',
      title: 'Overdue Tuition Reminders',
      description: 'Monthly billing cycle: 6 families are past due — total outstanding $3,780.',
      aiResponse: 'Sent graduated reminders: 3 families at 7 days received a friendly nudge with a payment link, 2 families at 14 days received a firmer notice, and 1 family at 30 days was flagged to the director. Noted that the 30-day family previously mentioned financial difficulty — suggested a payment plan option.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 3780 },
    },
    {
      time: '9:00 PM',
      title: 'Recital Program Design',
      description: 'Piano recital program needs to be finalized: 16 performers, order of appearance, song titles, and bios.',
      aiResponse: 'Compiled the recital program from the enrollment database: organized performers by level (beginners first, advanced last), pulled each student\'s bio from their profile, matched song titles from teacher lesson logs, and generated a printable PDF program. Sent to the director for approval.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 PM',
      title: 'Overnight Inquiry Handling',
      description: 'Late-night messages from 3 parents asking about fall enrollment and 1 adult student asking about evening jazz piano slots.',
      aiResponse: 'Auto-responded to all 4 inquiries with relevant info: sent the 3 parents fall enrollment dates and pricing, and sent the adult student the evening class schedule with open slots. Queued all for the morning briefing with lead scores. Confirmed receipt so no message goes unanswered.',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 4 },
    },
  ],
  capabilityExamples: {
    communication: 'Answers inquiries about instruments, age requirements, trial lessons, and recital info across Instagram, WhatsApp, and Facebook',
    memory: 'Tracks each student\'s grade level, exam readiness, practice logs, and recital participation history',
    proactive: 'Morning briefing with lesson schedule, room bookings, instructor absences, and upcoming recital deadlines',
    bookings: 'Manages lesson scheduling, makeup classes, instructor substitutions, and recital RSVPs automatically',
    leads: 'Converts Instagram inquiries into trial lesson bookings with age-appropriate program recommendations',
    revenue: 'Sends tiered tuition reminders and suggests payment plans for families with financial difficulties',
    reputation: 'Responds to reviews highlighting specific student achievements and teacher quality within the hour',
    content: 'Creates recital announcements, summer intensive promotions, and student spotlight posts for social media',
    reporting: 'Generates recital programs, weekly enrollment reports, and attendance analytics for each class',
    workflow: 'Resolves room booking conflicts and syncs instructor schedules across studios automatically',
  },
  stats: {
    messagesPerDay: 64,
    bookingsPerWeek: 18,
    monthlySavings: 2400,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'operator',
  recommendationReason: 'Music and dance schools run on lesson scheduling, parent communication, and recital coordination — the Operator tier handles bookings, reminders, and multi-channel responses that form the daily backbone.',
};

/* ------------------------------------------------------------------ */
/* 4. COACHING / TRAINING                                              */
/* ------------------------------------------------------------------ */

const coaching: Industry = {
  id: 'coaching',
  label: 'Coaching / Training',
  emoji: '📐',
  category: 'Education & Childcare',
  tagline: 'Every client progressing, every session productive, every lead nurtured — so you focus on transforming lives.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning Pipeline Briefing',
      description: 'System wake-up: 6 coaching sessions today, 2 discovery calls scheduled, 1 client completed their 12-week program yesterday, and 3 proposal follow-ups are due.',
      aiResponse: 'Sent the coach a morning briefing with today\'s session details, prep notes for each client, the 2 discovery call profiles (researched LinkedIn and intake forms), and reminded about the 3 proposals pending response. Flagged that client Danielle hasn\'t logged her weekly homework.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:15 AM',
      title: 'Discovery Call Lead Research',
      description: 'Two discovery calls today: a startup founder looking for executive coaching, and a mid-career professional considering a career pivot.',
      aiResponse: 'Researched both prospects: Startup founder — Series A company, 15 employees, recently featured in TechCrunch, likely needs leadership scaling coaching. Career pivoter — 12 years in finance, MBA, interested in tech transition. Compiled dossiers with LinkedIn summaries, mutual connections, and suggested talking points for each call.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'Client Check-In Message',
      description: 'WhatsApp from coaching client Marcus R.: "Hey coach, I had that difficult conversation with my VP yesterday like we practiced. It went better than expected! He actually agreed to the restructure."',
      aiResponse: 'Logged the win in Marcus\'s client journal, sent a congratulatory response referencing the specific role-play from last session, and reminded him to document his reflections before Thursday\'s session. Updated his progress tracker: 4 of 5 quarterly goals now completed.',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Group Workshop Registration',
      description: 'Email from HR director at Meridian Corp: "We\'d like to enroll 8 managers in your Leadership Fundamentals workshop. What dates are available and is there a corporate rate?"',
      aiResponse: 'Checked the workshop calendar: next available cohort starts April 14 (6 Tuesdays, 2–4 PM). Sent the corporate rate ($850/person for 5+, saving $1,200 total), the syllabus, facilitator bio, and a registration link for all 8 managers. Scheduled a follow-up for Day 3.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '11:30 AM',
      title: 'Session Rescheduling Chain',
      description: 'Client Amy W. needs to move her Thursday 2 PM session. Coach also needs to block Friday afternoon for a speaking engagement.',
      aiResponse: 'Offered Amy three alternative slots: Wednesday 10 AM, Thursday 4 PM, or the following Monday 9 AM. Amy chose Wednesday 10 AM. Updated the calendar, blocked Friday 1–5 PM for the speaking engagement, and shifted one other client to morning to keep the day balanced. All confirmations sent.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '1:00 PM',
      title: 'Program Completion & Upsell',
      description: 'Client Danielle F. completed her 12-week career transition program yesterday. Time to celebrate and discuss next steps.',
      aiResponse: 'Sent Danielle a congratulatory email with her journey summary: 12 sessions completed, 3 job interviews secured, salary negotiation skills developed, and confidence score self-rated from 4/10 to 8/10. Offered the Alumni Accountability program (monthly check-ins, $297/month) and requested a testimonial. Danielle replied wanting both.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 297 },
    },
    {
      time: '2:30 PM',
      title: 'Instagram Thought Leadership Post',
      description: 'Scheduled content day: need this week\'s LinkedIn article and Instagram carousel.',
      aiResponse: 'Created a LinkedIn article on "5 Signs Your Team Is Ready for a Leadership Coach" based on the coach\'s recent client wins (anonymized). Designed an Instagram carousel summarizing the key points with engaging visuals. Drafted 3 Instagram stories with polls about leadership challenges. All scheduled for optimal engagement times.',
      channel: 'instagram',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'messages', increment: 3 },
    },
    {
      time: '4:00 PM',
      title: 'Proposal Follow-Up Sequence',
      description: 'Three coaching proposals sent last week haven\'t received responses: a startup CEO, a law firm partner, and a nonprofit director.',
      aiResponse: 'Sent personalized follow-ups to each: the CEO got a message referencing a recent funding announcement and how coaching could help scale leadership. The law firm partner received a case study about a similar firm. The nonprofit director got an ROI breakdown. Scheduled Day 7 follow-ups for any still unanswered.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 3 },
    },
    {
      time: '5:30 PM',
      title: 'Google Review Request',
      description: 'Four clients completed programs in the last 30 days but haven\'t left reviews. Current rating is 4.7 stars with 23 reviews.',
      aiResponse: 'Sent personalized review requests to all 4 clients: each message referenced their specific transformation and thanked them for the journey. Included a direct link to the Google review page. 2 clients left 5-star reviews within 3 hours — rating bumped to 4.8 stars.',
      channel: 'whatsapp',
      capability: 'reputation',
      tier: 'manager',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '7:00 PM',
      title: 'Webinar Registration Monitoring',
      description: 'Free webinar "From Manager to Leader" is tomorrow at 12 PM. Currently 47 registrations, goal is 60.',
      aiResponse: 'Sent a last-call email to the 200-person newsletter list who hadn\'t registered. Created an Instagram story with a countdown and a compelling quote from the coach. Texted 15 warm leads who expressed interest in leadership coaching but haven\'t booked. Added 9 new registrations by 9 PM — total now 56.',
      channel: 'email',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'messages', increment: 15 },
    },
    {
      time: '8:30 PM',
      title: 'Client Homework Accountability',
      description: 'Three clients haven\'t submitted their weekly reflections due today: Marcus, Amy, and new client Jordan.',
      aiResponse: 'Sent gentle accountability nudges to all 3: Marcus got a reminder referencing his VP conversation win, Amy received an encouraging note about her job search momentum, and Jordan (week 2) got a supportive check-in asking if the reflection template was clear. Marcus submitted within 20 minutes.',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 3 },
    },
    {
      time: '10:00 PM',
      title: 'Weekly Business Summary',
      description: 'End of Wednesday — midweek check-in report for the coaching business.',
      aiResponse: 'Midweek report: 14 sessions delivered ($3,360 revenue), 2 discovery calls completed (1 converted to proposal), 1 program completion with upsell ($297/month recurring), 3 proposals pending, webinar at 93% registration target, 2 new Google reviews. Cash collected this week: $5,240. Outstanding invoices: $1,800.',
      channel: 'whatsapp',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
  ],
  capabilityExamples: {
    communication: 'Handles client check-ins, homework submissions, and scheduling requests across WhatsApp, SMS, and email',
    memory: 'Maintains detailed client journals with session notes, goals, progress milestones, and personal context',
    proactive: 'Morning briefing with session prep notes, discovery call dossiers, and follow-up reminders',
    bookings: 'Manages session scheduling, rescheduling, and calendar blocking for speaking engagements',
    leads: 'Researches prospects before discovery calls and sends personalized proposal follow-ups with case studies',
    revenue: 'Converts program completions into ongoing accountability packages and chases outstanding invoices',
    reputation: 'Requests reviews from program graduates with personalized messages referencing their transformation',
    content: 'Creates LinkedIn articles, Instagram carousels, and webinar promotions from anonymized client wins',
    reporting: 'Midweek and monthly reports with revenue, session counts, conversion rates, and pipeline value',
    browser: 'Researches prospects on LinkedIn and company websites to prepare detailed discovery call dossiers',
  },
  stats: {
    messagesPerDay: 48,
    bookingsPerWeek: 14,
    monthlySavings: 3600,
    responseTime: '< 45 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Coaching businesses need lead nurturing, content creation, and revenue recovery beyond basic scheduling — the Manager tier handles proposal follow-ups, reputation management, and thought-leadership content that drive growth.',
};

/* ------------------------------------------------------------------ */
/* EXPORT                                                              */
/* ------------------------------------------------------------------ */

export const educationIndustries: Industry[] = [
  daycare,
  tutoring,
  musicSchool,
  coaching,
];
