/* ================================================================
   FOOD & HOSPITALITY INDUSTRIES
   5 industries, each with 12 unique day events, stats,
   capability examples, and a recommended tier.
   ================================================================ */

import type { Industry } from '../experience-data';

export const foodIndustries: Industry[] = [
  /* ----------------------------------------------------------------
     1. RESTAURANT / CAFE
     ---------------------------------------------------------------- */
  {
    id: 'restaurant',
    label: 'Restaurant / Cafe',
    emoji: '🍕',
    category: 'Food & Hospitality',
    tagline: 'Every table filled, every guest remembered, every review answered — while you focus on the food.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Briefing Sent',
        description: 'System wake-up: 14 reservations today, 3 special dietary requests flagged, one VIP anniversary dinner at 7 PM.',
        aiResponse: 'Sent the owner a briefing with today\'s covers, flagged the nut allergy on table 6, and reminded the kitchen about the gluten-free tasting menu for the VIP couple.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'Supplier Delivery Issue',
        description: 'Email from Coastal Seafood: "Hey, the halibut shipment is delayed until tomorrow. Sorry for the inconvenience."',
        aiResponse: 'Alerted the head chef immediately, checked the menu for halibut dishes, suggested swapping to the pan-seared salmon special, and replied to the supplier confirming receipt and requesting a credit for the delay.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 2 },
      },
      {
        time: '8:30 AM',
        title: 'Large Party Reservation',
        description: 'WhatsApp from Diana R.: "Hi! Can we book a table for 12 this Saturday for my mom\'s 70th birthday? She loves Italian food."',
        aiResponse: 'Checked Saturday availability, found the 7 PM slot open for the private dining area, offered a customized Italian tasting menu with a complimentary tiramisu cake. Booked the party and sent a confirmation with dietary preference form.',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:45 AM',
        title: 'Instagram Menu Question',
        description: 'Instagram DM from @healthy_eats_nyc: "Love your page! Do you have any vegan options? My partner is celiac too."',
        aiResponse: 'Pulled the full vegan and gluten-free menu items from the database, sent a beautifully formatted list with photos, and offered to reserve a table with the kitchen pre-notified about dietary needs.',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Returning Customer Recognition',
        description: 'Reservation request from a phone number the system recognizes as Marcus T., who visited 4 times last month and always orders the wagyu steak.',
        aiResponse: 'Greeted Marcus by name, noted he\'s a frequent guest, offered his preferred corner booth, and let the kitchen know to prep the wagyu. Added a complimentary amuse-bouche to his reservation notes as a loyalty gesture.',
        channel: 'phone',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:15 PM',
        title: 'Negative Google Review',
        description: 'New 2-star Google review from "Chris M.": "Waited 40 minutes for our food on a Tuesday night. Unacceptable for the price point."',
        aiResponse: 'Flagged the review to the owner with a suggested response. Drafted a professional apology acknowledging the wait, explained the kitchen was short-staffed, and offered a complimentary appetizer on the next visit. Response posted within 18 minutes.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:00 PM',
        title: 'Weekly Content Created',
        description: 'Scheduled content creation: this week\'s social media posts need to go out.',
        aiResponse: 'Created 5 Instagram posts for the week: Monday chef spotlight, Wednesday wine pairing reel script, Thursday behind-the-scenes kitchen prep, Friday weekend specials announcement, and Sunday brunch teaser. All scheduled with captions and hashtags.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 5 },
      },
      {
        time: '2:30 PM',
        title: 'Catering Lead Qualification',
        description: 'Email from Sarah K. at TechFlow Inc.: "We\'re looking for catering for our company retreat — about 80 people, need vegan and kosher options. Budget around $4,000."',
        aiResponse: 'Pre-qualified the lead: corporate client, 80 pax, $50/head budget is within range. Sent Sarah a curated catering menu with vegan and kosher options, included the events coordinator\'s availability for a walkthrough, and added the lead to the CRM with a follow-up scheduled for Day 3.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:30 PM',
        title: 'Dinner Rush Reservation Shuffle',
        description: 'Three walk-in requests while all tables are booked. Phone ringing with another reservation request.',
        aiResponse: 'Answered the phone call and booked a 9 PM late seating. Texted the walk-ins estimated wait times. Noticed table 4\'s reservation was a no-show at 15 minutes past, released the table, and seated the first walk-in party. Sent a polite no-show message to the original booking.',
        channel: 'phone',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 2 },
      },
      {
        time: '7:00 PM',
        title: 'VIP Anniversary Dinner Live',
        description: 'The anniversary couple from the morning briefing has arrived at table 12.',
        aiResponse: 'Sent a discreet notification to the floor manager with the couple\'s name, occasion, and wine preferences from their last visit. Coordinated with the kitchen to have the complimentary dessert plated with "Happy Anniversary" at 8:15 PM.',
        channel: 'system',
        capability: 'memory',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 PM',
        title: 'Day-End Summary Report',
        description: 'End of service: kitchen closed, last tables finishing dessert.',
        aiResponse: 'Compiled the daily report: 87 covers served, $6,340 revenue (up 12% vs. last Tuesday), average table turn 62 minutes, 4 new reservations booked for the week, 1 review responded to. Sent to the owner via WhatsApp.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Overnight Reservation Handling',
        description: 'Late-night booking requests still coming in via the website and WhatsApp.',
        aiResponse: 'Set up overnight auto-responses confirming receipt of all reservation requests. Booked 3 confirmed requests into open slots for the weekend. Queued 2 large-party inquiries for the owner to review in the morning briefing.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 3 },
      },
    ],
    capabilityExamples: {
      communication: 'Answers DMs about menu items, hours, and dietary options across WhatsApp, Instagram, and Facebook simultaneously',
      memory: 'Remembers that Marcus always orders wagyu and prefers the corner booth — greets him by name every time',
      proactive: 'Morning briefing with today\'s covers, dietary alerts, VIP flags, and low-stock warnings',
      bookings: 'Books tables, sends confirmations, handles no-shows, and fills cancelled slots from the waitlist',
      leads: 'Pre-qualifies catering inquiries with budget, headcount, and dietary needs before they reach the owner',
      revenue: 'Chases outstanding catering invoices and re-engages customers who haven\'t visited in 60 days',
      reputation: 'Responds to every Google and Yelp review within the hour with a personalized, professional reply',
      content: 'Creates weekly Instagram posts, reel scripts, and email newsletters featuring specials and chef spotlights',
      reporting: 'Nightly revenue report with covers, average spend, table turn time, and week-over-week comparison',
      browser: 'Browses competitor menus weekly and alerts when they change prices or add new dishes',
      team: 'Kitchen staff messages the AI for supplier ETAs, recipe specs, and shift swap requests',
      workflow: 'Supplier emails auto-classified, delivery delays flagged to the kitchen, credits requested automatically',
      voice: 'Answers phone reservations with full conversation — checks availability, books the table, sends confirmation',
      multiagent: 'Runs separate agents for front-of-house bookings, kitchen coordination, and marketing content',
      environment: 'Adjusts smart thermostat and lighting scenes based on reservation density and time of day',
    },
    stats: {
      messagesPerDay: 85,
      bookingsPerWeek: 42,
      monthlySavings: 3200,
      responseTime: '< 30 seconds',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Restaurants need reputation management and content creation on top of reservations — the Manager tier handles reviews, social media, and revenue recovery automatically.',
  },

  /* ----------------------------------------------------------------
     2. BAR / NIGHTCLUB
     ---------------------------------------------------------------- */
  {
    id: 'bar',
    label: 'Bar / Nightclub',
    emoji: '🍺',
    category: 'Food & Hospitality',
    tagline: 'Packed house every night, VIP tables managed, and your reputation spotless — all on autopilot.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Overnight Message Roundup',
        description: 'System scan: 23 messages received after closing — 8 VIP table requests for Friday, 6 event inquiries, 9 general questions.',
        aiResponse: 'Categorized all overnight messages by priority. Responded to the 9 general questions (hours, dress code, age policy). Queued the VIP requests and event inquiries for the morning briefing with details and spend history.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 9 },
      },
      {
        time: '7:30 AM',
        title: 'Event Inquiry Follow-Up',
        description: 'Facebook message from Priya S.: "Hey, I messaged last week about renting the rooftop for a corporate mixer on March 22. Still interested — 60 people."',
        aiResponse: 'Retrieved the original conversation from last week, confirmed the rooftop is available March 22, sent Priya the private event package with pricing for 60 guests, drink minimums, and DJ options. Scheduled a follow-up for Day 3 if no response.',
        channel: 'facebook',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 AM',
        title: 'VIP Table Booking Surge',
        description: 'Instagram DM from @jake_nightlife: "Bro need a VIP booth for 8 this Saturday. Bottle service. What\'s the minimum?"',
        aiResponse: 'Checked Jake\'s history — he\'s booked 3 times before with average $1,800 spend. Offered him Booth 3 (his usual), quoted the $1,500 bottle minimum, sent the premium bottle menu, and confirmed the booking with a deposit link.',
        channel: 'instagram',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Competitor Event Intel',
        description: 'Scheduled competitor monitoring: weekly scan of rival venues\' social media and event listings.',
        aiResponse: 'Browsed 4 competitor Instagram pages and event sites. Found that Velvet Lounge is hosting a Y2K theme night the same Saturday. Alerted the owner and suggested counter-programming with the planned hip-hop night, recommending an earlier promo push.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:00 AM',
        title: 'DJ Booking Coordination',
        description: 'WhatsApp from DJ Melo: "I can do Saturday but I need to know set times and if you want me to bring my own visuals setup."',
        aiResponse: 'Checked the Saturday event schedule, confirmed DJ Melo for 11 PM - 2 AM, informed him the venue has its own LED wall so no visuals needed. Sent the load-in time, parking pass info, and sound check schedule. Updated the event run sheet automatically.',
        channel: 'whatsapp',
        capability: 'team',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Event Promo Content',
        description: 'Saturday\'s event needs promotion — only 3 days out and ticket sales are at 40%.',
        aiResponse: 'Created an Instagram story sequence and a feed post with the DJ lineup, VIP booth availability, and early-bird pricing. Drafted a WhatsApp broadcast to the 340-person VIP list with a personalized invite. Scheduled all posts for 6 PM peak engagement.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '2:00 PM',
        title: 'Google Review Response',
        description: 'New 1-star Google review from "Anonymous": "Bouncer was rude and wouldn\'t let us in even though we had a reservation. Never coming back."',
        aiResponse: 'Flagged to the owner as urgent. Cross-referenced reservation records to identify the likely guest. Drafted a response apologizing for the experience, explaining the venue\'s entry policy, and offering a direct contact number to resolve the issue. Owner approved and it was posted within 22 minutes.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Inventory Reorder Alert',
        description: 'System detected: Tito\'s vodka stock below reorder threshold (6 bottles remaining, weekend projected need: 18).',
        aiResponse: 'Browsed the distributor portal, checked current Tito\'s pricing across two suppliers, placed the reorder for 2 cases at the better price. Also flagged that Casamigos is running low and added it to the order. Total: $890, within approved budget.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 45 },
      },
      {
        time: '6:00 PM',
        title: 'Reservation Confirmations Sent',
        description: '28 reservations and 4 VIP booth bookings on the books for tonight.',
        aiResponse: 'Sent personalized SMS confirmations to all 32 bookings with arrival time, dress code reminder, and parking info. Identified 3 bookings that hadn\'t confirmed — sent a follow-up asking to confirm or release. Two confirmed, one cancelled, and the slot was offered to the waitlist.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 32 },
      },
      {
        time: '8:00 PM',
        title: 'Door List Live Management',
        description: 'Door staff texting about guest list issues: "There\'s a group of 6 saying they\'re on the list but I only see 4 under that name."',
        aiResponse: 'Pulled the original booking — confirmed 4 guests under that name but found a follow-up message from the booker adding 2 more that wasn\'t updated on the door list. Corrected the list instantly and sent the updated count to the door team.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 2 },
      },
      {
        time: '9:30 PM',
        title: 'Revenue Tracking Mid-Night',
        description: 'Peak hours underway — owner wants a pulse check on tonight\'s numbers.',
        aiResponse: 'Compiled a live snapshot: 186 guests through the door, 4/4 VIP booths occupied, bar revenue at $4,200 (ahead of last Friday by 15%), 12 bottle service orders placed. Sent the summary to the owner\'s WhatsApp with a note that the rooftop is at 90% capacity.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Lapsed VIP Re-Engagement',
        description: 'System identified 14 VIP customers who haven\'t visited in 45+ days.',
        aiResponse: 'Sent personalized WhatsApp messages to all 14 VIPs referencing their last visit and offering a complimentary bottle upgrade on their next booking. Three responded within the hour to book for next weekend.',
        channel: 'whatsapp',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'bookings', increment: 3 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles dress code questions, age policy, and event details across Instagram, WhatsApp, and Facebook at 2 AM',
      memory: 'Knows Jake always books Booth 3 with Casamigos and has spent $12K lifetime — treats him like the VIP he is',
      proactive: 'Morning roundup of overnight messages sorted by priority: VIP requests first, general questions auto-answered',
      bookings: 'Manages VIP booth reservations, guest lists, bottle service pre-orders, and door list updates in real time',
      leads: 'Qualifies private event inquiries by headcount, budget, and date — sends packages before the owner wakes up',
      revenue: 'Re-engages lapsed VIPs with personalized offers referencing their last visit and favorite bottle',
      reputation: 'Responds to negative reviews about door policy within 20 minutes with context from the actual reservation records',
      content: 'Creates event promo content, story sequences, and WhatsApp broadcasts to the VIP list for every weekend',
      reporting: 'Live mid-night revenue snapshot: door count, booth occupancy, bar sales, and capacity percentage',
      browser: 'Monitors competitor event listings and scans distributor portals for the best bottle pricing',
      team: 'Coordinates DJ set times, load-in schedules, and sends door staff the final guest list before open',
      workflow: 'Distributor invoices auto-filed, stock levels tracked, and reorders triggered when thresholds are hit',
      voice: 'Answers phone calls about tonight\'s event — covers, dress code, bottle minimums — books the table on the spot',
      multiagent: 'Separate agents for door management, VIP concierge, and event promotion running simultaneously',
      environment: 'Controls smart lighting scenes and sound levels based on capacity and time of night',
    },
    stats: {
      messagesPerDay: 120,
      bookingsPerWeek: 35,
      monthlySavings: 4100,
      responseTime: '< 45 seconds',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Bars and nightclubs live on reputation and event promotion — the Manager tier keeps the VIP list engaged, reviews handled, and every weekend promoted automatically.',
  },

  /* ----------------------------------------------------------------
     3. HOTEL / BNB
     ---------------------------------------------------------------- */
  {
    id: 'hotel',
    label: 'Hotel / BnB',
    emoji: '🏨',
    category: 'Food & Hospitality',
    tagline: 'Five-star guest experience from inquiry to checkout — without hiring a front desk team.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Daily Operations Briefing',
        description: 'System wake-up: 4 check-ins today, 3 check-outs, 2 special requests (late check-out, extra pillows), occupancy at 78%.',
        aiResponse: 'Sent the morning briefing to the property manager with room assignments, housekeeping priority order, and the two special requests flagged. Noted that Room 204 guest left a complaint about AC last night — maintenance alerted.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:00 AM',
        title: 'Pre-Arrival Guest Communication',
        description: 'Four guests checking in today — none have received arrival instructions yet.',
        aiResponse: 'Sent personalized pre-arrival emails to all 4 guests with check-in time, door codes, parking instructions, and local restaurant recommendations. For the honeymoon couple in Room 301, included a congratulations note and offered a complimentary bottle of prosecco.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 4 },
      },
      {
        time: '8:30 AM',
        title: 'Airbnb Booking Inquiry',
        description: 'Airbnb message from Tomoko H.: "Is the garden suite available April 12-15? We\'re traveling with a toddler — is the space child-friendly? Do you have a crib?"',
        aiResponse: 'Checked availability — garden suite is open April 12-15. Responded with confirmation, highlighted the child-friendly features (enclosed garden, baby gate available, blackout curtains), offered the crib at no extra charge, and sent the booking link with the family-friendly package pricing.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:15 AM',
        title: 'Guest Complaint Resolution',
        description: 'WhatsApp from Room 204 guest Elena V.: "The air conditioning still isn\'t working properly. It\'s really warm in here and I couldn\'t sleep well last night."',
        aiResponse: 'Apologized to Elena, confirmed that maintenance was already dispatched (from the morning briefing flag). Offered to move her to Room 208 (same category, confirmed AC working). Elena accepted the move. Coordinated housekeeping to prepare 208 and arranged her belongings transfer. Added a complimentary breakfast to her stay.',
        channel: 'whatsapp',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Check-Out Review Request',
        description: 'Three guests checking out this morning — all had smooth stays according to interaction history.',
        aiResponse: 'Sent personalized thank-you messages to all 3 guests via their preferred channel. Included a direct link to leave a Google review with a note referencing their specific stay highlights. One guest had mentioned loving the breakfast — the message mentioned the chef\'s recipe page.',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '12:00 PM',
        title: 'Competitor Rate Monitoring',
        description: 'Scheduled weekly rate comparison for the next 30 days across competing properties.',
        aiResponse: 'Browsed Booking.com and Airbnb for 6 competing properties within 2 miles. Found that weekend rates in the area have increased 15% due to a local festival. Recommended raising Saturday night rates by $35 and sent the owner a comparison table with screenshots.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 210 },
      },
      {
        time: '1:30 PM',
        title: 'Social Media Content Week',
        description: 'Weekly content calendar needs to be populated — property photos were taken yesterday.',
        aiResponse: 'Created 4 posts from yesterday\'s photo shoot: a carousel of the renovated patio, a reel script for the sunset view from Room 301, a guest testimonial graphic using last week\'s 5-star review, and a local area guide post. All scheduled across Instagram and Facebook.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 4 },
      },
      {
        time: '3:00 PM',
        title: 'Revenue Recovery — Abandoned Inquiry',
        description: 'System flagged: a guest inquired about a 5-night stay last week but never completed the booking. Estimated value: $1,250.',
        aiResponse: 'Sent a warm follow-up email to the guest referencing their original inquiry, mentioned that their preferred dates are still available but filling up, and offered a 10% early-booking discount. Included a one-click booking link.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 125 },
      },
      {
        time: '5:00 PM',
        title: 'Afternoon Check-In Welcome',
        description: 'The honeymoon couple just checked into Room 301. Smart lock shows the door was opened at 4:52 PM.',
        aiResponse: 'Sent a WhatsApp welcome message with Wi-Fi password, room guide, and dinner reservation suggestions. Confirmed the prosecco was placed in the room by housekeeping. Set a reminder to ask about their experience tomorrow morning.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 PM',
        title: 'Guest Concierge Request',
        description: 'WhatsApp from Room 301: "This place is amazing! Can you recommend a good seafood restaurant nearby? Somewhere romantic for our honeymoon?"',
        aiResponse: 'Recommended three romantic seafood restaurants within walking distance, ranked by guest review scores. Offered to make a reservation at the top pick. The couple chose Portofino — booked a window table for 8:30 PM and sent them walking directions.',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Weekly Performance Report',
        description: 'End of the business week — time for the owner\'s performance summary.',
        aiResponse: 'Compiled the weekly report: 89% average occupancy (up from 82% last week), $8,740 revenue, 4.8 average review score, 6 new bookings secured, one rate adjustment that yielded $420 additional revenue. Identified that midweek occupancy is lagging and suggested a Tuesday-Wednesday promo.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Overnight Guest Support Active',
        description: 'Property manager going to sleep — overnight guest requests need handling.',
        aiResponse: 'Activated overnight mode. Handled a late inquiry about early check-in tomorrow (approved and confirmed). Responded to a guest asking about checkout time. Set the smart thermostat in vacant rooms to energy-saving mode. All covered while the owner sleeps.',
        channel: 'whatsapp',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 2 },
      },
    ],
    capabilityExamples: {
      communication: 'Sends personalized pre-arrival instructions with door codes, parking info, and local tips in the guest\'s language',
      memory: 'Remembers that Elena had an AC issue last stay and proactively confirms her new room\'s climate control is working',
      proactive: 'Morning briefing with check-ins, check-outs, special requests, maintenance alerts, and occupancy rate',
      bookings: 'Handles Airbnb inquiries, direct bookings, and restaurant reservations for guests — all from one brain',
      leads: 'Captures inquiry details from every channel and follows up with personalized offers if they don\'t book',
      revenue: 'Recovers abandoned bookings with timed follow-ups and early-booking discounts worth $1,250+',
      reputation: 'Sends review requests at checkout referencing specific highlights from each guest\'s stay',
      content: 'Creates Instagram carousels, reel scripts, and guest testimonial graphics from property photos and reviews',
      reporting: 'Weekly occupancy, revenue, review scores, and rate optimization recommendations in one report',
      browser: 'Monitors competitor rates on Booking.com and Airbnb, recommends dynamic pricing adjustments',
      team: 'Housekeeping receives room priority lists and maintenance gets alerts — all coordinated by the AI',
      workflow: 'Smart lock triggers welcome messages, vacant rooms auto-switch to energy-saving mode overnight',
      voice: 'Answers property phone calls — handles availability questions, gives directions, and takes booking details',
      multiagent: 'Guest concierge agent, revenue optimization agent, and property maintenance agent running in parallel',
      environment: 'Controls smart thermostats and lighting in vacant rooms based on occupancy and check-in schedule',
    },
    stats: {
      messagesPerDay: 65,
      bookingsPerWeek: 18,
      monthlySavings: 5200,
      responseTime: '< 2 minutes',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Hotels and BnBs need 24/7 guest support, dynamic pricing, and smart property management — the Executive tier handles overnight requests, browses competitor rates, and controls smart devices automatically.',
  },

  /* ----------------------------------------------------------------
     4. BAKERY / CATERING
     ---------------------------------------------------------------- */
  {
    id: 'bakery',
    label: 'Bakery / Catering',
    emoji: '🍰',
    category: 'Food & Hospitality',
    tagline: 'Every custom order tracked, every wedding cake perfect, every wholesale client managed — automatically.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Production Schedule Briefing',
        description: 'System wake-up: 6 custom cake orders due today, 2 wholesale deliveries, 14 pre-orders for pickup, and a wedding cake tasting at 2 PM.',
        aiResponse: 'Sent the production schedule to the head baker with order details sorted by deadline. Flagged that the three-tier wedding cake for the Garcia order needs fondant flowers started by 8 AM. Confirmed delivery driver routes for the wholesale drops.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:45 AM',
        title: 'Wholesale Client Reorder',
        description: 'Email from Greenleaf Cafe: "Morning! Can we get our usual order for Thursday? 40 croissants, 30 muffins, 20 scones. Same as last week."',
        aiResponse: 'Retrieved Greenleaf\'s recurring order from memory, confirmed it matches last week\'s quantities exactly, scheduled the production for Wednesday evening, and replied with confirmation and the expected 6 AM delivery time. Auto-generated the invoice for $680.',
        channel: 'email',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Custom Cake Order Inquiry',
        description: 'Instagram DM from @bride2be_anna: "OMG your cakes are gorgeous!! I need a wedding cake for September 14 — 150 guests, thinking floral and elegant. What\'s the process?"',
        aiResponse: 'Thanked Anna, explained the custom cake process: consultation, tasting, design mockup, and deposit. Checked September 14 — it\'s available. Sent the wedding cake portfolio with pricing tiers, offered three tasting appointment slots next week, and collected her email for the detailed brochure.',
        channel: 'instagram',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:15 AM',
        title: 'Delivery Confirmation Calls',
        description: 'Two wholesale deliveries going out this morning to Greenleaf Cafe and The Brunch Spot.',
        aiResponse: 'Called both locations to confirm delivery windows. Greenleaf confirmed 10 AM, The Brunch Spot asked to push to 10:30 AM. Updated the driver\'s route accordingly and sent him the revised schedule via WhatsApp with parking instructions for both locations.',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 2 },
      },
      {
        time: '10:30 AM',
        title: 'Birthday Cake Pre-Order Rush',
        description: 'WhatsApp messages from 3 different customers wanting birthday cakes for this weekend.',
        aiResponse: 'Handled all three simultaneously: collected cake size, flavor, design preferences, and pickup times. Checked production capacity — Saturday is tight but doable with the morning shift. Booked all three, sent design confirmation images from the portfolio, and collected deposits via payment links.',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 3 },
      },
      {
        time: '12:00 PM',
        title: 'Recipe Content for Social Media',
        description: 'Scheduled content day — the bakery\'s Instagram hasn\'t posted since Tuesday.',
        aiResponse: 'Created 3 posts: a behind-the-scenes reel script of the morning croissant lamination process, a carousel of this week\'s custom cake gallery, and a poll asking followers to vote on next month\'s seasonal flavor. Drafted captions with the bakery\'s warm, personal voice.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '1:30 PM',
        title: 'Overdue Invoice Follow-Up',
        description: 'System flagged: The Brunch Spot\'s invoice from 2 weeks ago ($1,420) is still unpaid.',
        aiResponse: 'Sent a friendly payment reminder email to The Brunch Spot referencing the invoice number and amount. Noted this is their first late payment in 8 months, so kept the tone warm. Scheduled a second reminder for Day 7 if unpaid, and flagged it in the owner\'s weekly report.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 1420 },
      },
      {
        time: '2:00 PM',
        title: 'Wedding Cake Tasting Prep',
        description: 'The Garcia wedding tasting appointment is in 30 minutes — couple arriving at the bakery.',
        aiResponse: 'Sent a reminder to the head baker with the Garcia\'s preferences: vanilla bean and dark chocolate, floral design, 200 guests. Prepared a summary of their previous messages and Pinterest board references. Sent the couple a confirmation text with parking directions.',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Supplier Price Comparison',
        description: 'Butter prices have been climbing — owner asked the AI to find the best deal.',
        aiResponse: 'Browsed 3 wholesale supplier websites, compared prices for European-style butter in bulk. Found a 12% savings by switching the secondary order to Kerrygold wholesale through a different distributor. Sent the owner a comparison spreadsheet with delivery terms and minimum order quantities.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 340 },
      },
      {
        time: '6:30 PM',
        title: 'Google Review Highlight',
        description: 'New 5-star Google review from "Maria L.": "The birthday cake was absolutely stunning and delicious. My daughter was over the moon!"',
        aiResponse: 'Responded within 15 minutes thanking Maria, mentioning how much the team loved creating the unicorn design for her daughter. Shared the review on the bakery\'s Instagram story with a thank-you graphic. Added Maria to the loyalty program for a 10% discount on her next order.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Daily Production Summary',
        description: 'Kitchen closed for the day — time to reconcile orders and prep for tomorrow.',
        aiResponse: 'Compiled the daily summary: 14 orders fulfilled, 3 new custom orders booked ($2,100 total), wholesale revenue $1,680, 2 invoices sent, 1 overdue invoice flagged. Tomorrow\'s production queue: 8 custom orders including the Garcia wedding cake top tier.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Overnight Order Management',
        description: 'Website and Instagram orders continue coming in after hours.',
        aiResponse: 'Processed 4 new online pre-orders for weekend pickup. Responded to 2 Instagram DMs about custom cake availability. One inquiry is a 50-person corporate dessert platter — added it to the morning briefing as a high-value lead with full details.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'bookings', increment: 4 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles cake consultations across Instagram, WhatsApp, and email — collects flavor, size, design, and date in one flow',
      memory: 'Knows Greenleaf Cafe\'s standing order by heart and remembers that Maria\'s daughter loves unicorn designs',
      proactive: 'Morning production schedule with every order sorted by deadline, flagging anything that needs early prep',
      bookings: 'Books custom cake orders, tasting appointments, and wholesale deliveries with deposit collection built in',
      leads: 'Qualifies wedding cake inquiries by date, guest count, and design style before the first consultation',
      revenue: 'Chases overdue wholesale invoices with escalating reminders while keeping the relationship warm',
      reputation: 'Responds to 5-star reviews within minutes and turns them into Instagram story content automatically',
      content: 'Creates behind-the-scenes baking reels, custom cake carousels, and seasonal flavor polls every week',
      reporting: 'Daily production summary with order counts, revenue, bookings, and tomorrow\'s prep queue',
      browser: 'Compares wholesale butter and flour prices across supplier websites to find the best bulk deals',
      team: 'Delivery drivers get optimized routes, bakers get production schedules, all coordinated automatically',
      workflow: 'Online orders auto-processed, invoices auto-generated, and production queue updated in real time',
      voice: 'Calls wholesale clients to confirm delivery windows and handles incoming phone orders for custom cakes',
      multiagent: 'Production planning agent, wholesale account manager, and retail order agent running simultaneously',
      environment: 'Monitors walk-in cooler temperature sensors and alerts if anything goes out of range overnight',
    },
    stats: {
      messagesPerDay: 55,
      bookingsPerWeek: 28,
      monthlySavings: 3800,
      responseTime: '< 1 minute',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Bakeries juggle custom orders, wholesale accounts, and social content — the Manager tier handles invoicing, review management, and content creation while the Operator handles order flow.',
  },

  /* ----------------------------------------------------------------
     5. FOOD TRUCK
     ---------------------------------------------------------------- */
  {
    id: 'foodtruck',
    label: 'Food Truck',
    emoji: '🥗',
    category: 'Food & Hospitality',
    tagline: 'Know where to park, what to prep, and who\'s coming — before you even fire up the grill.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Location & Prep Briefing',
        description: 'System wake-up: Today\'s spot is the downtown tech park (permit confirmed). Weather: 72F sunny. Predicted foot traffic: high (Tuesday lunch rush). Pre-orders: 11.',
        aiResponse: 'Sent the morning briefing with location details, expected demand forecast based on historical Tuesday data at this spot, and the 11 pre-order details sorted by pickup time. Recommended prepping extra chicken bowls — they sold out by 12:30 last Tuesday here.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:00 AM',
        title: 'Event Booking Request',
        description: 'Email from Rachel at Bloom Marketing: "We have an outdoor company picnic on April 5 for 120 people. Would love to have your truck there. What\'s the pricing for a private event?"',
        aiResponse: 'Pre-qualified the lead: corporate event, 120 pax, outdoor venue. Sent Rachel the private event package with per-person pricing, menu customization options, and the minimum commitment. Included photos from the last corporate event. Scheduled a follow-up call for Thursday.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Pre-Order Surge on Instagram',
        description: 'Instagram story about today\'s location drove 8 new pre-orders in 45 minutes. DMs flooding in.',
        aiResponse: 'Processed all 8 pre-orders: collected name, order, and pickup time for each. Sent confirmations with the pickup window and a map pin for today\'s exact spot. Updated the prep sheet with the additional quantities. Total pre-orders now at 19.',
        channel: 'instagram',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 8 },
      },
      {
        time: '9:30 AM',
        title: 'Returning Customer Greeting',
        description: 'WhatsApp from a number recognized as Derek P., who orders the Korean BBQ bowl every Tuesday.',
        aiResponse: 'Greeted Derek by name, asked if he\'d like his usual Korean BBQ bowl with extra kimchi. Derek confirmed and asked to add a drink. Order placed for 12:15 PM pickup. Added the spicy mayo on the side — his preference from 3 visits ago.',
        channel: 'whatsapp',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:45 AM',
        title: 'Location Announcement Post',
        description: 'Time to post today\'s location for the lunch crowd — the post should go out 1 hour before service starts.',
        aiResponse: 'Posted to Instagram, Facebook, and the WhatsApp broadcast list: today\'s location with Google Maps pin, the daily special (mango habanero chicken bowl), and pre-order instructions. Used the high-performing post format that got 340 engagements last week.',
        channel: 'facebook',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '12:30 PM',
        title: 'Lunch Rush Live',
        description: 'Peak lunch hour — line is 15 people deep. Three more WhatsApp pre-order pickups incoming.',
        aiResponse: 'Sent ETAs to the 3 incoming pre-order pickups so they don\'t wait in line. Responded to 4 new WhatsApp messages asking "are you still there?" with the location and estimated wait time. Posted an Instagram story of the line with the caption "Get here before we sell out!"',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 7 },
      },
      {
        time: '2:00 PM',
        title: 'Post-Lunch Review Request',
        description: 'Lunch service wrapped up — 94 meals served. Several regulars were in line today.',
        aiResponse: 'Sent personalized review request texts to the 11 customers who pre-ordered, thanking them and including a direct Google review link. Worded each one slightly differently based on what they ordered. Two reviews came in within the hour — both 5 stars.',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 11 },
      },
      {
        time: '3:30 PM',
        title: 'Festival Application Submitted',
        description: 'Owner mentioned wanting to apply for the Spring Street Food Festival next month.',
        aiResponse: 'Browsed the festival\'s website, found the vendor application form, and pre-filled it with the truck\'s details, menu, insurance info, and photos. Sent the completed draft to the owner for review. Application deadline is March 20 — set a reminder for March 18.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Tomorrow\'s Location Strategy',
        description: 'Wednesday\'s location hasn\'t been decided yet. Two permits are available: brewery district or university campus.',
        aiResponse: 'Analyzed historical sales data for both locations on Wednesdays. Brewery district averages 72 meals (higher ticket), university campus averages 104 meals (lower ticket but higher volume). Cross-referenced with weather forecast (rain likely) — recommended the brewery district since it has covered seating nearby. Owner confirmed.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:30 PM',
        title: 'Staff Schedule Coordination',
        description: 'WhatsApp from Carlos (line cook): "Hey boss, I can\'t do Thursday. Family thing. Can someone cover?"',
        aiResponse: 'Checked the team schedule — Thursday has two staff confirmed. Asked Maria (backup cook) via WhatsApp if she can cover Carlos\'s shift. Maria confirmed within 20 minutes. Updated the schedule, notified Carlos, and sent the owner a summary of the swap.',
        channel: 'whatsapp',
        capability: 'team',
        tier: 'executive',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '9:00 PM',
        title: 'Daily Sales Report',
        description: 'Truck is cleaned and parked for the night — time for the numbers.',
        aiResponse: 'Daily report: 94 meals served, $1,680 revenue (best Tuesday this month), 19 pre-orders (up from 12 last Tuesday), food cost 28%, average ticket $17.87. Korean BBQ bowl was the top seller at 34 units. Chicken bowls sold out by 12:45 PM as predicted.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Supply Order for Thursday',
        description: 'Based on tomorrow and Thursday\'s projected sales, ingredients need to be ordered.',
        aiResponse: 'Calculated ingredient needs based on Wednesday and Thursday forecasts. Generated a supply list: 40 lbs chicken thighs, 20 lbs short rib, 15 lbs rice, produce and sauces. Sent the order to the regular supplier via their portal and confirmed a 6 AM Thursday delivery. Total: $620, within weekly budget.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 620 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles pre-orders, location questions, and wait-time updates across Instagram, WhatsApp, and SMS during the rush',
      memory: 'Knows Derek gets Korean BBQ with extra kimchi and spicy mayo on the side every Tuesday at 12:15',
      proactive: 'Morning briefing with location, weather, foot traffic prediction, pre-order count, and prep recommendations',
      bookings: 'Processes pre-orders from Instagram DMs with name, order, and pickup time — sends confirmation with map pin',
      leads: 'Qualifies private event and festival inquiries by headcount, date, and budget before the owner gets involved',
      revenue: 'Identifies slow-day locations and triggers WhatsApp broadcast offers to regulars within a 2-mile radius',
      reputation: 'Sends personalized review requests to every pre-order customer after service with a direct Google link',
      content: 'Posts daily location announcements, lunch specials, and sold-out hype stories across all platforms',
      reporting: 'Daily sales report with meal count, revenue, food cost percentage, top sellers, and sellout times',
      browser: 'Finds and pre-fills festival vendor applications, browses competitor trucks\' schedules and menus',
      team: 'Coordinates shift swaps between staff via WhatsApp and updates the schedule without bothering the owner',
      workflow: 'Auto-calculates ingredient needs from sales forecasts and places supplier orders within budget',
      voice: 'Answers phone calls about today\'s location, menu, and wait times during the lunch rush',
      multiagent: 'Location strategy agent, pre-order agent, and supply chain agent working in parallel for each day',
      environment: 'Monitors truck GPS to auto-post arrival at the day\'s location and trigger the "we\'re here" broadcast',
    },
    stats: {
      messagesPerDay: 45,
      bookingsPerWeek: 55,
      monthlySavings: 2600,
      responseTime: '< 30 seconds',
    },
    recommendedTier: 'operator',
    recommendationReason: 'Food trucks thrive on fast pre-order handling and daily location announcements — the Operator tier covers communication, bookings, and morning briefings that keep the line moving.',
  },
];
