/* ================================================================
   HEALTH & WELLNESS + FITNESS INDUSTRIES
   9 industries, 12 unique day-events each
   ================================================================ */

import type { Industry } from '../experience-data';

/* ------------------------------------------------------------------ */
/* 1. SPA / MASSAGE THERAPY                                            */
/* ------------------------------------------------------------------ */

const spa: Industry = {
  id: 'spa',
  label: 'Spa / Massage Therapy',
  emoji: '💆',
  category: 'Health & Wellness',
  tagline: 'Your AI receptionist keeps the zen unbroken',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning briefing',
      description: 'Pruve scans today\'s 14 appointments, flags two therapists with back-to-back deep-tissue sessions, and surfaces a VIP anniversary couple arriving at noon.',
      aiResponse: 'Good morning! Today you have 14 sessions across 4 therapists. Heads-up: Marcus and Leila are both stacked with deep-tissue blocks — consider shifting Leila\'s 2 PM to the open 3:30 slot. Your VIP couple (the Nguyens) arrive at 12 for their anniversary hot-stone package.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:15 AM',
      title: 'Hot stone availability inquiry',
      description: 'A new client asks on WhatsApp if hot stone massage is available this Saturday afternoon.',
      aiResponse: 'Hi there! Yes, we have hot stone massage openings this Saturday at 1:00 PM and 3:30 PM. The session is 75 minutes and includes aromatherapy. Would you like me to hold one of those slots for you?',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'Couples package booking',
      description: 'An Instagram DM requests a couples massage package for a birthday surprise.',
      aiResponse: 'Happy birthday to the lucky person! 🎂 Our Couples Bliss package includes side-by-side Swedish massages (60 min), a private jacuzzi session, and champagne. Available next Saturday at 11 AM or 2 PM. Shall I book one and send a printable gift certificate?',
      channel: 'instagram',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Returning client preference recall',
      description: 'Regular client Diane texts asking for her "usual" — Pruve recalls her history.',
      aiResponse: 'Hi Diane! Your usual is the 90-minute deep-tissue with lavender oil, therapist Marcus, heated table, pressure level 8/10. I have an opening Thursday at 10 AM — same as your last three visits. Want me to lock it in?',
      channel: 'sms',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'Post-treatment aftercare instructions',
      description: 'Client who had a deep-tissue session yesterday gets automated aftercare follow-up.',
      aiResponse: 'Hi James! Hope you\'re feeling great after yesterday\'s deep-tissue session. Quick aftercare reminders: drink extra water today, avoid intense workouts for 24 hours, and a warm Epsom salt bath tonight works wonders. Any soreness should ease within 48 hours. Questions? Just reply here!',
      channel: 'whatsapp',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:45 AM',
      title: 'New lead from Facebook ad',
      description: 'Someone clicks a Facebook ad for the "First Visit 30% Off" promo and messages the page.',
      aiResponse: 'Welcome! Thanks for your interest in our first-visit special — 30% off any 60-minute massage. We offer Swedish, deep tissue, hot stone, and prenatal. Which sounds right for you? I can check availability as soon as today!',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:30 PM',
      title: 'Slow afternoon detected — flash promo',
      description: 'Pruve notices three open afternoon slots and sends a targeted offer to regulars.',
      aiResponse: 'Slow afternoon detected: 3 open slots between 2–5 PM today. Sent a "Same-Day Serenity" flash offer (15% off) to 28 regulars who haven\'t visited in 3+ weeks. Two have already replied — booking them now.',
      channel: 'system',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 180 },
    },
    {
      time: '1:45 PM',
      title: 'Google review response',
      description: 'A new 4-star Google review mentions "lovely ambiance but the music was too loud."',
      aiResponse: 'Drafted a reply: "Thank you for the kind words about our ambiance, Sarah! We appreciate the music feedback — we\'ve added individual volume controls in each room so you can set your perfect level next visit. We\'d love to welcome you back!" Shall I post this?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '3:00 PM',
      title: 'Weekly social content draft',
      description: 'Pruve prepares three Instagram posts for the week — a reel script, a tip carousel, and a promo graphic caption.',
      aiResponse: 'Here\'s your content lineup for the week: (1) Reel script: "3 Signs You Need a Massage TODAY" — 30 sec, trending audio; (2) Carousel: "Hot Stone vs Deep Tissue — Which Is Right for You?"; (3) Promo post for the new CBD oil add-on. Drafts are ready for your review.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '5:00 PM',
      title: 'Unpaid invoice follow-up',
      description: 'Corporate client has an overdue invoice for a team wellness day from 3 weeks ago.',
      aiResponse: 'Sent a friendly second reminder to Meridian Corp for Invoice #1042 ($2,400 — Team Wellness Day, Feb 18). First reminder went out on Day 7 with no response. This one includes a direct payment link and a note offering to answer any billing questions.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 2400 },
    },
    {
      time: '7:30 PM',
      title: 'After-hours phone inquiry handled by AI',
      description: 'A potential client calls after hours asking about prenatal massage availability.',
      aiResponse: 'Answered the call: "Thank you for calling Serenity Spa! We do offer prenatal massage with our certified prenatal therapist, Ana. She\'s available Tuesday and Thursday mornings. Can I take your name and number so we can text you the available times tomorrow morning?" Caller info captured — lead saved.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:30 PM',
      title: 'Competitor pricing research',
      description: 'Pruve browses three nearby spa websites to compare pricing for hot stone packages.',
      aiResponse: 'Competitor scan complete. Your hot stone 75-min is $135 — Tranquil Touch charges $140, Bliss Day Spa charges $125, Lotus Room charges $150. You\'re competitively positioned. However, Bliss Day Spa just launched a couples hot stone package at $220 — $30 less than yours. Full report saved.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Responds to massage inquiries across WhatsApp, Instagram, Facebook, and SMS simultaneously',
    memory: 'Remembers each client\'s preferred therapist, pressure level, and oil allergies',
    proactive: 'Sends post-treatment aftercare tips and flags VIP arrivals in the morning briefing',
    bookings: 'Books couples packages, sends confirmations, handles therapist-specific scheduling',
    leads: 'Captures first-visit promo leads from Facebook ads and pre-qualifies them',
    revenue: 'Fills empty afternoon slots with flash offers and chases overdue corporate invoices',
    reputation: 'Responds to Google reviews within the hour with personalized, on-brand replies',
    content: 'Drafts weekly Instagram reels, tip carousels, and promo captions',
    reporting: 'Weekly breakdown of bookings per therapist, no-show rate, and revenue by service',
    browser: 'Monitors competitor spa pricing and new package launches',
    team: 'Therapists message Pruve for schedule changes and room assignments',
    workflow: 'Syncs bookings with calendar, sends automated aftercare sequences',
    voice: 'Answers after-hours calls about availability and captures caller info',
    multiagent: 'Runs separate agents for booking management and content creation',
    environment: 'Adjusts smart lighting and music in treatment rooms via IoT controls',
  },
  stats: {
    messagesPerDay: 45,
    bookingsPerWeek: 38,
    monthlySavings: 3200,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Most spas benefit from reputation management and content marketing to drive repeat visits and fill slow periods.',
};

/* ------------------------------------------------------------------ */
/* 2. NAIL SALON / BEAUTY BAR                                          */
/* ------------------------------------------------------------------ */

const nailsalon: Industry = {
  id: 'nailsalon',
  label: 'Nail Salon / Beauty Bar',
  emoji: '💅',
  category: 'Health & Wellness',
  tagline: 'Never miss a manicure request again',
  dayEvents: [
    {
      time: '7:00 AM',
      title: 'Daily schedule overview',
      description: 'Pruve delivers the morning brief: 22 appointments across 5 nail techs, two walk-in slots open.',
      aiResponse: 'Good morning! 22 appointments today across 5 techs. Lisa has a gap at 11:30 and another at 3 PM — those are your walk-in windows. Reminder: gel polish shipment arriving today between 10–12. Three clients are due for their 3-week fill reminders.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:00 AM',
      title: 'Instagram nail art inquiry',
      description: 'A follower DMs asking if the chrome ombré design from a recent post is available.',
      aiResponse: 'Hi! Yes, the chrome ombré from our latest post is available! That\'s our Premium Gel Art service ($65, 90 minutes). Our artist Mia specializes in that technique. She has openings tomorrow at 10 AM and 2 PM. Want me to book you in?',
      channel: 'instagram',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:15 AM',
      title: 'Appointment confirmation batch',
      description: 'Pruve sends confirmation texts to all 22 clients booked for today.',
      aiResponse: 'Sent 22 appointment confirmations via SMS. So far: 18 confirmed, 2 pending response, 2 not yet opened. I\'ll follow up with the 2 pending clients in one hour if they haven\'t replied.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 22 },
    },
    {
      time: '10:00 AM',
      title: 'Allergic reaction concern',
      description: 'Client from last week messages about mild redness around her cuticles after a gel manicure.',
      aiResponse: 'Hi Rosa! I\'m sorry to hear about the redness. That can occasionally happen with gel products. We recommend applying a gentle moisturizer and avoiding nail products for a few days. If it doesn\'t improve within 48 hours, please see a dermatologist. We\'ve flagged your profile for a hypoallergenic gel alternative for your next visit. Would you like to schedule a complimentary redo?',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:30 AM',
      title: 'Walk-in availability response',
      description: 'Someone calls asking if walk-ins are available today for a basic pedicure.',
      aiResponse: 'We have a walk-in opening right now with tech Lisa — she can take you for a classic pedicure ($35, 45 min). The next available slot after that is 3 PM. Would you like to come in now, or shall I hold the 3 PM for you?',
      channel: 'phone',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '12:45 PM',
      title: 'Birthday club automation',
      description: 'Pruve identifies 6 clients with birthdays this week and sends personalized offers.',
      aiResponse: 'Birthday week! Sent personalized birthday offers to 6 clients: complimentary nail art upgrade with any manicure booking this week. Two have already opened their messages. Last month\'s birthday campaign converted at 67% — strong ROI on the $5 upgrade cost.',
      channel: 'sms',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 210 },
    },
    {
      time: '1:30 PM',
      title: 'Content creation — nail trend reel',
      description: 'Pruve drafts an Instagram reel script featuring trending spring nail designs.',
      aiResponse: 'Drafted your trending reel: "Spring 2026 Nail Trends You NEED" — features butter yellow French tips, glazed donut chrome, and botanical press-ons. Script is 25 seconds, uses trending audio "Beautiful Things." Also drafted a carousel post: "Gel vs Dip Powder — The Honest Truth." Ready for review!',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '2:30 PM',
      title: 'New Google review — 5 stars',
      description: 'Client leaves a glowing 5-star review praising the pedicure experience.',
      aiResponse: 'New 5-star review from @JennaK: mentions the "incredible attention to detail" on her pedicure. Drafted reply: "Thank you so much, Jenna! We loved creating that look for you. Your tech Maria will be thrilled to hear this! See you at your next appointment 💅" Ready to post?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '3:45 PM',
      title: 'Bridal party group booking',
      description: 'Email inquiry about booking a bridal party of 8 for matching gel sets.',
      aiResponse: 'Hi Amanda! Congratulations on your upcoming wedding! We\'d love to host your bridal party. For 8 guests doing matching gel manicures, we can offer a private session on a Saturday morning (10 AM – 1 PM). Group rate: $55/person (normally $65) with complimentary champagne. Available dates: March 21 or April 4. Shall I hold one?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '5:00 PM',
      title: 'Weekly performance report',
      description: 'Pruve delivers the weekly numbers: bookings, revenue, no-shows, and top services.',
      aiResponse: 'Weekly report: 112 appointments completed (up 8% from last week). Revenue: $5,840. No-show rate: 4.5% (down from 7%). Top service: Gel Manicure (42%). Recommendation: Mia\'s nail art slots are 95% booked — consider adding a second nail artist for weekends.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 350 },
    },
    {
      time: '7:00 PM',
      title: 'Supply reorder via browser',
      description: 'Pruve detects low stock on OPI gel polish and browses the supplier site to compare prices.',
      aiResponse: 'Stock alert: 4 OPI gel colors running low (Bubble Bath, Lincoln Park, Cajun Shrimp, Mod About You). Checked 2 suppliers — Sally Beauty has a 15% off bulk deal this week ($187 vs. usual $220). Shall I place the order? Budget remaining this month: $450.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 33 },
    },
    {
      time: '9:00 PM',
      title: 'Team schedule coordination',
      description: 'Nail tech asks Pruve to swap her Thursday shift with another tech.',
      aiResponse: 'Lisa asked to swap Thursday with another tech. Checked availability: Mia can cover Lisa\'s Thursday 9–5 shift, and Lisa can take Mia\'s Friday 10–6. Both have confirmed via WhatsApp. Schedule updated — no client appointments need rebooking. Owner notified.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Responds to DMs about nail art designs with pricing and availability instantly',
    memory: 'Remembers each client\'s preferred nail shape, go-to colors, and allergy flags',
    proactive: 'Sends 3-week fill reminders and flags walk-in windows each morning',
    bookings: 'Books group parties, handles walk-ins, sends batch confirmations',
    leads: 'Captures bridal party inquiries and sends group rate proposals',
    revenue: 'Birthday club offers and slow-day promos that convert at 60%+',
    reputation: 'Responds to Google reviews same day with personalized thank-yous',
    content: 'Drafts nail trend reels and comparison carousels for Instagram',
    reporting: 'Weekly revenue per tech, top services, and no-show rate tracking',
    browser: 'Compares supplier prices and finds bulk deals before reordering',
    team: 'Coordinates shift swaps between techs without owner involvement',
    workflow: 'Auto-sends aftercare tips and rebooking reminders post-appointment',
    voice: 'Answers calls about walk-in availability and holds slots',
    multiagent: 'Separate agents handle booking confirmations and content scheduling',
    environment: 'Controls salon playlist and lighting presets via smart speaker',
  },
  stats: {
    messagesPerDay: 55,
    bookingsPerWeek: 45,
    monthlySavings: 2800,
    responseTime: '< 25 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Nail salons thrive on repeat visits and visual marketing — content creation and reputation management drive consistent rebookings.',
};

/* ------------------------------------------------------------------ */
/* 3. HAIR SALON / BARBERSHOP                                          */
/* ------------------------------------------------------------------ */

const hairsalon: Industry = {
  id: 'hairsalon',
  label: 'Hair Salon / Barbershop',
  emoji: '✂️',
  category: 'Health & Wellness',
  tagline: 'Every chair stays booked, every client remembered',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Morning briefing & no-show prediction',
      description: 'Pruve reviews 18 appointments and flags two clients with a history of no-shows.',
      aiResponse: 'Good morning! 18 clients today across 3 stylists. Heads-up: David R. (10 AM, balayage) has no-showed twice before — I\'ve sent him an extra confirmation with a "reply YES to keep your spot" prompt. Also, Marcus J. (2 PM fade) hasn\'t confirmed yet. Waitlist has 4 people ready if slots open.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'WhatsApp booking request',
      description: 'A regular client messages asking for his usual fade with stylist Carlos this week.',
      aiResponse: 'Hey Mike! Carlos has openings this Thursday at 11 AM and Friday at 3 PM for your usual mid-fade with lineup. Which works better? I\'ll get you locked in.',
      channel: 'whatsapp',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Color correction consultation request',
      description: 'New client emails with a photo of a botched color job asking if the salon can fix it.',
      aiResponse: 'Hi Taylor! Thank you for reaching out. I can see from the photo that the banding will need a color correction session. Our senior colorist Jade specializes in these — she recommends a consultation first (complimentary, 20 min) to assess the best approach. She has availability Wednesday at 9 AM or Saturday at 10 AM. Shall I book the consultation?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Client hair history lookup',
      description: 'Stylist asks Pruve what formula was used on a returning client\'s highlights last time.',
      aiResponse: 'Client: Rachel M. Last visit: Jan 15. Service: Partial highlights. Formula: Wella Blondor + 20 vol, toned with Redken Shades EQ 09V. Processing time: 35 min. Stylist note from Jade: "Fine hair, lifts fast — check at 25 min." Rachel prefers warm blonde, not ashy.',
      channel: 'system',
      capability: 'memory',
      tier: 'operator',
    },
    {
      time: '11:15 AM',
      title: 'SMS referral campaign blast',
      description: 'Pruve sends a "Refer a Friend" offer to the top 30 clients who visit most frequently.',
      aiResponse: 'Referral campaign sent to 30 top clients: "Love your look? Refer a friend and you both get $15 off your next visit!" Delivered to 30, opened by 22 so far. Last referral campaign generated 8 new clients — tracking this one now.',
      channel: 'sms',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 320 },
    },
    {
      time: '12:00 PM',
      title: 'Instagram transformation post drafted',
      description: 'Pruve creates a before/after post for a dramatic color transformation done this morning.',
      aiResponse: 'Drafted your transformation post: Before/after carousel of Taylor\'s color correction (with her permission on file). Caption: "From banding to blending ✨ Swipe to see Jade work her magic. Color corrections are an art — book a free consult to see what\'s possible." Scheduled for 6 PM peak engagement. Approve?',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '1:30 PM',
      title: 'Cancellation — slot filled from waitlist',
      description: 'A 2 PM appointment cancels last minute. Pruve contacts waitlisted clients.',
      aiResponse: 'Marcus J. cancelled his 2 PM fade (as flagged this morning). I\'ve already texted 4 waitlisted clients. Sarah K. responded in 3 minutes — she\'s booked for a 2 PM blowout with Carlos. Slot filled, no revenue lost!',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '2:45 PM',
      title: 'Negative Yelp review response',
      description: 'A 2-star review complains about wait time despite having an appointment.',
      aiResponse: 'New 2-star Yelp review from @Chris_D about wait time. Drafted response: "Chris, we sincerely apologize for the wait. We value your time and this isn\'t our standard. We\'ve adjusted our scheduling to prevent overlap, and we\'d love to make it right with a priority booking. Please DM us!" Posting now?',
      channel: 'system',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '4:00 PM',
      title: 'Product restock research',
      description: 'Pruve browses supplier websites for the best deal on Olaplex restocking.',
      aiResponse: 'Olaplex restock comparison: CosmoProf has No. 3, 4, 5, and 8 bundle at $189 (regular $220). Sally Beauty has individual units cheaper but no bundle deal. Amazon Professional is $195 with next-day shipping. Recommendation: CosmoProf bundle saves $31. Shall I place the order?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 31 },
    },
    {
      time: '5:30 PM',
      title: 'Stylist commission report',
      description: 'End-of-day summary showing each stylist\'s bookings, revenue, and product sales.',
      aiResponse: 'Daily stylist report: Carlos — 7 clients, $485 revenue, $62 retail. Jade — 5 clients, $720 revenue (color services), $45 retail. Ava — 6 clients, $390 revenue, $28 retail. Total day revenue: $1,595. Retail attachment rate: 44% (target: 50%). Jade crushed it with that color correction.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
    {
      time: '7:00 PM',
      title: 'After-hours call — wedding party inquiry',
      description: 'Bride-to-be calls after hours to ask about bridal party styling packages.',
      aiResponse: 'Answered the call and captured details: Bride Jessica needs updos for a party of 6 on September 12. Budget: $800–1,000. Preferences: romantic, loose curls, flower accessories. Sent her an email with our bridal package PDF and booked a trial consultation for next Saturday at 9 AM. Lead saved!',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '10:00 PM',
      title: 'Automated rebooking reminders',
      description: 'Pruve sends gentle rebooking nudges to clients approaching their usual 4–6 week cycle.',
      aiResponse: 'Sent rebooking reminders to 12 clients who are due for their regular cut/color cycle this week. Personalized each one: "Hey Alex, it\'s been 5 weeks since your last fade with Carlos — want me to book your usual Thursday slot?" 4 have already replied to book.',
      channel: 'whatsapp',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'bookings', increment: 4 },
    },
  ],
  capabilityExamples: {
    communication: 'Handles booking requests and color consultations across WhatsApp, DMs, and email',
    memory: 'Stores color formulas, preferred stylist, processing times, and product preferences',
    proactive: 'Predicts no-shows, sends rebooking reminders at each client\'s natural cycle',
    bookings: 'Fills cancelled slots from waitlist within minutes',
    leads: 'Captures walk-in consultation requests and bridal party inquiries',
    revenue: 'Referral campaigns and retail upsell tracking per stylist',
    reputation: 'Drafts thoughtful replies to Yelp and Google reviews same-day',
    content: 'Creates before/after transformation posts with engagement-optimized captions',
    reporting: 'Daily stylist commission, retail attachment rate, and revenue breakdown',
    browser: 'Compares product supplier prices and finds bundle deals',
    team: 'Stylists check their schedule, swap shifts, and look up client history via chat',
    workflow: 'Auto-sends post-appointment product care tips based on service',
    voice: 'Handles after-hours bridal and event inquiries, captures full details',
    multiagent: 'Separate agents for product inventory vs. client communications',
    environment: 'Controls salon ambiance — music, lighting — from smart devices',
  },
  stats: {
    messagesPerDay: 50,
    bookingsPerWeek: 42,
    monthlySavings: 3400,
    responseTime: '< 20 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Salons rely on repeat clients and referrals — content marketing and reputation management directly drive chair utilization.',
};

/* ------------------------------------------------------------------ */
/* 4. GYM / FITNESS STUDIO                                             */
/* ------------------------------------------------------------------ */

const gym: Industry = {
  id: 'gym',
  label: 'Gym / Fitness Studio',
  emoji: '🏋️',
  category: 'Health & Wellness',
  tagline: 'Fill every class, retain every member',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning class roster & waitlist alert',
      description: 'Pruve scans today\'s 8 group classes, alerts that the 6:30 AM HIIT class is full with 5 on waitlist.',
      aiResponse: 'Morning! 8 classes today. 6:30 AM HIIT is full (20/20) with 5 waitlisted — historically 2 people drop within 10 min of start. 9 AM Spin has 6 open spots. Personal training: 4 sessions booked, 2 trial sessions. Equipment note: Treadmill #7 is still flagged for maintenance.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:00 AM',
      title: 'Class booking via WhatsApp',
      description: 'Member asks to book the 12 PM Boxing class for herself and a friend (guest pass).',
      aiResponse: 'Hey Priya! I\'ve booked you into 12 PM Boxing with Coach Tran. For your friend, I\'ll set up a guest pass — they just need to sign a waiver at the front desk. Guest fee: $15 or use one of your 2 remaining buddy passes. Want to use a buddy pass?',
      channel: 'whatsapp',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '8:15 AM',
      title: 'Personal training lead inquiry',
      description: 'New lead fills out the "Free Trial" form on the website asking about personal training.',
      aiResponse: 'New lead: Jason M., age 32, goal: "lose 20 lbs and build muscle." Requested a free PT trial. I\'ve sent him a welcome email with trainer bios and available trial slots (Tue 7 AM, Wed 5 PM, Sat 10 AM). Pre-qualified: budget range $200–300/mo, can commit 3x/week.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:30 AM',
      title: 'Membership renewal reminder',
      description: 'Member\'s annual membership expires in 7 days — Pruve sends a personalized renewal nudge.',
      aiResponse: 'Hi Derek! Your gym membership renews on March 18. Great year — you attended 156 classes (up from 98 last year!) and your top classes were HIIT and Spin. Renew before the 18th and lock in your current rate of $79/mo. Want me to process the renewal or switch to a different plan?',
      channel: 'sms',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:45 AM',
      title: 'Equipment maintenance ticket',
      description: 'Member reports via Instagram DM that the cable machine on the second floor is jammed.',
      aiResponse: 'Thanks for letting us know about the cable machine, Kevin! I\'ve logged a maintenance ticket (priority: high) and notified our facilities team. We\'ll have it looked at today. In the meantime, the functional trainer on the first floor is available as an alternative. Sorry for the inconvenience!',
      channel: 'instagram',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:00 PM',
      title: 'Facebook ad lead captured',
      description: 'Someone clicks a Facebook ad for "First Month Free" and messages the page.',
      aiResponse: 'Welcome! Thanks for clicking on our First Month Free offer. Here\'s how it works: full access to all classes, equipment, and the sauna for 30 days. No commitment after that. Can I ask — what are your fitness goals? That way I can recommend the right membership tier when you\'re ready.',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:30 PM',
      title: 'Lapsed member re-engagement',
      description: 'Pruve identifies 15 members who haven\'t visited in 30+ days and sends a "We miss you" campaign.',
      aiResponse: 'Sent "We Miss You" messages to 15 lapsed members with a personalized offer: free guest pass + smoothie bar credit. Personalized each one based on their favorite class. Already got 3 replies — two are booking classes this week. Estimated recovery value: $1,185/mo if 5 return.',
      channel: 'sms',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 1185 },
    },
    {
      time: '3:00 PM',
      title: 'Weekly content calendar',
      description: 'Pruve drafts the week\'s social media content featuring member transformations and class highlights.',
      aiResponse: 'Content for the week: (1) Monday Motivation: Member spotlight on Derek\'s 156-class year (with his permission). (2) Wednesday: "5 Mistakes Killing Your Deadlift" reel — Coach Tran demos. (3) Friday: Weekend warrior class schedule graphic. (4) Story polls: "HIIT or Spin — what should we add more of?" All drafted and scheduled.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '4:30 PM',
      title: 'Google review engagement',
      description: 'New 5-star review praises the coaching staff and clean facilities.',
      aiResponse: 'New 5-star review from @FitMomSally: praises Coach Tran and the "spotless locker rooms." Drafted reply: "Thank you, Sally! Coach Tran is the real deal — we\'ll pass along your kind words. And our cleaning crew will love hearing this! See you in class 💪" Ready to post?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '6:00 PM',
      title: 'Monthly analytics report',
      description: 'Pruve generates the monthly business health report with member trends.',
      aiResponse: 'March report: 342 active members (up 4%). Class attendance: avg 82% capacity. Top class: HIIT (94% full). Churn rate: 5.2% (down from 6.8%). New member conversion: 35% of trials → paid. Revenue: $28,400. Recommendation: Add a second evening HIIT class — demand exceeds capacity by 40%.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 500 },
    },
    {
      time: '8:00 PM',
      title: 'Trainer schedule coordination',
      description: 'Coach Tran messages Pruve to request coverage for Friday morning classes.',
      aiResponse: 'Coach Tran needs Friday AM off. Checked trainer availability: Coach Maria can cover the 6:30 HIIT and 8 AM Strength classes. She\'s confirmed. Updated the schedule and notified the 34 members booked for those classes about the sub. No cancellations so far. Owner notified.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
    {
      time: '10:00 PM',
      title: 'Competitor class schedule scan',
      description: 'Pruve browses two competing gyms\' websites to check for new class offerings or pricing changes.',
      aiResponse: 'Competitor scan: FitZone just added a "Strength & Stretch" hybrid class on Saturdays. CrossFit Downtown raised their monthly rate from $159 to $175. Neither has added a boxing program yet — your Boxing class is a differentiator. Full competitor report saved to your dashboard.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Handles class bookings, guest passes, and equipment reports across all channels',
    memory: 'Tracks member attendance streaks, favorite classes, and personal records',
    proactive: 'Flags full classes with waitlists and sends renewal reminders with usage stats',
    bookings: 'Books group classes, manages waitlists, and coordinates guest passes',
    leads: 'Captures free trial leads and pre-qualifies budget and commitment level',
    revenue: 'Re-engages lapsed members with personalized comeback offers',
    reputation: 'Responds to gym reviews highlighting specific coaches and facilities',
    content: 'Creates member spotlight posts, workout tip reels, and class schedule graphics',
    reporting: 'Monthly churn rate, class capacity trends, and trial-to-paid conversion',
    browser: 'Monitors competitor pricing and class offerings weekly',
    team: 'Coordinates trainer substitutions and notifies affected members',
    workflow: 'Syncs class bookings with member check-in system and billing',
    voice: 'Answers calls about membership plans and trial availability',
    multiagent: 'Separate agents for member retention and new lead nurturing',
    environment: 'Controls gym sound system and lobby display with class countdown timers',
  },
  stats: {
    messagesPerDay: 65,
    bookingsPerWeek: 55,
    monthlySavings: 4200,
    responseTime: '< 15 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Gyms live and die on retention — lapsed member re-engagement, content marketing, and class analytics pay for themselves within weeks.',
};

/* ------------------------------------------------------------------ */
/* 5. YOGA / PILATES STUDIO                                            */
/* ------------------------------------------------------------------ */

const yoga: Industry = {
  id: 'yoga',
  label: 'Yoga / Pilates Studio',
  emoji: '🧘',
  category: 'Health & Wellness',
  tagline: 'You focus on flow — Pruve handles everything else',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Dawn schedule & mat count',
      description: 'Pruve reviews 6 classes today and confirms prop inventory: 18 mats, 12 bolsters, reformers serviced.',
      aiResponse: 'Namaste! 6 classes today. 6:30 AM Sunrise Vinyasa has 14/16 spots filled. 9 AM Reformer Pilates: fully booked (8/8). Props check: all 18 mats sanitized, 12 bolsters in place. Note: Reformer #3 spring tension was reported loose yesterday — maintenance checked it last night, good to go.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'New student intro class booking',
      description: 'First-time student messages on WhatsApp asking about beginner-friendly classes.',
      aiResponse: 'Welcome to our studio! We\'d love to have you. Our best class for beginners is "Gentle Flow" — Tuesdays and Thursdays at 10 AM with instructor Sana. She gives lots of modifications and the pace is relaxed. Your first class is free! Want me to save you a mat for Tuesday?',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Class pass expiration reminder',
      description: 'Student\'s 10-class pass has 2 classes left and expires in 5 days.',
      aiResponse: 'Hi Emma! Quick heads-up: you have 2 classes left on your 10-class pass, and it expires on March 16. Want to use them this week? I see openings in Thursday\'s Hot Yoga and Friday\'s Yin. Or if you\'re loving it, our unlimited monthly is $129 — saves you 30% vs. class packs.',
      channel: 'sms',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Workshop registration inquiry',
      description: 'Email asking about the upcoming "Arm Balances & Inversions" weekend workshop.',
      aiResponse: 'Hi Marcus! Great question about the Arm Balances workshop. It\'s Saturday, April 5, from 1–4 PM with guest instructor Kai Chen. Level: intermediate to advanced. Cost: $85 (members get 15% off → $72.25). Only 6 spots left out of 20. Shall I register you?',
      channel: 'email',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '11:15 AM',
      title: 'Instagram question about private sessions',
      description: 'DM asking about private one-on-one Pilates reformer sessions for post-surgery rehab.',
      aiResponse: 'Hi! Private reformer sessions are a great choice for post-surgery rehab. Our certified instructor Leah specializes in rehabilitation Pilates and works closely with your PT\'s recommendations. Sessions are $95/hour. She has availability Mon/Wed afternoons. Would you like to start with a 30-min assessment ($50)?',
      channel: 'instagram',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:30 PM',
      title: 'Mindfulness content post scheduled',
      description: 'Pruve drafts and schedules a calming Instagram post about breathwork benefits.',
      aiResponse: 'Scheduled for 5 PM today: "3 Breathwork Techniques for Instant Calm" — carousel post with box breathing, 4-7-8 technique, and alternate nostril demos. Caption includes a CTA for your new Breathwork & Meditation class launching next month. Also drafted a story poll: "Morning or evening — when do you prefer to practice?"',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '1:45 PM',
      title: 'Review request after first month',
      description: 'Pruve sends review requests to 8 students who completed their first month.',
      aiResponse: 'Sent personalized review requests to 8 students who hit their one-month mark. Each message references their most-attended class: "You\'ve completed 12 Vinyasa classes this month, Sarah — incredible! Would you mind sharing your experience on Google? Here\'s a direct link." Last batch had a 38% review rate.',
      channel: 'sms',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '3:00 PM',
      title: 'Slow evening class — targeted promo',
      description: 'Tonight\'s 7 PM Yin class has only 3 of 16 spots filled.',
      aiResponse: 'Tonight\'s 7 PM Yin class is only 19% full (3/16). Sent a "Wind-Down Wednesday" promo to 40 students who\'ve taken Yin before but haven\'t booked tonight: "Need to decompress? Tonight\'s Yin with Sana has plenty of room — bring a friend for free." 5 responses so far, 3 booking now.',
      channel: 'whatsapp',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'bookings', increment: 3 },
    },
    {
      time: '4:30 PM',
      title: 'Weekly studio metrics',
      description: 'Pruve delivers weekly attendance, revenue, and retention data.',
      aiResponse: 'Weekly metrics: 142 class check-ins (up 11%). Average class fill rate: 74%. Revenue: $4,680. New students: 7 (4 converted from intro offer). Retention risk: 3 monthly members haven\'t attended in 2+ weeks — sent check-in messages. Top class: Hot Vinyasa (92% full every session).',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 400 },
    },
    {
      time: '6:00 PM',
      title: 'Instructor messages about sub coverage',
      description: 'Instructor Sana asks Pruve to find coverage for her Saturday morning class.',
      aiResponse: 'Sana needs Saturday 9 AM Vinyasa covered. Checked availability: Instructor Kai can sub — she confirmed via WhatsApp. Updated schedule and sent notifications to the 12 registered students: "Saturday\'s 9 AM Vinyasa will be taught by the amazing Kai — same great flow!" Zero cancellations so far.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
    {
      time: '8:00 PM',
      title: 'Wholesale mat supplier comparison',
      description: 'Pruve researches bulk yoga mat suppliers for a studio refresh.',
      aiResponse: 'Mat supplier comparison for 20 premium mats: Manduka PRO — $108/ea ($2,160 total, free shipping). Jade Harmony — $85/ea ($1,700, $50 shipping). Liforme — $140/ea ($2,800). Recommendation: Jade Harmony offers best value at $1,750 shipped with 10-year warranty. Shall I place the order?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 460 },
    },
    {
      time: '9:30 PM',
      title: 'New skill created: teacher training intake',
      description: 'Pruve self-creates a new workflow for handling 200-hour teacher training applications.',
      aiResponse: 'I noticed you received 3 teacher training inquiries this week with no automated flow. I\'ve built a new skill: "Teacher Training Intake" — captures applicant details, sends the program PDF, collects prerequisites (min 1 year practice, CPR cert), and schedules an interview call. Want me to activate it?',
      channel: 'system',
      capability: 'multiagent',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Answers beginner questions about class levels, props, and what to wear',
    memory: 'Tracks class pass usage, favorite instructors, and physical limitations',
    proactive: 'Alerts when class passes near expiration and flags reformer maintenance',
    bookings: 'Handles workshop registrations, private session bookings, and intro offers',
    leads: 'Captures rehab Pilates and private session inquiries with intake details',
    revenue: 'Fills empty evening classes with targeted promos to past attendees',
    reputation: 'Sends review requests referencing each student\'s class milestones',
    content: 'Creates breathwork tip carousels and mindfulness content for Instagram',
    reporting: 'Weekly fill rates, retention risk flags, and new student conversion tracking',
    browser: 'Compares wholesale pricing on mats, blocks, and reformer parts',
    team: 'Finds sub instructors and notifies registered students automatically',
    workflow: 'Auto-sends class reminders with what-to-bring tips for different styles',
    voice: 'Answers calls about schedules and pricing with a calm, on-brand tone',
    multiagent: 'Creates new intake workflows for teacher training programs automatically',
    environment: 'Controls studio heating for hot yoga and adjusts ambient sound',
  },
  stats: {
    messagesPerDay: 40,
    bookingsPerWeek: 48,
    monthlySavings: 2900,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Studios with class-based revenue need fill rate optimization, retention tracking, and community content to keep students engaged.',
};

/* ------------------------------------------------------------------ */
/* 6. DENTAL CLINIC                                                    */
/* ------------------------------------------------------------------ */

const dental: Industry = {
  id: 'dental',
  label: 'Dental Clinic',
  emoji: '🦷',
  category: 'Health & Wellness',
  tagline: 'Every chair filled, every patient followed up',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Morning schedule & insurance verifications',
      description: 'Pruve reviews 24 patient appointments and flags 3 with unverified insurance.',
      aiResponse: 'Good morning! 24 patients today across 2 dentists and 3 hygienists. Three insurance verifications still pending: Maria L. (10 AM crown prep), David K. (11:30 cleaning), and Baby Olivia (2 PM first visit). I\'ve sent verification requests to their carriers. Dr. Chen\'s first patient arrives at 7:30.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Emergency toothache call',
      description: 'Patient calls in pain asking for an emergency same-day appointment.',
      aiResponse: 'I\'m sorry you\'re in pain! Dr. Chen has an emergency slot available today at 9:15 AM. In the meantime, you can take ibuprofen for the pain and avoid hot/cold foods on that side. Can I book you for 9:15? Please arrive 10 minutes early to fill out a brief form. We\'ll take care of you!',
      channel: 'phone',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Kids cleaning appointment — parent follow-up',
      description: 'Parent texts asking what to expect for her 4-year-old\'s first dental cleaning.',
      aiResponse: 'Hi Sarah! Great question. For little Olivia\'s first visit, here\'s what to expect: a gentle teeth counting game, a soft polishing (no scary tools!), and a fun ride in our "spaceship" chair. It takes about 20 minutes. She\'ll pick a prize from our treasure chest afterward! Dr. Patel is wonderful with first-timers. See you at 2 PM!',
      channel: 'sms',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Insurance verification result',
      description: 'Pruve receives insurance verification and updates the patient record before their crown prep.',
      aiResponse: 'Insurance verified for Maria L.: Delta Dental PPO, crown covered at 50% after deductible. Patient\'s estimated out-of-pocket: $420. I\'ve updated her chart and prepared a cost breakdown to present before the procedure. Her deductible has already been met for the year.',
      channel: 'system',
      capability: 'workflow',
      tier: 'executive',
    },
    {
      time: '11:15 AM',
      title: 'X-ray follow-up results',
      description: 'Patient from last week\'s visit messages asking about their X-ray findings.',
      aiResponse: 'Hi Robert! Dr. Chen reviewed your X-rays and found a small cavity on tooth #14 (upper left premolar). It\'s early stage and a straightforward filling — about 30 minutes. She recommends scheduling within the next 2–3 weeks to prevent it from growing. I have openings next Tuesday at 8 AM or Thursday at 2 PM. Which works?',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '12:30 PM',
      title: '6-month recall reminders batch',
      description: 'Pruve sends 6-month cleaning reminders to 35 patients due this month.',
      aiResponse: 'Sent 6-month recall reminders to 35 patients. Personalized by last visit: "Hi Tom, it\'s been 6 months since your last cleaning with hygienist Amy. Time to keep that smile in top shape! Book online or reply here." 12 have responded so far — 9 booked, 3 asked for next month.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 9 },
    },
    {
      time: '1:45 PM',
      title: 'New patient inquiry from Google',
      description: 'Prospective patient finds the clinic on Google and submits a contact form about Invisalign.',
      aiResponse: 'New Invisalign lead: Jennifer P., age 28, concerned about crowding on her lower teeth. I\'ve sent her a welcome email with our Invisalign before/after gallery, financing options (as low as $99/mo through CareCredit), and available consultation slots. Pre-qualified: has dental insurance, budget flexible.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '3:00 PM',
      title: 'Post-procedure care automated',
      description: 'Patient who had a crown prep this morning receives aftercare instructions.',
      aiResponse: 'Hi Maria! Your temporary crown looks great. Here are your care instructions: avoid sticky/hard foods on that side, brush gently around the temporary, and if it feels loose, call us right away. Your permanent crown will be ready in 2 weeks — I\'ve booked your seating for March 25 at 10 AM. Any discomfort, just text us!',
      channel: 'whatsapp',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '4:15 PM',
      title: 'Review generation campaign',
      description: 'Pruve sends review requests to today\'s patients who had positive experiences.',
      aiResponse: 'Sent review requests to 8 patients who completed appointments today. Filtered out Maria (crown prep — too early to review) and the emergency patient (follow-up pending). Message: "Thanks for visiting us today! If you had a great experience, a quick Google review helps other families find quality dental care." Last month: 14 reviews collected, rating up to 4.8.',
      channel: 'sms',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '5:30 PM',
      title: 'Monthly production report',
      description: 'Pruve generates the monthly practice production and collections report.',
      aiResponse: 'March production report: $68,400 produced, $61,200 collected (89% collection rate). Top procedures: cleanings (42%), fillings (22%), crowns (18%). Invisalign consultations: 6 (3 started treatment). No-show rate: 6% (down from 9% since adding SMS confirmations). Hygienist utilization: 91%. Dr. Chen is at 87% — 2 more patients per week fills her schedule.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 800 },
    },
    {
      time: '7:00 PM',
      title: 'Dental education blog post drafted',
      description: 'Pruve writes a blog post about "When to Choose a Crown vs. a Filling" for the clinic website.',
      aiResponse: 'Drafted blog post: "Crown vs. Filling — How Your Dentist Decides" — 600 words, patient-friendly language, includes a comparison table and your clinic\'s approach. SEO-optimized for "do I need a crown or filling" (1,200 monthly searches). Also created a short-form version for Instagram carousel. Ready for Dr. Chen to review.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '9:00 PM',
      title: 'Supply price comparison',
      description: 'Pruve browses dental supply sites to find the best price on composite resin refills.',
      aiResponse: 'Composite resin price check — 3M Filtek Supreme refill kit: Henry Schein $285, Patterson Dental $292, Net32 $248 (15% off bulk). You use ~4 kits/month. Switching to Net32 saves $148/month ($1,776/year). They also have free shipping over $200. Want me to set up a recurring order?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 148 },
    },
  ],
  capabilityExamples: {
    communication: 'Handles emergency calls, parent questions about kids\' visits, and Invisalign inquiries',
    memory: 'Stores treatment history, insurance details, X-ray notes, and preferred hygienist',
    proactive: 'Sends post-procedure aftercare instructions and flags unverified insurance early',
    bookings: 'Manages 6-month recall reminders and fills emergency same-day slots',
    leads: 'Captures Invisalign and cosmetic dentistry leads with financing info',
    revenue: 'Reactivates patients overdue for cleanings with personalized outreach',
    reputation: 'Generates Google reviews by targeting patients with positive experiences',
    content: 'Writes dental education blog posts and patient-friendly social content',
    reporting: 'Monthly production, collection rate, and procedure mix analysis',
    browser: 'Compares dental supply prices across distributors for bulk savings',
    team: 'Hygienists check schedules and flag equipment needs through chat',
    workflow: 'Verifies insurance coverage and prepares cost breakdowns before procedures',
    voice: 'Answers emergency calls with triage guidance and same-day scheduling',
    multiagent: 'Separate agents for insurance verification and patient communication',
    environment: 'Controls operatory displays showing patient education videos',
  },
  stats: {
    messagesPerDay: 60,
    bookingsPerWeek: 50,
    monthlySavings: 5200,
    responseTime: '< 20 seconds',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Dental clinics benefit enormously from insurance verification automation, supply cost optimization, and recall systems that directly impact production.',
};

/* ------------------------------------------------------------------ */
/* 7. OPTOMETRIST                                                      */
/* ------------------------------------------------------------------ */

const optometrist: Industry = {
  id: 'optometrist',
  label: 'Optometrist',
  emoji: '👁️',
  category: 'Health & Wellness',
  tagline: 'Clear vision for your patients and your practice',
  dayEvents: [
    {
      time: '7:00 AM',
      title: 'Morning briefing — lab orders & schedule',
      description: 'Pruve reviews 16 patient appointments and flags 4 glasses orders ready for pickup.',
      aiResponse: 'Good morning! 16 appointments today: 10 comprehensive exams, 3 contact lens fittings, 2 follow-ups, 1 pediatric. Four glasses orders are ready for pickup — I\'ve texted those patients. Reminder: Mrs. Hernandez (9 AM) needs her diabetic eye exam documented for her endocrinologist.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:00 AM',
      title: 'Annual exam reminder batch',
      description: 'Pruve sends annual eye exam reminders to 40 patients due this month.',
      aiResponse: 'Sent annual exam reminders to 40 patients. Personalized by last visit type: "Hi Karen, it\'s been a year since your last comprehensive eye exam. Time to check in on that prescription! We have openings this week — reply to book or click the link." 15 opened within the first hour.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 40 },
    },
    {
      time: '9:15 AM',
      title: 'Contact lens reorder request',
      description: 'Regular patient WhatsApps asking to reorder the same contacts as last time.',
      aiResponse: 'Hi Jason! Your last order was Acuvue Oasys 1-Day, -3.25 both eyes, 90-pack. Your prescription is still valid until August. I can place the order now — $165 for the 90-day supply with free shipping. Shall I charge the card on file, or would you prefer to pick up in-store?',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'Insurance coverage question',
      description: 'New patient calls asking if the clinic accepts VSP insurance and what\'s covered.',
      aiResponse: 'Yes, we accept VSP! With your plan, you\'re typically covered for a comprehensive eye exam (copay applies), plus an allowance of $130–180 toward frames and a separate contact lens benefit. Coverage depends on your specific plan tier. Can I take your member ID number so I can look up your exact benefits before your visit?',
      channel: 'phone',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:45 AM',
      title: 'Glasses ready for pickup notification',
      description: 'Four patients\' glasses orders arrived from the lab — Pruve notifies each one.',
      aiResponse: 'Notified 4 patients that their glasses are ready: sent texts with store hours and a note that fitting adjustments are included. Mrs. Park\'s progressive lenses and Mr. Chen\'s photochromic sunglasses both arrived today. Pickup window: Mon–Fri 9 AM–6 PM, Sat 9 AM–1 PM.',
      channel: 'sms',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '1:00 PM',
      title: 'Pediatric eye exam lead from Facebook',
      description: 'Parent messages on Facebook asking about eye exams for kids and at what age to start.',
      aiResponse: 'Great question! The American Optometric Association recommends a child\'s first eye exam at 6 months, then at age 3, and before first grade. Our pediatric exams are playful and quick — we use picture charts for pre-readers and Dr. Reyes is wonderful with little ones. Your child\'s first exam is covered by most insurance. Would you like to schedule?',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '2:15 PM',
      title: 'Frame inventory flash sale',
      description: 'Pruve notices 15 frames from last season\'s collection still in stock and proposes a clearance campaign.',
      aiResponse: 'You have 15 frames from the 2025 collection still in inventory (retail value: $3,200). Proposal: "Spring Frame Clearance — 40% off select designer frames" campaign to your email list (1,200 subscribers) and Instagram. At 40% off, you still clear $1,920 and free up display space for the new collection. Launch it?',
      channel: 'system',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 1920 },
    },
    {
      time: '3:30 PM',
      title: 'Google review response',
      description: 'A 3-star review mentions long wait times but praises the thoroughness of the exam.',
      aiResponse: 'Drafted response to the 3-star review: "Thank you for your feedback, Michael. We\'re glad Dr. Reyes provided a thorough exam — that\'s always our priority. We hear you on the wait time and have adjusted our scheduling to allow more buffer between appointments. We\'d love another chance to wow you — your next visit will be right on time!" Post it?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '4:45 PM',
      title: 'Eye health awareness content',
      description: 'Pruve creates a post about digital eye strain for National Eye Health Month.',
      aiResponse: 'Drafted post for Eye Health Month: "Screens all day? Follow the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds." Includes a branded graphic and a CTA for booking a digital eye strain assessment. Also drafted an email newsletter with 5 eye health tips and an exam booking link. Review and approve?',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '5:30 PM',
      title: 'Weekly practice analytics',
      description: 'End-of-week report on exams completed, optical sales, and recall conversion.',
      aiResponse: 'Weekly report: 68 exams completed (target: 70). Optical sales: $12,400 (avg $182/patient). Contact lens revenue: $3,200. Recall conversion: 37% of reminded patients booked (15 of 40). Top frame brand sold: Ray-Ban (22%). Recommendation: Thursday afternoons are consistently slow — consider a "Lunch Hour Express Exam" promotion.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 600 },
    },
    {
      time: '7:30 PM',
      title: 'Lens supplier price monitoring',
      description: 'Pruve checks lab pricing for progressive lenses across three suppliers.',
      aiResponse: 'Progressive lens comparison — Essilor Varilux Comfort: Lab A ($142), Lab B ($128), Lab C ($135). Your current lab (Lab A) is the most expensive. Lab B offers the same lens at $14 less per pair. At 30 progressive orders/month, switching saves $420/month. Lab B also offers 2-day turnaround. Shall I request a sample order?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 420 },
    },
    {
      time: '9:00 PM',
      title: 'Staff scheduling automation',
      description: 'Front desk staff requests next week\'s schedule adjustment through Pruve.',
      aiResponse: 'Receptionist Ana requested to swap her Monday morning shift with Tuesday morning. Checked: Tuesday has lighter patient volume (12 vs. 16 Monday). Confirmed with backup receptionist Mia to cover Monday. Updated schedule, notified both staff members and the practice manager. No patient-facing impact.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Answers insurance coverage questions and explains exam procedures for children',
    memory: 'Stores prescription history, preferred frame styles, and contact lens brand/power',
    proactive: 'Sends annual exam reminders and notifies patients when glasses orders arrive',
    bookings: 'Manages recall reminders, contact lens reorders, and fitting follow-ups',
    leads: 'Captures pediatric exam and specialty lens inquiries from social media',
    revenue: 'Clears old frame inventory with targeted clearance campaigns',
    reputation: 'Addresses wait time feedback with genuine scheduling improvements',
    content: 'Creates eye health awareness content and digital strain prevention tips',
    reporting: 'Weekly exam volume, optical sales per patient, and recall conversion rates',
    browser: 'Monitors lens lab pricing and finds savings on progressive lens orders',
    team: 'Staff manages shift swaps and schedule adjustments through chat',
    workflow: 'Auto-verifies vision insurance benefits before patient arrival',
    voice: 'Handles calls about insurance acceptance and appointment availability',
    multiagent: 'Separate agents for optical sales follow-up and clinical recalls',
    environment: 'Controls waiting room displays showing eye health education content',
  },
  stats: {
    messagesPerDay: 42,
    bookingsPerWeek: 35,
    monthlySavings: 3800,
    responseTime: '< 25 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Optometry practices benefit from recall automation, frame inventory campaigns, and reputation management to fill exam chairs consistently.',
};

/* ------------------------------------------------------------------ */
/* 8. MEDICAL CLINIC / DOCTOR                                          */
/* ------------------------------------------------------------------ */

const medical: Industry = {
  id: 'medical',
  label: 'Medical Clinic / Doctor',
  emoji: '🏥',
  category: 'Health & Wellness',
  tagline: 'Run a healthier practice while patients get healthier care',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Morning briefing — patient load & lab results',
      description: 'Pruve reviews 28 patient appointments and flags 5 pending lab results that need physician review.',
      aiResponse: 'Good morning, Dr. Martinez! 28 patients today: 18 follow-ups, 6 new patients, 2 physicals, 2 urgent walk-in slots held. Five lab results arrived overnight needing your review — I\'ve prioritized them by urgency: Mrs. Kim\'s A1C, Mr. Patel\'s lipid panel (borderline flagged), and 3 routine CBCs. All charted and ready.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Prescription refill request',
      description: 'Patient messages on the portal asking for a refill of their blood pressure medication.',
      aiResponse: 'Hi Mr. Torres! I see your request for a Lisinopril 10mg refill. Your last refill was 3 months ago and you\'re due for a blood pressure check. Dr. Martinez has approved a 30-day refill sent to your Walgreens on Main St. We\'ll need to schedule a follow-up within 30 days to continue. I have openings next Thursday at 9 AM or Friday at 2 PM — which works?',
      channel: 'email',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'New patient intake form chase',
      description: 'Three new patients arriving today haven\'t completed their intake forms — Pruve follows up.',
      aiResponse: 'Sent follow-up to 3 new patients with incomplete intake forms: "Hi Sarah, your appointment with Dr. Martinez is at 11 AM today. To make the most of your visit, please complete your intake form before you arrive — it takes about 5 minutes." Included the direct link. Two of three have now completed it.',
      channel: 'sms',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 3 },
    },
    {
      time: '10:00 AM',
      title: 'Test results follow-up',
      description: 'Patient calls asking about blood work results from last week\'s visit.',
      aiResponse: 'Hi Mrs. Kim! Dr. Martinez has reviewed your lab results. Your A1C came back at 6.2 — slightly elevated from 5.9 last time but still in the pre-diabetic range. She\'d like to discuss dietary adjustments and possibly adjusting your Metformin. Can we schedule a 15-minute follow-up? I have availability this Thursday at 10:30 AM.',
      channel: 'phone',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '11:15 AM',
      title: 'Appointment confirmation round',
      description: 'Pruve sends confirmations to tomorrow\'s 30 patients with arrival instructions.',
      aiResponse: 'Sent 30 confirmations for tomorrow. Each includes: arrival time (15 min early for new patients), parking info, and what to bring (insurance card, medication list). 22 confirmed so far, 5 pending, 3 not opened. Will re-send to non-responders at 4 PM. Two patients requested reschedules — handled and waitlist notified.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 30 },
    },
    {
      time: '12:30 PM',
      title: 'Chronic care management outreach',
      description: 'Pruve identifies 20 diabetic patients due for quarterly A1C checks and sends reminders.',
      aiResponse: 'Quarterly care outreach: 20 diabetic patients due for A1C checks this month. Sent personalized messages: "Hi [name], it\'s time for your quarterly diabetes check-in with Dr. Martinez. Regular monitoring keeps you on track — book your blood draw and follow-up today." 8 have booked so far. This program improves outcomes and generates $4,200/mo in CCM reimbursement.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 4200 },
    },
    {
      time: '1:45 PM',
      title: 'Flu season awareness post',
      description: 'Pruve drafts a social media post about flu shot availability at the clinic.',
      aiResponse: 'Drafted post: "Flu season isn\'t over yet! Walk in for your flu shot — no appointment needed, Mon–Fri 8 AM–5 PM. Most insurance covers it at 100%. Protect yourself and your family." Also drafted an email to the patient list (2,400 subscribers) highlighting flu shots + annual physicals. Scheduled for Thursday morning.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '3:00 PM',
      title: 'Negative Google review flagged',
      description: 'A 1-star review complains about billing confusion after an office visit.',
      aiResponse: 'Alert: 1-star review from @PatientJohn about unexpected billing. Drafted response: "John, we\'re sorry for the billing confusion. Our office manager will reach out directly to review your charges and resolve this. We pride ourselves on transparency and want to make this right. Please expect a call tomorrow." This needs your approval given the sensitivity. Shall I also have billing pull his account?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '4:15 PM',
      title: 'Weekly clinic metrics',
      description: 'Pruve delivers weekly performance data: patient volume, no-shows, and revenue.',
      aiResponse: 'Weekly report: 132 patients seen (target: 140). No-show rate: 8% (12 patients). Revenue: $42,800. Top visit types: follow-ups (45%), new patients (22%), physicals (15%). Wait time average: 14 min (target: <10). Recommendation: Adding a medical assistant for rooming would cut wait times by 5 min — estimated cost vs. revenue impact attached.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 1200 },
    },
    {
      time: '5:30 PM',
      title: 'Insurance verification automation',
      description: 'Pruve auto-verifies insurance for tomorrow\'s 30 patients and flags issues.',
      aiResponse: 'Insurance verification complete for tomorrow: 27 of 30 verified. Issues flagged: Patient #18 (policy expired — contacted patient to update), Patient #22 (referral required — sent request to PCP), Patient #29 (high deductible not met — prepared cost estimate). All notes added to charts.',
      channel: 'system',
      capability: 'workflow',
      tier: 'executive',
    },
    {
      time: '7:00 PM',
      title: 'Medical supply cost comparison',
      description: 'Pruve browses supplier sites to compare pricing on exam gloves and rapid test kits.',
      aiResponse: 'Supply comparison: Nitrile gloves (case of 1,000): McKesson $68, Henry Schein $72, Amazon Business $59. Rapid strep test kits (25-pack): McKesson $45, Medline $42. Switching gloves to Amazon Business saves $108/month. Rapid tests from Medline save $36/month. Total annual savings: $1,728. Place orders?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 144 },
    },
    {
      time: '9:00 PM',
      title: 'Staff task delegation from voice note',
      description: 'Dr. Martinez sends a voice note asking Pruve to handle several administrative tasks.',
      aiResponse: 'Transcribed your voice note and created tasks: (1) Schedule staff meeting for Friday 12:30 PM — sent calendar invites to all 8 team members. (2) Order flu vaccine restock — checking CDC pricing now. (3) Draft letter for Mrs. Hernandez\'s disability form — pulled her chart notes from the last 6 months. All three in progress, will update you by morning.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
  ],
  capabilityExamples: {
    communication: 'Handles refill requests, test result inquiries, and new patient questions',
    memory: 'Tracks medication history, lab trends, chronic conditions, and preferred pharmacy',
    proactive: 'Flags pending lab results, sends post-visit instructions, and chases intake forms',
    bookings: 'Sends confirmations with arrival instructions and manages waitlist for cancellations',
    leads: 'Captures new patient inquiries and ensures intake forms are completed before arrival',
    revenue: 'Drives chronic care management reimbursement through quarterly outreach',
    reputation: 'Handles sensitive billing reviews with empathy and escalates to office manager',
    content: 'Creates health awareness posts about flu shots, screenings, and preventive care',
    reporting: 'Weekly patient volume, no-show rate, wait times, and revenue by visit type',
    browser: 'Compares medical supply pricing across distributors for bulk savings',
    team: 'Transcribes physician voice notes into delegated tasks and tracks completion',
    workflow: 'Auto-verifies insurance and flags referral requirements before appointments',
    voice: 'Answers calls about test results and guides patients with appropriate triage',
    multiagent: 'Separate agents for clinical follow-up and administrative workflow',
    environment: 'Controls waiting room check-in kiosk and patient education displays',
  },
  stats: {
    messagesPerDay: 75,
    bookingsPerWeek: 60,
    monthlySavings: 6500,
    responseTime: '< 15 seconds',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Medical clinics see the highest ROI from insurance verification automation, chronic care outreach, and supply cost optimization that directly impacts the bottom line.',
};

/* ------------------------------------------------------------------ */
/* 9. VETERINARY CLINIC                                                */
/* ------------------------------------------------------------------ */

const vet: Industry = {
  id: 'vet',
  label: 'Veterinary Clinic',
  emoji: '🐾',
  category: 'Health & Wellness',
  tagline: 'Happier pets, less stressed practice',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Morning briefing — surgeries & walk-in slots',
      description: 'Pruve reviews 20 appointments including 2 surgeries and flags critical post-op check-ins.',
      aiResponse: 'Good morning! 20 appointments today: 12 wellness exams, 3 sick visits, 2 dental cleanings under anesthesia, 2 spay/neuter surgeries, 1 follow-up. Post-op: Golden Retriever "Bailey" (spay yesterday) — owner check-in call due at 9 AM. Emergency slots: 2 held open. Vaccine inventory: Rabies running low (8 doses left).',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Dog rash photo triage',
      description: 'Pet owner sends a WhatsApp photo of a red, bumpy rash on their dog\'s belly.',
      aiResponse: 'Hi Amanda! Thank you for sending the photo of Max\'s belly. The red bumps could be a contact allergy, hot spot, or skin infection — it\'s hard to tell from photos alone, but it doesn\'t look like an emergency. Dr. Nguyen recommends bringing him in for a skin scraping to rule out mites. We have an opening today at 11:30 AM or tomorrow at 9 AM. In the meantime, try to keep Max from licking the area. Want to book?',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Vaccination reminder batch',
      description: 'Pruve sends vaccination reminders to 25 pets due for annual boosters this month.',
      aiResponse: 'Sent vaccination reminders to 25 pet owners. Personalized by pet: "Hi Tom! Buddy\'s DHPP and Bordetella boosters are due this month. He\'s such a trooper — let\'s keep him protected! Book his quick vaccine visit (15 min) anytime this week." 10 have responded so far — 7 booked appointments.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 7 },
    },
    {
      time: '9:30 AM',
      title: 'Post-surgery check-in call',
      description: 'Pruve calls Bailey\'s owner for the 24-hour post-spay wellness check.',
      aiResponse: 'Called Bailey\'s owner (Mrs. Chen) for post-spay check-in. Report: Bailey ate half her breakfast, no vomiting, incision looks clean, resting comfortably, wearing her e-collar. No concerning signs. I\'ve logged the notes in Bailey\'s chart and reminded Mrs. Chen about the 10-day suture removal appointment on March 21. All good!',
      channel: 'phone',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'New puppy registration from Instagram',
      description: 'New puppy owner DMs asking about first-visit puppy packages and what vaccines are needed.',
      aiResponse: 'Congratulations on your new puppy! 🐶 Our Puppy Wellness Package includes the full first-year vaccine series (DHPP, Rabies, Bordetella), deworming, fecal test, microchip, and a spay/neuter consult — all for $385 (saves $120 vs. individual pricing). Dr. Nguyen loves meeting new puppies! First available appointment: Thursday 10 AM. Want me to book Luna\'s first visit?',
      channel: 'instagram',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '11:45 AM',
      title: 'Dental cleaning cost estimate request',
      description: 'Cat owner emails asking about the cost of a dental cleaning for her senior cat.',
      aiResponse: 'Hi Rachel! Dental cleanings for cats typically range from $280–450 depending on whether any extractions are needed. For Mochi (age 12), Dr. Nguyen recommends pre-anesthesia bloodwork ($95) given her age — this checks kidney and liver function to ensure she\'s safe under anesthesia. We can provide an exact estimate after the pre-dental exam ($55). Shall I book the exam?',
      channel: 'email',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:00 PM',
      title: 'Heartworm prevention campaign',
      description: 'Pruve launches a spring heartworm awareness campaign to the full client list.',
      aiResponse: 'Spring heartworm campaign sent to 800 pet owners: "Spring = mosquitoes = heartworm risk. Is [pet name] protected? Book a quick heartworm test ($35) and get 10% off a 12-month prevention supply this month." Segmented by pet type: dog owners get full message, cat owners get modified indoor/outdoor version. 42 opened in the first hour.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 2800 },
    },
    {
      time: '2:15 PM',
      title: 'Pet health tip content posted',
      description: 'Pruve publishes a "5 Toxic Plants for Dogs" spring safety post to social media.',
      aiResponse: 'Posted to Instagram and Facebook: "5 Common Spring Plants That Are Toxic to Dogs — #3 will surprise you!" Carousel with photos and symptoms for each plant (lilies, azaleas, tulips, sago palm, daffodils). CTA: "Save this post and share with your dog park friends!" Also scheduled a follow-up post about cat-safe houseplants for Thursday.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '3:30 PM',
      title: 'Google review — happy rescue adoption',
      description: 'Client leaves a 5-star review about the clinic\'s care for their newly adopted rescue dog.',
      aiResponse: 'New 5-star review from @RescueMomJess: "Dr. Nguyen was so gentle with our nervous rescue. She took her time and didn\'t rush Cooper at all." Drafted reply: "Jess, thank you so much! Cooper is lucky to have found you. Rescue dogs hold a special place in our hearts. We can\'t wait to see him for his follow-up!" Ready to post?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '4:45 PM',
      title: 'Weekly practice dashboard',
      description: 'Pruve delivers the weekly numbers: patient visits, revenue, vaccine compliance rate.',
      aiResponse: 'Weekly report: 92 patient visits (up 6%). Revenue: $18,600. Vaccine compliance rate: 78% (target: 85%). Dental procedures: 6 completed ($2,700). Top referral source: Google (34%), word of mouth (28%), Instagram (18%). Alert: Rabies vaccine stock will run out in 3 days at current rate — reorder needed.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 700 },
    },
    {
      time: '6:30 PM',
      title: 'After-hours emergency triage call',
      description: 'Panicked owner calls about their dog eating chocolate — Pruve triages.',
      aiResponse: 'Answered after-hours call: Dog "Rocky" (Lab mix, 70 lbs) ate approximately 4 oz of milk chocolate 30 minutes ago. Based on weight and chocolate type, this is a low-to-moderate toxicity risk. Advised the owner: induce vomiting with hydrogen peroxide (1 tbsp per 20 lbs), monitor for symptoms, and go to the 24-hour ER if vomiting or tremors start. Sent the nearest emergency vet address. Logged for Dr. Nguyen\'s follow-up tomorrow.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:00 PM',
      title: 'Pharmaceutical supplier price check',
      description: 'Pruve compares pricing on heartworm prevention and flea/tick medications across distributors.',
      aiResponse: 'Heartworm/flea-tick pricing comparison: Heartgard Plus (6-pack, 26–50 lbs) — Covetrus $38, Patterson Vet $41, VetSource $36. NexGard (6-pack, 24–60 lbs) — Covetrus $112, Patterson $118, VetSource $105. Switching both to VetSource saves $9/unit. At 40 units/month, that\'s $360/month saved. Shall I set up the new account?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 360 },
    },
  ],
  capabilityExamples: {
    communication: 'Triages pet health photos, explains procedures, and provides cost estimates',
    memory: 'Stores each pet\'s vaccine history, allergies, weight trends, and behavioral notes',
    proactive: 'Sends vaccination reminders, post-surgery check-ins, and low-stock alerts',
    bookings: 'Manages vaccine visit scheduling, surgery follow-ups, and dental exam bookings',
    leads: 'Captures new puppy and kitten registrations with wellness package offers',
    revenue: 'Drives seasonal prevention campaigns (heartworm, flea/tick) to the full client list',
    reputation: 'Responds to heartfelt pet stories and rescue adoption reviews',
    content: 'Creates pet safety tips, seasonal health awareness posts, and patient spotlights',
    reporting: 'Weekly visit volume, vaccine compliance rate, and referral source tracking',
    browser: 'Compares pharmaceutical and supply pricing across veterinary distributors',
    team: 'Vet techs check surgery schedules and update post-op notes via chat',
    workflow: 'Auto-sends post-visit care instructions based on diagnosis and treatment',
    voice: 'Triages after-hours emergency calls with toxicity calculators and ER referrals',
    multiagent: 'Separate agents for client communication and inventory management',
    environment: 'Controls kennel area monitors showing pet names and care instructions',
  },
  stats: {
    messagesPerDay: 55,
    bookingsPerWeek: 45,
    monthlySavings: 4800,
    responseTime: '< 20 seconds',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Vet clinics handle life-or-death calls after hours and benefit enormously from voice triage, pharmaceutical cost optimization, and proactive care reminders.',
};

/* ------------------------------------------------------------------ */
/* EXPORT                                                              */
/* ------------------------------------------------------------------ */

export const healthIndustries: Industry[] = [
  spa,
  nailsalon,
  hairsalon,
  gym,
  yoga,
  dental,
  optometrist,
  medical,
  vet,
];
