/* ================================================================
   HOME SERVICES INDUSTRIES
   10 industries, 12 unique day-events each (6 AM – 10 PM)
   ================================================================ */

import type { Industry } from '../experience-data';

/* ------------------------------------------------------------------ */
/* 1. PLUMBER / HVAC                                                    */
/* ------------------------------------------------------------------ */

const plumber: Industry = {
  id: 'plumber',
  label: 'Plumber / HVAC',
  emoji: '🔧',
  category: 'Home Services',
  tagline: 'Never miss an emergency call — AI handles dispatch, quotes, and follow-ups 24/7.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning briefing delivered',
      description: 'AI compiles overnight emergency requests, today\'s 5 scheduled jobs, and 2 outstanding invoices.',
      aiResponse: 'Good morning! You have 5 jobs today. Priority: burst pipe at 412 Oak St (emergency, dispatched Mike). 2 invoices overdue — reminders sent automatically.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:15 AM',
      title: 'Emergency leak call received',
      description: 'Homeowner calls about water flooding their basement. AI answers the phone and gathers details.',
      aiResponse: 'I understand you have standing water in your basement. I\'ve captured your address and photos. Our nearest technician can arrive by 8:30 AM. I\'ve scheduled the emergency visit and sent you a confirmation text.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:00 AM',
      title: 'Water heater installation quote',
      description: 'Customer requests a quote for a tankless water heater installation via WhatsApp.',
      aiResponse: 'Great question! A tankless water heater installation typically runs $2,800–$4,200 depending on the model and gas line requirements. I\'ve scheduled a free assessment for Thursday at 10 AM so we can give you an exact price. Sound good?',
      channel: 'whatsapp',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:30 AM',
      title: 'Google review response',
      description: 'New 5-star review mentions fast response to a weekend emergency. AI replies within minutes.',
      aiResponse: 'Thank you so much, David! We\'re glad our team got there quickly on Saturday. We know plumbing emergencies don\'t wait — neither do we. Thanks for trusting us with your home!',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '10:15 AM',
      title: 'Pipe repair scheduling conflict',
      description: 'Customer wants to reschedule their pipe repair. AI checks availability and adjusts.',
      aiResponse: 'No problem at all! I\'ve moved your pipe repair from Tuesday 2 PM to Wednesday 9 AM. Your technician will be Carlos — he specializes in copper pipe work. Confirmation sent to your email.',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:00 AM',
      title: 'HVAC maintenance reminder campaign',
      description: 'AI identifies 47 customers due for annual furnace maintenance and sends personalized messages.',
      aiResponse: 'Hi Mrs. Patterson! It\'s been 11 months since your furnace tune-up. We\'re booking fall maintenance now — early birds get 15% off. Want me to reserve your usual Thursday morning slot?',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 320 },
    },
    {
      time: '12:30 PM',
      title: 'Instagram DM for clogged drain',
      description: 'A potential customer messages on Instagram asking about drain cleaning pricing.',
      aiResponse: 'Hey! Drain cleaning starts at $149 for standard clogs. If it\'s a main sewer line, we bring the camera out first ($99 inspection). Where\'s the clog — kitchen, bathroom, or basement? I can get you on the schedule today!',
      channel: 'instagram',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:45 PM',
      title: 'Supplier price check for parts',
      description: 'AI browses supplier websites to compare prices on PEX fittings needed for tomorrow\'s job.',
      aiResponse: 'Price check complete: Ferguson has 1/2" PEX fittings at $3.42/ea (vs. $4.10 at SupplyHouse). I\'ve added 50 units to your Ferguson cart — total $171.00, within your $200 pre-approved limit. Shall I place the order?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 34 },
    },
    {
      time: '3:00 PM',
      title: 'Overdue invoice follow-up',
      description: 'AI sends a friendly payment reminder for a $1,200 water heater job completed 14 days ago.',
      aiResponse: 'Hi Mr. Gomez! Just a friendly reminder that invoice #1847 for $1,200 is due. I\'ve attached the invoice again for convenience. You can pay online via the link below. Let me know if you have any questions!',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 1200 },
    },
    {
      time: '4:30 PM',
      title: 'Technician job completion update',
      description: 'Field tech messages the AI with job completion details and photos from a slab leak repair.',
      aiResponse: 'Got it, Carlos! I\'ve logged the completion for 412 Oak St — slab leak repaired, 6 hours labor. Photos uploaded to the customer file. Invoice #1902 generated for $3,400 and sent to the homeowner. Review request scheduled for tomorrow morning.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '6:00 PM',
      title: 'Facebook lead from ad campaign',
      description: 'New lead fills out a Facebook form for a bathroom remodel plumbing estimate.',
      aiResponse: 'Hi Sarah! Thanks for your interest in bathroom remodel plumbing. I have a few quick questions: How many bathrooms? Are you moving any fixtures? I\'ve reserved a consultation slot for you this Friday at 11 AM — does that work?',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:00 PM',
      title: 'End-of-day summary',
      description: 'AI sends the owner a summary of the day: jobs completed, revenue, tomorrow\'s schedule.',
      aiResponse: 'Day complete! 5 jobs finished, $8,700 invoiced. 3 new leads captured (2 scheduled). Tomorrow: 4 jobs starting at 8 AM. Cash flow note: $3,600 in receivables past 7 days — follow-ups queued.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Answers WhatsApp, Instagram, Facebook, and SMS simultaneously — customers never wait.',
    memory: 'Remembers every home\'s plumbing history — pipe material, past repairs, warranty dates.',
    proactive: 'Morning briefing with emergency flags, schedule gaps, and overdue invoices.',
    bookings: 'Books service calls, sends reminders, reschedules conflicts, fills cancelled slots.',
    leads: 'Pre-qualifies every lead — emergency vs. routine, residential vs. commercial.',
    revenue: 'Chases unpaid invoices at 7, 14, 30 days and sends seasonal maintenance offers.',
    reputation: 'Responds to every Google and Yelp review within the hour.',
    content: 'Creates weekly plumbing tip posts and seasonal HVAC maintenance reminders.',
    reporting: 'Weekly report: jobs completed, close rate, average ticket, revenue by technician.',
    browser: 'Browses supplier sites, compares part prices, places orders within budget.',
    team: 'Technicians message AI for part lookups, schedule changes, and job notes.',
    workflow: 'Syncs job completions to QuickBooks, updates CRM, triggers review requests.',
    voice: 'Answers emergency calls 24/7, captures details, dispatches nearest technician.',
    multiagent: 'Runs separate agents for dispatch, invoicing, and customer follow-up simultaneously.',
    environment: 'Reads smart water sensor alerts and proactively contacts affected customers.',
  },
  stats: {
    messagesPerDay: 45,
    bookingsPerWeek: 22,
    monthlySavings: 4200,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Plumbing businesses need proactive invoice chasing and reputation management to grow. The Manager tier recovers revenue and builds your online presence automatically.',
};

/* ------------------------------------------------------------------ */
/* 2. ELECTRICIAN                                                       */
/* ------------------------------------------------------------------ */

const electrician: Industry = {
  id: 'electrician',
  label: 'Electrician',
  emoji: '⚡',
  category: 'Home Services',
  tagline: 'From panel upgrades to emergency outages — AI keeps your schedule full and customers informed.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Daily schedule and priority alerts',
      description: 'AI delivers the day\'s 6 appointments, highlights a panel upgrade requiring permit pickup, and flags an emergency callback.',
      aiResponse: 'Morning! 6 jobs today. Priority: the Garcia panel upgrade needs the permit picked up from City Hall by 9 AM. Also, emergency callback from last night — homeowner lost power to half their house. I\'ve slotted them at 7:30 AM.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:00 AM',
      title: 'Emergency power outage call',
      description: 'Homeowner calls at 7 AM — half their house has no power after a storm. AI handles intake.',
      aiResponse: 'I\'m sorry you\'re dealing with that. It sounds like a partial panel failure or a tripped main breaker. I have an electrician available at 7:30 AM this morning. I\'ve texted you a safety checklist — please don\'t touch the panel until we arrive.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'EV charger installation inquiry',
      description: 'Customer sends WhatsApp message asking about Level 2 EV charger installation for their Tesla.',
      aiResponse: 'Great timing! Level 2 EV charger installation runs $800–$1,500 depending on your panel capacity and distance from the garage. We\'ll need to check if your panel can handle the 50-amp circuit. Free assessment available tomorrow at 10 AM — interested?',
      channel: 'whatsapp',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Panel upgrade job confirmed',
      description: 'AI sends confirmation and pre-job checklist to customer whose 200-amp panel upgrade is scheduled for next week.',
      aiResponse: 'Hi Mr. Chen! Your 200-amp panel upgrade is confirmed for Monday at 8 AM. The job takes 6–8 hours. Please note: power will be off for most of the day. Here\'s a checklist to prepare. Any questions before then?',
      channel: 'email',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'Negative review detected and flagged',
      description: 'AI detects a 2-star Google review mentioning "messy wiring" and alerts the owner with a draft response.',
      aiResponse: 'Alert: 2-star review from James K. — mentions "messy wiring left behind." Draft response: "James, we take workmanship seriously. I\'d like to send our lead electrician back at no charge to address this. Please contact us directly." Approve or edit?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '11:30 AM',
      title: 'Whole-home rewiring lead qualification',
      description: 'Facebook lead requests a quote for rewiring a 1960s home. AI qualifies with targeted questions.',
      aiResponse: 'Hi Lisa! Rewiring a 1960s home is a smart safety investment. A few quick questions: How many square feet? Do you still have a fuse box or breakers? Any knob-and-tube wiring visible? This helps me give you an accurate range before we schedule the walkthrough.',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:45 PM',
      title: 'Weekly content post scheduled',
      description: 'AI creates and schedules an Instagram post about electrical safety during storm season.',
      aiResponse: 'Post ready: "Storm season is here ⚡ 5 signs your home\'s electrical system needs attention before the next big one hits." Includes carousel with tips and before/after surge protector photos. Scheduled for tomorrow at 9 AM. Approve?',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '2:00 PM',
      title: 'Apprentice asks about wire gauge',
      description: 'Junior electrician messages the AI asking what wire gauge to use for a 30-amp dryer circuit.',
      aiResponse: 'For a 30-amp dryer circuit, use 10 AWG copper wire (or 8 AWG aluminum). The run from the panel to the laundry room is about 45 feet based on the blueprints on file — 10 AWG copper is fine for that distance. Need me to add wire to the supply order?',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
    {
      time: '3:15 PM',
      title: 'Permit status check automated',
      description: 'AI checks the city\'s online permit portal for the status of 3 pending electrical permits.',
      aiResponse: 'Permit update: Garcia panel upgrade — APPROVED (pick up today). Johnson rewire — PENDING (submitted 5 days ago, typical wait is 7). Miller EV charger — APPROVED (attached). I\'ll keep checking Johnson daily.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
    },
    {
      time: '4:30 PM',
      title: 'Upsell opportunity detected',
      description: 'AI notices a customer booked for outlet repair also has an outdated panel and suggests mentioning an upgrade.',
      aiResponse: 'Note: Tomorrow\'s 2 PM outlet repair at the Rivera home — their records show a Federal Pacific panel (known fire hazard). Consider mentioning a panel upgrade during the visit. I can prepare a quote sheet if you\'d like.',
      channel: 'system',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'savings', increment: 450 },
    },
    {
      time: '6:30 PM',
      title: 'SMS follow-up on completed job',
      description: 'AI sends a thank-you text and review request to today\'s ceiling fan installation customer.',
      aiResponse: 'Hi Angela! Hope you\'re enjoying the new ceiling fan. If everything looks great, we\'d really appreciate a quick Google review — it helps other homeowners find reliable electricians. Here\'s the link: [review link]. Thank you!',
      channel: 'sms',
      capability: 'reputation',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 PM',
      title: 'End-of-day financial snapshot',
      description: 'AI delivers daily revenue summary and flags a large outstanding invoice.',
      aiResponse: 'Daily wrap: 6 jobs completed, $5,200 invoiced. New leads: 3 (EV charger, rewire, outlet repair). Outstanding: $8,400 total — the $4,200 commercial job from 3 weeks ago needs escalation. Weekly report drops Monday at 7 AM.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Responds across WhatsApp, phone, email, and Facebook — customers always get answers fast.',
    memory: 'Tracks every home\'s panel type, wiring age, past jobs, and code compliance history.',
    proactive: 'Flags permit pickups, emergency callbacks, and weather-related surge in service calls.',
    bookings: 'Schedules jobs around permit timelines and coordinates multi-day projects.',
    leads: 'Pre-qualifies leads by service type — EV charger, panel upgrade, emergency, rewire.',
    revenue: 'Chases invoices and detects upsell opportunities from customer service history.',
    reputation: 'Monitors reviews, flags negative ones instantly, and requests reviews after every job.',
    content: 'Creates storm prep tips, energy savings guides, and EV charger educational content.',
    reporting: 'Weekly report: revenue per electrician, close rate by service type, permit pipeline.',
    browser: 'Checks permit portals, compares supplier prices, orders materials automatically.',
    team: 'Apprentices message AI for code references, wire gauges, and parts lookups.',
    workflow: 'Syncs completed jobs to accounting, updates permit tracker, generates invoices.',
    voice: 'Answers emergency calls, assesses urgency, dispatches the nearest available electrician.',
    multiagent: 'Separate agents for dispatch, permit tracking, and customer communications.',
    environment: 'Monitors smart panel alerts and proactively contacts homeowners about electrical anomalies.',
  },
  stats: {
    messagesPerDay: 38,
    bookingsPerWeek: 18,
    monthlySavings: 3800,
    responseTime: '< 45 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Electricians benefit from reputation management and content marketing to stand out. The Manager tier builds your brand and recovers revenue from unpaid commercial jobs.',
};

/* ------------------------------------------------------------------ */
/* 3. GENERAL CONTRACTOR                                                */
/* ------------------------------------------------------------------ */

const contractor: Industry = {
  id: 'contractor',
  label: 'General Contractor',
  emoji: '🏠',
  category: 'Home Services',
  tagline: 'Coordinate subs, manage permits, and keep clients informed — AI runs the project office.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Project status briefing',
      description: 'AI summarizes 4 active projects, flagging a delayed drywall delivery and a permit inspection due today.',
      aiResponse: 'Morning! 4 active projects. Heads up: drywall delivery for the Martinez kitchen is delayed to Thursday (was Tuesday). Permit inspection at 221 Elm St today at 11 AM — make sure framing is exposed. All subs confirmed for today.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:30 AM',
      title: 'Kitchen renovation quote request',
      description: 'Homeowner emails asking for a complete kitchen renovation estimate with photos of existing space.',
      aiResponse: 'Hi Karen! Thanks for the photos — beautiful space with great bones. A full kitchen renovation typically ranges from $35K–$65K depending on cabinetry, countertops, and whether we\'re moving plumbing or electrical. I\'d love to schedule a walkthrough — how\'s Thursday at 2 PM?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Subcontractor schedule coordination',
      description: 'AI messages the plumbing and electrical subs to confirm their start dates on the bathroom remodel.',
      aiResponse: 'Schedule update: Plumber (Ray) confirmed for Monday 8 AM — rough-in day. Electrician (Maria\'s team) starts Tuesday. I\'ve built a 2-day buffer before drywall. Both subs have the project specs and access codes.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
    {
      time: '9:30 AM',
      title: 'Permit question from homeowner',
      description: 'Client asks on WhatsApp whether they need a permit for their deck addition and who handles it.',
      aiResponse: 'Yes, a deck over 200 sq ft requires a building permit in your county. Don\'t worry — we handle the entire permit process. I\'ve already started the application based on your plans. Typical approval takes 10–14 business days. I\'ll keep you updated!',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'Material cost comparison',
      description: 'AI browses three supplier websites to find the best price on LVP flooring for an ongoing project.',
      aiResponse: 'Flooring comparison complete: Lumber Liquidators — $3.29/sqft (sale ends Friday), Home Depot — $3.89/sqft, Floor & Decor — $3.49/sqft. For 800 sqft, Lumber Liquidators saves $480. Want me to reserve at the sale price?',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 480 },
    },
    {
      time: '11:45 AM',
      title: 'Client progress update with photos',
      description: 'AI compiles today\'s job site photos from the foreman and sends a progress update to the homeowner.',
      aiResponse: 'Hi Tom! Here\'s your Tuesday update on the basement finish-out: framing is 100% complete, electrical rough-in starts tomorrow. See attached photos. We\'re on track for drywall next Monday. Any questions?',
      channel: 'email',
      capability: 'workflow',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '1:00 PM',
      title: 'Change order request processed',
      description: 'Homeowner wants to upgrade countertops from laminate to quartz mid-project. AI calculates the price difference.',
      aiResponse: 'Great choice! Upgrading to quartz countertops adds $4,200 to the project (materials + fabrication + install). This won\'t affect the timeline — we can order today for delivery in 10 days. I\'ve prepared the change order. Want to proceed?',
      channel: 'whatsapp',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 4200 },
    },
    {
      time: '2:30 PM',
      title: 'Google review reply for completed project',
      description: 'AI responds to a glowing 5-star review about a recent bathroom remodel.',
      aiResponse: 'Thank you so much, Jennifer! It was a pleasure transforming your master bath. Your tile selection was spot-on — the herringbone pattern looks stunning. We appreciate you trusting us with your home. Enjoy!',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '3:30 PM',
      title: 'New Facebook lead for addition',
      description: 'Potential customer inquires about a home addition on Facebook. AI captures details and qualifies the lead.',
      aiResponse: 'Hi Mark! A home addition is a great way to add space. To give you a ballpark: What size are you thinking (approx. sq ft)? Will it include a bathroom or kitchen? Do you have a rough budget in mind? I\'ll match you with the right project manager.',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '5:00 PM',
      title: 'Invoice generated for milestone payment',
      description: 'AI generates the second milestone invoice for the Martinez kitchen renovation — 50% completion.',
      aiResponse: 'Invoice #2034 generated for the Martinez kitchen — Milestone 2 (50% completion): $16,250. Breakdown attached: demolition, framing, plumbing rough-in, electrical rough-in. Sent to client with online payment link.',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '7:00 PM',
      title: 'Before/after project showcase post',
      description: 'AI creates a before/after Instagram carousel for a recently completed deck project.',
      aiResponse: 'Post ready: "From old concrete patio to a 400 sqft composite deck with built-in lighting. Swipe to see the transformation!" 6-image carousel with before/after pairs. Scheduled for Saturday at 10 AM for peak engagement. Approve?',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '9:30 PM',
      title: 'Weekly project pipeline report',
      description: 'AI delivers the weekly report covering all active projects, pending bids, and cash flow.',
      aiResponse: 'Weekly report: 4 active projects ($142K total contract value), 3 pending bids ($87K), 2 completed this month ($53K invoiced). Cash flow: $28K received, $16K outstanding. Busiest week ahead — all subs confirmed. Detailed breakdown attached.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Keeps homeowners updated across WhatsApp and email — no more "when will it be done?" calls.',
    memory: 'Tracks every project detail — change orders, material selections, sub schedules, permit dates.',
    proactive: 'Flags delayed deliveries, upcoming inspections, and sub no-shows before they become problems.',
    bookings: 'Schedules walkthroughs, coordinates sub start dates, and manages inspection timelines.',
    leads: 'Qualifies renovation leads by scope, budget, and timeline before the first meeting.',
    revenue: 'Generates milestone invoices, tracks change orders, and chases payments automatically.',
    reputation: 'Responds to reviews and sends review requests after project completion.',
    content: 'Creates before/after showcases, project progress posts, and seasonal tips.',
    reporting: 'Weekly pipeline report: active projects, pending bids, cash flow, and sub utilization.',
    browser: 'Compares material prices across suppliers and reserves sale-priced items.',
    team: 'Coordinates subs, shares specs, and tracks task completion across crews.',
    workflow: 'Syncs project milestones to accounting, updates Gantt charts, files permits.',
    voice: 'Answers client calls with real-time project status and schedules site visits.',
    multiagent: 'Separate agents for project management, client communication, and procurement.',
    environment: 'Monitors weather forecasts and adjusts outdoor work schedules proactively.',
  },
  stats: {
    messagesPerDay: 52,
    bookingsPerWeek: 8,
    monthlySavings: 6500,
    responseTime: '< 1 minute',
  },
  recommendedTier: 'executive',
  recommendationReason: 'General contractors juggle subs, permits, clients, and materials. The Executive tier coordinates your entire operation — team management, browser-based procurement, and automated project updates.',
};

/* ------------------------------------------------------------------ */
/* 4. LANDSCAPING / LAWN CARE                                           */
/* ------------------------------------------------------------------ */

const landscaping: Industry = {
  id: 'landscaping',
  label: 'Landscaping / Lawn Care',
  emoji: '🌿',
  category: 'Home Services',
  tagline: 'Fill your route, automate recurring schedules, and grow with zero office staff.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Route and weather briefing',
      description: 'AI delivers today\'s 8-property route, optimized for drive time, plus a weather alert for afternoon rain.',
      aiResponse: 'Good morning! 8 properties today, route optimized — start at Maple Ct, end at Riverside Dr (saves 22 min). Weather alert: rain expected after 3 PM. I\'ve moved the Henderson edging job to tomorrow and pulled forward the Garcia mulch delivery.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:15 AM',
      title: 'Weekly mowing schedule confirmation',
      description: 'AI sends weekly mowing confirmations to all 32 recurring residential clients.',
      aiResponse: 'Hi Mrs. Taylor! Just confirming your weekly lawn service for today between 10–11 AM. Our crew will handle mowing, edging, and blowing. Gate code still 4521? Let me know if anything changes!',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 32 },
    },
    {
      time: '8:30 AM',
      title: 'New customer inquiry for lawn service',
      description: 'Potential customer texts asking about weekly lawn care pricing for a half-acre lot.',
      aiResponse: 'Hi! For a half-acre lot, our weekly full-service (mow, edge, blow) runs $55/week. We also offer bi-weekly at $70/visit. First service includes a free assessment. I have openings on Tuesdays and Fridays — which works better?',
      channel: 'sms',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Seasonal cleanup quote on Instagram',
      description: 'Homeowner sends an Instagram DM requesting a fall leaf cleanup quote with yard photos.',
      aiResponse: 'Thanks for the photos! Based on the yard size and tree coverage, a full fall cleanup would be $350–$450 (leaf removal, bed cleanup, gutter clearing). We\'re booking up fast for October — want me to lock in a date? We can do as early as next Saturday.',
      channel: 'instagram',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:00 AM',
      title: 'Irrigation repair scheduling',
      description: 'Existing client reports a broken sprinkler head via WhatsApp. AI schedules the repair.',
      aiResponse: 'Oh no! I can see from your records you have a Rain Bird system installed last spring. Our irrigation tech has an opening tomorrow at 8 AM. Sprinkler head replacement is typically $75–$120. I\'ve booked the slot — he\'ll bring the right parts. Confirmation sent!',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '12:00 PM',
      title: 'Crew lunch break — review request sent',
      description: 'AI sends a review request to the property completed this morning.',
      aiResponse: 'Hi Mr. Adams! Your lawn is looking fresh! If you\'re happy with today\'s service, a quick Google review would mean the world to us. Here\'s the link: [review link]. We appreciate your continued trust! 🌿',
      channel: 'sms',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '1:30 PM',
      title: 'Mulch and materials reorder',
      description: 'AI detects mulch inventory is running low and compares prices at two local suppliers.',
      aiResponse: 'Mulch alert: down to 3 cubic yards — you need 12 for this week\'s jobs. Green Earth Landscaping Supply has premium hardwood mulch at $38/yd (vs. $44 at SiteOne). Total for 12 yards: $456. Delivery available Thursday AM. Order placed — within your $500 limit.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 72 },
    },
    {
      time: '2:30 PM',
      title: 'Upsell: aeration and overseeding',
      description: 'AI identifies 18 mowing clients whose lawns would benefit from fall aeration and sends offers.',
      aiResponse: 'Hi Mrs. Chen! Fall is the perfect time for lawn aeration and overseeding — it helps your grass come back thicker in spring. We\'re offering 20% off for existing clients this month. Your half-acre lot would be $280 (normally $350). Interested?',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 280 },
    },
    {
      time: '3:45 PM',
      title: 'Rain delay customer notifications',
      description: 'Rain starts early — AI automatically notifies remaining clients about the delay.',
      aiResponse: 'Hi! Due to this afternoon\'s rain, we\'re rescheduling your lawn service to Thursday. Same time window (2–3 PM). Sorry for the inconvenience — we\'ll make sure your yard looks great! No action needed from you.',
      channel: 'sms',
      capability: 'workflow',
      tier: 'executive',
      stat: { key: 'messages', increment: 4 },
    },
    {
      time: '5:00 PM',
      title: 'Landscape design lead follow-up',
      description: 'AI follows up with a lead from 3 days ago who inquired about a patio and garden design.',
      aiResponse: 'Hi Jason! Following up on your patio and garden design inquiry. I wanted to share a few photos of similar projects we\'ve completed in your neighborhood. Would you still like to schedule a design consultation? We have availability this weekend.',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:00 PM',
      title: 'Social media content posted',
      description: 'AI posts a time-lapse video of today\'s hedge trimming transformation.',
      aiResponse: 'Posted! "From overgrown to pristine in 45 minutes. Swipe for the before shot." Time-lapse video with upbeat music. Reached 1,200 accounts on last similar post. Also drafted next week\'s content: spring lawn prep tips series.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '8:30 PM',
      title: 'Daily revenue and route summary',
      description: 'AI delivers the day\'s summary: properties serviced, revenue, and tomorrow\'s optimized route.',
      aiResponse: 'Day summary: 7 of 8 properties completed (1 rain delay rescheduled). Revenue: $785. New leads: 2 (cleanup + design). Tomorrow: 9 properties, clear skies, route starts at 7 AM. Fuel expense today: $42.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Sends service confirmations and handles all customer messages across SMS and WhatsApp.',
    memory: 'Knows every property — lot size, grass type, irrigation system, gate codes, pet warnings.',
    proactive: 'Weather-aware scheduling — adjusts routes and notifies clients before rain hits.',
    bookings: 'Manages recurring weekly schedules for 30+ clients and fills open route slots.',
    leads: 'Qualifies new leads by lot size, service frequency, and neighborhood route fit.',
    revenue: 'Sends seasonal upsell offers and chases unpaid invoices for one-time jobs.',
    reputation: 'Requests reviews after every service and responds to all Google reviews.',
    content: 'Posts time-lapse transformations, seasonal tips, and before/after project photos.',
    reporting: 'Daily route summary with revenue, fuel costs, and properties serviced.',
    browser: 'Compares mulch and material prices, orders supplies at the best price.',
    team: 'Crew leads report job completion and flag issues via WhatsApp to the AI.',
    workflow: 'Syncs completed jobs to billing, updates route optimization, tracks supplies.',
    voice: 'Answers calls from new customers, quotes based on address lookup, books the first visit.',
    multiagent: 'Separate agents for route planning, customer communications, and supply ordering.',
    environment: 'Reads weather station data to make real-time scheduling decisions.',
  },
  stats: {
    messagesPerDay: 55,
    bookingsPerWeek: 35,
    monthlySavings: 3200,
    responseTime: '< 2 minutes',
  },
  recommendedTier: 'operator',
  recommendationReason: 'Landscaping businesses run on tight recurring schedules. The Operator tier handles all client communication, booking confirmations, and reminders — so you can focus on the work.',
};

/* ------------------------------------------------------------------ */
/* 5. CLEANING SERVICE                                                  */
/* ------------------------------------------------------------------ */

const cleaning: Industry = {
  id: 'cleaning',
  label: 'Cleaning Service',
  emoji: '🧹',
  category: 'Home Services',
  tagline: 'Book recurring cleans, manage your team, and never lose a client to a missed message.',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Team assignments and daily schedule',
      description: 'AI distributes today\'s 6 cleaning assignments to 3 two-person teams with addresses and special instructions.',
      aiResponse: 'Morning! Today\'s assignments: Team A — 2 deep cleans (Anderson home, Park condo). Team B — 3 recurring cleans (weekly clients). Team C — 1 move-out clean at Maple Apartments #204. Special note: Anderson has a cat — use pet-safe products. All addresses and access codes sent.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:30 AM',
      title: 'Recurring deep clean confirmation',
      description: 'AI sends confirmation to bi-weekly deep clean client with arrival time and checklist.',
      aiResponse: 'Hi Rachel! Your bi-weekly deep clean is confirmed for today, 9 AM–12 PM. Our team will cover all rooms plus oven, fridge interior, and baseboards. Alarm code still 7890? See you soon!',
      channel: 'sms',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:15 AM',
      title: 'Move-out cleaning quote via WhatsApp',
      description: 'Property manager asks for a move-out cleaning quote for a 2-bedroom apartment.',
      aiResponse: 'Hi Diana! A move-out clean for a 2-bed/1-bath apartment runs $250–$350 depending on condition. That includes deep clean of kitchen, bathrooms, all floors, windows, and inside cabinets. When is the move-out date? I can get a team there same-day or next-day.',
      channel: 'whatsapp',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:30 AM',
      title: 'Supply inventory and reorder alert',
      description: 'AI detects low stock on all-purpose cleaner, microfiber cloths, and trash bags. Auto-orders from preferred supplier.',
      aiResponse: 'Supply alert: All-purpose cleaner (2 gallons left, need 10), microfiber cloths (8 left, need 30), trash bags (1 box left, need 5). Order placed with CleanPro Supply — $187.50, arriving Thursday. All within monthly supply budget.',
      channel: 'system',
      capability: 'workflow',
      tier: 'executive',
      stat: { key: 'savings', increment: 188 },
    },
    {
      time: '10:45 AM',
      title: 'Client complaint handled proactively',
      description: 'Returning client messages that the team missed the guest bathroom last visit. AI apologizes and schedules a fix.',
      aiResponse: 'I\'m so sorry about that, Mrs. Kim! I\'ve noted this in your file so it won\'t happen again. I\'d like to send a team member back tomorrow morning to take care of the guest bathroom at no charge. Does 9 AM work? We value your loyalty.',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:00 PM',
      title: 'Google review response',
      description: 'AI replies to a 5-star review praising the team\'s attention to detail.',
      aiResponse: 'Thank you so much, Emily! We\'re thrilled to hear the team did a fantastic job. Attention to detail is what we pride ourselves on. Looking forward to your next clean! Thank you for the wonderful review.',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '1:00 PM',
      title: 'Overdue payment follow-up',
      description: 'AI sends a gentle payment reminder for a $450 deep clean completed 10 days ago.',
      aiResponse: 'Hi Mr. Brooks! Just a friendly reminder that your deep clean invoice (#3021, $450) is now 10 days past due. I\'ve attached the invoice with a convenient online payment link. Please let me know if you have any questions!',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 450 },
    },
    {
      time: '2:15 PM',
      title: 'Airbnb turnover cleaning request',
      description: 'Airbnb host requests an urgent turnover clean — guests checking in at 4 PM today.',
      aiResponse: 'Got it! I have Team C finishing up at 2:30 PM nearby. They can be at your property by 3 PM for a full turnover clean (linens, bathrooms, kitchen, floors, restock supplies). That gives an hour buffer before check-in. Confirming now!',
      channel: 'phone',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '3:30 PM',
      title: 'Team member reports job completion',
      description: 'Team B lead messages the AI confirming all 3 recurring cleans are done with photos.',
      aiResponse: 'Great work, Team B! All 3 jobs logged. Photos look excellent. Hours tracked: 6.5 total. I\'ve sent satisfaction check-ins to all 3 clients and queued review requests. Tomorrow you\'re at the Walker residence at 8 AM — deep clean, 4-bedroom.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
    },
    {
      time: '4:45 PM',
      title: 'Seasonal promotion email blast',
      description: 'AI creates and sends a spring deep clean promotion to 120 past customers.',
      aiResponse: 'Spring clean promo sent to 120 past clients: "Spring into a Fresh Home — 20% off deep cleans booked this week!" Personalized with each client\'s last service date. Expected response based on past campaigns: 8–12 bookings.',
      channel: 'email',
      capability: 'content',
      tier: 'manager',
      stat: { key: 'savings', increment: 960 },
    },
    {
      time: '6:30 PM',
      title: 'New employee onboarding task created',
      description: 'AI detects a new hire starting Monday and prepares the onboarding checklist automatically.',
      aiResponse: 'New hire alert: Jessica starts Monday. I\'ve prepared: training checklist, supply kit assignment, first-week buddy pairing with Sarah. Background check cleared. She\'s been added to Team A for her training week. Welcome message drafted — want to review?',
      channel: 'system',
      capability: 'workflow',
      tier: 'executive',
    },
    {
      time: '9:00 PM',
      title: 'End-of-day summary and weekly outlook',
      description: 'AI delivers the day\'s stats and previews the rest of the week.',
      aiResponse: 'Day done! 6 cleans completed, $1,680 revenue. Client satisfaction: 100% (all check-ins positive). Supplies ordered for Thursday. Tomorrow: 7 cleans, all confirmed. This week total so far: $4,200 — on track for a $12K month.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Handles all booking requests across WhatsApp, phone, Instagram, and email.',
    memory: 'Remembers every client\'s preferences — pet-safe products, alarm codes, locked rooms, special instructions.',
    proactive: 'Sends team assignments each morning with addresses, codes, and special notes.',
    bookings: 'Manages 30+ recurring cleans, handles cancellations, and fills open slots.',
    leads: 'Qualifies new leads by home size, frequency, and service type (recurring, one-time, move-out).',
    revenue: 'Chases overdue invoices and sends seasonal promotions to past clients.',
    reputation: 'Sends satisfaction check-ins after every clean and requests Google reviews.',
    content: 'Creates cleaning tips content, seasonal promos, and before/after transformation posts.',
    reporting: 'Daily revenue summary, team utilization, client retention rate tracking.',
    browser: 'Orders cleaning supplies from preferred vendors at the best available price.',
    team: 'Distributes daily assignments, tracks job completion, coordinates urgent requests.',
    workflow: 'Syncs job completions to invoicing, tracks supply usage, manages employee schedules.',
    voice: 'Answers booking calls, provides instant quotes based on home size, schedules the first clean.',
    multiagent: 'Separate agents for scheduling, team dispatch, and customer retention.',
    environment: 'Smart lock integration — grants team access codes and revokes after job completion.',
  },
  stats: {
    messagesPerDay: 48,
    bookingsPerWeek: 28,
    monthlySavings: 3600,
    responseTime: '< 1 minute',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Cleaning services thrive on recurring revenue and client retention. The Manager tier automates follow-ups, seasonal promotions, and reputation management to keep clients coming back.',
};

/* ------------------------------------------------------------------ */
/* 6. SECURITY / LOCKSMITH                                              */
/* ------------------------------------------------------------------ */

const security: Industry = {
  id: 'security',
  label: 'Security / Locksmith',
  emoji: '🔒',
  category: 'Home Services',
  tagline: 'Emergency lockouts, alarm monitoring, and security installations — AI dispatches in seconds.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Overnight emergency summary',
      description: 'AI summarizes 3 overnight lockout calls handled and today\'s 4 scheduled security installations.',
      aiResponse: 'Morning! Overnight: 3 lockout calls handled — all dispatched within 4 minutes, all resolved. Revenue: $675. Today: 4 scheduled jobs — 2 camera installations, 1 smart lock upgrade, 1 alarm system install. All techs confirmed.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:00 AM',
      title: 'Emergency lockout call at dawn',
      description: 'Locked-out homeowner calls at 7 AM — keys inside, infant in car. AI prioritizes and dispatches immediately.',
      aiResponse: 'I understand — that\'s stressful, especially with your baby. I\'m dispatching our nearest technician right now. ETA: 12 minutes. His name is Derek, he\'ll arrive in a white van, ID badge #247. Stay near the vehicle. Help is on the way.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'Camera installation inquiry via WhatsApp',
      description: 'Business owner asks about installing a 6-camera security system for their warehouse.',
      aiResponse: 'Hi Carlos! A 6-camera commercial system (1080p with night vision, cloud storage) typically runs $2,200–$3,400 installed. We offer 24/7 monitoring add-on for $49/month. I\'d recommend a site survey first — free, takes 30 minutes. How\'s Thursday at 9 AM?',
      channel: 'whatsapp',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:15 AM',
      title: 'Alarm monitoring alert triaged',
      description: 'AI receives an alarm trigger from a monitored residential client and follows the response protocol.',
      aiResponse: 'Alarm triggered at 847 Pine St — motion sensor in garage. I\'ve called the homeowner: they confirmed it\'s a false alarm (teenager came home early). Alarm reset remotely. Log entry created. No dispatch needed.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Smart lock installation confirmation',
      description: 'AI sends prep instructions to the customer getting smart locks installed today.',
      aiResponse: 'Hi Rebecca! Your smart lock installation is confirmed for today at 1 PM. Our tech will install August Wi-Fi Smart Locks on your front and back doors. Please have your Wi-Fi password ready. The install takes about 90 minutes. See you then!',
      channel: 'email',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:30 AM',
      title: 'Competitor pricing research',
      description: 'AI browses competitor websites to compare pricing on smart lock installation packages.',
      aiResponse: 'Competitor check: SafeHome charges $399/lock installed (we charge $349). SecureNow offers a 2-lock package at $599 (ours is $599 too). Recommendation: create a "Whole Home Smart Lock" package — 3+ locks at $299 each. This undercuts everyone and increases average ticket.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 150 },
    },
    {
      time: '12:30 PM',
      title: 'Rekeying service lead from Google',
      description: 'New homeowner finds the business on Google and calls about rekeying all locks after purchase.',
      aiResponse: 'Congratulations on your new home! Rekeying is a smart first step. For a typical 3-bed home with 4 exterior locks, rekeying runs $180–$240 (vs. $800+ for new locks). We can usually do it same-day. I have an opening today at 4 PM — would that work?',
      channel: 'phone',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '2:00 PM',
      title: 'Monthly monitoring renewal reminders',
      description: 'AI sends renewal reminders to 15 clients whose alarm monitoring subscriptions expire this month.',
      aiResponse: 'Hi Mr. Foster! Your alarm monitoring subscription renews on the 15th. Everything has been working perfectly — zero false alarms this quarter. Your rate stays at $39/month. Auto-renewal is on. Let me know if you have any questions!',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 585 },
    },
    {
      time: '3:30 PM',
      title: 'Technician completes camera install',
      description: 'Tech messages the AI with completion details, test footage, and customer sign-off.',
      aiResponse: 'Logged: 6-camera install at Carlos\'s warehouse complete. Test footage verified — all 6 angles clear, night vision confirmed. Customer signed off. Invoice #4102 for $2,800 sent. Review request scheduled for tomorrow. Great job, Derek!',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '5:00 PM',
      title: 'Google review reply and reputation check',
      description: 'AI responds to two new reviews — one 5-star and one 3-star with constructive feedback.',
      aiResponse: '5-star reply sent to Janet: "Thank you, Janet! Glad we could get you back inside quickly." 3-star from Mike (mentioned wait time): Draft reply: "Mike, we apologize for the 45-minute wait. We\'ve added another technician to evening shifts to reduce response times." Approve?',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '7:00 PM',
      title: 'Security tips content for social media',
      description: 'AI creates a Facebook post about home security tips during vacation season.',
      aiResponse: 'Post ready: "Going on vacation? 5 ways to secure your home before you leave." Includes tips on smart locks, timer lights, camera placement, mail holds, and neighbor alerts. Scheduled for Friday at 11 AM. Includes call-to-action for free security assessment.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '9:30 PM',
      title: 'Daily operations report',
      description: 'AI summarizes the day\'s lockout calls, installations, monitoring events, and revenue.',
      aiResponse: 'Daily report: 4 installations completed ($7,200), 5 lockout calls ($1,125), 1 alarm event (false, resolved). Total revenue: $8,325. Response time average: 14 minutes. New leads: 3. Monitoring clients: 142 active. Tomorrow: 3 installations scheduled.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Handles emergency calls, WhatsApp inquiries, and email quotes around the clock.',
    memory: 'Tracks every client\'s lock types, alarm codes, access history, and service records.',
    proactive: 'Overnight emergency dispatch with morning summary — nothing falls through the cracks.',
    bookings: 'Schedules installations, sends prep instructions, and manages technician availability.',
    leads: 'Qualifies leads by service type — lockout, installation, monitoring, commercial vs. residential.',
    revenue: 'Sends monitoring renewal reminders and follows up on installation quotes.',
    reputation: 'Responds to every review and flags negative feedback for immediate owner attention.',
    content: 'Creates seasonal security tips, smart lock guides, and customer safety content.',
    reporting: 'Daily report: response times, revenue by service type, monitoring alerts handled.',
    browser: 'Researches competitor pricing and sources hardware at the best available cost.',
    team: 'Dispatches nearest technician, tracks job completion, manages on-call rotation.',
    workflow: 'Monitors alarm systems, triages alerts, and logs all events automatically.',
    voice: 'Answers emergency lockout calls 24/7, gathers location, and dispatches within minutes.',
    multiagent: 'Separate agents for emergency dispatch, monitoring, and scheduled installations.',
    environment: 'Integrates with alarm panels and smart locks for remote monitoring and access control.',
  },
  stats: {
    messagesPerDay: 42,
    bookingsPerWeek: 20,
    monthlySavings: 5100,
    responseTime: '< 15 seconds',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Security and locksmith businesses depend on instant response and 24/7 availability. The Executive tier handles phone calls, dispatches techs, and monitors alarm systems autonomously.',
};

/* ------------------------------------------------------------------ */
/* 7. PAINTER / RENOVATIONS                                             */
/* ------------------------------------------------------------------ */

const painter: Industry = {
  id: 'painter',
  label: 'Painter / Renovations',
  emoji: '🎨',
  category: 'Home Services',
  tagline: 'From color consultations to final walkthrough — AI manages every brushstroke of the business.',
  dayEvents: [
    {
      time: '6:30 AM',
      title: 'Daily crew assignments and prep',
      description: 'AI delivers today\'s 3 job assignments with color specs, square footage, and prep requirements.',
      aiResponse: 'Morning! 3 jobs today. Crew 1: Interior — Davis living room and dining room (Benjamin Moore "Revere Pewter", 650 sqft, walls prepped yesterday). Crew 2: Exterior — Thompson house trim and soffits (Sherwin-Williams "Alabaster"). Crew 3: Wallpaper removal at Park residence, then prime.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:30 AM',
      title: 'Room color consultation request',
      description: 'Homeowner messages on Instagram asking for help choosing paint colors for their nursery.',
      aiResponse: 'How exciting — congratulations! For nurseries, soft greens and warm neutrals are trending this year. Some favorites: "Soft Fern" by Benjamin Moore or "Alabaster" by Sherwin-Williams. I can bring color swatches to your home — free 30-minute consultation. How\'s Saturday morning?',
      channel: 'instagram',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'Exterior paint quote via email',
      description: 'Homeowner requests a quote for painting the exterior of their 2,400 sqft two-story home.',
      aiResponse: 'Hi David! An exterior paint job for a 2,400 sqft two-story typically runs $5,500–$8,200 depending on prep work, siding condition, and color changes. We include power washing, scraping, priming, and two coats. I\'d love to schedule a free estimate — how\'s Wednesday at 10 AM?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Wallpaper removal progress update',
      description: 'Crew lead messages that the wallpaper removal is taking longer than estimated due to multiple layers.',
      aiResponse: 'Got it — multiple layers of wallpaper can double the removal time. I\'ve noted this in the Park project file. Adjusted timeline: wallpaper removal today, skim coat tomorrow, prime Thursday. I\'ll update the client now so they\'re not caught off guard.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:30 AM',
      title: 'Paint supply order placed',
      description: 'AI calculates paint needed for next week\'s jobs and orders from the preferred supplier.',
      aiResponse: 'Paint order for next week: 8 gal Benjamin Moore "Simply White" (interior), 12 gal Sherwin-Williams "Iron Ore" (exterior), 4 gal primer. Ordered from Sherwin-Williams Pro account — 30% contractor discount applied. Total: $842. Pickup scheduled for Monday 7 AM.',
      channel: 'system',
      capability: 'browser',
      tier: 'executive',
      stat: { key: 'savings', increment: 360 },
    },
    {
      time: '11:30 AM',
      title: 'Estimate follow-up for pending quote',
      description: 'AI follows up with a homeowner who received an estimate 5 days ago but hasn\'t responded.',
      aiResponse: 'Hi Michelle! Just checking in on the kitchen cabinet painting estimate I sent last week ($2,800 for 22 cabinets, includes sanding, priming, and 2 coats). We have availability starting next Tuesday. Any questions I can answer? Happy to adjust the scope if needed.',
      channel: 'sms',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:45 PM',
      title: 'Client requests color change mid-project',
      description: 'Customer wants to switch accent wall color after seeing the first coat. AI manages the change order.',
      aiResponse: 'No problem at all! Switching the accent wall from "Navy Blue" to "Hale Navy" is a close shade — minimal extra work. Additional cost: $120 for the new gallon and one extra coat. I\'ve updated the project file. The crew will apply the new color tomorrow morning. Sound good?',
      channel: 'whatsapp',
      capability: 'memory',
      tier: 'operator',
      stat: { key: 'savings', increment: 120 },
    },
    {
      time: '2:00 PM',
      title: 'Five-star review response',
      description: 'AI responds to a Google review praising the crew\'s clean work and color recommendation.',
      aiResponse: 'Thank you so much, Karen! We\'re thrilled you love the "Revere Pewter" — it really transformed the space. Our crew takes pride in leaving everything spotless. It was a pleasure working in your home. Enjoy the new look!',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '3:15 PM',
      title: 'Commercial painting lead from Facebook',
      description: 'Property management company inquires about painting 12 apartment units during tenant turnover.',
      aiResponse: 'Hi! We do a lot of apartment turnover painting. For 12 units, we typically price per unit based on size and condition. Standard 1-bed unit runs $600–$900. We can handle 2–3 units per day to match your turnover schedule. Want to set up a walkthrough of a sample unit?',
      channel: 'facebook',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '4:30 PM',
      title: 'Job completion photos and invoice',
      description: 'AI generates the invoice and sends completion photos to the client for the Davis interior job.',
      aiResponse: 'Davis interior job complete! Living room and dining room — "Revere Pewter" with "Simply White" trim. Before/after photos attached. Invoice #5023: $3,200 (includes premium paint, 2 coats, trim work). Online payment link included. Review request scheduled for tomorrow.',
      channel: 'email',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '6:30 PM',
      title: 'Before/after transformation post',
      description: 'AI creates an Instagram reel showcasing today\'s completed living room transformation.',
      aiResponse: 'Reel ready: "From builder beige to Revere Pewter — this living room is giving modern farmhouse." 15-second before/after with trending audio. Hashtags: #homepainting #transformation #interiordesign. Scheduled for tomorrow at 6 PM. Also drafted: "5 paint colors that make small rooms look bigger" blog post.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '9:00 PM',
      title: 'Weekly business performance report',
      description: 'AI delivers the weekly report with revenue, job count, lead pipeline, and crew utilization.',
      aiResponse: 'Weekly report: 8 jobs completed this week, $18,400 revenue. Lead pipeline: 6 pending estimates ($42K potential). Crew utilization: 87%. Top revenue: exterior jobs ($9,200). Paint costs: $1,840 (10% of revenue — good margin). Next week: 7 jobs confirmed.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Handles color consultation requests, quote inquiries, and project updates across all channels.',
    memory: 'Remembers every client\'s color choices, brand preferences, room dimensions, and past projects.',
    proactive: 'Morning crew assignments with color specs, square footage, and prep requirements.',
    bookings: 'Schedules estimates, coordinates multi-day projects, and sends completion confirmations.',
    leads: 'Qualifies leads by project scope — interior, exterior, commercial, cabinet painting, wallpaper.',
    revenue: 'Follows up on pending estimates, manages change orders, and chases overdue invoices.',
    reputation: 'Responds to reviews highlighting craftsmanship and color expertise.',
    content: 'Creates before/after transformations, color trend posts, and DIY painting tips.',
    reporting: 'Weekly report: revenue per crew, paint cost ratio, lead conversion rate, utilization.',
    browser: 'Orders paint from pro accounts with contractor discounts, compares brand pricing.',
    team: 'Crew leads report progress, flag issues, and confirm color specs via WhatsApp.',
    workflow: 'Syncs job completions to invoicing, tracks paint inventory, manages project timelines.',
    voice: 'Answers calls, provides ballpark estimates based on project type, books free consultations.',
    multiagent: 'Separate agents for estimating, project management, and marketing.',
    environment: 'Monitors weather for exterior projects and auto-reschedules when rain is forecast.',
  },
  stats: {
    messagesPerDay: 35,
    bookingsPerWeek: 12,
    monthlySavings: 4800,
    responseTime: '< 2 minutes',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Painting businesses win on reputation and visual marketing. The Manager tier automates before/after content, review management, and follow-ups to keep your pipeline full.',
};

/* ------------------------------------------------------------------ */
/* 8. MOVING COMPANY                                                    */
/* ------------------------------------------------------------------ */

const moving: Industry = {
  id: 'moving-company',
  label: 'Moving Company',
  emoji: '📦',
  category: 'Home Services',
  tagline: 'From quote to final box — AI coordinates crews, inventory, and customers so nothing gets lost.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Morning schedule and crew assignment',
      description: 'AI compiles today\'s 3 moves, assigns crew leads, and flags a long-distance job requiring DOT paperwork.',
      aiResponse: 'Good morning! 3 moves today. Crew A: local 2-bed apartment (8 AM, 412 Elm St). Crew B: 4-bed house to storage unit (9 AM, needs extra padding for antiques). Crew C: long-distance to Phoenix — DOT paperwork verified, fuel card loaded. All trucks inspected.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:15 AM',
      title: 'Quote request for long-distance move',
      description: 'Customer calls asking for a quote to move a 3-bedroom home from Denver to Austin — 930 miles.',
      aiResponse: 'Hi! For a 3-bedroom Denver-to-Austin move (about 930 miles), you\'re typically looking at $4,200–$6,800 depending on volume and services. That includes loading, transport, and unloading. Packing service adds $600–$900. I\'d love to schedule a free virtual walkthrough — how\'s tomorrow at 10 AM? I\'ll give you a binding estimate.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '8:30 AM',
      title: 'Booking confirmation with inventory checklist',
      description: 'AI sends the inventory checklist and booking confirmation to a customer whose move is scheduled for Saturday.',
      aiResponse: 'Hi Jennifer! Your move is confirmed for Saturday at 8 AM. Crew of 4, 26-ft truck. I\'ve attached your inventory checklist — please mark any fragile items (especially the china cabinet you mentioned). Estimated duration: 5–6 hours. Parking permit for your new building is secured. Any last-minute additions?',
      channel: 'email',
      capability: 'bookings',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:45 AM',
      title: 'Insurance and valuation question',
      description: 'Customer texts asking about coverage options — they have a $12,000 piano and expensive artwork.',
      aiResponse: 'Great question! Standard coverage is $0.60/lb per item (included free). For your piano and artwork, I\'d recommend Full Value Protection at $189 — covers repair or replacement at current market value. Your piano alone would be covered up to $12,000. Want me to add it to your booking? I\'ll also assign our piano-certified crew.',
      channel: 'sms',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:00 AM',
      title: 'Day-of move coordination texts',
      description: 'Crew lead reports the first move is running 30 minutes behind. AI adjusts the afternoon schedule and notifies affected customers.',
      aiResponse: 'Got it, Marcus. I\'ve pushed the Elm St ETA to 11:30 AM and notified the customer. Your afternoon pickup at 2 PM is now 2:30 PM — Mrs. Chen has been texted with the update. She confirmed that works. I also extended the truck reservation by 1 hour.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '12:15 PM',
      title: 'Packing supplies upsell opportunity',
      description: 'Customer booking a move next week mentions they haven\'t started packing yet. AI identifies the upsell.',
      aiResponse: 'No worries at all! We offer a full packing service — our team brings all materials and packs everything the day before your move. For a 2-bedroom, that\'s $450 including boxes, tape, and bubble wrap. Alternatively, I can deliver a DIY packing kit ($89, includes 30 boxes, paper, and tape) tomorrow. Which sounds better?',
      channel: 'instagram',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 450 },
    },
    {
      time: '1:30 PM',
      title: 'Storage unit inquiry from website chat',
      description: 'Customer\'s new home won\'t be ready for 2 weeks — asks about short-term storage options.',
      aiResponse: 'We have climate-controlled storage available! For a 2-bedroom household, you\'d need a 10x15 unit at $185/month (first month pro-rated). We\'ll load your items directly from the truck into storage, then deliver to your new home when you\'re ready — second delivery is just $350. Want me to reserve a unit?',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '3:00 PM',
      title: 'Customer review follow-up',
      description: 'AI sends a review request to a customer whose move was completed yesterday and responds to a new Google review.',
      aiResponse: 'Review request sent to the Hendersons (yesterday\'s 4-bed move). Also, new 5-star review from Mike T: "Crew was incredible with my antiques." Reply posted: "Thank you, Mike! Our team takes extra care with heirloom pieces — glad everything arrived safely. Enjoy your new home!"',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '4:15 PM',
      title: 'Last-minute add-on: piano on Saturday move',
      description: 'Saturday\'s customer calls — they forgot to mention a baby grand piano in the living room.',
      aiResponse: 'No problem! I\'ve added the baby grand to your inventory. This adds $350 for piano-specific handling (custom crating, 2 extra movers, piano dolly). I\'ve swapped in our piano-certified crew lead, Terrence. Your new total is $2,850. Updated confirmation sent. Anything else we should know about?',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'savings', increment: 350 },
    },
    {
      time: '5:30 PM',
      title: 'Weather delay notification',
      description: 'AI detects a severe thunderstorm warning for tomorrow morning and proactively adjusts the schedule.',
      aiResponse: 'Weather alert: severe thunderstorms forecast tomorrow 6–10 AM. I\'ve pushed tomorrow\'s 8 AM move to 11 AM and notified the customer (they confirmed). Crew A rescheduled accordingly. Second move at 2 PM is unaffected. All outdoor staging will use waterproof wrapping as a precaution.',
      channel: 'system',
      capability: 'environment',
      tier: 'manager',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:00 PM',
      title: 'Payment and tipping question',
      description: 'Customer texts asking about payment methods and whether they should tip the crew.',
      aiResponse: 'We accept credit card, debit, Zelle, and certified check — no cash required! Your invoice for $2,500 will be emailed at job completion. As for tipping, it\'s never expected but always appreciated. Most customers tip $20–$40 per mover for a full-day move. I can add a digital tip option to your invoice if you\'d like!',
      channel: 'sms',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:00 PM',
      title: 'End-of-day crew debrief',
      description: 'AI compiles the day\'s results: moves completed, revenue, damage reports, and tomorrow\'s prep.',
      aiResponse: 'Day complete! 3 moves finished — $7,200 invoiced, zero damage reports. Crew A finished 20 min early (bonus efficiency). Long-distance truck en route to Phoenix, ETA tomorrow 2 PM. Tomorrow: 2 local moves, 1 delivery from storage. Truck maintenance due Friday — reminder set.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Coordinates between customers, crew leads, and dispatchers across SMS, phone, and WhatsApp.',
    memory: 'Tracks every customer\'s inventory list, fragile items, access codes, and elevator reservations.',
    proactive: 'Morning crew briefings with truck assignments, route plans, and weather-adjusted ETAs.',
    bookings: 'Books moves, sends inventory checklists, manages reschedules, and coordinates storage handoffs.',
    leads: 'Qualifies leads by move size, distance, and timeline — local vs. long-distance, residential vs. commercial.',
    revenue: 'Upsells packing services, insurance upgrades, and storage solutions at the right moment.',
    reputation: 'Sends post-move review requests and responds to Google reviews within the hour.',
    content: 'Creates moving tip guides, seasonal discount posts, and before/after transformation content.',
    reporting: 'Daily summary: moves completed, revenue, crew efficiency, damage rate, truck utilization.',
    browser: 'Checks DOT requirements, compares fuel prices along routes, and books parking permits online.',
    team: 'Crew leads report progress, flag delays, and confirm inventory counts via WhatsApp.',
    workflow: 'Syncs completed moves to invoicing, updates CRM, triggers review requests and insurance claims.',
    voice: 'Answers calls 24/7, provides instant ballpark quotes, and books virtual walkthroughs.',
    multiagent: 'Separate agents for quoting, dispatch coordination, and post-move follow-up.',
    environment: 'Monitors weather forecasts and proactively reschedules outdoor moves before storms hit.',
  },
  stats: {
    messagesPerDay: 52,
    bookingsPerWeek: 18,
    monthlySavings: 5400,
    responseTime: '< 1 minute',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Moving companies juggle real-time crew coordination, inventory tracking, and last-minute changes. The Executive tier handles live dispatch, voice calls, and proactive weather adjustments so nothing falls through the cracks.',
};

/* ------------------------------------------------------------------ */
/* 9. PEST CONTROL                                                      */
/* ------------------------------------------------------------------ */

const pestcontrol: Industry = {
  id: 'pest-control',
  label: 'Pest Control',
  emoji: '🐛',
  category: 'Home Services',
  tagline: 'From termite emergencies to quarterly treatments — AI keeps your routes full and customers pest-free.',
  dayEvents: [
    {
      time: '6:15 AM',
      title: 'Emergency call — termites spotted',
      description: 'Homeowner calls in a panic at dawn after discovering termite swarmers in their kitchen.',
      aiResponse: 'I understand how alarming that is. Swarmer termites indicate an active colony nearby. Don\'t disturb them — we need to see the evidence. I\'ve booked an emergency inspection today at 8:30 AM with our termite specialist, Ray. He\'ll do a full substructure assessment. I\'ve texted you prep instructions.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:30 AM',
      title: 'Quarterly treatment reminder campaign',
      description: 'AI identifies 38 customers due for their quarterly perimeter treatment and sends personalized reminders.',
      aiResponse: 'Hi Mrs. Delgado! Your quarterly perimeter treatment is due. Last visit we treated for ants and spiders — any new activity since then? I have openings this Thursday or Friday morning. Your price stays at $129. Want me to book your usual Thursday slot?',
      channel: 'sms',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 245 },
    },
    {
      time: '8:45 AM',
      title: 'New customer inspection booking',
      description: 'First-time customer reaches out on Instagram asking about general pest inspection for a home they\'re buying.',
      aiResponse: 'Hi! Smart move getting a pest inspection before closing. Our comprehensive home inspection covers termites, carpenter ants, rodents, and wood-destroying organisms — everything your lender needs. It\'s $175 with a full written report. I can fit you in tomorrow at 9 AM. What\'s the property address?',
      channel: 'instagram',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Safety question — chemicals and pets',
      description: 'Customer with 2 dogs and a cat texts asking if the treatment products are safe for animals.',
      aiResponse: 'Great question! We use pet-friendly, low-toxicity products (Sentricon for termites, Demand CS for general pests). After interior treatment, pets should stay off treated surfaces for 2 hours until dry. Exterior treatments are safe once the spray dries (about 30 minutes). We always flag pet households and adjust our approach. Your fur babies will be fine!',
      channel: 'sms',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:15 AM',
      title: 'Commercial property inquiry',
      description: 'Restaurant manager emails asking about a monthly pest management contract for their 3 locations.',
      aiResponse: 'Hi Chef Ramirez! Commercial accounts are our specialty. For 3 restaurant locations, I\'d recommend our monthly service plan: interior/exterior treatment, drain line foaming, and rodent monitoring stations. Volume pricing: $275/location/month (vs. $350 individual). Includes documentation for your health department file. Can we schedule site surveys this week?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '12:30 PM',
      title: 'Recurring service enrollment',
      description: 'One-time customer from last month asks about signing up for a recurring plan after seeing ants return.',
      aiResponse: 'The ants coming back actually proves why our quarterly plan works so well — one treatment creates a temporary barrier, but quarterly visits maintain it year-round. Our annual plan is $129/quarter ($516/year vs. $175 per one-time visit). Includes free callbacks between visits if anything pops up. Want me to start you on the next available slot?',
      channel: 'whatsapp',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 516 },
    },
    {
      time: '1:45 PM',
      title: 'Google review response',
      description: 'AI responds to a 4-star review mentioning great service but lingering spider concern.',
      aiResponse: 'Reply posted: "Thanks for the review, Tom! Spiders can take 2–3 weeks to fully clear after treatment since they need to contact the treated surfaces. If you\'re still seeing activity after 3 weeks, we\'ll come back for a free callback — just text us. That\'s included in your plan!"',
      channel: 'google',
      capability: 'reputation',
      tier: 'manager',
    },
    {
      time: '2:30 PM',
      title: 'Seasonal pest alert content',
      description: 'AI creates a Facebook post about fall rodent prevention as temperatures start dropping.',
      aiResponse: 'Post ready: "Mice need just a 1/4-inch gap to enter your home. As temps drop, rodents are house-hunting too. 5 entry points to seal before winter." Includes checklist graphic with garage doors, utility pipes, dryer vents, foundation cracks, and attic soffits. CTA: free rodent inspection. Scheduled for Monday at 10 AM.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '3:45 PM',
      title: 'Rodent vs. insect triage call',
      description: 'Customer calls hearing scratching in the attic at night — unsure if it\'s mice, rats, or squirrels.',
      aiResponse: 'Scratching at night usually points to rodents — rats or mice. Squirrels are more active during the day. A few questions: is the scratching fast and light (mice) or heavier with thumping (rats)? Have you noticed droppings? I\'ve scheduled an attic inspection for tomorrow at 8 AM. Our tech will set up trail cameras if needed to confirm the species before treatment.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '5:00 PM',
      title: 'Invoice follow-up for completed job',
      description: 'AI sends a payment reminder for a termite treatment completed 10 days ago — $1,850 outstanding.',
      aiResponse: 'Hi Mr. Nakamura! Just a friendly reminder that invoice #2847 for $1,850 (termite treatment at 221 Birch Lane) is due. Your termite warranty is active for 1 year from treatment date. Pay online via the link below, or I can arrange a 3-payment plan if that\'s easier. Let me know!',
      channel: 'email',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 1850 },
    },
    {
      time: '6:30 PM',
      title: 'Referral program mention',
      description: 'Satisfied customer mentions their neighbor has a wasp problem. AI triggers the referral program.',
      aiResponse: 'Thanks for thinking of us, Lisa! I\'ve texted your neighbor a $25-off coupon for their first service, and you\'ll get a $25 credit on your next quarterly treatment once they book. Wasp nests this time of year can be aggressive — we can usually get out within 24 hours. Win-win!',
      channel: 'sms',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '9:00 PM',
      title: 'End-of-day route optimization report',
      description: 'AI analyzes tomorrow\'s 8 appointments and reorders the route for maximum efficiency.',
      aiResponse: 'Tomorrow\'s route optimized: 8 stops reorganized from 127 miles to 89 miles (30% reduction). Estimated fuel savings: $18. New order groups the 3 Westside appointments together instead of zigzagging. First stop 7:30 AM (termite inspection), last stop 4:15 PM (quarterly treatment). Supplies check: bait stations low — reorder placed with Univar.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
      stat: { key: 'savings', increment: 18 },
    },
  ],
  capabilityExamples: {
    communication: 'Answers pest emergency calls and treatment questions across phone, text, and social media.',
    memory: 'Tracks every property\'s pest history, treatment products used, pet/child safety notes, and warranty dates.',
    proactive: 'Sends quarterly treatment reminders and seasonal pest alerts before customers even notice a problem.',
    bookings: 'Schedules inspections, recurring treatments, and free callbacks — auto-fills cancelled slots.',
    leads: 'Qualifies by pest type, urgency, property type (residential vs. commercial), and service tier.',
    revenue: 'Converts one-time customers to annual plans, chases overdue invoices, and runs referral programs.',
    reputation: 'Responds to reviews with pest-specific follow-up advice and callback reminders.',
    content: 'Creates seasonal pest prevention guides, identification tips, and safety FAQ content.',
    reporting: 'Route efficiency reports, revenue per technician, callback rate, and recurring plan conversion stats.',
    browser: 'Orders treatment products from supplier portals and compares pricing across distributors.',
    team: 'Technicians report findings, upload photos, and confirm product usage via WhatsApp.',
    workflow: 'Syncs completed treatments to invoicing, updates warranty records, and triggers follow-up scheduling.',
    voice: 'Answers pest emergency calls 24/7, triages by pest type and urgency, and books same-day inspections.',
    multiagent: 'Separate agents for emergency dispatch, recurring service management, and commercial accounts.',
    environment: 'Monitors seasonal temperature changes and triggers proactive treatment reminders before pest surges.',
  },
  stats: {
    messagesPerDay: 40,
    bookingsPerWeek: 24,
    monthlySavings: 3800,
    responseTime: '< 45 seconds',
  },
  recommendedTier: 'manager',
  recommendationReason: 'Pest control thrives on recurring revenue and route efficiency. The Manager tier automates quarterly reminders, referral programs, and reputation management to maximize customer lifetime value.',
};

/* ------------------------------------------------------------------ */
/* 10. ROOFING                                                          */
/* ------------------------------------------------------------------ */

const roofing: Industry = {
  id: 'roofing',
  label: 'Roofing',
  emoji: '🏗️',
  category: 'Home Services',
  tagline: 'Storm damage to full replacements — AI handles inspections, insurance questions, and project updates.',
  dayEvents: [
    {
      time: '6:00 AM',
      title: 'Storm damage inquiry surge',
      description: 'Last night\'s hailstorm generated 14 overnight messages. AI triages by urgency and auto-responds.',
      aiResponse: 'Morning! Last night\'s storm generated 14 inquiries. I\'ve triaged them: 3 active leaks (emergency — scheduled for today), 7 hail damage inspections (booked this week), 4 general questions (auto-replied with FAQ). Emergency crew dispatched to the worst leak at 619 Maple Dr. All customers received confirmation texts.',
      channel: 'system',
      capability: 'proactive',
      tier: 'operator',
    },
    {
      time: '7:30 AM',
      title: 'Free inspection booking from Facebook ad',
      description: 'Homeowner clicks a Facebook ad for free storm damage inspections and fills out the lead form.',
      aiResponse: 'Hi David! Thanks for requesting a free storm damage inspection. I can see your area got hit hard last night. I have openings tomorrow at 9 AM or Thursday at 2 PM. Our inspector will check shingles, flashing, gutters, and attic for water intrusion. Takes about 45 minutes. Which time works for you?',
      channel: 'facebook',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '8:45 AM',
      title: 'Insurance claim assistance question',
      description: 'Homeowner calls asking how to file an insurance claim for hail damage — never done it before.',
      aiResponse: 'I\'ll walk you through it! Step 1: call your insurance company and file a claim (I\'ll text you a script to use). Step 2: they\'ll send an adjuster — we\'ll meet them at your property for free. Step 3: we provide a detailed damage report with photos to support your claim. Most homeowners pay only their deductible. What\'s your insurance provider? I\'ll tailor the instructions.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '10:00 AM',
      title: 'Material options — shingle vs. metal',
      description: 'Customer getting a full roof replacement asks about the pros and cons of architectural shingles versus standing seam metal.',
      aiResponse: 'Great comparison! Architectural shingles: $8,500–$12,000 for your 2,000 sq ft roof, 30-year warranty, tons of color options. Standing seam metal: $18,000–$24,000, 50+ year lifespan, better wind/hail resistance, and it can lower your insurance premium by 15–25%. Metal costs more upfront but saves over time. Want me to prepare side-by-side quotes for both?',
      channel: 'whatsapp',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '11:30 AM',
      title: 'Before/after photo content creation',
      description: 'AI compiles before/after photos from yesterday\'s completed tear-off and creates social media content.',
      aiResponse: 'Content ready! Before/after carousel for the Johnson residence: old 3-tab shingles (25 years, wind damage) vs. new Owens Corning Duration in Brownwood. 6 photos including drone shot of the finished roof. Caption: "From storm-damaged to storm-ready in 2 days." Scheduled for Instagram and Facebook at noon tomorrow.',
      channel: 'system',
      capability: 'content',
      tier: 'manager',
    },
    {
      time: '12:45 PM',
      title: 'Commercial flat roof quote request',
      description: 'Property manager emails requesting a quote for a 15,000 sq ft commercial flat roof repair with ponding issues.',
      aiResponse: 'Hi Angela! For 15,000 sq ft with ponding issues, we\'d need to assess drainage and membrane condition first. Common solutions: TPO overlay ($4.50–$6.50/sq ft), modified bitumen repair ($3–$5/sq ft), or full spray foam with silicone coating ($5–$7/sq ft, best for ponding). I can schedule a site survey with our commercial specialist this week. Does Wednesday at 10 AM work?',
      channel: 'email',
      capability: 'leads',
      tier: 'operator',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '2:00 PM',
      title: 'Gutter cleaning add-on opportunity',
      description: 'Customer scheduled for a roof repair next week. AI identifies they haven\'t had gutter service in 2 years.',
      aiResponse: 'Hi Kevin! While our crew is on your roof next Tuesday for the flashing repair, would you like us to clean and inspect your gutters too? Since we\'ll already have ladders and safety equipment set up, we can add gutter cleaning for $149 (normally $225). We\'ll also check for any gutter damage from the last storm. Want me to add it?',
      channel: 'sms',
      capability: 'revenue',
      tier: 'manager',
      stat: { key: 'savings', increment: 149 },
    },
    {
      time: '3:15 PM',
      title: 'Warranty question from past customer',
      description: 'Customer whose roof was installed 3 years ago calls about a small leak near a skylight.',
      aiResponse: 'Hi Patricia! Your roof is absolutely still under warranty — you have a 10-year workmanship warranty with us, plus the manufacturer\'s 30-year shingle warranty. Skylight flashing leaks are covered. I\'ve scheduled a warranty repair visit for Thursday at 9 AM — no charge to you. Our tech will also inspect the rest of the flashing while he\'s up there.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '4:30 PM',
      title: 'Neighbor referral from completed job',
      description: 'Crew finishes a tear-off and the neighbor walks over asking about their own roof. Crew lead texts the AI.',
      aiResponse: 'Nice! I\'ve texted the neighbor (Mark, 621 Maple Dr) with a $250 referral discount and our portfolio link. Also added a $250 referral credit to the Johnsons\' account. Mark\'s inspection is booked for Saturday at 10 AM. These block referrals are gold — 3 houses on Maple already done this year.',
      channel: 'whatsapp',
      capability: 'team',
      tier: 'executive',
      stat: { key: 'bookings', increment: 1 },
    },
    {
      time: '5:45 PM',
      title: 'Emergency leak triage',
      description: 'Homeowner calls — water is dripping through their bedroom ceiling during a rainstorm.',
      aiResponse: 'I\'m sorry you\'re dealing with that. First, place a bucket under the drip and move any electronics away. If you can safely access the attic, look for where water is entering — that helps our crew locate the breach. I\'m dispatching an emergency tarp crew now — ETA 45 minutes. They\'ll waterproof the area tonight, and we\'ll do the permanent repair when it\'s dry. Stay safe.',
      channel: 'phone',
      capability: 'voice',
      tier: 'executive',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '7:00 PM',
      title: 'Financing options question',
      description: 'Customer approved for a $16,000 roof replacement asks about payment plans — tight on cash after the deductible.',
      aiResponse: 'Totally understand! We offer 3 financing options: (1) 12-month same-as-cash through GreenSky — no interest if paid in full. (2) 60-month fixed at 7.99% APR — about $316/month. (3) We accept insurance supplement checks directly, so you may only pay your deductible upfront. Most of our customers go with option 1 or let insurance cover it. Want me to send the GreenSky pre-qualification link?',
      channel: 'sms',
      capability: 'communication',
      tier: 'operator',
      stat: { key: 'messages', increment: 1 },
    },
    {
      time: '9:00 PM',
      title: 'Weekly project status report',
      description: 'AI delivers the weekly summary: jobs completed, revenue, material costs, and pipeline.',
      aiResponse: 'Weekly report: 4 roofs completed this week — $62,400 revenue. Material cost: $24,100 (38.7% ratio, under your 40% target). Insurance jobs: 3 approved, 2 pending adjuster visits. Pipeline: 11 signed contracts ($148K), 6 pending estimates ($78K). Crew utilization: 91%. Storm season is filling the schedule — consider adding a subcontractor crew.',
      channel: 'system',
      capability: 'reporting',
      tier: 'manager',
    },
  ],
  capabilityExamples: {
    communication: 'Handles storm damage inquiries, material questions, and insurance guidance across all channels.',
    memory: 'Tracks every roof\'s age, material, warranty status, past repairs, and insurance claim history.',
    proactive: 'Detects storm events and auto-triages incoming damage inquiries by severity.',
    bookings: 'Schedules inspections, coordinates multi-day projects, and manages adjuster meeting times.',
    leads: 'Qualifies leads by damage type, insurance status, roof age, and project scope.',
    revenue: 'Upsells gutter cleaning, attic insulation, and maintenance plans during roof projects.',
    reputation: 'Responds to reviews highlighting insurance assistance and project timelines.',
    content: 'Creates before/after photo carousels, storm damage guides, and material comparison posts.',
    reporting: 'Weekly report: revenue, material cost ratio, insurance approval rate, crew utilization.',
    browser: 'Checks material pricing at supplier portals, compares shingle color availability, and orders supplies.',
    team: 'Crew leads report completion, flag material shortages, and submit daily progress photos.',
    workflow: 'Syncs inspections to estimates, tracks insurance approvals, and triggers invoicing on completion.',
    voice: 'Answers storm damage calls 24/7, triages by severity, and walks homeowners through insurance filing.',
    multiagent: 'Separate agents for storm response, insurance coordination, and project management.',
    environment: 'Monitors severe weather alerts and pre-positions crews for emergency tarp deployments.',
  },
  stats: {
    messagesPerDay: 55,
    bookingsPerWeek: 16,
    monthlySavings: 7200,
    responseTime: '< 30 seconds',
  },
  recommendedTier: 'executive',
  recommendationReason: 'Roofing depends on rapid storm response and insurance coordination. The Executive tier answers emergency calls 24/7, triages damage inquiries, and walks homeowners through claims — capturing leads that competitors miss.',
};

/* ------------------------------------------------------------------ */
/* EXPORT                                                               */
/* ------------------------------------------------------------------ */

export const homeIndustries: Industry[] = [
  plumber,
  electrician,
  contractor,
  landscaping,
  cleaning,
  security,
  painter,
  moving,
  pestcontrol,
  roofing,
];
