import type { Industry } from '../experience-data';

export const otherIndustries: Industry[] = [
  /* ================================================================
     B2B / Corporate
     ================================================================ */
  {
    id: 'b2b',
    label: 'B2B / Corporate',
    emoji: '🏢',
    category: 'Other',
    tagline: 'Close deals faster with an AI that manages your entire sales pipeline around the clock.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Pipeline Morning Brief',
        description: 'AI compiles overnight CRM activity — new inbound leads, stalled deals, and contracts expiring this week.',
        aiResponse: 'Good morning. 3 new enterprise leads came in overnight. Deal #4821 with Meridian Corp has been idle for 9 days — I\'ve drafted a nudge email for your review. Two contracts expire Friday; renewal decks are ready.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Inbound Lead Qualification',
        description: 'A VP of Operations fills out the enterprise contact form. AI researches the company and pre-qualifies the lead.',
        aiResponse: 'New lead: Sarah Chen, VP Ops at NovaTech (Series C, 320 employees, $48M ARR). They match your Ideal Customer Profile on 4/5 criteria. I\'ve scored them as high-priority and scheduled a discovery call slot for tomorrow at 2 PM. Sending a personalized welcome sequence now.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:15 AM',
        title: 'Proposal Follow-Up',
        description: 'AI detects that a proposal sent last week has been opened 4 times but no reply was received.',
        aiResponse: 'Heads up — the Greenfield Industries proposal was opened again this morning by two different IP addresses (likely shared internally). No reply yet. I\'ve drafted a check-in message referencing their Q3 expansion timeline. Want me to send it?',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 8500 },
      },
      {
        time: '9:00 AM',
        title: 'Partner Channel Update',
        description: 'A reseller partner messages asking for updated pricing tiers and co-branded collateral.',
        aiResponse: 'Hi Marcus, great to hear from you. I\'ve attached the updated 2026 partner pricing sheet and the co-branded one-pager template. Your current deal registrations are on track — 2 of 3 are in proposal stage. Let me know if you need custom pricing for the Acme opportunity.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Contract Renewal Outreach',
        description: 'AI initiates automated renewal conversations 60 days before contract expiry.',
        aiResponse: 'I\'ve started the renewal sequence for 4 accounts expiring in April. Each received a personalized email highlighting their usage stats and ROI metrics. Two accounts qualify for a volume upgrade — I\'ve flagged those for upsell conversations.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 12000 },
      },
      {
        time: '11:00 AM',
        title: 'Meeting Prep Package',
        description: 'AI prepares a briefing dossier before a discovery call with a prospect.',
        aiResponse: 'Your 2 PM call with NovaTech is prepped. Dossier includes: company background, recent funding news, LinkedIn profiles of attendees, their current tech stack (pulled from job postings), and 3 pain points likely relevant to them. Talking points are in your shared doc.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 500 },
      },
      {
        time: '12:00 PM',
        title: 'Competitor Intelligence Alert',
        description: 'AI detects a competitor just launched a new feature that overlaps with your offering.',
        aiResponse: 'Alert: CompetitorX just announced an AI-powered analytics module — similar to your Premium tier. I\'ve summarized their positioning, pricing, and feature gaps. Your differentiators: deeper integrations and dedicated onboarding. I\'ve drafted a battle card for the sales team.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '1:30 PM',
        title: 'Client Success Check-In',
        description: 'AI sends a quarterly business review reminder and gathers usage data for the deck.',
        aiResponse: 'QBR with DataFlow Inc is next Thursday. I\'ve compiled their usage dashboard: 34% increase in active users, 12 support tickets (all resolved), and 2 feature requests pending. Draft slide deck is ready. Their NPS score went from 7 to 9 this quarter.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '2:30 PM',
        title: 'RFP Response Coordination',
        description: 'A prospect sends an RFP with 47 questions. AI begins drafting responses from your knowledge base.',
        aiResponse: 'Received the TechCorp RFP — 47 questions across security, compliance, integration, and pricing. I\'ve auto-filled 38 answers from our knowledge base. 9 need your input (flagged in yellow). Deadline is March 20th. I\'ve set reminders for the team contributors.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 3000 },
      },
      {
        time: '4:00 PM',
        title: 'Lead Nurture Sequence Trigger',
        description: 'AI detects a cold lead re-engaging with content and escalates them back into the warm pipeline.',
        aiResponse: 'Remember BluePeak Solutions? They went cold 3 months ago. Their CTO just downloaded your integration whitepaper and visited the pricing page twice today. I\'ve moved them back to warm pipeline and queued a personal outreach from their original account exec.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Daily Pipeline Summary',
        description: 'AI generates end-of-day pipeline movement report for the sales team.',
        aiResponse: 'Today\'s pipeline: 3 new leads added ($127K potential), 1 deal moved to negotiation (Meridian — $45K), 2 proposals sent, 4 renewal sequences started. Pipeline value up 6.2% this week. Tomorrow\'s priorities: NovaTech discovery call and Greenfield follow-up.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Overnight International Lead Capture',
        description: 'AI handles an inquiry from a prospect in a different timezone while the team is offline.',
        aiResponse: 'Handled an after-hours inquiry from a London-based fintech (CapitalFlow Ltd). They asked about API rate limits, SOC 2 compliance, and enterprise pricing. I answered all three from the knowledge base and booked a demo for 9 AM GMT tomorrow. Full transcript saved to CRM.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to enterprise prospects across email, WhatsApp, and LinkedIn messages with full deal context.',
      memory: 'Remembers every interaction with each account — last meeting notes, objections raised, key stakeholders.',
      proactive: 'Morning pipeline briefs, stalled deal alerts, contract expiry warnings 60 days out.',
      bookings: 'Books discovery calls, demos, and QBRs directly into team calendars.',
      leads: 'Scores inbound leads against ICP, researches companies, routes to the right sales rep.',
      revenue: 'Chases overdue invoices, triggers renewal sequences, identifies upsell opportunities.',
      reporting: 'Weekly pipeline reports, monthly win/loss analysis, quarterly forecasting summaries.',
      browser: 'Researches prospects, monitors competitor launches, pulls company intel from public sources.',
      workflow: 'Syncs CRM, email, calendar, and proposal tools — no manual data entry.',
    },
    stats: {
      messagesPerDay: 65,
      bookingsPerWeek: 18,
      monthlySavings: 9200,
      responseTime: '< 4 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'B2B sales cycles need persistent follow-up, pipeline reporting, and competitive intelligence that go beyond basic communication.',
  },

  /* ================================================================
     Tech / Software
     ================================================================ */
  {
    id: 'tech',
    label: 'Tech / Software',
    emoji: '📱',
    category: 'Other',
    tagline: 'Ship faster with an AI that triages support, coordinates sprints, and keeps users engaged.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Deployment Health Check',
        description: 'AI reviews overnight deployment logs, error rates, and uptime monitoring dashboards.',
        aiResponse: 'Good morning. Last night\'s v3.8.2 deploy completed at 2:14 AM — zero rollback triggers. Error rate is 0.03% (within threshold). Two Sentry alerts fired but both were transient timeout issues that self-resolved. All systems green.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'Support Ticket Triage',
        description: 'AI categorizes and prioritizes 14 support tickets that came in overnight from users across timezones.',
        aiResponse: 'Triaged 14 overnight tickets: 2 critical (payment processing errors — assigned to payments team), 5 moderate (UI bugs in the new dashboard), 7 low (how-to questions — I\'ve auto-replied with docs links). The 2 critical tickets have been escalated to on-call.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 14 },
      },
      {
        time: '8:30 AM',
        title: 'Sprint Standup Summary',
        description: 'AI compiles async standup updates from the engineering team and flags blockers.',
        aiResponse: 'Sprint 24 standup: 8/10 engineers submitted updates. 2 blockers flagged — the API rate limiter PR needs security review, and the mobile team is waiting on design specs for the settings page. Velocity is on track: 34 of 52 story points completed, 5 days remaining.',
        channel: 'system',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '9:00 AM',
        title: 'Feature Request Pattern Detection',
        description: 'AI analyzes recent feature requests and identifies a trending pattern across user segments.',
        aiResponse: 'Interesting trend: 23 users requested CSV export in the last 30 days — up 340% from the previous period. 78% are on the Pro plan. Top use cases: monthly reporting and data migration. I\'ve created a feature brief with user quotes and added it to the backlog for prioritization.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '10:00 AM',
        title: 'User Onboarding Assist',
        description: 'A new trial user is stuck on the integration setup step. AI provides real-time guidance.',
        aiResponse: 'Hi Alex! I see you\'re setting up the Stripe integration. The webhook URL should be pasted into your Stripe dashboard under Developers > Webhooks. Here\'s a 30-second walkthrough video. Also, make sure you\'re using the live key, not the test key — I noticed the prefix is "sk_test". Let me know if you need help!',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Churn Risk Detection',
        description: 'AI flags an enterprise account whose usage dropped 60% this month.',
        aiResponse: 'Churn risk alert: CloudStack Inc (Enterprise plan, $2,400/mo) usage dropped 62% this month. Last login was 11 days ago. Their admin hasn\'t opened our last 3 emails. I recommend a personal check-in call — I\'ve drafted talking points and pulled their usage history.',
        channel: 'system',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'savings', increment: 2400 },
      },
      {
        time: '12:30 PM',
        title: 'Knowledge Base Auto-Update',
        description: 'AI detects that a help article is outdated after the latest release and drafts an update.',
        aiResponse: 'The "Getting Started with Webhooks" article references the v2 API endpoint that was deprecated in v3.8. I\'ve drafted an updated version with the new endpoint, added a migration note, and included the new authentication flow. Ready for review in your docs repo.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '1:30 PM',
        title: 'Bug Report Investigation',
        description: 'A user reports a bug via in-app chat. AI reproduces the issue and files a detailed ticket.',
        aiResponse: 'Confirmed bug: date picker shows incorrect timezone for users in UTC+10 and above. Reproduced on Chrome 124 and Safari 18. Root cause likely in the date-fns locale config. I\'ve filed JIRA-4521 with reproduction steps, browser logs, and suggested fix. Assigned to the frontend team.',
        channel: 'whatsapp',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Trial-to-Paid Conversion Nudge',
        description: 'AI sends a personalized upgrade prompt to a trial user who has hit usage limits.',
        aiResponse: 'Alex from earlier just hit the free tier API limit (1,000 calls). They\'ve integrated 3 webhooks and created 2 dashboards — clearly getting value. I\'ve sent a personalized upgrade email highlighting their usage, offering 20% off the first month of Pro, and showing features they\'d unlock.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 590 },
      },
      {
        time: '4:30 PM',
        title: 'Release Notes Draft',
        description: 'AI drafts user-facing release notes from the Git changelog and Jira tickets closed this sprint.',
        aiResponse: 'Drafted release notes for v3.8.2: 3 new features (CSV export, dark mode, webhook retry config), 7 bug fixes, and 2 performance improvements. Written in user-friendly language with screenshots. Blog post version and in-app changelog version are both ready for review.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Engineering Report',
        description: 'AI summarizes the day\'s engineering output, support metrics, and user growth.',
        aiResponse: 'Daily wrap: 8 PRs merged, 2 critical bugs fixed, 14 tickets resolved (avg response: 18 min). New signups: 47 (12% above daily average). Trial-to-paid conversions: 3. Server costs down 4% after the caching optimization. Tomorrow: security review for the rate limiter PR.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'After-Hours Critical Alert',
        description: 'Monitoring detects a spike in 500 errors. AI investigates and escalates if needed.',
        aiResponse: 'Alert: 500 error rate spiked to 2.1% at 9:47 PM — traced to the payment service. The third-party Stripe webhook endpoint is returning 503. This is on Stripe\'s side (confirmed via their status page). I\'ve enabled the fallback queue so no transactions are lost. On-call notified as FYI only.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles support tickets, in-app chat, and developer community questions across all channels.',
      memory: 'Tracks every user\'s plan, feature usage, past tickets, and sentiment history.',
      proactive: 'Deployment health checks, error rate monitoring, churn risk detection alerts.',
      bookings: 'Schedules demos for trial users, onboarding calls, and QBRs with enterprise accounts.',
      leads: 'Scores trial signups by engagement, routes enterprise inquiries to sales.',
      revenue: 'Identifies upgrade opportunities, sends conversion nudges, chases overdue invoices.',
      content: 'Drafts release notes, updates help docs, writes changelog posts from Git history.',
      reporting: 'Daily engineering metrics, weekly support KPIs, monthly product analytics.',
      browser: 'Monitors competitor product pages, tracks pricing changes, reads Hacker News mentions.',
      workflow: 'Syncs Jira, GitHub, Slack, and docs — auto-files bugs, assigns tickets, updates boards.',
      team: 'Compiles async standups, flags blockers, coordinates cross-team dependencies.',
    },
    stats: {
      messagesPerDay: 85,
      bookingsPerWeek: 12,
      monthlySavings: 7800,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Software companies need deep workflow integration, team coordination, and browser-based monitoring that require Executive-tier autonomy.',
  },

  /* ================================================================
     Creative / Media Agency
     ================================================================ */
  {
    id: 'creative',
    label: 'Creative / Media Agency',
    emoji: '🎬',
    category: 'Other',
    tagline: 'Never miss a deadline again — AI tracks every brief, revision, and deliverable across all your clients.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Daily Project Dashboard',
        description: 'AI compiles the status of all active client projects, flagging deadlines within 48 hours.',
        aiResponse: 'Morning update: 11 active projects across 7 clients. 2 deadlines today (Luna Cosmetics social pack, GreenEat brand guidelines v2). 1 project at risk — the Apex Fitness video edit is waiting on client footage since Tuesday. I\'ve sent a follow-up to their marketing director.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'New Client Brief Intake',
        description: 'A new client submits a creative brief via the intake form. AI parses requirements and sets up the project.',
        aiResponse: 'New brief from Solara Wines: Brand refresh — logo, packaging, website. Budget: $18,000. Timeline: 6 weeks. I\'ve created the project folder, set up the timeline with milestones, drafted the scope document, and scheduled a kick-off call for Thursday at 10 AM.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Revision Round Tracking',
        description: 'A client sends feedback on logo concepts via WhatsApp with voice notes and image markups.',
        aiResponse: 'Luna Cosmetics feedback on logo concepts: They love Option B (the botanical monogram) but want the green shifted warmer, the tagline in a serif font, and the icon simplified. I\'ve logged all 6 revision points in the project tracker and assigned them to the design team with the original voice notes attached.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Content Calendar Review',
        description: 'AI presents this week\'s content calendar for a retainer client, ready for approval.',
        aiResponse: 'GreenEat\'s content calendar for this week: Monday — recipe reel (shot last Friday), Wednesday — ingredient sourcing behind-the-scenes, Friday — customer testimonial carousel. Captions are drafted, hashtag sets researched, and posting times optimized based on their last 90 days of engagement data.',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '10:30 AM',
        title: 'Vendor Quote Comparison',
        description: 'AI collects and compares quotes from 3 print vendors for a client\'s packaging job.',
        aiResponse: 'Print quotes for Solara Wines labels: Vendor A — $2.10/unit (min 5,000), Vendor B — $1.85/unit (min 10,000), Vendor C — $2.40/unit (min 1,000, eco-certified). Given the client\'s 8,000-unit run and sustainability values, I recommend Vendor C for the first batch. Comparison spreadsheet attached.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 1200 },
      },
      {
        time: '11:30 AM',
        title: 'Client Approval Reminder',
        description: 'AI follows up on a deliverable that\'s been pending client approval for 3 days, blocking the next phase.',
        aiResponse: 'Gentle reminder sent to Apex Fitness: the website wireframes have been pending approval since Friday, and the development phase can\'t start until sign-off. I\'ve included a direct approval link and noted the timeline impact if we don\'t hear back by tomorrow. Their PM acknowledged receipt.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Freelancer Coordination',
        description: 'AI briefs a freelance videographer for an upcoming shoot and shares the production schedule.',
        aiResponse: 'Briefed freelance videographer (Marco) for the Solara Wines shoot next Wednesday: location confirmed (their vineyard in Napa), shot list attached (15 scenes), call time 7 AM for golden hour. Equipment checklist sent. He confirmed availability and his day rate of $850.',
        channel: 'whatsapp',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '2:00 PM',
        title: 'Social Media Performance Report',
        description: 'AI generates a monthly performance report for a retainer client\'s social channels.',
        aiResponse: 'GreenEat February report: Instagram grew 12% (3,240 new followers), top post was the farm-to-table reel (48K views). TikTok engagement up 23%. Website traffic from social increased 18%. Three content themes outperformed: behind-the-scenes, recipes, and customer stories. Recommendations for March included.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '3:00 PM',
        title: 'Scope Creep Detection',
        description: 'AI detects that a client is requesting work outside the agreed project scope.',
        aiResponse: 'Heads up: Luna Cosmetics just asked for an animated logo version and social media templates — neither is in the original scope ($8,500 for static brand identity). I\'ve drafted a friendly change order for $3,200 covering the additions with a 2-week extension. Ready for your review before sending.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 3200 },
      },
      {
        time: '4:30 PM',
        title: 'Portfolio Case Study Draft',
        description: 'AI drafts a portfolio case study from a recently completed project.',
        aiResponse: 'Drafted a case study for the Apex Fitness rebrand: problem statement, creative approach, results (32% increase in gym membership inquiries post-launch). Includes before/after visuals and a client testimonial quote. Formatted for your website portfolio and a LinkedIn carousel version.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Project Sync',
        description: 'AI sends a daily status update to each active client with their project\'s progress.',
        aiResponse: 'Sent EOD updates to 5 clients: Luna Cosmetics (revisions in progress, delivery Friday), GreenEat (content scheduled for the week), Apex Fitness (awaiting footage), Solara Wines (kick-off Thursday), Brightpath (final files delivered today). All timelines current except Apex — flagged at risk.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 5 },
      },
      {
        time: '10:00 PM',
        title: 'Late-Night Client Message Handling',
        description: 'A client in a different timezone sends urgent feedback on a campaign going live tomorrow.',
        aiResponse: 'GreenEat\'s founder (in London) just sent urgent feedback on tomorrow\'s launch post: swap the hero image to the one from the tasting event and adjust the CTA to "Order Your Spring Box." I\'ve logged the changes, notified the designer for first thing tomorrow, and confirmed receipt with the client.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Manages client feedback across WhatsApp, email, and project tools — voice notes, markups, and all.',
      memory: 'Remembers each client\'s brand guidelines, preferences, past feedback patterns, and key contacts.',
      proactive: 'Daily project dashboards, deadline alerts, stalled-approval follow-ups.',
      bookings: 'Schedules kick-off calls, review meetings, shoot dates, and client presentations.',
      leads: 'Captures new briefs, qualifies project scope, sends proposals with pricing.',
      revenue: 'Detects scope creep, drafts change orders, chases overdue invoices.',
      content: 'Drafts social posts, case studies, newsletters, and performance reports for clients.',
      reporting: 'Monthly social analytics, project profitability analysis, team utilization reports.',
      browser: 'Compares vendor quotes, researches stock asset libraries, monitors competitor campaigns.',
      team: 'Briefs freelancers, coordinates shoot schedules, tracks team assignments.',
    },
    stats: {
      messagesPerDay: 72,
      bookingsPerWeek: 15,
      monthlySavings: 8500,
      responseTime: '< 5 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Creative agencies need content management, client reporting, and revenue tracking on top of multi-client communication.',
  },

  /* ================================================================
     Consulting
     ================================================================ */
  {
    id: 'consulting',
    label: 'Consulting',
    emoji: '💬',
    category: 'Other',
    tagline: 'Deliver more value to clients while AI handles intake, scheduling, follow-ups, and deliverable tracking.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Agenda Brief',
        description: 'AI reviews today\'s client meetings, prep requirements, and outstanding deliverables.',
        aiResponse: 'Good morning. Today: 9 AM strategy session with Pinnacle Group (deck is prepped), 1 PM check-in with BrightPath (their monthly KPIs are attached), and 4 PM new prospect call (Horizon Capital — research dossier ready). Outstanding: Pinnacle\'s implementation roadmap is due Friday.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Client Intake Processing',
        description: 'A new prospect fills out the consulting intake form. AI processes the information and prepares for the first call.',
        aiResponse: 'New intake: Horizon Capital, private equity firm, 45 employees. Challenge: operational efficiency across portfolio companies. Budget range: $15K-25K/month. Decision-maker: COO Rachel Kim. I\'ve researched their portfolio (12 companies, mostly B2B SaaS), prepared 3 relevant case studies, and drafted an agenda for today\'s 4 PM call.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Deliverable Progress Tracker',
        description: 'AI updates the status of all active consulting engagements and flags items behind schedule.',
        aiResponse: 'Engagement tracker: 4 active clients. Pinnacle Group — Phase 2 (on track, 68% complete). BrightPath — Monthly retainer (KPI report due today, drafted). NovaTech — Workshop series (3 of 5 complete, next one March 18). Atlas Ventures — Proposal stage (awaiting sign-off since Monday, follow-up sent).',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Post-Meeting Action Items',
        description: 'After the Pinnacle Group strategy session, AI extracts action items from the meeting transcript.',
        aiResponse: 'Meeting with Pinnacle Group — 7 action items captured: 1) Finalize org chart redesign by Thursday (you), 2) Share employee survey data (their HR team, deadline Wednesday), 3) Draft change management communication plan (you, by Friday), 4-7) minor follow-ups assigned and tracked. Summary sent to all attendees.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
      },
      {
        time: '10:30 AM',
        title: 'Thought Leadership Article Draft',
        description: 'AI drafts a LinkedIn article based on insights from recent client engagements (anonymized).',
        aiResponse: 'Drafted your next LinkedIn article: "Why 73% of Operational Transformations Stall at Phase 2 — And How to Prevent It." Based on patterns from your last 8 engagements (fully anonymized). 1,200 words, includes 3 actionable frameworks. Engagement prediction: strong, based on your audience analytics.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '11:30 AM',
        title: 'Client KPI Report Generation',
        description: 'AI compiles BrightPath\'s monthly performance report from multiple data sources.',
        aiResponse: 'BrightPath February KPI report ready: Revenue up 8%, customer acquisition cost down 12%, employee satisfaction score improved from 7.2 to 7.8. Compared against the benchmarks we set in January — 4 of 6 KPIs are on or ahead of target. 2 recommendations included for areas lagging. Ready for your 1 PM call.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '1:30 PM',
        title: 'Follow-Up Proposal Nudge',
        description: 'AI follows up on a proposal that\'s been with a prospect for 5 days without response.',
        aiResponse: 'Atlas Ventures hasn\'t responded to the $22K/month proposal sent last Monday. I\'ve sent a soft follow-up referencing their board meeting next week (found on their events page) and positioned the engagement as preparation for Q2 planning. Also offered a 30-minute clarification call.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 22000 },
      },
      {
        time: '2:30 PM',
        title: 'Workshop Material Preparation',
        description: 'AI prepares materials for the next NovaTech leadership workshop.',
        aiResponse: 'Workshop 4 materials for NovaTech ready: "Scaling Decision-Making Frameworks." Includes facilitator guide, participant workbooks (personalized with their org structure), pre-work survey (sent to 12 attendees), and the breakout room assignments based on their team composition. Printed materials shipping Thursday.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Competitive Research Scan',
        description: 'AI monitors competitor consulting firms for new service offerings and published research.',
        aiResponse: 'Weekly competitor scan: McKnight Advisory just published a report on AI adoption in mid-market (I\'ve summarized key findings). Clarity Consulting launched a new "90-Day Transformation" package at $45K — similar to your Phase 1 offering but less comprehensive. I\'ve updated the competitive positioning doc.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '4:30 PM',
        title: 'New Prospect Discovery Call',
        description: 'AI joins the discovery call with Horizon Capital, takes notes, and drafts the proposal framework.',
        aiResponse: 'Horizon Capital call complete — excellent fit. Key needs: standardize operations across 12 portfolio companies, reduce reporting overhead, implement shared KPI frameworks. Budget confirmed at $20K/month. I\'ve drafted a proposal outline, identified 2 similar past engagements for reference, and scheduled a follow-up for next Tuesday.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Weekly Utilization Summary',
        description: 'AI calculates consulting hours, billable utilization, and revenue for the week.',
        aiResponse: 'Weekly utilization: 32 billable hours across 4 clients (80% utilization — above your 75% target). Revenue this week: $14,200. Pipeline: $42K in proposals outstanding, $20K from today\'s Horizon Capital opportunity. Recommendation: you have capacity for one more retainer client starting April.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Client Reference Request Handling',
        description: 'A prospect asks for client references after hours. AI responds with curated case studies.',
        aiResponse: 'Horizon Capital\'s COO requested references. I\'ve sent 3 curated case studies matching their profile (PE firms, operational consulting) along with testimonial quotes. Also offered to arrange a brief call with a past client (confirmed their willingness last quarter). Full response personalized and professional.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles client emails, WhatsApp messages, and prospect inquiries with full engagement context.',
      memory: 'Tracks every client\'s goals, deliverables, key contacts, preferences, and historical performance data.',
      proactive: 'Daily agenda briefs, deliverable deadline alerts, engagement progress tracking.',
      bookings: 'Schedules strategy sessions, workshops, discovery calls, and QBRs across client calendars.',
      leads: 'Processes intake forms, researches prospects, prepares discovery call dossiers.',
      revenue: 'Follows up on proposals, tracks billable hours, chases overdue retainer payments.',
      content: 'Drafts thought leadership articles, case studies, and workshop materials.',
      reporting: 'Client KPI reports, weekly utilization summaries, pipeline forecasting.',
      browser: 'Monitors competitor firms, researches prospect companies, tracks industry publications.',
      workflow: 'Extracts meeting action items, tracks deliverables, syncs project management tools.',
    },
    stats: {
      messagesPerDay: 48,
      bookingsPerWeek: 14,
      monthlySavings: 11000,
      responseTime: '< 6 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Consultants need thought leadership content, client reporting, and revenue tracking alongside communication and scheduling.',
  },

  /* ================================================================
     Other (Generic Fallback)
     ================================================================ */
  {
    id: 'other',
    label: 'Other',
    emoji: '❓',
    category: 'Other',
    tagline: 'An AI employee that handles communication, bookings, and follow-ups for any type of business.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Business Brief',
        description: 'AI reviews overnight messages, today\'s appointments, and anything that needs your attention.',
        aiResponse: 'Good morning. You have 5 appointments today (first one at 9 AM). 3 new customer inquiries came in overnight — all responded to. One returning customer asked about pricing for your premium service; I\'ve sent the details. No cancellations. Here\'s your full rundown.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'New Customer Inquiry',
        description: 'A potential customer messages asking about your services and availability.',
        aiResponse: 'Hi! Thanks for reaching out. We\'d love to help. Our services include [your core offerings], and we currently have availability this week on Wednesday and Thursday. Would either of those work for you? I can also send over our full pricing guide if that\'s helpful.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Appointment Booking',
        description: 'A customer confirms they\'d like to book a time slot. AI checks availability and schedules it.',
        aiResponse: 'Perfect — I\'ve booked you in for Wednesday at 2 PM. You\'ll receive a confirmation email shortly with all the details. We\'ll also send a reminder the day before. Is there anything specific you\'d like us to prepare or know ahead of time?',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Returning Customer Recognition',
        description: 'A previous customer reaches out again. AI recognizes them and references their history.',
        aiResponse: 'Welcome back, Maria! Great to hear from you again. Last time you came in was back in January for your regular service. Would you like to book the same thing, or were you looking at something different this time? We also have a few new options I think you\'d like.',
        channel: 'whatsapp',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Lead Follow-Up Sequence',
        description: 'AI follows up with a prospect who inquired 3 days ago but never booked.',
        aiResponse: 'Hi James, just following up on your inquiry from a few days ago about our services. I know things get busy! We still have some availability this week if you\'re interested. No pressure at all — happy to answer any questions you might have. Here\'s a quick link to book online anytime.',
        channel: 'sms',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Review Request After Service',
        description: 'A customer completed their appointment yesterday. AI sends a friendly review request.',
        aiResponse: 'Hi Sarah, thanks so much for coming in yesterday! We hope everything was great. If you have a moment, we\'d really appreciate a quick Google review — it means the world to a small business like ours. Here\'s the link. Thanks again, and we look forward to seeing you next time!',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Google Review Response',
        description: 'A new 5-star review appears on Google. AI responds promptly and professionally.',
        aiResponse: 'New 5-star Google review from Sarah: "Amazing service, so professional and easy to book!" I\'ve responded: "Thank you so much, Sarah! We\'re thrilled you had a great experience. We look forward to welcoming you back soon!" Your rating is now 4.8 with 127 reviews.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '2:00 PM',
        title: 'Cancellation Recovery',
        description: 'A customer cancels their appointment for tomorrow. AI cross-references the waitlist, recent inquiries, and lapsed customers to fill the slot.',
        aiResponse: 'Tomorrow\'s 3 PM slot just opened up from a cancellation. I\'ve already reached out to 4 customers from the waitlist and 2 recent inquiries who hadn\'t booked yet. Lisa confirmed she can take the slot — rebooked and confirmed. No lost revenue.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Weekly Social Media Post',
        description: 'AI drafts and schedules a social media post showcasing your business.',
        aiResponse: 'This week\'s Instagram post is ready: a behind-the-scenes look at your workspace with a caption highlighting what makes your service special. Hashtags researched and optimized for your local area. Scheduled for Thursday at 6 PM (your audience\'s peak engagement time). Want to preview it?',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Overdue Invoice Follow-Up',
        description: 'AI detects an unpaid invoice from 10 days ago, cross-references payment history, and sends a polite reminder with a direct payment link.',
        aiResponse: 'Friendly reminder sent to David regarding his invoice from February 28th ($350, 10 days overdue). The message was warm and professional with a direct payment link. This is his first late payment — usually pays within 3 days. If no response by Friday, I\'ll send a second reminder.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 350 },
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Summary',
        description: 'AI compiles the full day\'s activity across every channel and system into a concise summary delivered to your phone.',
        aiResponse: 'Today\'s wrap-up: 5 appointments completed, 2 new bookings made, 1 cancellation recovered, 3 new inquiries handled, 1 five-star review received and responded to, 1 overdue invoice chased. Tomorrow: 4 appointments starting at 10 AM. Everything is running smoothly.',
        channel: 'email',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'After-Hours Inquiry',
        description: 'A customer messages late at night asking if you\'re open tomorrow. AI responds instantly.',
        aiResponse: 'Hi! Thanks for reaching out. Yes, we\'re open tomorrow from 9 AM to 6 PM. We still have a few slots available — would you like me to book one for you? Just let me know what time works best and I\'ll get you set up right away.',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to customer messages across WhatsApp, Instagram, Facebook, email, and SMS — all from one brain.',
      memory: 'Remembers every customer\'s name, history, preferences, and past interactions.',
      proactive: 'Morning briefings, end-of-day summaries, and real-time alerts when something needs attention.',
      bookings: 'Books appointments, sends reminders, handles cancellations, and fills empty slots automatically.',
      leads: 'Captures every inquiry, follows up automatically, and never lets a lead slip through the cracks.',
      revenue: 'Chases overdue payments, re-engages lapsed customers, and sends offers on slow days.',
      reputation: 'Responds to every Google review within the hour and requests reviews after each completed service.',
      content: 'Creates and schedules social media posts, writes email campaigns, and tracks what performs best.',
      reporting: 'Daily summaries and weekly reports so you always know how your business is performing.',
    },
    stats: {
      messagesPerDay: 40,
      bookingsPerWeek: 22,
      monthlySavings: 5500,
      responseTime: '< 2 min',
    },
    recommendedTier: 'operator',
    recommendationReason: 'The Operator tier covers communication, bookings, and lead management — the essentials every business needs running 24/7.',
  },

  /* ================================================================
     Event Planning / Wedding
     ================================================================ */
  {
    id: 'event-planning',
    label: 'Event Planning / Wedding',
    emoji: '🎉',
    category: 'Other',
    tagline: 'Every vendor coordinated, every timeline perfected, every detail remembered — so you can focus on making magic happen.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Wedding Venue Inquiry',
        description: 'A couple submits an inquiry about availability for their September wedding at the venue you manage.',
        aiResponse: 'New venue inquiry from Emily & James — September 20th, 150 guests, outdoor ceremony + indoor reception. September 20th is available! I\'ve responded with our wedding packet: pricing ($8,500 venue fee), floor plans, photo gallery, and 3 available tasting dates. Also offered a virtual walkthrough this Thursday. This is our 4th September inquiry this week.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Vendor Coordination',
        description: 'AI coordinates with the florist, caterer, and DJ for the upcoming Saturday wedding.',
        aiResponse: 'Saturday\'s Robinson wedding vendor check-in complete. Florist (Bloom & Co): centerpieces confirmed, delivery at 10 AM. Caterer (Table & Vine): final headcount updated to 142, dietary restrictions list sent. DJ (SoundWave): song list approved, setup at 3 PM. Photographer confirmed golden hour session at 5:30 PM. All on track.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 4 },
      },
      {
        time: '8:45 AM',
        title: 'Timeline Review',
        description: 'The bride requests changes to the wedding day timeline, shifting the ceremony 30 minutes later.',
        aiResponse: 'Hi Emily! I\'ve updated the timeline — ceremony now at 4:30 PM instead of 4:00 PM. Here\'s the cascade of changes: cocktail hour shifts to 5:15 PM, dinner service to 6:30 PM, first dance at 7:45 PM, and cake cutting at 8:15 PM. I\'ve notified all vendors of the new schedule. The photographer confirmed golden hour still works perfectly at the new time.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Guest List RSVP Tracking',
        description: 'AI compiles the latest RSVP status and flags guests who haven\'t responded with the deadline approaching.',
        aiResponse: 'RSVP update for the Robinson wedding: 118 confirmed yes, 14 declined, 18 still pending (deadline is Friday). I\'ve sent gentle reminders to all 18 non-responders with a one-tap RSVP link. Notable: the groom\'s uncle\'s family of 6 hasn\'t responded — flagged for a personal follow-up. Meal selections so far: 72 beef, 38 fish, 8 vegetarian.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 18 },
      },
      {
        time: '11:15 AM',
        title: 'Budget Question',
        description: 'A client asks if they\'re on track with their budget and where they can save.',
        aiResponse: 'Budget snapshot for the Robinson wedding: Total budget $42,000. Committed so far: $36,800 (88%). Remaining: $5,200. Biggest expenses: venue ($8,500), catering ($12,400), photography ($4,200). You\'re $800 over on florals — I\'d recommend switching the lounge arrangements from fresh to dried flowers (saves $600). Gratuities and day-of extras still need $2,100 budgeted.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Decoration Style Consultation',
        description: 'A new client wants help deciding between two decoration themes for their corporate gala.',
        aiResponse: 'Hi Natasha! I\'ve put together mood boards for both options: the "Modern Luxe" theme (black, gold, geometric centerpieces) and the "Garden Party" theme (greenery, soft pastels, mixed florals). Based on your venue\'s existing decor, I\'d lean toward Modern Luxe — it complements the industrial space beautifully. I\'ve attached cost comparisons: Modern Luxe at $3,200 vs Garden Party at $3,800. Want to discuss on a call?',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:45 PM',
        title: 'Catering Menu Finalization',
        description: 'The caterer sends the final menu proof for review. AI cross-references with guest dietary restrictions.',
        aiResponse: 'Menu proof reviewed for the Robinson wedding. Cross-referenced with dietary needs: 8 vegetarian, 3 gluten-free, 2 nut allergies, 1 vegan. Issue found: the appetizer sampler contains tree nuts — I\'ve flagged this with Table & Vine and suggested substituting the almond crostini with bruschetta. Everything else looks perfect. Sent to Emily for final approval.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Day-of Coordination Checklist',
        description: 'AI generates the detailed day-of coordination checklist for the upcoming Saturday event.',
        aiResponse: 'Saturday\'s day-of checklist is ready — 47 items across 6 time blocks. Key items: 8 AM venue access and setup begins, 10 AM floral delivery, 11 AM linen and tableware setup, 1 PM caterer arrives for kitchen prep, 3 PM DJ and photographer setup, 3:30 PM bridal party arrives. Emergency kit packed: sewing kit, stain remover, backup phone chargers, and Advil. Shared with the on-site coordinator.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '4:00 PM',
        title: 'Rehearsal Scheduling',
        description: 'AI coordinates the rehearsal dinner schedule with the wedding party and venue.',
        aiResponse: 'Rehearsal dinner confirmed for Friday at 6 PM at Rosetta\'s (private dining room, 28 guests). Wedding rehearsal at the venue at 4 PM — I\'ve sent the wedding party a schedule: arrive at 3:45 PM, walkthrough at 4 PM, ceremony practice at 4:30 PM, wrap by 5:15 PM. Transportation from venue to dinner confirmed (shuttle departs 5:30 PM). Menu preselected — just need the wine pairing choice.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '5:15 PM',
        title: 'Vendor Payment Reminder',
        description: 'AI tracks vendor payment deadlines and sends reminders for upcoming balances due.',
        aiResponse: 'Vendor payment reminders: Bloom & Co florist — final balance of $1,800 due by Friday (I\'ve prepared the check). SoundWave DJ — $500 deposit received, $750 balance due day-of. Table & Vine caterer — 50% deposit ($6,200) already paid, final 50% due 7 days before. All on track. Total outstanding: $8,750. Want me to process the florist payment today?',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 1800 },
      },
      {
        time: '7:00 PM',
        title: 'Post-Event Thank You',
        description: 'AI sends personalized thank-you notes to vendors and guests after a completed event.',
        aiResponse: 'Thank-you messages sent for last Saturday\'s Chen corporate gala: personalized notes to all 6 vendors thanking them for specific contributions, a group thank-you to the 85 attendees with event photos, and a detailed debrief to the client with highlights and attendee feedback. Also requested Google reviews from 3 vendors and the client.',
        channel: 'email',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 10 },
      },
      {
        time: '9:00 PM',
        title: 'Portfolio Content Creation',
        description: 'AI curates photos from a recent event into social media content and portfolio pieces.',
        aiResponse: 'Portfolio content created from the Chen gala: Instagram carousel (8 photos highlighting decor, venue, and candid moments), a styled Pinterest board for the "Corporate Luxe" aesthetic, and 3 new portfolio page entries for the website. Blog post drafted: "How to Plan a 100-Person Corporate Gala in 6 Weeks." Scheduled to publish Thursday.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Coordinates between couples, vendors, venues, and wedding parties across all channels.',
      memory: 'Tracks every detail — guest dietary needs, vendor contracts, color palettes, song requests, and timelines.',
      proactive: 'Sends RSVP deadline reminders, vendor payment alerts, and day-of checklists automatically.',
      bookings: 'Schedules tastings, venue tours, rehearsals, and vendor meetings across multiple calendars.',
      leads: 'Captures venue inquiries, follows up on consultation requests, and nurtures leads through the booking funnel.',
      revenue: 'Tracks vendor payments, manages client invoicing, and identifies upsell opportunities for premium packages.',
      reputation: 'Sends post-event thank-yous and review requests to clients and vendor partners.',
      content: 'Creates portfolio showcases, blog posts, styled social media content, and Pinterest boards from event photos.',
      reporting: 'Budget tracking, RSVP dashboards, vendor status reports, and post-event ROI analysis.',
      browser: 'Researches venue availability, compares vendor pricing, and checks weather forecasts for outdoor events.',
      team: 'On-site coordinators query AI for timeline details, vendor contacts, and guest information.',
      workflow: 'Syncs event management tools with calendars, payment tracking, and vendor communication logs.',
      voice: 'Handles client calls, takes vendor messages, and manages day-of phone coordination.',
      multiagent: 'Coordinates parallel vendor outreach and availability checking across multiple events.',
      environment: 'Controls venue lighting, AV systems, and playlist management during events.',
    },
    stats: {
      messagesPerDay: 50,
      bookingsPerWeek: 14,
      monthlySavings: 5800,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Event planning requires complex vendor coordination, day-of workflow management, and call handling that demand executive-tier capabilities.',
  },

  /* ================================================================
     Photography Studio
     ================================================================ */
  {
    id: 'photography',
    label: 'Photography Studio',
    emoji: '📸',
    category: 'Other',
    tagline: 'Every inquiry answered, every session booked, every gallery delivered — while you stay behind the lens.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Portrait Session Booking',
        description: 'A family reaches out to book a fall portrait session after seeing your work on Instagram.',
        aiResponse: 'New booking inquiry from the Martinez family — they\'d love a fall outdoor family session (2 adults, 3 kids ages 4–10). I\'ve responded with our Family Portrait package ($450, includes 1-hour session + 30 edited images + online gallery). Suggested dates: October 11th or 18th at 4 PM for golden hour. Sent our style guide and location portfolio.',
        channel: 'instagram',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Wedding Package Inquiry',
        description: 'A newly engaged couple asks about wedding photography packages and availability.',
        aiResponse: 'Congrats to Sarah & David! They\'re looking at June 14th for their wedding at Rosewood Estate. June 14th is available! I\'ve sent our three packages: Silver ($3,200 — 6 hours, 1 photographer), Gold ($4,800 — 8 hours, 2 photographers + engagement session), and Platinum ($6,500 — 10 hours, 2 photographers, album, and engagement session). Offered a complimentary consultation call Thursday at 2 PM.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:00 AM',
        title: 'Mini Session Promotion',
        description: 'AI creates and sends a promotional campaign for upcoming limited-edition spring mini sessions.',
        aiResponse: 'Spring Mini Session campaign ready! 20-minute sessions at the cherry blossom gardens, $250 each (includes 15 edited images). Dates: April 5th and 6th, 8 slots per day. Email blast sent to 480 subscribers, Instagram story + reel scheduled, and Facebook event created. Early bird pricing ($225) for the first 5 bookings. Already 3 inquiries from the email preview.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Gallery Delivery',
        description: 'AI delivers the online gallery from last week\'s newborn session with a personalized message.',
        aiResponse: 'Gallery delivered to Amanda & Ryan for baby Olivia\'s newborn session! 45 edited images in a password-protected online gallery. Message included: "Your gallery is ready! Baby Olivia was an absolute dream to photograph. Here are your images — my favorites are #12 and #28. Gallery is available for 30 days. Print orders can be placed directly from the gallery. Enjoy!"',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Print Order',
        description: 'A client places a print order from their online gallery — canvas, framed prints, and an album.',
        aiResponse: 'Print order received from the Nguyen family: 1 large canvas (24x36, $280), 3 framed 8x10s ($75 each), and a 20-page leather album ($450). Order total: $955. I\'ve confirmed the order, sent a payment link, and submitted the print request to our lab. Estimated delivery: 2 weeks for prints, 4 weeks for the album. Confirmation sent to the client.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 955 },
      },
      {
        time: '12:30 PM',
        title: 'Location Scouting',
        description: 'AI researches and suggests locations for an upcoming engagement session based on the couple\'s style.',
        aiResponse: 'Location options for the Chen engagement session (they love urban industrial + nature mix): 1) The Railyard District — brick walls, graffiti murals, train tracks (permit: $50). 2) Riverside Park — willow trees and golden light (free, best at 5 PM). 3) The Greenhouse at Oakwood — lush botanicals inside industrial glass (rental: $150/hr). I\'d recommend starting at the Railyard and ending at Riverside for variety. Golden hour is at 6:12 PM that day.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Rescheduling Due to Weather',
        description: 'Rain is forecast for Saturday\'s outdoor session. AI proactively reaches out to reschedule.',
        aiResponse: 'Weather alert: 80% chance of rain Saturday afternoon. I\'ve proactively messaged the Martinez family: "Hi! Unfortunately Saturday\'s forecast shows rain during our session time. I\'d love to reschedule to Sunday at 4 PM (sunny, 72\u00B0F) or next Saturday at the same time. Alternatively, we have a beautiful indoor studio option. Which would you prefer?" They chose Sunday — rebooked and confirmed.',
        channel: 'sms',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Review Response',
        description: 'A client leaves a glowing 5-star Google review about their wedding photography experience.',
        aiResponse: 'New 5-star review from Sarah & David: "Our wedding photos are absolutely stunning. The team captured every moment perfectly." I\'ve responded: "Thank you so much, Sarah & David! Your wedding at Rosewood was one of our favorite days this year. We\'re so happy you love your images — you two made our job easy! Wishing you a lifetime of beautiful moments together."',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '3:30 PM',
        title: 'Instagram Content Scheduling',
        description: 'AI curates and schedules the week\'s Instagram content from recent sessions.',
        aiResponse: 'This week\'s Instagram content scheduled: Monday — behind-the-scenes reel from the Chen engagement session. Wednesday — baby Olivia newborn spotlight (with parent permission). Friday — "Why Golden Hour Matters" educational carousel with before/after examples. Saturday — Martinez family sneak peek. All captions written, hashtags researched, and posted at peak engagement times.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '4:30 PM',
        title: 'Second Photographer Coordination',
        description: 'AI coordinates with a second shooter for an upcoming wedding, sharing the timeline and shot list.',
        aiResponse: 'Second photographer briefing sent to Jake for the Robinson wedding: timeline (10 hours, 8 AM–6 PM), shot list (42 must-have shots), venue map with key locations marked, and the couple\'s priority moments list. Also shared the lighting plan for the reception (difficult venue — low ceilings, warm tungsten). Jake confirmed and will bring his 70-200mm for the ceremony.',
        channel: 'email',
        capability: 'team',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Contract/Deposit Question',
        description: 'A potential client asks about the booking process, contract terms, and deposit requirements.',
        aiResponse: 'Hi Rachel! Great question. To book, we require a signed contract and a 30% non-refundable retainer ($960 for the Gold package). The remaining balance is due 14 days before your wedding. The contract covers rescheduling policies (free reschedule up to 30 days out), image delivery timeline (6–8 weeks), and print rights (full personal use license included). I\'ve attached a sample contract for your review.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Editing Timeline Update',
        description: 'AI sends proactive updates to clients about their gallery editing progress.',
        aiResponse: 'Editing timeline updates sent to 3 clients: The Nguyen family gallery — editing complete, delivery tomorrow. Sarah & David\'s wedding — 60% edited (420 of 700 images), on track for delivery April 10th. The Chen engagement session — culling complete, editing begins Monday. Each client received a personalized message with their specific timeline and a sneak peek image.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles inquiries about packages, pricing, availability, and session details across all channels.',
      memory: 'Tracks every client\'s session history, style preferences, family details, and print orders.',
      proactive: 'Weather alerts for outdoor sessions, editing timeline updates, and gallery expiration reminders.',
      bookings: 'Schedules sessions, consultations, and second shooter availability with calendar integration.',
      leads: 'Captures inquiries from Instagram, wedding directories, and referrals, then nurtures them to booking.',
      revenue: 'Manages print orders, album sales, session add-ons, and follow-up campaigns for past clients.',
      reputation: 'Responds to Google and WeddingWire reviews and requests them after gallery delivery.',
      content: 'Creates Instagram reels, educational carousels, blog posts, and Pinterest content from session images.',
      reporting: 'Weekly booking pipeline, monthly revenue tracking, and editing workload management.',
      browser: 'Researches locations, checks permit requirements, and monitors weather forecasts for sessions.',
      team: 'Second shooters and assistants query AI for timelines, shot lists, and client preferences.',
      workflow: 'Syncs CRM with calendar, invoicing, gallery delivery, and print lab orders.',
      voice: 'Handles client calls about session details and last-minute schedule changes.',
      multiagent: 'Runs parallel location research and vendor coordination for multi-day wedding coverage.',
      environment: 'Controls studio lighting presets and backdrop changes for in-studio sessions.',
    },
    stats: {
      messagesPerDay: 30,
      bookingsPerWeek: 8,
      monthlySavings: 4500,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Photography studios thrive on reputation and visual content marketing. The Manager tier handles reviews, social media, revenue from print sales, and the content that fills your calendar.',
  },

  /* ================================================================
     Travel Agency
     ================================================================ */
  {
    id: 'travel-agency',
    label: 'Travel Agency',
    emoji: '✈️',
    category: 'Other',
    tagline: 'Every trip planned, every itinerary perfected, every traveler supported — from first inquiry to post-trip review.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Honeymoon Package Inquiry',
        description: 'A newlywed couple reaches out asking about honeymoon packages to the Maldives.',
        aiResponse: 'New honeymoon inquiry from Jessica & Tom — Maldives, 10 days in June, budget $12,000–$15,000. I\'ve responded with 3 curated packages: Overwater Villa at Soneva Fushi ($14,200, all-inclusive), Beach Bungalow at Cocoa Island ($11,800, half-board), and Island-Hopping Experience ($13,500, 3 resorts). Each includes flights, transfers, and a couples spa session. Offered a video consultation Thursday at 3 PM.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Group Trip Coordination',
        description: 'A corporate client needs to coordinate a team retreat for 25 people in Costa Rica.',
        aiResponse: 'Group trip update for Meridian Corp\'s Costa Rica retreat (25 pax, May 15–19). I\'ve secured group rates at the Andaz Papagayo ($185/night pp vs. $260 rack rate). Activities confirmed: zip-lining Day 2, team cooking class Day 3, catamaran sunset cruise Day 4. Still pending: airport transfer manifest (need 3 more passport numbers). Sent a reminder to the 3 missing attendees.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:00 AM',
        title: 'Flight Change Notification',
        description: 'An airline sends a schedule change notification affecting a client\'s upcoming trip.',
        aiResponse: 'Flight change alert: United moved the Rodriguez family\'s LAX-Cancun flight from 8:15 AM to 11:40 AM on April 3rd. This cuts into their first day at the resort. I\'ve found an alternative: Delta at 7:30 AM (similar price, 15 minutes shorter). I\'ve messaged the family: "Your flight was changed. I found a better option — shall I rebook? No price difference." Waiting for confirmation.',
        channel: 'sms',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:15 AM',
        title: 'Hotel Upgrade Offer',
        description: 'AI detects a price drop on a premium room category for an upcoming client booking.',
        aiResponse: 'Price drop opportunity for the Patels\' Santorini trip: their booked Deluxe Room at Katikies is now only $40/night more for an upgrade to Infinity Pool Suite (was $120/night more). Over 5 nights, that\'s $200 for a significant upgrade. I\'ve messaged them: "Great news — a premium upgrade is available for your Santorini stay at a fraction of the usual cost. Interested?" They said yes — upgrade confirmed!',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'savings', increment: 400 },
      },
      {
        time: '11:30 AM',
        title: 'Visa Requirement Question',
        description: 'A client planning a trip to Vietnam asks about visa requirements for US passport holders.',
        aiResponse: 'Hi Marcus! For Vietnam with a US passport: you\'ll need an e-visa ($25, processed in 3 business days) for stays up to 90 days. Your trip is 12 days, so you\'re well within the limit. I recommend applying at least 2 weeks before departure. I\'ve sent you the official e-visa application link and a step-by-step guide. Your passport expires March 2027 — needs to be valid 6 months past entry, so you\'re all set.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Travel Insurance Recommendation',
        description: 'A client with a $15,000 trip asks about travel insurance options.',
        aiResponse: 'Travel insurance options for the Thompsons\' European trip ($15,200 total cost): 1) World Nomads Explorer ($342) — trip cancellation + medical + baggage. 2) Allianz OneTrip Prime ($298) — trip cancellation + medical, lower baggage coverage. 3) Cancel For Any Reason upgrade (+$180) — 75% reimbursement for any cancellation. Given the trip cost, I\'d strongly recommend option 1 with the CFAR add-on. Shall I enroll you?',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Itinerary Delivery',
        description: 'AI compiles and delivers a beautifully formatted day-by-day itinerary to a client.',
        aiResponse: 'Itinerary delivered to the Rodriguez family for their Cancun trip! 7-day plan includes: Day 1 — resort check-in and beach day. Day 2 — Chichen Itza guided tour. Day 3 — cenote snorkeling. Day 4 — Isla Mujeres catamaran. Day 5 — resort spa day. Day 6 — Tulum ruins + beach club. Day 7 — departure. Each day has restaurant recommendations, transfer details, and confirmation numbers. PDF and mobile-friendly versions sent.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Airport Transfer Booking',
        description: 'AI books private airport transfers for a client arriving in Bali at midnight.',
        aiResponse: 'Private airport transfer booked for the Nguyens arriving in Bali March 20th at 11:55 PM. Driver will be in arrivals holding a sign. Vehicle: private AC minivan (comfortable for the family of 5 with luggage). Cost: $35 — much better than the $65 taxi rate. Driver\'s WhatsApp number shared with the client for real-time coordination. Return transfer on March 28th also confirmed.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Destination Comparison',
        description: 'A couple can\'t decide between Greece and Croatia for their summer vacation. AI prepares a comparison.',
        aiResponse: 'Comparison ready for Karen & Mike: Greece vs. Croatia, 10 days in July. Greece: $8,200 (island-hopping Santorini + Mykonos + Athens, iconic sunsets, higher food costs). Croatia: $6,800 (Dubrovnik + Split + Hvar, Game of Thrones scenery, better value dining). Both offer stunning coastlines and history. Greece is more romantic; Croatia is more adventurous. I\'d recommend Croatia for the better value and fewer crowds in July. Want to dive deeper into either?',
        channel: 'email',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Loyalty Points Redemption',
        description: 'A frequent client asks how to best use their 180,000 airline miles for an upcoming trip.',
        aiResponse: 'Great news, David! With 180,000 United miles, here are your best redemption options for Tokyo in October: 1) Business class round-trip (160K miles + $86 taxes — incredible value at $8,400 retail). 2) Economy round-trip (70K miles) + use remaining 110K for a 3-night Hyatt stay. I\'d recommend option 1 — business class to Tokyo is a bucket-list experience and the best cents-per-mile value. Want me to search specific dates?',
        channel: 'whatsapp',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 8400 },
      },
      {
        time: '7:00 PM',
        title: 'Post-Trip Review Request',
        description: 'AI sends a follow-up to clients who returned from their trip 3 days ago.',
        aiResponse: 'Welcome home messages sent to 4 clients who returned this week. Each received a personalized follow-up: "Welcome back from [destination]! We hope it was everything you dreamed of. We\'d love to hear about your favorite moments — and if you have a minute, a Google review would mean the world to us." Also included a 10% discount code for their next booking. The Patels already left a 5-star review!',
        channel: 'email',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 4 },
      },
      {
        time: '9:00 PM',
        title: 'Seasonal Deals Newsletter',
        description: 'AI compiles and sends a curated newsletter featuring the best travel deals for the upcoming season.',
        aiResponse: 'Summer deals newsletter sent to 1,200 subscribers. Featured: 40% off Maldives overwater villas (June), $899 all-inclusive Cancun packages, Greek island-hopping from $2,400, and an exclusive Japan cherry blossom early-bird for next spring. Personalized recommendations based on each subscriber\'s travel history and preferences. Last newsletter had a 32% open rate and generated 14 inquiries.',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles trip inquiries, visa questions, itinerary changes, and real-time travel support across all channels.',
      memory: 'Tracks every client\'s travel history, preferences, passport details, loyalty programs, and dream destinations.',
      proactive: 'Alerts for flight changes, price drops, visa deadlines, and passport expiration reminders.',
      bookings: 'Coordinates flights, hotels, transfers, activities, and restaurant reservations across complex itineraries.',
      leads: 'Captures trip inquiries, follows up on quotes, and nurtures leads with destination inspiration content.',
      revenue: 'Manages loyalty points optimization, upsell opportunities, and re-engagement campaigns for past travelers.',
      reputation: 'Sends post-trip review requests and responds to Google and TripAdvisor reviews promptly.',
      content: 'Creates seasonal deal newsletters, destination guides, travel tips, and social media content.',
      reporting: 'Monthly booking summaries, revenue per destination analysis, and client satisfaction tracking.',
      browser: 'Researches flight prices, hotel availability, visa requirements, and destination safety advisories.',
      team: 'Travel consultants query AI for client preferences, booking details, and destination information.',
      workflow: 'Syncs booking platforms with CRM, invoicing, and itinerary delivery systems.',
      voice: 'Handles client calls about trip changes, emergency support, and new booking consultations.',
      multiagent: 'Runs parallel searches across airlines, hotels, and activity providers for the best deals.',
      environment: 'Controls presentation screens for client consultation meetings with destination showcases.',
    },
    stats: {
      messagesPerDay: 40,
      bookingsPerWeek: 12,
      monthlySavings: 8500,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Travel agencies need real-time flight monitoring, multi-platform booking research, and complex itinerary management that require executive-tier capabilities.',
  },

  /* ================================================================
     Nonprofit / Charity
     ================================================================ */
  {
    id: 'nonprofit',
    label: 'Nonprofit / Charity',
    emoji: '💚',
    category: 'Other',
    tagline: 'Every donor thanked, every volunteer engaged, every campaign amplified — so you can focus on your mission.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Donation Thank-You',
        description: 'AI sends personalized thank-you messages to overnight donors with tax receipt information.',
        aiResponse: 'Thank-you messages sent to 8 overnight donors. Total received: $2,340. Each message is personalized: "Dear Margaret, thank you so much for your generous $250 gift to Bright Futures. Your donation will provide school supplies for 5 children this semester. Your tax receipt is attached (EIN: 47-1234567). You\'re making a real difference." Recurring donors received an additional impact update.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 8 },
      },
      {
        time: '7:30 AM',
        title: 'Volunteer Sign-Up',
        description: 'A new volunteer registers through the website to help at the upcoming community food drive.',
        aiResponse: 'New volunteer registration: Alex Chen — interested in the April 12th food drive. I\'ve sent a welcome email with event details (8 AM–2 PM at Community Center), parking info, what to wear, and a volunteer waiver to sign. Also added him to the food drive group chat. Current volunteer count: 34 of 40 needed. I\'ll send a final recruitment push if we\'re not at capacity by Friday.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:45 AM',
        title: 'Event Registration',
        description: 'Registrations are coming in for the annual charity gala. AI manages RSVPs and seating.',
        aiResponse: 'Gala registration update: 142 of 200 seats filled. 12 new registrations overnight (8 individual, 2 couples, 1 table of 8 from Meridian Corp). I\'ve assigned seating based on sponsor tier and preferences. The silent auction catalog was sent to all registrants. VIP reception list: 28 confirmed. Sent a reminder to 15 unconfirmed invitees. Revenue from tickets so far: $21,300.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 12 },
      },
      {
        time: '10:00 AM',
        title: 'Grant Deadline Reminder',
        description: 'A major grant application deadline is approaching in 5 days. AI sends reminders and checks status.',
        aiResponse: 'REMINDER: The Johnson Foundation grant application ($50,000) is due Friday, March 17th. Status check: narrative section complete, budget finalized, board resolution attached, but we\'re still missing the letter of support from Councilwoman Davis. I\'ve sent a follow-up to her office this morning. Also flagged: the Community Impact Fund LOI is due March 25th — I\'ve started the draft.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:15 AM',
        title: 'Donor Follow-Up',
        description: 'AI identifies lapsed donors (no gift in 12+ months) and sends personalized re-engagement messages.',
        aiResponse: 'Lapsed donor re-engagement sent to 22 supporters who haven\'t given in 12+ months. Each message references their last gift and its impact: "Hi Robert — your $500 gift last year helped us serve 200 meals at our Thanksgiving event. This year, we\'re aiming for 500 meals and we\'d love your support again." Included a matching gift opportunity (all gifts doubled through March 31st). Last year\'s campaign recovered 18% of lapsed donors.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'messages', increment: 22 },
      },
      {
        time: '12:30 PM',
        title: 'Social Media Campaign',
        description: 'AI creates and schedules a week of social media content for the current fundraising campaign.',
        aiResponse: 'Fundraising campaign social content scheduled for the week: Monday — impact video (testimonial from a scholarship recipient). Tuesday — infographic showing program growth. Wednesday — matching gift announcement. Thursday — behind-the-scenes at the food pantry. Friday — countdown to gala with ticket link. Saturday — volunteer spotlight. All posts have branded graphics, hashtags (#BrightFutures2026), and donation links.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:45 PM',
        title: 'Newsletter Distribution',
        description: 'AI compiles and sends the monthly newsletter to supporters, donors, and community members.',
        aiResponse: 'March newsletter sent to 3,400 subscribers. Contents: Executive Director\'s letter, spring program highlights, upcoming events (gala + food drive), volunteer spotlight on Maria Torres, and a "Where Your Dollars Go" infographic. Personalized sections: donors see their giving history and impact, volunteers see upcoming opportunities, and corporate partners see their logo placement. Open rate target: 28%.',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Impact Report Delivery',
        description: 'AI generates and sends a quarterly impact report to major donors and board members.',
        aiResponse: 'Q1 Impact Report delivered to 45 major donors and 12 board members. Key highlights: 1,200 meals served (up 15% YoY), 48 scholarships awarded, 3 new community partnerships. Financial snapshot: $185,000 raised this quarter, 92% program spending ratio. Report includes beneficiary testimonials, photos, and a thank-you from the Executive Director. Board version includes detailed financials and strategic updates.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Corporate Sponsorship Inquiry',
        description: 'A local business reaches out about sponsoring the annual gala and getting involved.',
        aiResponse: 'New sponsorship inquiry from DataFlow Technologies! They\'re interested in the annual gala and ongoing partnership. I\'ve responded with our sponsorship packet: Gold ($10,000 — table of 10, logo on all materials, social media features), Silver ($5,000 — 4 seats, logo on event signage), and Bronze ($2,500 — 2 seats, website listing). Also included our corporate volunteer program info. Offered a meeting next Tuesday.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '4:30 PM',
        title: 'Recurring Donation Setup',
        description: 'A donor wants to convert their one-time gift into a monthly recurring donation.',
        aiResponse: 'Hi Patricia! Great news — I\'ve set up your monthly recurring donation of $50, starting April 1st. That\'s $600 annually, which funds an entire year of after-school tutoring for one student. You\'ll receive a monthly confirmation email and an annual tax summary in January. You can modify or cancel anytime through your donor portal. Thank you for this incredible commitment to our students!',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 600 },
      },
      {
        time: '6:00 PM',
        title: 'Community Outreach',
        description: 'AI reaches out to local organizations about partnership opportunities and upcoming programs.',
        aiResponse: 'Community outreach sent to 8 local organizations: 3 schools (after-school program expansion), 2 churches (food drive collection points), 2 businesses (employee volunteer days), and 1 community center (shared space for summer camp). Each message is tailored to the organization\'s mission and how a partnership would benefit both parties. Last quarter\'s outreach resulted in 5 new partnerships.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 8 },
      },
      {
        time: '9:00 PM',
        title: 'Annual Report Stats Compilation',
        description: 'AI compiles program data and financial metrics for the upcoming annual report.',
        aiResponse: 'Annual report data compilation in progress. Key stats gathered: Total raised: $742,000 (up 12% from last year). Programs served: 4,800 individuals. Volunteer hours: 8,200. Top programs by impact: Food Pantry (2,100 families), Scholarship Fund (48 recipients, $96,000 awarded), Youth Mentoring (120 matches). Financial health: 94% program spending ratio, 6-month operating reserve. Draft report will be ready for board review next week.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles donor inquiries, volunteer questions, and community outreach across email, phone, and social media.',
      memory: 'Tracks every donor\'s giving history, volunteer hours, event attendance, and communication preferences.',
      proactive: 'Grant deadline reminders, donor anniversary alerts, and campaign milestone notifications.',
      bookings: 'Manages volunteer sign-ups, event registrations, meeting scheduling, and facility reservations.',
      leads: 'Captures sponsorship inquiries, event registrations, and converts one-time donors into recurring supporters.',
      revenue: 'Re-engages lapsed donors, manages recurring giving programs, and tracks fundraising campaign progress.',
      reputation: 'Sends impact updates to donors and responds to community feedback and reviews.',
      content: 'Creates fundraising campaigns, newsletters, social media content, and annual report materials.',
      reporting: 'Quarterly impact reports, fundraising dashboards, and grant compliance documentation.',
      browser: 'Researches grant opportunities, monitors foundation deadlines, and tracks peer organization benchmarks.',
      team: 'Staff and volunteers query AI for donor information, event details, and program data.',
      workflow: 'Syncs CRM with email marketing, event management, and accounting systems.',
      voice: 'Handles donor calls, takes event RSVPs, and manages volunteer hotline inquiries.',
      multiagent: 'Runs parallel grant research and donor prospecting across multiple databases.',
      environment: 'Controls event displays, presentation screens, and livestream setups for fundraising events.',
    },
    stats: {
      messagesPerDay: 45,
      bookingsPerWeek: 16,
      monthlySavings: 6200,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Nonprofits need strong donor relationship management, content marketing for campaigns, and revenue tracking to maximize fundraising impact — all core Manager tier capabilities.',
  },
];
