import type { Industry } from '../experience-data';

export const otherIndustries: Industry[] = [
  /* ================================================================
     B2B / Corporate
     ================================================================ */
  {
    id: 'b2b',
    label: 'B2B / Corporate',
    emoji: '🏢',
    category: 'Other',
    tagline: 'Close deals faster with an AI that manages your entire sales pipeline around the clock.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Pipeline Morning Brief',
        description: 'AI compiles overnight CRM activity — new inbound leads, stalled deals, and contracts expiring this week.',
        aiResponse: 'Good morning. 3 new enterprise leads came in overnight. Deal #4821 with Meridian Corp has been idle for 9 days — I\'ve drafted a nudge email for your review. Two contracts expire Friday; renewal decks are ready.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Inbound Lead Qualification',
        description: 'A VP of Operations fills out the enterprise contact form. AI researches the company and pre-qualifies the lead.',
        aiResponse: 'New lead: Sarah Chen, VP Ops at NovaTech (Series C, 320 employees, $48M ARR). They match your Ideal Customer Profile on 4/5 criteria. I\'ve scored them as high-priority and scheduled a discovery call slot for tomorrow at 2 PM. Sending a personalized welcome sequence now.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:15 AM',
        title: 'Proposal Follow-Up',
        description: 'AI detects that a proposal sent last week has been opened 4 times but no reply was received.',
        aiResponse: 'Heads up — the Greenfield Industries proposal was opened again this morning by two different IP addresses (likely shared internally). No reply yet. I\'ve drafted a check-in message referencing their Q3 expansion timeline. Want me to send it?',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 8500 },
      },
      {
        time: '9:00 AM',
        title: 'Partner Channel Update',
        description: 'A reseller partner messages asking for updated pricing tiers and co-branded collateral.',
        aiResponse: 'Hi Marcus, great to hear from you. I\'ve attached the updated 2026 partner pricing sheet and the co-branded one-pager template. Your current deal registrations are on track — 2 of 3 are in proposal stage. Let me know if you need custom pricing for the Acme opportunity.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Contract Renewal Outreach',
        description: 'AI initiates automated renewal conversations 60 days before contract expiry.',
        aiResponse: 'I\'ve started the renewal sequence for 4 accounts expiring in April. Each received a personalized email highlighting their usage stats and ROI metrics. Two accounts qualify for a volume upgrade — I\'ve flagged those for upsell conversations.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 12000 },
      },
      {
        time: '11:00 AM',
        title: 'Meeting Prep Package',
        description: 'AI prepares a briefing dossier before a discovery call with a prospect.',
        aiResponse: 'Your 2 PM call with NovaTech is prepped. Dossier includes: company background, recent funding news, LinkedIn profiles of attendees, their current tech stack (pulled from job postings), and 3 pain points likely relevant to them. Talking points are in your shared doc.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 500 },
      },
      {
        time: '12:00 PM',
        title: 'Competitor Intelligence Alert',
        description: 'AI detects a competitor just launched a new feature that overlaps with your offering.',
        aiResponse: 'Alert: CompetitorX just announced an AI-powered analytics module — similar to your Premium tier. I\'ve summarized their positioning, pricing, and feature gaps. Your differentiators: deeper integrations and dedicated onboarding. I\'ve drafted a battle card for the sales team.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '1:30 PM',
        title: 'Client Success Check-In',
        description: 'AI sends a quarterly business review reminder and gathers usage data for the deck.',
        aiResponse: 'QBR with DataFlow Inc is next Thursday. I\'ve compiled their usage dashboard: 34% increase in active users, 12 support tickets (all resolved), and 2 feature requests pending. Draft slide deck is ready. Their NPS score went from 7 to 9 this quarter.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '2:30 PM',
        title: 'RFP Response Coordination',
        description: 'A prospect sends an RFP with 47 questions. AI begins drafting responses from your knowledge base.',
        aiResponse: 'Received the TechCorp RFP — 47 questions across security, compliance, integration, and pricing. I\'ve auto-filled 38 answers from our knowledge base. 9 need your input (flagged in yellow). Deadline is March 20th. I\'ve set reminders for the team contributors.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 3000 },
      },
      {
        time: '4:00 PM',
        title: 'Lead Nurture Sequence Trigger',
        description: 'AI detects a cold lead re-engaging with content and escalates them back into the warm pipeline.',
        aiResponse: 'Remember BluePeak Solutions? They went cold 3 months ago. Their CTO just downloaded your integration whitepaper and visited the pricing page twice today. I\'ve moved them back to warm pipeline and queued a personal outreach from their original account exec.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Daily Pipeline Summary',
        description: 'AI generates end-of-day pipeline movement report for the sales team.',
        aiResponse: 'Today\'s pipeline: 3 new leads added ($127K potential), 1 deal moved to negotiation (Meridian — $45K), 2 proposals sent, 4 renewal sequences started. Pipeline value up 6.2% this week. Tomorrow\'s priorities: NovaTech discovery call and Greenfield follow-up.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Overnight International Lead Capture',
        description: 'AI handles an inquiry from a prospect in a different timezone while the team is offline.',
        aiResponse: 'Handled an after-hours inquiry from a London-based fintech (CapitalFlow Ltd). They asked about API rate limits, SOC 2 compliance, and enterprise pricing. I answered all three from the knowledge base and booked a demo for 9 AM GMT tomorrow. Full transcript saved to CRM.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to enterprise prospects across email, WhatsApp, and LinkedIn messages with full deal context.',
      memory: 'Remembers every interaction with each account — last meeting notes, objections raised, key stakeholders.',
      proactive: 'Morning pipeline briefs, stalled deal alerts, contract expiry warnings 60 days out.',
      bookings: 'Books discovery calls, demos, and QBRs directly into team calendars.',
      leads: 'Scores inbound leads against ICP, researches companies, routes to the right sales rep.',
      revenue: 'Chases overdue invoices, triggers renewal sequences, identifies upsell opportunities.',
      reporting: 'Weekly pipeline reports, monthly win/loss analysis, quarterly forecasting summaries.',
      browser: 'Researches prospects, monitors competitor launches, pulls company intel from public sources.',
      workflow: 'Syncs CRM, email, calendar, and proposal tools — no manual data entry.',
    },
    stats: {
      messagesPerDay: 65,
      bookingsPerWeek: 18,
      monthlySavings: 9200,
      responseTime: '< 4 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'B2B sales cycles need persistent follow-up, pipeline reporting, and competitive intelligence that go beyond basic communication.',
  },

  /* ================================================================
     Tech / Software
     ================================================================ */
  {
    id: 'tech',
    label: 'Tech / Software',
    emoji: '📱',
    category: 'Other',
    tagline: 'Ship faster with an AI that triages support, coordinates sprints, and keeps users engaged.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Deployment Health Check',
        description: 'AI reviews overnight deployment logs, error rates, and uptime monitoring dashboards.',
        aiResponse: 'Good morning. Last night\'s v3.8.2 deploy completed at 2:14 AM — zero rollback triggers. Error rate is 0.03% (within threshold). Two Sentry alerts fired but both were transient timeout issues that self-resolved. All systems green.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'Support Ticket Triage',
        description: 'AI categorizes and prioritizes 14 support tickets that came in overnight from users across timezones.',
        aiResponse: 'Triaged 14 overnight tickets: 2 critical (payment processing errors — assigned to payments team), 5 moderate (UI bugs in the new dashboard), 7 low (how-to questions — I\'ve auto-replied with docs links). The 2 critical tickets have been escalated to on-call.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 14 },
      },
      {
        time: '8:30 AM',
        title: 'Sprint Standup Summary',
        description: 'AI compiles async standup updates from the engineering team and flags blockers.',
        aiResponse: 'Sprint 24 standup: 8/10 engineers submitted updates. 2 blockers flagged — the API rate limiter PR needs security review, and the mobile team is waiting on design specs for the settings page. Velocity is on track: 34 of 52 story points completed, 5 days remaining.',
        channel: 'system',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '9:00 AM',
        title: 'Feature Request Pattern Detection',
        description: 'AI analyzes recent feature requests and identifies a trending pattern across user segments.',
        aiResponse: 'Interesting trend: 23 users requested CSV export in the last 30 days — up 340% from the previous period. 78% are on the Pro plan. Top use cases: monthly reporting and data migration. I\'ve created a feature brief with user quotes and added it to the backlog for prioritization.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '10:00 AM',
        title: 'User Onboarding Assist',
        description: 'A new trial user is stuck on the integration setup step. AI provides real-time guidance.',
        aiResponse: 'Hi Alex! I see you\'re setting up the Stripe integration. The webhook URL should be pasted into your Stripe dashboard under Developers > Webhooks. Here\'s a 30-second walkthrough video. Also, make sure you\'re using the live key, not the test key — I noticed the prefix is "sk_test". Let me know if you need help!',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Churn Risk Detection',
        description: 'AI flags an enterprise account whose usage dropped 60% this month.',
        aiResponse: 'Churn risk alert: CloudStack Inc (Enterprise plan, $2,400/mo) usage dropped 62% this month. Last login was 11 days ago. Their admin hasn\'t opened our last 3 emails. I recommend a personal check-in call — I\'ve drafted talking points and pulled their usage history.',
        channel: 'system',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'savings', increment: 2400 },
      },
      {
        time: '12:30 PM',
        title: 'Knowledge Base Auto-Update',
        description: 'AI detects that a help article is outdated after the latest release and drafts an update.',
        aiResponse: 'The "Getting Started with Webhooks" article references the v2 API endpoint that was deprecated in v3.8. I\'ve drafted an updated version with the new endpoint, added a migration note, and included the new authentication flow. Ready for review in your docs repo.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '1:30 PM',
        title: 'Bug Report Investigation',
        description: 'A user reports a bug via in-app chat. AI reproduces the issue and files a detailed ticket.',
        aiResponse: 'Confirmed bug: date picker shows incorrect timezone for users in UTC+10 and above. Reproduced on Chrome 124 and Safari 18. Root cause likely in the date-fns locale config. I\'ve filed JIRA-4521 with reproduction steps, browser logs, and suggested fix. Assigned to the frontend team.',
        channel: 'whatsapp',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Trial-to-Paid Conversion Nudge',
        description: 'AI sends a personalized upgrade prompt to a trial user who has hit usage limits.',
        aiResponse: 'Alex from earlier just hit the free tier API limit (1,000 calls). They\'ve integrated 3 webhooks and created 2 dashboards — clearly getting value. I\'ve sent a personalized upgrade email highlighting their usage, offering 20% off the first month of Pro, and showing features they\'d unlock.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 590 },
      },
      {
        time: '4:30 PM',
        title: 'Release Notes Draft',
        description: 'AI drafts user-facing release notes from the Git changelog and Jira tickets closed this sprint.',
        aiResponse: 'Drafted release notes for v3.8.2: 3 new features (CSV export, dark mode, webhook retry config), 7 bug fixes, and 2 performance improvements. Written in user-friendly language with screenshots. Blog post version and in-app changelog version are both ready for review.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Engineering Report',
        description: 'AI summarizes the day\'s engineering output, support metrics, and user growth.',
        aiResponse: 'Daily wrap: 8 PRs merged, 2 critical bugs fixed, 14 tickets resolved (avg response: 18 min). New signups: 47 (12% above daily average). Trial-to-paid conversions: 3. Server costs down 4% after the caching optimization. Tomorrow: security review for the rate limiter PR.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'After-Hours Critical Alert',
        description: 'Monitoring detects a spike in 500 errors. AI investigates and escalates if needed.',
        aiResponse: 'Alert: 500 error rate spiked to 2.1% at 9:47 PM — traced to the payment service. The third-party Stripe webhook endpoint is returning 503. This is on Stripe\'s side (confirmed via their status page). I\'ve enabled the fallback queue so no transactions are lost. On-call notified as FYI only.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles support tickets, in-app chat, and developer community questions across all channels.',
      memory: 'Tracks every user\'s plan, feature usage, past tickets, and sentiment history.',
      proactive: 'Deployment health checks, error rate monitoring, churn risk detection alerts.',
      bookings: 'Schedules demos for trial users, onboarding calls, and QBRs with enterprise accounts.',
      leads: 'Scores trial signups by engagement, routes enterprise inquiries to sales.',
      revenue: 'Identifies upgrade opportunities, sends conversion nudges, chases overdue invoices.',
      content: 'Drafts release notes, updates help docs, writes changelog posts from Git history.',
      reporting: 'Daily engineering metrics, weekly support KPIs, monthly product analytics.',
      browser: 'Monitors competitor product pages, tracks pricing changes, reads Hacker News mentions.',
      workflow: 'Syncs Jira, GitHub, Slack, and docs — auto-files bugs, assigns tickets, updates boards.',
      team: 'Compiles async standups, flags blockers, coordinates cross-team dependencies.',
    },
    stats: {
      messagesPerDay: 85,
      bookingsPerWeek: 12,
      monthlySavings: 7800,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Software companies need deep workflow integration, team coordination, and browser-based monitoring that require Executive-tier autonomy.',
  },

  /* ================================================================
     Creative / Media Agency
     ================================================================ */
  {
    id: 'creative',
    label: 'Creative / Media Agency',
    emoji: '🎬',
    category: 'Other',
    tagline: 'Never miss a deadline again — AI tracks every brief, revision, and deliverable across all your clients.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Daily Project Dashboard',
        description: 'AI compiles the status of all active client projects, flagging deadlines within 48 hours.',
        aiResponse: 'Morning update: 11 active projects across 7 clients. 2 deadlines today (Luna Cosmetics social pack, GreenEat brand guidelines v2). 1 project at risk — the Apex Fitness video edit is waiting on client footage since Tuesday. I\'ve sent a follow-up to their marketing director.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'New Client Brief Intake',
        description: 'A new client submits a creative brief via the intake form. AI parses requirements and sets up the project.',
        aiResponse: 'New brief from Solara Wines: Brand refresh — logo, packaging, website. Budget: $18,000. Timeline: 6 weeks. I\'ve created the project folder, set up the timeline with milestones, drafted the scope document, and scheduled a kick-off call for Thursday at 10 AM.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Revision Round Tracking',
        description: 'A client sends feedback on logo concepts via WhatsApp with voice notes and image markups.',
        aiResponse: 'Luna Cosmetics feedback on logo concepts: They love Option B (the botanical monogram) but want the green shifted warmer, the tagline in a serif font, and the icon simplified. I\'ve logged all 6 revision points in the project tracker and assigned them to the design team with the original voice notes attached.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Content Calendar Review',
        description: 'AI presents this week\'s content calendar for a retainer client, ready for approval.',
        aiResponse: 'GreenEat\'s content calendar for this week: Monday — recipe reel (shot last Friday), Wednesday — ingredient sourcing behind-the-scenes, Friday — customer testimonial carousel. Captions are drafted, hashtag sets researched, and posting times optimized based on their last 90 days of engagement data.',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '10:30 AM',
        title: 'Vendor Quote Comparison',
        description: 'AI collects and compares quotes from 3 print vendors for a client\'s packaging job.',
        aiResponse: 'Print quotes for Solara Wines labels: Vendor A — $2.10/unit (min 5,000), Vendor B — $1.85/unit (min 10,000), Vendor C — $2.40/unit (min 1,000, eco-certified). Given the client\'s 8,000-unit run and sustainability values, I recommend Vendor C for the first batch. Comparison spreadsheet attached.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 1200 },
      },
      {
        time: '11:30 AM',
        title: 'Client Approval Reminder',
        description: 'AI follows up on a deliverable that\'s been pending client approval for 3 days, blocking the next phase.',
        aiResponse: 'Gentle reminder sent to Apex Fitness: the website wireframes have been pending approval since Friday, and the development phase can\'t start until sign-off. I\'ve included a direct approval link and noted the timeline impact if we don\'t hear back by tomorrow. Their PM acknowledged receipt.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Freelancer Coordination',
        description: 'AI briefs a freelance videographer for an upcoming shoot and shares the production schedule.',
        aiResponse: 'Briefed freelance videographer (Marco) for the Solara Wines shoot next Wednesday: location confirmed (their vineyard in Napa), shot list attached (15 scenes), call time 7 AM for golden hour. Equipment checklist sent. He confirmed availability and his day rate of $850.',
        channel: 'whatsapp',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '2:00 PM',
        title: 'Social Media Performance Report',
        description: 'AI generates a monthly performance report for a retainer client\'s social channels.',
        aiResponse: 'GreenEat February report: Instagram grew 12% (3,240 new followers), top post was the farm-to-table reel (48K views). TikTok engagement up 23%. Website traffic from social increased 18%. Three content themes outperformed: behind-the-scenes, recipes, and customer stories. Recommendations for March included.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '3:00 PM',
        title: 'Scope Creep Detection',
        description: 'AI detects that a client is requesting work outside the agreed project scope.',
        aiResponse: 'Heads up: Luna Cosmetics just asked for an animated logo version and social media templates — neither is in the original scope ($8,500 for static brand identity). I\'ve drafted a friendly change order for $3,200 covering the additions with a 2-week extension. Ready for your review before sending.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 3200 },
      },
      {
        time: '4:30 PM',
        title: 'Portfolio Case Study Draft',
        description: 'AI drafts a portfolio case study from a recently completed project.',
        aiResponse: 'Drafted a case study for the Apex Fitness rebrand: problem statement, creative approach, results (32% increase in gym membership inquiries post-launch). Includes before/after visuals and a client testimonial quote. Formatted for your website portfolio and a LinkedIn carousel version.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Project Sync',
        description: 'AI sends a daily status update to each active client with their project\'s progress.',
        aiResponse: 'Sent EOD updates to 5 clients: Luna Cosmetics (revisions in progress, delivery Friday), GreenEat (content scheduled for the week), Apex Fitness (awaiting footage), Solara Wines (kick-off Thursday), Brightpath (final files delivered today). All timelines current except Apex — flagged at risk.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 5 },
      },
      {
        time: '10:00 PM',
        title: 'Late-Night Client Message Handling',
        description: 'A client in a different timezone sends urgent feedback on a campaign going live tomorrow.',
        aiResponse: 'GreenEat\'s founder (in London) just sent urgent feedback on tomorrow\'s launch post: swap the hero image to the one from the tasting event and adjust the CTA to "Order Your Spring Box." I\'ve logged the changes, notified the designer for first thing tomorrow, and confirmed receipt with the client.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Manages client feedback across WhatsApp, email, and project tools — voice notes, markups, and all.',
      memory: 'Remembers each client\'s brand guidelines, preferences, past feedback patterns, and key contacts.',
      proactive: 'Daily project dashboards, deadline alerts, stalled-approval follow-ups.',
      bookings: 'Schedules kick-off calls, review meetings, shoot dates, and client presentations.',
      leads: 'Captures new briefs, qualifies project scope, sends proposals with pricing.',
      revenue: 'Detects scope creep, drafts change orders, chases overdue invoices.',
      content: 'Drafts social posts, case studies, newsletters, and performance reports for clients.',
      reporting: 'Monthly social analytics, project profitability analysis, team utilization reports.',
      browser: 'Compares vendor quotes, researches stock asset libraries, monitors competitor campaigns.',
      team: 'Briefs freelancers, coordinates shoot schedules, tracks team assignments.',
    },
    stats: {
      messagesPerDay: 72,
      bookingsPerWeek: 15,
      monthlySavings: 8500,
      responseTime: '< 5 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Creative agencies need content management, client reporting, and revenue tracking on top of multi-client communication.',
  },

  /* ================================================================
     Consulting
     ================================================================ */
  {
    id: 'consulting',
    label: 'Consulting',
    emoji: '💬',
    category: 'Other',
    tagline: 'Deliver more value to clients while AI handles intake, scheduling, follow-ups, and deliverable tracking.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Agenda Brief',
        description: 'AI reviews today\'s client meetings, prep requirements, and outstanding deliverables.',
        aiResponse: 'Good morning. Today: 9 AM strategy session with Pinnacle Group (deck is prepped), 1 PM check-in with BrightPath (their monthly KPIs are attached), and 4 PM new prospect call (Horizon Capital — research dossier ready). Outstanding: Pinnacle\'s implementation roadmap is due Friday.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Client Intake Processing',
        description: 'A new prospect fills out the consulting intake form. AI processes the information and prepares for the first call.',
        aiResponse: 'New intake: Horizon Capital, private equity firm, 45 employees. Challenge: operational efficiency across portfolio companies. Budget range: $15K-25K/month. Decision-maker: COO Rachel Kim. I\'ve researched their portfolio (12 companies, mostly B2B SaaS), prepared 3 relevant case studies, and drafted an agenda for today\'s 4 PM call.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Deliverable Progress Tracker',
        description: 'AI updates the status of all active consulting engagements and flags items behind schedule.',
        aiResponse: 'Engagement tracker: 4 active clients. Pinnacle Group — Phase 2 (on track, 68% complete). BrightPath — Monthly retainer (KPI report due today, drafted). NovaTech — Workshop series (3 of 5 complete, next one March 18). Atlas Ventures — Proposal stage (awaiting sign-off since Monday, follow-up sent).',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Post-Meeting Action Items',
        description: 'After the Pinnacle Group strategy session, AI extracts action items from the meeting transcript.',
        aiResponse: 'Meeting with Pinnacle Group — 7 action items captured: 1) Finalize org chart redesign by Thursday (you), 2) Share employee survey data (their HR team, deadline Wednesday), 3) Draft change management communication plan (you, by Friday), 4-7) minor follow-ups assigned and tracked. Summary sent to all attendees.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
      },
      {
        time: '10:30 AM',
        title: 'Thought Leadership Article Draft',
        description: 'AI drafts a LinkedIn article based on insights from recent client engagements (anonymized).',
        aiResponse: 'Drafted your next LinkedIn article: "Why 73% of Operational Transformations Stall at Phase 2 — And How to Prevent It." Based on patterns from your last 8 engagements (fully anonymized). 1,200 words, includes 3 actionable frameworks. Engagement prediction: strong, based on your audience analytics.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '11:30 AM',
        title: 'Client KPI Report Generation',
        description: 'AI compiles BrightPath\'s monthly performance report from multiple data sources.',
        aiResponse: 'BrightPath February KPI report ready: Revenue up 8%, customer acquisition cost down 12%, employee satisfaction score improved from 7.2 to 7.8. Compared against the benchmarks we set in January — 4 of 6 KPIs are on or ahead of target. 2 recommendations included for areas lagging. Ready for your 1 PM call.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '1:30 PM',
        title: 'Follow-Up Proposal Nudge',
        description: 'AI follows up on a proposal that\'s been with a prospect for 5 days without response.',
        aiResponse: 'Atlas Ventures hasn\'t responded to the $22K/month proposal sent last Monday. I\'ve sent a soft follow-up referencing their board meeting next week (found on their events page) and positioned the engagement as preparation for Q2 planning. Also offered a 30-minute clarification call.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 22000 },
      },
      {
        time: '2:30 PM',
        title: 'Workshop Material Preparation',
        description: 'AI prepares materials for the next NovaTech leadership workshop.',
        aiResponse: 'Workshop 4 materials for NovaTech ready: "Scaling Decision-Making Frameworks." Includes facilitator guide, participant workbooks (personalized with their org structure), pre-work survey (sent to 12 attendees), and the breakout room assignments based on their team composition. Printed materials shipping Thursday.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Competitive Research Scan',
        description: 'AI monitors competitor consulting firms for new service offerings and published research.',
        aiResponse: 'Weekly competitor scan: McKnight Advisory just published a report on AI adoption in mid-market (I\'ve summarized key findings). Clarity Consulting launched a new "90-Day Transformation" package at $45K — similar to your Phase 1 offering but less comprehensive. I\'ve updated the competitive positioning doc.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '4:30 PM',
        title: 'New Prospect Discovery Call',
        description: 'AI joins the discovery call with Horizon Capital, takes notes, and drafts the proposal framework.',
        aiResponse: 'Horizon Capital call complete — excellent fit. Key needs: standardize operations across 12 portfolio companies, reduce reporting overhead, implement shared KPI frameworks. Budget confirmed at $20K/month. I\'ve drafted a proposal outline, identified 2 similar past engagements for reference, and scheduled a follow-up for next Tuesday.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Weekly Utilization Summary',
        description: 'AI calculates consulting hours, billable utilization, and revenue for the week.',
        aiResponse: 'Weekly utilization: 32 billable hours across 4 clients (80% utilization — above your 75% target). Revenue this week: $14,200. Pipeline: $42K in proposals outstanding, $20K from today\'s Horizon Capital opportunity. Recommendation: you have capacity for one more retainer client starting April.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Client Reference Request Handling',
        description: 'A prospect asks for client references after hours. AI responds with curated case studies.',
        aiResponse: 'Horizon Capital\'s COO requested references. I\'ve sent 3 curated case studies matching their profile (PE firms, operational consulting) along with testimonial quotes. Also offered to arrange a brief call with a past client (confirmed their willingness last quarter). Full response personalized and professional.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles client emails, WhatsApp messages, and prospect inquiries with full engagement context.',
      memory: 'Tracks every client\'s goals, deliverables, key contacts, preferences, and historical performance data.',
      proactive: 'Daily agenda briefs, deliverable deadline alerts, engagement progress tracking.',
      bookings: 'Schedules strategy sessions, workshops, discovery calls, and QBRs across client calendars.',
      leads: 'Processes intake forms, researches prospects, prepares discovery call dossiers.',
      revenue: 'Follows up on proposals, tracks billable hours, chases overdue retainer payments.',
      content: 'Drafts thought leadership articles, case studies, and workshop materials.',
      reporting: 'Client KPI reports, weekly utilization summaries, pipeline forecasting.',
      browser: 'Monitors competitor firms, researches prospect companies, tracks industry publications.',
      workflow: 'Extracts meeting action items, tracks deliverables, syncs project management tools.',
    },
    stats: {
      messagesPerDay: 48,
      bookingsPerWeek: 14,
      monthlySavings: 11000,
      responseTime: '< 6 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Consultants need thought leadership content, client reporting, and revenue tracking alongside communication and scheduling.',
  },

  /* ================================================================
     EVENT PLANNING
     ================================================================ */
  {
    id: 'event-planning',
    label: 'Event Planning',
    emoji: '🎉',
    category: 'Other',
    tagline: 'Every vendor coordinated, every guest accounted for, every timeline on track — your AI never drops a detail.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Event Overview',
        description: 'AI compiles today\'s event prep tasks, upcoming deadlines, and vendor confirmations into a single briefing.',
        aiResponse: 'Good morning — 2 active events this week. Saturday\'s Johnson wedding: caterer confirmed (180 guests), florist delivery at 8 AM, DJ sound check at 3 PM. Next Thursday\'s corporate gala: venue walkthrough today at 11 AM, AV rental invoice due. 3 new inquiry emails overnight — all responded to with availability and pricing.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Venue Coordination Call',
        description: 'The venue manager calls to confirm setup logistics for Saturday\'s wedding.',
        aiResponse: 'Thank you for calling, Marcus. For the Johnson wedding Saturday: setup access begins at 7 AM, ceremony in the garden at 4 PM, reception in the Grand Ballroom at 5:30 PM. We need 18 round tables (seats 10), a head table for 12, and the dance floor positioned by the east windows. I\'ll send the updated floor plan within the hour.',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:45 AM',
        title: 'Vendor Payment Tracking',
        description: 'AI reviews all vendor contracts and flags payments due this week.',
        aiResponse: 'Payment tracker update: 3 vendor payments due this week — florist deposit ($1,200, due today), photographer balance ($2,800, due Friday), and lighting rental ($650, due Saturday on delivery). Total: $4,650. The Johnson\'s final payment of $8,500 was received yesterday. All vendor contracts are signed and filed.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 4650 },
      },
      {
        time: '10:00 AM',
        title: 'Guest RSVP Follow-Up',
        description: 'AI identifies guests who haven\'t responded to the wedding invitation and sends reminders.',
        aiResponse: 'RSVP follow-up for the Johnson wedding: 162 of 200 guests have responded (81%). Sent polite reminders to the remaining 38 guests with a direct RSVP link. Current count: 148 attending, 14 declined. Meal selections so far: 82 chicken, 41 salmon, 25 vegetarian. I\'ll update the caterer once we hit the 95% threshold.',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 38 },
      },
      {
        time: '11:00 AM',
        title: 'Venue Walkthrough for Corporate Gala',
        description: 'AI prepares the walkthrough checklist and sends reminders to the client and venue contact.',
        aiResponse: 'Walkthrough checklist ready for the Apex Corp gala at The Sterling: stage dimensions, AV setup points, cocktail hour flow, coat check location, parking validation process, emergency exits, and load-in dock access. Sent reminders to your client (Sarah from Apex) and the venue coordinator (James). Meeting in 30 minutes.',
        channel: 'email',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'New Event Inquiry',
        description: 'A couple reaches out about planning their destination wedding for next year.',
        aiResponse: 'New inquiry from Rachel and Tom — destination wedding in Tulum, Mexico, October 2027, approximately 80 guests. Budget range: $45,000–$60,000. I\'ve responded with our destination wedding packages, portfolio of past tropical weddings, and offered a complimentary discovery call. Availability check: we\'re open for October weekends. Shall I schedule the call for this week?',
        channel: 'instagram',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Timeline Management Update',
        description: 'AI adjusts the Saturday wedding timeline after the couple requests the ceremony start 30 minutes later.',
        aiResponse: 'Timeline updated: ceremony now at 4:30 PM (was 4:00 PM). Cascading adjustments made — cocktail hour shifted to 5:30 PM, reception entrance at 6:15 PM, first dance at 6:30 PM, dinner service at 7:00 PM. All vendors notified: DJ, caterer, photographer, and venue coordinator. Updated timeline PDF sent to the couple and wedding party.',
        channel: 'whatsapp',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Vendor Replacement Emergency',
        description: 'The wedding cake baker cancels due to a family emergency. AI finds a replacement immediately.',
        aiResponse: 'Emergency: Sweet Layers Bakery cancelled the Johnson wedding cake. I\'ve already contacted 4 backup bakers in our vendor network. Two can accommodate: Flour & Frost ($680, 3-tier buttercream, pickup Friday) and Cake Atelier ($820, fondant with sugar flowers, delivery Saturday morning). I\'ve sent both portfolios. The Johnsons\' original budget was $750. Recommend Flour & Frost — similar style, within budget.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 750 },
      },
      {
        time: '3:30 PM',
        title: 'Budget Tracking Report',
        description: 'AI updates the real-time budget tracker for both active events.',
        aiResponse: 'Budget update — Johnson wedding: $32,400 of $35,000 budget spent (93%). Remaining: $2,600 (cake replacement pending). On track. Apex Corp gala: $18,200 of $25,000 spent (73%). Major remaining: AV rental ($3,500), catering balance ($2,800), decor ($500). Both events under budget. Detailed spreadsheet updated.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Social Media Content Creation',
        description: 'AI creates behind-the-scenes content from the venue walkthrough for the company\'s social media.',
        aiResponse: 'Content from today\'s Sterling venue walkthrough: Instagram story series (5 clips showing the space transformation vision), a carousel post with "before vs. after" concept renderings, and a reel of the ballroom with the caption "Where magic happens Saturday." Scheduled for tonight at 7 PM. Also drafted a blog post: "5 Questions to Ask During Your Venue Walkthrough."',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Day-Of Logistics Briefing',
        description: 'AI creates the detailed day-of coordination document for the wedding team.',
        aiResponse: 'Day-of document finalized for Saturday: minute-by-minute timeline from 7 AM setup to 11 PM last dance. Vendor arrival schedule, contact numbers, floor plan, meal counts, and emergency contacts. Assigned team roles: you — ceremony coordination, Jess — reception management, Alex — vendor liaison. Document shared with all team members and vendors.',
        channel: 'email',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '9:30 PM',
        title: 'Google Review Response',
        description: 'A past client left a glowing review about their corporate event experience.',
        aiResponse: 'Thank you so much, Sarah and the Apex team! Seeing your vision come to life at last year\'s product launch was incredible. We\'re thrilled the event exceeded your expectations and drove such great media coverage. We can\'t wait to work together on this year\'s gala — it\'s going to be even bigger!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
    ],
    capabilityExamples: {
      communication: 'Handles client questions, vendor coordination, and guest inquiries across all channels simultaneously.',
      memory: 'Tracks every event\'s guest list, vendor contracts, dietary requirements, client preferences, and design choices.',
      proactive: 'Morning event briefings, deadline reminders, vendor confirmation alerts, and payment due notifications.',
      bookings: 'Schedules venue walkthroughs, vendor meetings, client consultations, and tastings.',
      leads: 'Captures wedding and corporate event inquiries, sends proposals, and follows up with discovery call invitations.',
      revenue: 'Tracks vendor payments, client installments, budget adherence, and flags overdue deposits.',
      reputation: 'Responds to reviews highlighting creativity and flawless execution, requests testimonials post-event.',
      content: 'Creates behind-the-scenes content, venue showcases, event recaps, and seasonal inspiration posts.',
      reporting: 'Real-time budget tracking, guest RSVP dashboards, and post-event performance summaries.',
      browser: 'Researches backup vendors, compares venue pricing, and monitors competitor event offerings.',
      team: 'Creates day-of coordination documents, assigns team roles, and manages multi-person event execution.',
      workflow: 'Syncs event management software with vendor contracts, guest lists, and billing systems.',
      voice: 'Handles vendor coordination calls, confirms logistics details, and discusses floor plan changes.',
      multiagent: 'Runs parallel vendor sourcing and guest tracking across multiple simultaneous events.',
      environment: 'Controls event AV systems, lighting cues, and presentation displays during corporate events.',
    },
    stats: {
      messagesPerDay: 52,
      bookingsPerWeek: 16,
      monthlySavings: 6800,
      responseTime: '< 4 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Event planning requires vendor calls, emergency replacements via web research, and team coordination across complex multi-day timelines that demand executive-tier capabilities.',
  },

  /* ================================================================
     PHOTOGRAPHY STUDIO
     ================================================================ */
  {
    id: 'photography',
    label: 'Photography Studio',
    emoji: '📸',
    category: 'Other',
    tagline: 'Every session booked, every gallery delivered, every client coming back for more — your AI runs the studio.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Studio Briefing',
        description: 'AI reviews today\'s shoot schedule, pending gallery deliveries, and incoming inquiries.',
        aiResponse: 'Good morning — 2 shoots today: family portrait at Riverside Park (10 AM, the Garcias, 5 people including a toddler) and headshot session at the studio (2 PM, corporate client, 8 employees). 3 galleries pending delivery: Martinez wedding (due today), Thompson family (due Thursday), and Lee headshots (delivered last night — awaiting feedback). 2 new inquiries overnight.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Gallery Delivery — Wedding',
        description: 'AI prepares and sends the completed wedding gallery to the couple with a personalized message.',
        aiResponse: 'Hi Sofia and Daniel! Your wedding gallery is ready — 487 fully edited images from your beautiful day at the vineyard. I\'ve organized them by timeline: getting ready, ceremony, portraits, reception, and golden hour. Your private online gallery link is below (password-protected, shareable with family). Print-ready high-res downloads included. Let me know your favorites for the album!',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Mini-Session Campaign Launch',
        description: 'AI creates and launches a seasonal mini-session promotion for spring family portraits.',
        aiResponse: 'Spring mini-session campaign launched! "Cherry Blossom Sessions" — 20-minute sessions, 10 edited images, $250 per family. Available March 29–30 at Brookside Gardens (peak bloom). Email blast sent to 890 past clients. Instagram carousel posted with sample images from last year. Facebook event created. 6 slots per day, 12 total. Already 3 bookings in the first hour!',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'bookings', increment: 3 },
      },
      {
        time: '10:00 AM',
        title: 'Client Prep Message — Family Session',
        description: 'AI sends a pre-session preparation guide to the family arriving for their portrait session.',
        aiResponse: 'Hi Garcia family! Excited for your session at Riverside Park today at 10 AM. Quick prep tips: coordinating outfits (not matching — think complementary colors), arrive 10 minutes early, and bring a favorite toy for little Mia in case she needs a break. Meeting point: the stone bridge near the east entrance. Weather looks perfect — partly cloudy, great light!',
        channel: 'sms',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Print Order Processing',
        description: 'A past client places a print order from their online gallery — canvas, framed prints, and a photo book.',
        aiResponse: 'New print order from the Hendersons! 1 x 24x36 canvas gallery wrap ($280), 2 x 8x10 framed prints ($65 each), and a 12x12 premium photo book with 40 pages ($350). Order total: $760. I\'ve submitted it to our print lab — estimated delivery: 10 business days. Sent Emily a confirmation with a timeline and a preview of the canvas crop.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 760 },
      },
      {
        time: '12:30 PM',
        title: 'New Inquiry — Wedding Photography',
        description: 'A couple reaches out on Instagram asking about wedding photography packages and availability.',
        aiResponse: 'Hi Ashley and Ryan! Congratulations on your engagement! I\'d love to tell you about our wedding packages. We offer 3 tiers: Essential (6 hours, $3,200), Classic (8 hours + engagement session, $4,500), and Premium (10 hours + engagement + album, $6,200). Your date — October 18th — is currently available. Want to schedule a complimentary consultation call this week?',
        channel: 'instagram',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Client Follow-Up — Feedback Request',
        description: 'AI follows up with a client who received their gallery 5 days ago but hasn\'t responded.',
        aiResponse: 'Hi Jess! Just checking in — I hope you\'ve had a chance to browse your family gallery. We\'d love to hear your favorites! If you\'re interested in prints, albums, or holiday cards, I can put together a custom quote. Also, we\'re offering 15% off all print orders placed this month. Let me know if you have any questions!',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Corporate Headshot Session Management',
        description: 'AI manages the flow of 8 employees through the studio headshot session.',
        aiResponse: 'Corporate headshot session for Apex Media underway — 8 employees scheduled in 20-minute slots from 2–5 PM. Sent each person their time slot, wardrobe suggestions, and the studio address. First 3 complete — turnaround for basic retouching: 48 hours. I\'ll deliver all headshots in a branded folder with LinkedIn-optimized and web-resolution versions.',
        channel: 'system',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'bookings', increment: 8 },
      },
      {
        time: '4:00 PM',
        title: 'Google Review Response',
        description: 'A family client leaves a 5-star review praising the photographer\'s patience with their kids.',
        aiResponse: 'Thank you so much, Garcia family! Mia was an absolute star — that giggle photo by the bridge is one of my favorites from this year. Working with families is my favorite part of this job, and yours made it so easy. I can\'t wait for you to see the full gallery!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '5:30 PM',
        title: 'Social Media Portfolio Post',
        description: 'AI creates a portfolio showcase post from a recent wedding with client permission.',
        aiResponse: 'Portfolio post ready: "Sofia & Daniel — A Vineyard Love Story." Instagram carousel with 10 curated images showcasing ceremony, golden hour portraits, and reception moments. Caption tells their story (with permission). Tagged the venue, florist, and wedding planner. Reel version with behind-the-scenes clips scheduled for Thursday. Previous wedding posts averaged 340 likes.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Overdue Gallery Delivery Alert',
        description: 'AI flags a gallery that\'s approaching the promised delivery deadline.',
        aiResponse: 'Heads up: the Thompson family gallery is due Thursday and you\'re at 60% edited (72 of 120 images). At your current editing pace, you\'ll need about 4 more hours. I\'ve blocked tomorrow morning 8 AM–12 PM on your calendar for editing. If you want to prioritize, their top 20 favorites from the in-session review are tagged and ready to edit first.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Weekly Business Summary',
        description: 'AI compiles the week\'s bookings, revenue, and marketing performance.',
        aiResponse: 'Weekly recap: 4 sessions shot, 2 galleries delivered, 1 album ordered. Revenue: $4,960 (sessions: $3,200, prints: $760, mini-session deposits: $1,000). Pipeline: 2 wedding inquiries ($4,500–$6,200 potential), 12 mini-session spots booked (of 12 — sold out!). Instagram growth: +85 followers this week. Next week: 3 shoots scheduled, 2 galleries due.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles session inquiries, sends gallery previews, processes print orders, and follows up with clients post-delivery.',
      memory: 'Tracks every client\'s session history, image preferences, family members, print purchases, and referral source.',
      proactive: 'Morning shoot briefings, gallery delivery deadline alerts, and seasonal mini-session campaign scheduling.',
      bookings: 'Schedules sessions, sends location prep guides, manages multi-person corporate shoot logistics.',
      leads: 'Captures wedding and portrait inquiries from Instagram and website, sends packages, and schedules consultations.',
      revenue: 'Promotes print products, runs seasonal campaigns, tracks album orders, and manages mini-session deposits.',
      reputation: 'Responds to reviews with personal touches, requests testimonials after gallery delivery.',
      content: 'Creates portfolio showcases, behind-the-scenes reels, mini-session promotions, and blog posts from recent work.',
      reporting: 'Weekly revenue summaries, session utilization tracking, and marketing campaign performance analysis.',
      browser: 'Researches location permits, compares print lab pricing, and monitors photography trend reports.',
      team: 'Coordinates second shooters, assigns editing tasks, and manages assistant schedules.',
      workflow: 'Syncs booking calendar with editing queue, gallery delivery pipeline, and accounting.',
      voice: 'Handles consultation calls for wedding inquiries and discusses package details with potential clients.',
      multiagent: 'Manages parallel editing workflows, print fulfillment tracking, and multi-session booking coordination.',
      environment: 'Controls studio lighting presets, backdrop systems, and music playlists for different session types.',
    },
    stats: {
      messagesPerDay: 38,
      bookingsPerWeek: 12,
      monthlySavings: 4200,
      responseTime: '< 5 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Photography studios thrive on content marketing and seasonal campaigns. The Manager tier handles portfolio showcases, mini-session promotions, print revenue campaigns, and the reputation management that fills the calendar.',
  },

  /* ================================================================
     TRAVEL AGENCY
     ================================================================ */
  {
    id: 'travel-agency',
    label: 'Travel Agency',
    emoji: '✈️',
    category: 'Other',
    tagline: 'Every trip planned, every itinerary perfect, every traveler cared for — from booking to boarding and beyond.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Travel Alert Scan',
        description: 'AI scans for flight delays, weather disruptions, and travel advisories affecting active bookings.',
        aiResponse: 'Good morning — 12 active trips this week. Alert: Storm system in the Caribbean may affect the Wilson family\'s Cancun flight on Thursday. No delays yet, but I\'m monitoring hourly. The Patel honeymoon in Bali — all flights confirmed, hotel check-in details sent. Two new trip planning requests overnight from your website.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Booking Confirmation Delivery',
        description: 'AI sends a complete booking confirmation package to a client who just finalized their European vacation.',
        aiResponse: 'Hi Jennifer! Your European adventure is officially booked! Here\'s your full itinerary: Paris (3 nights, Hotel Le Marais), train to Barcelona (2 nights, Casa Gracia), and Rome (3 nights, Hotel Raphael). Flights, hotels, and transfers all confirmed. I\'ve attached your day-by-day itinerary with restaurant recommendations, museum pre-bookings, and local tips. Total: $6,840 for two.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Document Reminder — Passport Expiration',
        description: 'AI detects a client\'s passport expires within 6 months of their travel date and sends an alert.',
        aiResponse: 'Hi David — important reminder! Your passport expires August 15th, and your Thailand trip is July 20th. Many countries require at least 6 months of passport validity. You\'re cutting it close — I\'d recommend expedited renewal immediately (2–3 week processing). Here\'s the State Department link and checklist. Want me to adjust your booking dates if the renewal takes longer?',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:45 AM',
        title: 'New Trip Planning Request',
        description: 'A couple inquires about a 10-day anniversary trip to Japan.',
        aiResponse: 'Hi Sarah and Mike! Japan for your 15th anniversary — what a wonderful choice! For 10 days, I\'d recommend: Tokyo (3 nights), Hakone hot springs (1 night), Kyoto (3 nights), and Osaka (2 nights). Cherry blossom season is mid-March to mid-April — stunning timing. Budget range for flights + hotels + rail pass: $5,500–$8,000 for two depending on hotel tier. Want to schedule a planning call?',
        channel: 'whatsapp',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '11:00 AM',
        title: 'Itinerary Change Request',
        description: 'A client asks to swap their hotel in Barcelona for a different property after reading reviews.',
        aiResponse: 'No problem, Jennifer! I\'ve found 3 alternatives in the same neighborhood: Hotel Neri (boutique, rooftop pool, $285/night), Mercer Barcelona (historic palace, $310/night), and El Palace (grand luxury, $350/night). All have excellent reviews and are walking distance to La Rambla. Your current booking at Casa Gracia can be cancelled penalty-free until Friday. Which appeals to you?',
        channel: 'email',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Flight Disruption Alert',
        description: 'AI detects a client\'s connecting flight has been cancelled and immediately begins rebooking.',
        aiResponse: 'ALERT: The Wilson family\'s connecting flight through Miami to Cancun (Thursday, AA 847) has been cancelled due to the weather system. I\'ve already found 2 alternatives: a direct flight via Dallas (arrives 1 hour later, same price) or a next-morning flight with overnight hotel voucher. Recommending the Dallas reroute. Sent options to the Wilsons for approval — awaiting response.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 2400 },
      },
      {
        time: '1:30 PM',
        title: 'Hotel Price Drop Alert',
        description: 'AI monitors hotel prices and detects a significant price drop on an upcoming booking.',
        aiResponse: 'Price drop detected! The Hotel Raphael in Rome dropped from $310/night to $245/night for Jennifer\'s dates. That\'s a $195 savings over 3 nights. Since her booking was a flexible rate, I can rebook at the lower price with no penalty. Want me to go ahead and lock it in?',
        channel: 'whatsapp',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 195 },
      },
      {
        time: '2:30 PM',
        title: 'Loyalty Program Points Optimization',
        description: 'AI analyzes a frequent traveler\'s points balances and recommends optimal redemption strategies.',
        aiResponse: 'Hi Tom — your points update: Marriott Bonvoy: 124,000 points (enough for 3 free nights at a Category 5 property). Delta SkyMiles: 68,000 (perfect for a domestic round-trip in first class). My recommendation for your September trip: use Marriott points for the hotel (saves $840) and pay cash for flights (points redemption value is low right now). Net savings: $840.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 840 },
      },
      {
        time: '3:30 PM',
        title: 'Travel Insurance Follow-Up',
        description: 'AI reminds a client to purchase travel insurance before the penalty-free deadline.',
        aiResponse: 'Hi Wilson family — friendly reminder that your cancel-for-any-reason travel insurance window closes in 5 days (14 days from initial booking). For your Cancun trip ($4,200 total cost), coverage would be $294 through our partner Allianz. Given the weather patterns we\'ve been monitoring, I\'d strongly recommend it. Here\'s the enrollment link.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Destination Content Post',
        description: 'AI creates a social media post showcasing a destination deal for the upcoming season.',
        aiResponse: 'New content posted: "Why Japan in Cherry Blossom Season Is the Trip of a Lifetime" — Instagram carousel with 8 stunning images, reel with a 30-second travel highlight montage, and a blog post with a 10-day sample itinerary. Includes a CTA to book a free planning call. Scheduled across Instagram, Facebook, and the email newsletter for maximum reach.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Post-Trip Review Request',
        description: 'AI sends a follow-up to clients who returned from their trip 3 days ago.',
        aiResponse: 'Hi Patel family! Welcome home from Bali — I hope it was everything you dreamed of! If you have a moment, we\'d love a quick Google review about your experience working with us. Your feedback helps other travelers find us. And if you\'re already dreaming about the next trip, I have some ideas based on what you loved about Bali!',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Weekly Booking and Revenue Report',
        description: 'AI compiles the week\'s new bookings, active trips, and commission tracking.',
        aiResponse: 'Weekly recap: 3 new bookings this week ($14,200 total trip value, $1,704 commission). Active trips: 12 clients traveling this month. Pipeline: 4 trip planning requests in progress ($22,000 potential). Client satisfaction: 4.9 average post-trip rating. Top destination this quarter: Italy (5 bookings). Commission YTD: $18,400.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Sends itineraries, handles change requests, delivers travel alerts, and provides destination guidance.',
      memory: 'Tracks every traveler\'s preferences, passport details, loyalty numbers, dietary needs, and past trip history.',
      proactive: 'Morning travel alerts, passport expiration warnings, payment deadline reminders, and flight disruption monitoring.',
      bookings: 'Schedules planning consultations, books flights and hotels, and coordinates multi-city itineraries.',
      leads: 'Captures trip planning inquiries, sends destination proposals, and follows up with personalized recommendations.',
      revenue: 'Loyalty points optimization, travel insurance upsells, group booking coordination, and commission tracking.',
      reputation: 'Post-trip review requests, responds to Google reviews, and collects destination testimonials.',
      content: 'Creates destination showcases, seasonal deal promotions, travel tip blogs, and itinerary inspiration posts.',
      reporting: 'Weekly booking summaries, commission tracking, pipeline forecasting, and client satisfaction scores.',
      browser: 'Monitors flight prices, hotel availability, travel advisories, and competitor package offerings.',
      team: 'Coordinates between booking agents, assigns client portfolios, and manages peak season workloads.',
      workflow: 'Syncs booking platforms with CRM, accounting, and itinerary management systems.',
      voice: 'Handles urgent rebooking calls during travel disruptions and discusses trip options with prospects.',
      multiagent: 'Monitors multiple flights and hotel prices simultaneously across booking platforms.',
      environment: 'Controls office displays showing real-time flight boards and destination showcases for walk-in clients.',
    },
    stats: {
      messagesPerDay: 44,
      bookingsPerWeek: 14,
      monthlySavings: 5600,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Travel agencies need real-time flight monitoring, hotel price scanning, and emergency rebooking across multiple platforms that require executive-tier browser and workflow capabilities.',
  },

  /* ================================================================
     NONPROFIT
     ================================================================ */
  {
    id: 'nonprofit',
    label: 'Nonprofit',
    emoji: '💚',
    category: 'Other',
    tagline: 'Every donor appreciated, every volunteer coordinated, every grant deadline met — your AI amplifies your mission.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Mission Briefing',
        description: 'AI compiles overnight donations, upcoming grant deadlines, and today\'s volunteer schedule.',
        aiResponse: 'Good morning — 4 online donations overnight totaling $735 (thank-you messages sent automatically). Grant deadline alert: the Community Foundation application is due Friday at 5 PM (draft is 80% complete). Today: 12 volunteers scheduled for the food bank shift (9 AM–1 PM). Board meeting prep materials due to directors by end of day.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Donor Thank-You and Receipt',
        description: 'AI sends personalized thank-you messages and tax receipts to recent donors.',
        aiResponse: 'Hi Margaret — thank you so much for your generous $250 donation to our after-school literacy program! Your support helps us provide reading materials and tutors to 45 children in underserved communities. Your tax-deductible receipt is attached. You\'ve now contributed $1,200 this year — you\'re making an incredible difference.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Volunteer Shift Confirmation',
        description: 'AI sends reminders to today\'s food bank volunteers with logistics details.',
        aiResponse: 'Volunteer reminders sent to 12 people for today\'s food bank shift. Details: 9 AM–1 PM at the Community Center (123 Main St.), parking in Lot B, check in at the volunteer desk. Dress code: closed-toe shoes and comfortable clothing. 2 volunteers confirmed via reply, 10 pending. I\'ll follow up with non-responders at 8:45 AM.',
        channel: 'sms',
        capability: 'scheduling',
        tier: 'operator',
        stat: { key: 'messages', increment: 12 },
      },
      {
        time: '9:30 AM',
        title: 'Grant Application Progress',
        description: 'AI continues drafting the Community Foundation grant application with updated impact data.',
        aiResponse: 'Grant application update: draft is now 90% complete. I\'ve added the latest impact data — 1,240 meals served last quarter (up 18%), 45 students in the literacy program (92% reading level improvement), and 380 volunteer hours logged. Budget section needs your review. Narrative is compelling — I\'ve tied outcomes to the Foundation\'s strategic priorities. Ready for final review by Thursday.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Event Promotion — Annual Gala',
        description: 'AI creates and schedules promotional content for the annual fundraising gala next month.',
        aiResponse: 'Gala promotion launched: "Hope in Bloom — Annual Spring Gala" on April 12th. Email blast to 2,400 supporters with early-bird ticket pricing ($125 per person, $200 per couple). Instagram carousel showcasing last year\'s highlights. Facebook event created with silent auction sneak peek. Ticket sales goal: 200. Already at 34 tickets in the first 2 hours!',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Corporate Sponsor Outreach',
        description: 'AI identifies and reaches out to potential corporate sponsors for the gala.',
        aiResponse: 'Sponsorship outreach sent to 8 local businesses. Personalized pitches referencing each company\'s community involvement and CSR programs. Tiers: Platinum ($5,000 — logo on all materials, 10 tickets, stage recognition), Gold ($2,500 — 6 tickets, program listing), Silver ($1,000 — 2 tickets, social media mention). 2 responses already — both interested in Gold tier.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'savings', increment: 5000 },
      },
      {
        time: '12:30 PM',
        title: 'Impact Report Compilation',
        description: 'AI compiles the quarterly impact report with stories, data, and visuals for stakeholders.',
        aiResponse: 'Q1 impact report drafted: 3,720 meals served, 45 students tutored (14 graduated to grade level), 1,140 volunteer hours, $42,000 raised. Includes 3 beneficiary stories (with permission), infographics, and a letter from the Executive Director. Formatted for email newsletter, board presentation, and social media highlights. Ready for your review.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Recurring Donor Upgrade Campaign',
        description: 'AI identifies monthly donors and sends personalized upgrade requests.',
        aiResponse: 'Upgrade campaign sent to 45 monthly donors. Each message is personalized: "Hi Tom — your $25/month donation has provided 300 meals this year. If you could increase to $35/month, that would feed 120 more people annually." Included an impact calculator and one-click upgrade link. Last year\'s campaign converted 22% of donors to higher tiers.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'messages', increment: 45 },
      },
      {
        time: '2:30 PM',
        title: 'Volunteer Coordination for Weekend Event',
        description: 'AI recruits and schedules volunteers for Saturday\'s community cleanup event.',
        aiResponse: 'Community cleanup volunteer recruitment: posted on our website, Facebook, and Nextdoor. Need 30 volunteers for Saturday 9 AM–12 PM at Riverside Park. Sign-up form includes T-shirt size and waiver. 18 signed up so far. Sent targeted messages to 50 past volunteers who live nearby. Supplies confirmed: 30 bags, 15 grabbers, gloves for all. Water and snacks sponsored by Main Street Deli.',
        channel: 'facebook',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '4:00 PM',
        title: 'Grant Deadline Calendar Review',
        description: 'AI reviews all upcoming grant deadlines and their current status.',
        aiResponse: 'Grant calendar: Community Foundation — due Friday (90% complete, on track). State Arts Council — due March 28th (not started, I\'ve drafted an outline from last year\'s successful application). United Way — due April 15th (LOI submitted, full proposal invited). Total potential: $78,000 across 3 grants. I\'ve blocked time on your calendar for review sessions this week.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Board Meeting Prep Package',
        description: 'AI compiles all materials for tomorrow\'s board meeting and distributes to directors.',
        aiResponse: 'Board meeting package sent to all 9 directors: agenda, Q1 financial statements, program update, fundraising progress (82% of annual goal), gala planning update, and 2 action items requiring board votes. Meeting is tomorrow at 6 PM via Zoom — link included. 7 directors confirmed attendance. I\'ll send a reminder tomorrow at noon.',
        channel: 'email',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '9:00 PM',
        title: 'End-of-Day Fundraising Summary',
        description: 'AI compiles the day\'s donations, gala ticket sales, and fundraising progress.',
        aiResponse: 'Today\'s fundraising: $1,485 in new donations (4 online + 1 mailed check). Gala ticket sales: 34 (goal: 200). Monthly recurring total: $4,200 (45 active donors). Grant pipeline: $78,000 across 3 applications. Year-to-date raised: $42,000 of $120,000 annual goal (35%, on pace). Highlight: 2 new corporate sponsors interested in Gold tier ($5,000 potential).',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Sends donor thank-yous, volunteer confirmations, beneficiary updates, and sponsor communications.',
      memory: 'Tracks every donor\'s giving history, volunteer hours, event attendance, and communication preferences.',
      proactive: 'Grant deadline reminders, donation anniversary alerts, volunteer shift confirmations, and board meeting prep.',
      bookings: 'Schedules volunteer shifts, donor meetings, event logistics, and board meetings.',
      leads: 'Identifies corporate sponsors, captures new donor inquiries, and nurtures major gift prospects.',
      revenue: 'Manages recurring donor upgrades, gala ticket sales, sponsorship tracking, and year-end giving campaigns.',
      reputation: 'Shares impact stories, responds to community feedback, and requests testimonials from beneficiaries.',
      content: 'Creates fundraising campaigns, impact reports, event promotions, and volunteer recruitment posts.',
      reporting: 'Quarterly impact reports, fundraising dashboards, grant tracking, and board meeting packages.',
      browser: 'Researches grant opportunities, monitors peer nonprofit programs, and tracks foundation deadlines.',
      team: 'Coordinates board communications, assigns staff tasks, and manages volunteer team logistics.',
      workflow: 'Syncs donor database with accounting, grant management, and volunteer scheduling systems.',
      voice: 'Handles donor calls, discusses giving opportunities, and provides program information to the community.',
      multiagent: 'Manages parallel grant applications, fundraising campaigns, and volunteer recruitment drives.',
      environment: 'Controls event AV systems, digital signage for fundraisers, and community space scheduling.',
    },
    stats: {
      messagesPerDay: 48,
      bookingsPerWeek: 12,
      monthlySavings: 5200,
      responseTime: '< 4 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Nonprofits need grant research and writing, multi-system donor management, and board coordination that require executive-tier workflow automation and browser capabilities.',
  },

  /* ================================================================
     Other (Generic Fallback)
     ================================================================ */
  {
    id: 'other',
    label: 'Other',
    emoji: '❓',
    category: 'Other',
    tagline: 'An AI employee that handles communication, bookings, and follow-ups for any type of business.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Business Brief',
        description: 'AI reviews overnight messages, today\'s appointments, and anything that needs your attention.',
        aiResponse: 'Good morning. You have 5 appointments today (first one at 9 AM). 3 new customer inquiries came in overnight — all responded to. One returning customer asked about pricing for your premium service; I\'ve sent the details. No cancellations. Here\'s your full rundown.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'New Customer Inquiry',
        description: 'A potential customer messages asking about your services and availability.',
        aiResponse: 'Hi! Thanks for reaching out. We\'d love to help. Our services include [your core offerings], and we currently have availability this week on Wednesday and Thursday. Would either of those work for you? I can also send over our full pricing guide if that\'s helpful.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Appointment Booking',
        description: 'A customer confirms they\'d like to book a time slot. AI checks availability and schedules it.',
        aiResponse: 'Perfect — I\'ve booked you in for Wednesday at 2 PM. You\'ll receive a confirmation email shortly with all the details. We\'ll also send a reminder the day before. Is there anything specific you\'d like us to prepare or know ahead of time?',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Returning Customer Recognition',
        description: 'A previous customer reaches out again. AI recognizes them and references their history.',
        aiResponse: 'Welcome back, Maria! Great to hear from you again. Last time you came in was back in January for your regular service. Would you like to book the same thing, or were you looking at something different this time? We also have a few new options I think you\'d like.',
        channel: 'whatsapp',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Lead Follow-Up Sequence',
        description: 'AI follows up with a prospect who inquired 3 days ago but never booked.',
        aiResponse: 'Hi James, just following up on your inquiry from a few days ago about our services. I know things get busy! We still have some availability this week if you\'re interested. No pressure at all — happy to answer any questions you might have. Here\'s a quick link to book online anytime.',
        channel: 'sms',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Review Request After Service',
        description: 'A customer completed their appointment yesterday. AI sends a friendly review request.',
        aiResponse: 'Hi Sarah, thanks so much for coming in yesterday! We hope everything was great. If you have a moment, we\'d really appreciate a quick Google review — it means the world to a small business like ours. Here\'s the link. Thanks again, and we look forward to seeing you next time!',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Google Review Response',
        description: 'A new 5-star review appears on Google. AI responds promptly and professionally.',
        aiResponse: 'New 5-star Google review from Sarah: "Amazing service, so professional and easy to book!" I\'ve responded: "Thank you so much, Sarah! We\'re thrilled you had a great experience. We look forward to welcoming you back soon!" Your rating is now 4.8 with 127 reviews.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '2:00 PM',
        title: 'Cancellation Recovery',
        description: 'A customer cancels their appointment for tomorrow. AI cross-references the waitlist, recent inquiries, and lapsed customers to fill the slot.',
        aiResponse: 'Tomorrow\'s 3 PM slot just opened up from a cancellation. I\'ve already reached out to 4 customers from the waitlist and 2 recent inquiries who hadn\'t booked yet. Lisa confirmed she can take the slot — rebooked and confirmed. No lost revenue.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Weekly Social Media Post',
        description: 'AI drafts and schedules a social media post showcasing your business.',
        aiResponse: 'This week\'s Instagram post is ready: a behind-the-scenes look at your workspace with a caption highlighting what makes your service special. Hashtags researched and optimized for your local area. Scheduled for Thursday at 6 PM (your audience\'s peak engagement time). Want to preview it?',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Overdue Invoice Follow-Up',
        description: 'AI detects an unpaid invoice from 10 days ago, cross-references payment history, and sends a polite reminder with a direct payment link.',
        aiResponse: 'Friendly reminder sent to David regarding his invoice from February 28th ($350, 10 days overdue). The message was warm and professional with a direct payment link. This is his first late payment — usually pays within 3 days. If no response by Friday, I\'ll send a second reminder.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 350 },
      },
      {
        time: '6:00 PM',
        title: 'End-of-Day Summary',
        description: 'AI compiles the full day\'s activity across every channel and system into a concise summary delivered to your phone.',
        aiResponse: 'Today\'s wrap-up: 5 appointments completed, 2 new bookings made, 1 cancellation recovered, 3 new inquiries handled, 1 five-star review received and responded to, 1 overdue invoice chased. Tomorrow: 4 appointments starting at 10 AM. Everything is running smoothly.',
        channel: 'email',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'After-Hours Inquiry',
        description: 'A customer messages late at night asking if you\'re open tomorrow. AI responds instantly.',
        aiResponse: 'Hi! Thanks for reaching out. Yes, we\'re open tomorrow from 9 AM to 6 PM. We still have a few slots available — would you like me to book one for you? Just let me know what time works best and I\'ll get you set up right away.',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to customer messages across WhatsApp, Instagram, Facebook, email, and SMS — all from one brain.',
      memory: 'Remembers every customer\'s name, history, preferences, and past interactions.',
      proactive: 'Morning briefings, end-of-day summaries, and real-time alerts when something needs attention.',
      bookings: 'Books appointments, sends reminders, handles cancellations, and fills empty slots automatically.',
      leads: 'Captures every inquiry, follows up automatically, and never lets a lead slip through the cracks.',
      revenue: 'Chases overdue payments, re-engages lapsed customers, and sends offers on slow days.',
      reputation: 'Responds to every Google review within the hour and requests reviews after each completed service.',
      content: 'Creates and schedules social media posts, writes email campaigns, and tracks what performs best.',
      reporting: 'Daily summaries and weekly reports so you always know how your business is performing.',
    },
    stats: {
      messagesPerDay: 40,
      bookingsPerWeek: 22,
      monthlySavings: 5500,
      responseTime: '< 2 min',
    },
    recommendedTier: 'operator',
    recommendationReason: 'The Operator tier covers communication, bookings, and lead management — the essentials every business needs running 24/7.',
  },
];

