import type { Industry } from '../experience-data';

export const professionalIndustries: Industry[] = [
  /* ================================================================
     1. LAW FIRM
     ================================================================ */
  {
    id: 'lawfirm',
    label: 'Law Firm',
    emoji: '⚖️',
    category: 'Professional Services',
    tagline: 'Win more cases while your AI manages client intake, deadlines, and billing',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Case Briefing',
        description: 'AI compiles overnight emails, court filing deadlines, and today\'s calendar into a single briefing.',
        aiResponse: 'Good morning — you have 3 depositions today, a filing deadline at 2 PM for the Henderson matter, and 2 new consultation requests overnight. I\'ve prioritized them by urgency.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'New Case Inquiry via Website',
        description: 'A potential client submits a personal injury inquiry through the firm\'s contact form.',
        aiResponse: 'Thank you for reaching out. I\'ve noted the details of your incident. Could you share the police report number and your insurance information? I\'ll have an attorney review your case today.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'Court Date Scheduling Conflict',
        description: 'Court clerk sends a notice that overlaps with an existing hearing on the calendar.',
        aiResponse: 'Conflict detected — the Miller hearing and the Davis motion are both set for March 18 at 9 AM. I\'ve drafted a continuance motion for Davis and flagged it for your review.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '9:45 AM',
        title: 'Client Document Follow-Up',
        description: 'A client hasn\'t returned the signed engagement letter sent 5 days ago.',
        aiResponse: 'Hi Mrs. Park — just a friendly reminder that we\'re still waiting on your signed engagement letter. I can resend it now or schedule a quick call to walk through any questions. Which would you prefer?',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Retainer Billing Reminder',
        description: 'Three client retainers are running low and need replenishment notices.',
        aiResponse: 'I\'ve sent retainer replenishment invoices to the Garcia, Thompson, and Liu accounts. Current balances are below the 20% threshold. All invoices include a one-click payment link.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 2400 },
      },
      {
        time: '11:15 AM',
        title: 'Case Law Research Request',
        description: 'Attorney needs precedent cases for an upcoming motion to dismiss.',
        aiResponse: 'I found 4 relevant precedents in the 9th Circuit for your motion to dismiss in Williams v. Apex Corp. I\'ve compiled summaries with citations and highlighted the strongest supporting language.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '12:00 PM',
        title: 'Client Consultation Booking',
        description: 'A referral from an existing client calls to schedule an initial consultation.',
        aiResponse: 'Thank you for calling. I understand you were referred by Mr. Chen regarding a contract dispute. I have openings this Thursday at 2 PM or Friday at 10 AM. Which works better for you?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Opposing Counsel Response',
        description: 'Opposing counsel sends a settlement counteroffer via email.',
        aiResponse: 'Opposing counsel in Martinez v. DataFlow has countered at $85,000. Their original was $60,000, your client authorized up to $100,000. I\'ve prepared a comparison table and flagged this for your immediate review.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Filing Deadline Countdown',
        description: 'A statute of limitations deadline is approaching in 48 hours.',
        aiResponse: 'URGENT: The statute of limitations for the Robinson personal injury claim expires in 48 hours. The complaint draft is 90% complete — I\'ve sent it to you and the paralegal for final review.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
      },
      {
        time: '4:30 PM',
        title: 'Google Review Response',
        description: 'A former client leaves a 5-star review mentioning the firm\'s responsiveness.',
        aiResponse: 'Thank you so much for your kind words, James. We\'re glad we could help resolve your case efficiently. Your trust in our firm means everything. We wish you all the best.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'Weekly Content Draft',
        description: 'AI prepares a LinkedIn article draft about recent changes in employment law.',
        aiResponse: 'I\'ve drafted a 600-word LinkedIn article titled "3 Employment Law Changes Every Business Owner Should Know in 2026." It covers the new overtime rules, contractor classification updates, and remote work provisions.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '10:00 PM',
        title: 'End-of-Day Case Digest',
        description: 'AI summarizes all activity across active cases for the day.',
        aiResponse: 'Today\'s wrap-up: 4 client communications handled, 1 scheduling conflict resolved, 3 retainer invoices sent ($7,200 total), and the Robinson complaint is ready for filing. Tomorrow\'s priority: Henderson motion deadline at 2 PM.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to client inquiries across email, phone, and messaging with full case context',
      memory: 'Remembers every case detail, client preference, and communication history',
      proactive: 'Alerts you to filing deadlines, statute expirations, and scheduling conflicts',
      bookings: 'Schedules consultations, depositions, and court dates without conflicts',
      leads: 'Captures and pre-qualifies new case inquiries from website, referrals, and calls',
      revenue: 'Sends retainer replenishment invoices and chases outstanding balances',
      reputation: 'Responds to Google and Avvo reviews within the hour',
      content: 'Drafts LinkedIn articles and blog posts on recent legal developments',
      reporting: 'Weekly caseload summary with billing, deadlines, and conversion metrics',
      browser: 'Researches case law precedents and opposing counsel backgrounds',
      team: 'Paralegals and associates message AI for case status, deadlines, and document locations',
      workflow: 'Syncs case management system with calendar, billing, and document storage',
      voice: 'Answers intake calls, collects case details, and schedules consultations',
      multiagent: 'Spawns research agents for multi-jurisdiction legal questions',
      environment: 'Controls conference room displays for client presentations',
    },
    stats: {
      messagesPerDay: 45,
      bookingsPerWeek: 12,
      monthlySavings: 4800,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Law firms need proactive deadline management and reputation monitoring beyond basic communication handling.',
  },

  /* ================================================================
     2. ACCOUNTING / BOOKKEEPING
     ================================================================ */
  {
    id: 'accounting',
    label: 'Accounting / Bookkeeping',
    emoji: '💼',
    category: 'Professional Services',
    tagline: 'Automate client communication and never miss a tax deadline again',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Tax Season Dashboard',
        description: 'AI produces a daily overview of pending returns, client document status, and upcoming deadlines.',
        aiResponse: 'Good morning — 14 returns are in progress, 6 are waiting on client documents, and 3 have filing deadlines this week. I\'ve flagged the Martinez and O\'Brien returns as highest priority.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Client Document Collection Chase',
        description: 'Five clients haven\'t uploaded their W-2s and 1099s despite two previous reminders.',
        aiResponse: 'Hi David — tax season is moving fast! I still need your W-2 and 1099-INT to complete your return. You can upload them securely here or snap a photo and send it back on this chat. Need help?',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 5 },
      },
      {
        time: '8:45 AM',
        title: 'New Business Client Inquiry',
        description: 'A small business owner asks about monthly bookkeeping services via the website form.',
        aiResponse: 'Thanks for your interest in our bookkeeping services. I have a few questions to prepare a quote: How many monthly transactions does your business typically process? Do you use QuickBooks, Xero, or another platform?',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Quarterly Filing Reminder',
        description: 'Estimated quarterly tax payments are due in 5 days for 22 business clients.',
        aiResponse: 'I\'ve sent quarterly estimated tax payment reminders to all 22 business clients with their calculated amounts. Each email includes payment instructions and a link to schedule a call if they have questions.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 22 },
      },
      {
        time: '10:15 AM',
        title: 'Bookkeeping Reconciliation Alert',
        description: 'AI detects a $3,200 discrepancy in a client\'s bank reconciliation.',
        aiResponse: 'Discrepancy found in Bright Ventures\' March reconciliation — bank statement shows $3,200 more than the ledger. I traced it to two unrecorded deposits on March 5 and 12. Ready for your review.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 3200 },
      },
      {
        time: '11:00 AM',
        title: 'Client Appointment Booking',
        description: 'An existing client wants to schedule a year-end tax planning session.',
        aiResponse: 'Great to hear from you, Ms. Tanaka! I have openings for a tax planning session next Tuesday at 3 PM or Wednesday at 11 AM. The session typically runs 45 minutes. Which time works for you?',
        channel: 'whatsapp',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Overdue Invoice Follow-Up',
        description: 'Three client invoices are past 30 days and need a second reminder.',
        aiResponse: 'I\'ve sent the 30-day reminder to Greenfield LLC, Apex Consulting, and River Home Design. Combined outstanding: $4,750. Each includes the original invoice and a direct payment link.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 4750 },
      },
      {
        time: '1:45 PM',
        title: 'Tax Law Update Research',
        description: 'AI monitors IRS announcements and flags a new deduction relevant to small business clients.',
        aiResponse: 'The IRS just published updated guidance on the home office deduction for hybrid workers. This affects approximately 15 of your small business clients. I\'ve drafted an email advisory for your review.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '3:00 PM',
        title: 'Client Phone Call — Payroll Question',
        description: 'A client calls with an urgent question about payroll tax withholding for a new employee.',
        aiResponse: 'Thank you for calling. I can help with payroll setup questions. For a new W-2 employee in California, the standard withholdings include federal income tax, FICA, state income tax, and SDI. Would you like me to schedule a call with your accountant for specifics?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '4:30 PM',
        title: 'Client Review Request',
        description: 'After completing a tax return, AI sends a review request to the client.',
        aiResponse: 'Hi Mr. Chen — your 2025 return has been filed and accepted! We\'d love to hear about your experience. Would you mind leaving a quick review? Here\'s a direct link to our Google page.',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '6:00 PM',
        title: 'Monthly Newsletter Draft',
        description: 'AI prepares the monthly client newsletter with tax tips and firm updates.',
        aiResponse: 'I\'ve drafted the April newsletter: "3 Tax Moves to Make Before Q2 Ends." It covers estimated payments, retirement contribution strategies, and the new home office rules. Ready for your edits.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '9:00 PM',
        title: 'Weekly Performance Report',
        description: 'AI generates a weekly summary of returns filed, revenue collected, and client pipeline.',
        aiResponse: 'This week: 11 returns filed, $8,400 in fees collected, 3 new client consultations booked. Document collection rate improved to 78% from 65% last week. Top bottleneck: 6 clients still missing K-1 forms.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Follows up with clients for missing tax documents across SMS, email, and WhatsApp',
      memory: 'Tracks every client\'s filing history, entity type, and special deductions',
      proactive: 'Sends quarterly filing reminders and flags approaching deadlines automatically',
      bookings: 'Schedules tax planning sessions and return review appointments',
      leads: 'Qualifies new bookkeeping inquiries by transaction volume and software platform',
      revenue: 'Chases overdue invoices at 7, 14, and 30 days with payment links',
      reputation: 'Requests Google reviews after successful tax filings',
      content: 'Drafts monthly newsletters with tax tips and regulatory updates',
      reporting: 'Weekly report on returns filed, fees collected, and document collection rates',
      browser: 'Monitors IRS announcements and state tax authority updates daily',
      team: 'Staff ask AI about client status, document checklists, and deadline priorities',
      workflow: 'Syncs tax software with client portal, calendar, and billing system',
      voice: 'Answers client calls about payroll, deadlines, and filing status',
      multiagent: 'Runs parallel agents to reconcile multiple client books simultaneously',
      environment: 'Controls office displays showing real-time filing season progress',
    },
    stats: {
      messagesPerDay: 55,
      bookingsPerWeek: 8,
      monthlySavings: 5200,
      responseTime: '< 4 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Accounting firms benefit most from proactive deadline tracking, automated document collection, and revenue recovery during tax season.',
  },

  /* ================================================================
     3. REAL ESTATE AGENT / BROKER
     ================================================================ */
  {
    id: 'realestate',
    label: 'Real Estate Agent / Broker',
    emoji: '🏡',
    category: 'Professional Services',
    tagline: 'Close more deals while your AI nurtures every lead and manages every showing',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Daily Market Intelligence Brief',
        description: 'AI scans MLS for new listings, price changes, and expired listings in target areas.',
        aiResponse: 'Morning market update: 7 new listings in your target zip codes, 3 price reductions on properties matching buyer criteria, and 2 expired listings that could be prospecting opportunities. Details attached.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Open House Scheduling & Promotion',
        description: 'AI organizes this weekend\'s open house logistics and drafts social media announcements.',
        aiResponse: 'I\'ve scheduled two open houses for Saturday: 142 Oak Lane (1-3 PM) and 89 River Rd (3:30-5:30 PM). Instagram and Facebook posts are drafted with property photos. Sign delivery is confirmed. Want me to send email blasts to your buyer list?',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'bookings', increment: 2 },
      },
      {
        time: '8:15 AM',
        title: 'New Buyer Lead from Zillow',
        description: 'A buyer submits an inquiry on a listing through Zillow at 2 AM.',
        aiResponse: 'Hi Sarah — thanks for your interest in 142 Oak Lane! It\'s a beautiful 3-bed, 2-bath with a renovated kitchen. Are you pre-approved for financing? I can schedule a private showing as early as tomorrow.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Property Viewing Follow-Up',
        description: 'AI follows up with buyers who viewed properties last week but haven\'t provided feedback.',
        aiResponse: 'Hi Mike — hope you\'re doing well! I wanted to check in after your viewing of 55 Maple Dr last Thursday. What did you think? If it wasn\'t the right fit, I have two new listings that match your criteria. Want me to send the details?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '10:45 AM',
        title: 'Listing Presentation Research',
        description: 'AI compiles a comparative market analysis for an upcoming listing appointment.',
        aiResponse: 'CMA ready for your 2 PM listing appointment at 310 Elm St. I found 6 comparable sales within 0.5 miles in the last 90 days. Suggested list price range: $485,000-$510,000. I\'ve formatted it into your branded presentation template.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '12:00 PM',
        title: 'Offer Negotiation Support',
        description: 'A buyer\'s agent sends a counter-offer on a listing, and AI organizes the details for quick review.',
        aiResponse: 'Counter-offer received on 142 Oak Lane: $472,000 (original ask $489,000), 30-day close, $15,000 earnest money, inspection contingency waived. Buyer is pre-approved with First National. I\'ve prepared a side-by-side comparison for your seller.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:15 PM',
        title: 'Showing Schedule Coordination',
        description: 'Multiple buyers want to see the same property at overlapping times.',
        aiResponse: 'I\'ve organized 4 showings for 310 Elm St tomorrow: 10 AM (Rodriguez family), 11:15 AM (Mr. Patel), 1 PM (Ms. Kim), and 2:30 PM (the Johnsons). Confirmation texts have been sent to all parties.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 4 },
      },
      {
        time: '2:30 PM',
        title: 'Expired Listing Prospecting',
        description: 'AI identifies homeowners whose listings expired and drafts personalized outreach.',
        aiResponse: 'Found 3 expired listings this week in your farm area. I\'ve drafted personalized letters for each homeowner highlighting what we\'d do differently — updated pricing strategy, professional staging, and targeted digital marketing.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '4:00 PM',
        title: 'Transaction Milestone Tracking',
        description: 'AI tracks inspection, appraisal, and closing deadlines for active transactions.',
        aiResponse: 'Transaction update for 55 Maple Dr: inspection passed (minor repairs negotiated), appraisal scheduled for Friday, and title search is in progress. Closing still on track for April 10. I\'ve updated your transaction tracker.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
      },
      {
        time: '5:30 PM',
        title: 'Client Anniversary Check-In',
        description: 'AI remembers a past client\'s home purchase anniversary and sends a personalized message.',
        aiResponse: 'Hi Lisa — happy 2-year homeowner anniversary! I hope you\'re still loving the neighborhood. Your home\'s estimated value has increased about 8% since you purchased. Let me know if you ever need anything!',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:00 PM',
        title: 'Zillow Review Response',
        description: 'A recent buyer leaves a glowing review on Zillow mentioning the agent\'s market knowledge.',
        aiResponse: 'Thank you so much, James and Maria! It was a pleasure helping you find your dream home. Your trust in my market expertise means the world. Wishing you many happy years at 89 River Rd!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '9:30 PM',
        title: 'Weekly Pipeline Report',
        description: 'AI summarizes active listings, pending transactions, and lead pipeline for the week.',
        aiResponse: 'Weekly summary: 4 active listings (avg DOM: 12 days), 2 pending transactions, 9 new leads captured, 3 showings scheduled for next week. Projected commission pipeline: $34,200. Top priority: follow up with pre-approved buyers from Saturday\'s open house.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to buyer inquiries within minutes across Zillow, email, and WhatsApp',
      memory: 'Remembers every buyer\'s criteria, budget, preferred neighborhoods, and showing feedback',
      proactive: 'Morning MLS alerts for new listings, price changes, and expired listing opportunities',
      bookings: 'Coordinates showings across multiple properties and buyer schedules',
      leads: 'Captures and qualifies leads from Zillow, Realtor.com, social media, and referrals',
      revenue: 'Tracks commission pipeline and follows up on stalled transactions',
      reputation: 'Responds to Zillow and Google reviews and requests them after closings',
      content: 'Creates listing posts, open house promotions, and market update videos',
      reporting: 'Weekly pipeline report with active listings, lead conversion, and projected commissions',
      browser: 'Pulls comparable sales data and compiles market analyses automatically',
      team: 'Buyer agents and transaction coordinators message AI for showing schedules and deadlines',
      workflow: 'Syncs MLS data with CRM, calendar, and transaction management platform',
      voice: 'Answers calls from sign riders and online listings, qualifies buyers instantly',
      multiagent: 'Runs parallel research on multiple neighborhoods for relocation clients',
      environment: 'Controls office listing displays and open house digital signage',
    },
    stats: {
      messagesPerDay: 60,
      bookingsPerWeek: 18,
      monthlySavings: 6200,
      responseTime: '< 2 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Real estate agents need aggressive lead follow-up, content marketing for listings, and reputation management to stay competitive.',
  },

  /* ================================================================
     4. FINANCIAL ADVISOR
     ================================================================ */
  {
    id: 'financial',
    label: 'Financial Advisor',
    emoji: '📊',
    category: 'Professional Services',
    tagline: 'Deepen client relationships while your AI handles scheduling, compliance, and outreach',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Pre-Market Intelligence Brief',
        description: 'AI summarizes overnight market movements, economic news, and portfolio alerts.',
        aiResponse: 'Markets overview: S&P futures up 0.4%, 10-year yield at 4.12%. Fed minutes release at 2 PM today. 3 client portfolios triggered rebalancing alerts overnight — details in your dashboard.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:15 AM',
        title: 'Market Volatility Client Alert',
        description: 'A sector sell-off triggers concern; AI proactively reaches out to affected clients.',
        aiResponse: 'Hi Robert — you may have seen headlines about the tech sector dip this morning. Your portfolio has limited tech exposure (about 12%), and your diversification strategy is working as designed. No action needed, but I\'m here if you\'d like to discuss.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 8 },
      },
      {
        time: '8:30 AM',
        title: 'Portfolio Review Scheduling',
        description: 'Quarterly reviews are due for 15 clients; AI sends scheduling invitations.',
        aiResponse: 'Hi Ms. Yamamoto — it\'s time for your quarterly portfolio review. I have availability next week on Tuesday at 10 AM, Wednesday at 2 PM, or Thursday at 4 PM. The review typically takes 45 minutes. Which works best?',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 5 },
      },
      {
        time: '9:45 AM',
        title: 'Retirement Planning Inquiry',
        description: 'A new prospect reaches out asking about retirement planning services.',
        aiResponse: 'Thank you for your interest in our retirement planning services. To prepare a preliminary analysis, could you share your target retirement age, current savings estimate, and any existing employer plans? I\'ll schedule a complimentary strategy session.',
        channel: 'whatsapp',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Compliance Documentation Check',
        description: 'AI audits recent client communications for compliance with regulatory requirements.',
        aiResponse: 'Compliance audit complete for this week\'s communications: 34 client emails reviewed, all within guidelines. One flag — the Johnson proposal needs a risk disclosure addendum before sending. I\'ve drafted it for your approval.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
      },
      {
        time: '11:45 AM',
        title: 'Client Life Event Follow-Up',
        description: 'AI remembers a client mentioned an upcoming retirement date and initiates a planning check-in.',
        aiResponse: 'Hi Dr. Evans — with your retirement just 6 months away, I wanted to check in about your transition plan. We should review your withdrawal strategy, Medicare enrollment timeline, and Social Security claiming options. Want to schedule a session this week?',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:00 PM',
        title: 'Referral Lead Qualification',
        description: 'A current client\'s colleague calls asking about investment management.',
        aiResponse: 'Thank you for calling — Dr. Patel mentioned you might be interested in our services. I\'d love to learn more about your financial goals. Are you primarily looking for investment management, retirement planning, or comprehensive wealth management?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'Fee Billing and Statement Prep',
        description: 'AI calculates quarterly advisory fees and prepares client billing statements.',
        aiResponse: 'Q1 billing complete: 42 accounts processed totaling $31,500 in advisory fees. All statements are formatted and queued for delivery. Three accounts had AUM changes requiring fee recalculation — all verified.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 1800 },
      },
      {
        time: '3:45 PM',
        title: 'Competitor Rate Research',
        description: 'AI monitors competitor advisory fee structures and service offerings.',
        aiResponse: 'Competitor update: Meridian Wealth just launched a robo-advisory tier at 0.35% AUM. Two other local firms raised minimum account sizes to $500K. Your current positioning remains competitive for the $250K-$1M segment.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '5:00 PM',
        title: 'Client Appreciation Campaign',
        description: 'AI drafts personalized year-end thank-you messages for top clients.',
        aiResponse: 'I\'ve prepared personalized appreciation messages for your top 20 clients by AUM. Each mentions their specific portfolio milestones this year. Ready to send via email, or would you prefer to review them first?',
        channel: 'email',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 20 },
      },
      {
        time: '7:00 PM',
        title: 'Google Review from Satisfied Client',
        description: 'A long-term client leaves a review praising the advisor\'s proactive communication.',
        aiResponse: 'Thank you for the wonderful review, Margaret. It\'s been a privilege to partner with you on your financial journey over the past 8 years. Your confidence in our team means everything to us.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '9:00 PM',
        title: 'Monthly AUM and Growth Report',
        description: 'AI generates a comprehensive monthly report on assets under management and client activity.',
        aiResponse: 'Monthly summary: Total AUM $18.4M (+2.1% from market gains, +$450K net new assets). 6 quarterly reviews completed, 2 new clients onboarded, 4 referral leads in pipeline. Client retention: 100%. Next month\'s priority: 9 remaining quarterly reviews.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Proactively reassures clients during market volatility with portfolio-specific context',
      memory: 'Tracks client life events, risk tolerance, retirement dates, and beneficiary changes',
      proactive: 'Pre-market intelligence briefs and rebalancing alerts before markets open',
      bookings: 'Schedules quarterly portfolio reviews and financial planning sessions',
      leads: 'Qualifies referral prospects by investment goals and minimum asset thresholds',
      revenue: 'Calculates and sends quarterly advisory fee statements automatically',
      reputation: 'Responds to Google reviews and requests testimonials after milestone meetings',
      content: 'Drafts market commentary newsletters and client appreciation campaigns',
      reporting: 'Monthly AUM report with growth attribution, client activity, and pipeline metrics',
      browser: 'Monitors competitor fee structures, regulatory updates, and market research',
      team: 'Paraplanners and assistants query AI for client data, compliance status, and scheduling',
      workflow: 'Syncs portfolio management platform with CRM, compliance logs, and billing system',
      voice: 'Answers prospect calls, collects financial goals, and schedules introductory meetings',
      multiagent: 'Runs parallel analysis across multiple client portfolios during market events',
      environment: 'Controls conference room displays for portfolio review presentations',
    },
    stats: {
      messagesPerDay: 40,
      bookingsPerWeek: 10,
      monthlySavings: 5500,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Financial advisors need proactive client communication during market events, compliance tracking, and consistent reputation management to build trust.',
  },

  /* ================================================================
     5. INSURANCE BROKER
     ================================================================ */
  {
    id: 'insurance',
    label: 'Insurance Broker',
    emoji: '📋',
    category: 'Professional Services',
    tagline: 'Retain more policies and close more renewals with AI-powered client management',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Policy Renewal Pipeline Brief',
        description: 'AI summarizes policies expiring in the next 30, 60, and 90 days.',
        aiResponse: 'Good morning — 8 policies expire in the next 30 days, 14 in 60 days, and 22 in 90 days. Three high-value commercial policies need renewal outreach this week. I\'ve prioritized by premium size.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Policy Renewal Reminder — Auto',
        description: 'A client\'s auto insurance policy expires in 15 days; AI sends a proactive reminder.',
        aiResponse: 'Hi Angela — your auto insurance policy with SafeGuard expires on March 26. I\'ve already pulled renewal quotes from 3 carriers. Your current rate increased 4%, but I found a comparable option that\'s actually 6% lower. Want to review the comparison?',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:30 AM',
        title: 'New Quote Request — Homeowner',
        description: 'A prospective client fills out a quote request form on the website.',
        aiResponse: 'Thank you for requesting a homeowner\'s insurance quote. I\'ve noted the property details for 445 Cedar Lane. To finalize quotes, could you confirm: the year the roof was last replaced, whether you have a security system, and your current coverage limits?',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 AM',
        title: 'Claim Filing Assistance',
        description: 'A client messages about a fender bender and needs to start the claims process.',
        aiResponse: 'I\'m sorry to hear about the accident, Mr. Torres. Let me help you get started. I need the date, time, and location of the incident, the other driver\'s information, and any photos of the damage. Your policy number is AH-29471 and I\'ll file the claim as soon as I have the details.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:45 AM',
        title: 'Quote Comparison Research',
        description: 'AI pulls rates from multiple carriers for a commercial liability renewal.',
        aiResponse: 'I\'ve compared commercial general liability quotes for Brightside Construction across 5 carriers. Rates range from $4,200 to $6,800 annually. Hartford offers the best combination of price ($4,450) and coverage limits. Full comparison matrix is ready for your review.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 2350 },
      },
      {
        time: '11:30 AM',
        title: 'Coverage Review Appointment',
        description: 'A business client wants to schedule their annual coverage review.',
        aiResponse: 'Hi Carlos — it\'s time for your annual coverage review for Brightside Construction. I have openings next Tuesday at 9 AM or Thursday at 2 PM. We\'ll review your general liability, workers\' comp, and commercial auto. Which time works?',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:45 PM',
        title: 'Cross-Sell Opportunity Detection',
        description: 'AI identifies a homeowner client who doesn\'t have an umbrella policy.',
        aiResponse: 'I noticed Mrs. Patterson has home and auto policies but no umbrella coverage. Given her asset profile, a $1M umbrella policy would be approximately $200/year. I\'ve drafted a personalized recommendation email for your approval.',
        channel: 'system',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'savings', increment: 200 },
      },
      {
        time: '2:00 PM',
        title: 'Commission Reconciliation',
        description: 'AI tracks incoming carrier commission statements and flags discrepancies.',
        aiResponse: 'Commission reconciliation for March: $12,400 received across 6 carriers. Two discrepancies found — National Mutual underpaid by $340 on the Rivera commercial policy, and Keystone hasn\'t paid the Henderson renewal commission. I\'ve drafted follow-up emails to both.',
        channel: 'system',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 340 },
      },
      {
        time: '3:30 PM',
        title: 'Client Life Event — New Baby',
        description: 'AI detects from a client conversation that they just had a baby and suggests coverage updates.',
        aiResponse: 'Congratulations on the new addition to your family! This is a great time to review your life insurance coverage and consider adding your baby to your health plan. I can also look into a 529 education savings plan. Want me to schedule a quick review?',
        channel: 'sms',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Google Review Follow-Up',
        description: 'A client who just renewed leaves a positive review about the savings found.',
        aiResponse: 'Thank you for the kind words, Angela! We\'re glad we could find you better coverage at a lower rate. It\'s exactly what we aim to do for every client. Thanks for trusting us with your insurance needs!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Educational Content — Storm Season Prep',
        description: 'AI drafts a seasonal content piece about preparing for storm season and reviewing coverage.',
        aiResponse: 'I\'ve drafted a blog post and email blast: "Is Your Home Ready for Storm Season? 5 Coverage Gaps Most Homeowners Miss." It covers flood exclusions, deductible thresholds, and documentation tips. Scheduled to post next Monday.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '9:30 PM',
        title: 'Monthly Book of Business Report',
        description: 'AI generates a report on retention rates, new policies written, and commission projections.',
        aiResponse: 'Monthly report: 94% retention rate (up from 91%), 12 new policies written ($18,600 annual premium), commission income $14,200. Top risk: 3 commercial accounts shopping rates. Recommendation: schedule proactive reviews with each.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Reaches out about renewals, claims assistance, and coverage questions across all channels',
      memory: 'Tracks every client\'s policy details, claims history, life events, and coverage gaps',
      proactive: 'Alerts you to upcoming renewals 90, 60, and 30 days before expiration',
      bookings: 'Schedules annual coverage reviews and new policy consultations',
      leads: 'Qualifies quote requests by coverage type, property details, and risk profile',
      revenue: 'Reconciles carrier commission statements and chases underpayments',
      reputation: 'Responds to Google reviews and requests them after successful renewals',
      content: 'Creates seasonal content about coverage preparation and risk awareness',
      reporting: 'Monthly book of business report with retention rates, new policies, and commissions',
      browser: 'Pulls and compares carrier quotes across multiple platforms automatically',
      team: 'Account managers query AI for policy details, renewal dates, and claim status',
      workflow: 'Syncs agency management system with carrier portals and client database',
      voice: 'Answers calls about claims, quotes, and policy questions with full client context',
      multiagent: 'Runs parallel quote comparisons across multiple carriers simultaneously',
      environment: 'Controls office displays showing renewal pipeline and retention metrics',
    },
    stats: {
      messagesPerDay: 50,
      bookingsPerWeek: 14,
      monthlySavings: 4600,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Insurance brokers need proactive renewal management, multi-carrier quote comparison, and consistent follow-up to maintain high retention rates.',
  },

  /* ================================================================
     6. ARCHITECTURE / ENGINEERING
     ================================================================ */
  {
    id: 'architecture',
    label: 'Architecture / Engineering',
    emoji: '🏗️',
    category: 'Professional Services',
    tagline: 'Deliver projects on time while your AI manages timelines, permits, and client revisions',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Active Projects Dashboard',
        description: 'AI compiles status updates across all active projects — milestones, deadlines, and blockers.',
        aiResponse: 'Good morning — 5 active projects in progress. The Riverdale mixed-use is on track for schematic review Friday. The Elm Street renovation has a permit delay (2 days behind). Henderson residence revisions are due back from the client today.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Permit Application Status Check',
        description: 'AI checks the city planning portal for updates on pending permit applications.',
        aiResponse: 'Permit update: The Elm Street renovation building permit has been assigned to reviewer J. Martinez. Estimated review completion is March 18. The Riverdale site plan amendment was approved yesterday — I\'ve downloaded the stamped documents.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '8:30 AM',
        title: 'Client Revision Review Request',
        description: 'A residential client sends back marked-up floor plans with revision requests.',
        aiResponse: 'I\'ve received Mrs. Henderson\'s revision notes on the floor plans. She\'s requesting: 1) enlarged master closet, 2) kitchen island moved 2 feet north, 3) addition of a mudroom entry. I\'ve organized these into a revision checklist and assigned them to the drafting queue.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:45 AM',
        title: 'New Project Inquiry',
        description: 'A commercial developer reaches out about designing a 10-unit townhome community.',
        aiResponse: 'Thank you for reaching out about the townhome project on Parker Ave. To prepare a preliminary scope and fee proposal, could you share the lot dimensions, target unit sizes, and your timeline for permitting? I\'ll schedule a site visit and discovery meeting.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Contractor Coordination Call',
        description: 'The general contractor on the Riverdale project needs structural drawing clarification.',
        aiResponse: 'Thank you for calling. Regarding the steel beam specification on Drawing S-4, the W12x26 at grid line C was revised to W14x30 in Addendum 2. I\'ll send you the updated drawing set right after this call. Would you also like the revised connection details?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Project Timeline Milestone Alert',
        description: 'The schematic design deadline for a commercial project is approaching.',
        aiResponse: 'Reminder: Riverdale mixed-use schematic design review is this Friday at 2 PM with the client. Current status — floor plans are complete, elevations need facade material selections, and the site plan needs updated parking calculations. Assigning the elevation task to your senior designer.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Invoice and Payment Tracking',
        description: 'AI tracks project billing milestones and sends invoices at completion of each phase.',
        aiResponse: 'The Henderson residence has reached the 60% construction document milestone. I\'ve generated the Phase 3 invoice for $8,500 and sent it to the client. Also, the Elm Street deposit ($5,000) is 10 days overdue — I sent a gentle reminder this morning.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 5000 },
      },
      {
        time: '2:00 PM',
        title: 'Design Team Task Assignment',
        description: 'AI distributes drafting tasks across the team based on workload and expertise.',
        aiResponse: 'I\'ve assigned this week\'s tasks: Maria — Riverdale elevations and material board (due Thursday). James — Henderson master closet and mudroom revisions (due Wednesday). Priya — Parker Ave site feasibility study (due Friday). All assignments are in the project tracker.',
        channel: 'system',
        capability: 'team',
        tier: 'executive',
      },
      {
        time: '3:30 PM',
        title: 'Building Code Research',
        description: 'AI researches updated energy code requirements for an upcoming commercial project.',
        aiResponse: 'Updated energy code research for Riverdale: The 2025 IECC requires R-30 continuous roof insulation (up from R-25) and high-performance glazing with U-0.28 max. I\'ve summarized the changes and their cost impact in a memo for the client meeting Friday.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '5:00 PM',
        title: 'Portfolio Showcase Content',
        description: 'AI drafts an Instagram post featuring a recently completed project.',
        aiResponse: 'I\'ve drafted an Instagram post showcasing the completed Lakeview residence: professional photos arranged in a carousel, caption highlighting the sustainable design features and open floor plan. Hashtags and posting time optimized for your audience.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'Houzz Review Response',
        description: 'A past client leaves a 5-star review on Houzz praising the design process.',
        aiResponse: 'Thank you so much for the wonderful review, Mr. and Mrs. Chen! It was a joy to bring your vision to life. Your home\'s blend of modern design and natural materials is one of our favorite projects. We hope you enjoy it for years to come.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '10:00 PM',
        title: 'Weekly Project Health Report',
        description: 'AI generates a summary of all projects with budget, timeline, and risk assessments.',
        aiResponse: 'Weekly report: 5 active projects, total contracted value $287,000. On schedule: 3/5. At risk: Elm Street (permit delay) and Parker Ave (awaiting client deposit). Revenue collected this month: $21,500. Outstanding invoices: $13,500. Next week\'s priorities: Riverdale review meeting and Henderson revisions.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles client revision requests, contractor questions, and consultant coordination',
      memory: 'Tracks every project\'s design decisions, client preferences, and revision history',
      proactive: 'Monitors project timelines and alerts you to approaching milestones and blockers',
      bookings: 'Schedules client design reviews, site visits, and consultant coordination meetings',
      leads: 'Qualifies new project inquiries by scope, budget, and timeline',
      revenue: 'Sends milestone-based invoices and chases overdue project deposits',
      reputation: 'Responds to Houzz and Google reviews and requests them after project completion',
      content: 'Creates portfolio showcases, project update posts, and design process stories',
      reporting: 'Weekly project health report with budget tracking, timeline status, and risk flags',
      browser: 'Checks permit status on city portals and researches building code updates',
      team: 'Designers and drafters query AI for project specs, deadlines, and client feedback',
      workflow: 'Syncs project management tools with drawing logs, billing, and permit tracking',
      voice: 'Answers contractor calls with drawing specifications and addendum details',
      multiagent: 'Runs parallel code compliance checks across multiple jurisdictions',
      environment: 'Controls presentation displays for client design review meetings',
    },
    stats: {
      messagesPerDay: 35,
      bookingsPerWeek: 8,
      monthlySavings: 5800,
      responseTime: '< 5 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Architecture firms need browser-based permit tracking, team task management, and contractor call handling that require executive-tier capabilities.',
  },

  /* ================================================================
     7. RECRUITMENT / STAFFING AGENCY
     ================================================================ */
  {
    id: 'recruitment',
    label: 'Recruitment Agency',
    emoji: '🎯',
    category: 'Professional Services',
    tagline: 'Fill roles faster while your AI sources candidates, schedules interviews, and nurtures talent pipelines 24/7',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Morning Job Board Update',
        description: 'AI scans all active job boards for new postings, refreshes listings that are aging, and flags roles that need attention.',
        aiResponse: 'Good morning — 14 active roles across 6 clients. I\'ve refreshed 4 listings on Indeed and LinkedIn that were losing visibility. 2 new applications overnight for the Senior Developer role at TechCorp. The Marketing Manager posting at Pinnacle has had zero applications in 5 days — I\'ve rewritten the job description and boosted it.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Candidate Resume Screening',
        description: 'AI screens 28 new resumes that came in overnight against role requirements and client preferences.',
        aiResponse: 'Screened 28 new applications. 6 are strong matches: 3 for the DevOps Engineer role (all have Kubernetes experience), 2 for the Account Manager at Bright Media (both have SaaS backgrounds), and 1 excellent fit for the CFO search at Meridian. I\'ve ranked them by match score and flagged the top 3 for immediate outreach.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:45 AM',
        title: 'Interview Scheduling',
        description: 'A client approves 3 candidates for first-round interviews. AI coordinates availability across all parties.',
        aiResponse: 'TechCorp approved 3 candidates for the Senior Developer role. I\'ve cross-referenced calendars and sent scheduling links: Maria — Tuesday 10 AM, James — Tuesday 2 PM, Arun — Wednesday 9 AM. All confirmations are in. I\'ve also sent each candidate a prep packet with company info and interview tips.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 3 },
      },
      {
        time: '9:30 AM',
        title: 'Client Job Order Intake',
        description: 'A new client calls with an urgent need to fill a project manager role within 2 weeks.',
        aiResponse: 'New job order from Cascade Solutions: Project Manager, hybrid, $95–110K, start date April 1st. I\'ve created the intake profile, drafted the job description based on similar roles, and identified 8 candidates in our database who match. Want me to reach out to the top 5 today?',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Reference Check Follow-Up',
        description: 'AI follows up on pending reference checks for a candidate in the final stage of the hiring process.',
        aiResponse: 'Reference check update for Lisa Park (Meridian CFO role): 2 of 3 references completed — both highly positive. Her former CEO called her "the most strategic finance leader I\'ve worked with." Third reference, David Chen, hasn\'t responded. I\'ve sent a second request and will call him at 2 PM if no reply.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:45 AM',
        title: 'Candidate Status Update',
        description: 'Several candidates message asking about their application status. AI responds with personalized updates.',
        aiResponse: 'Updated 6 candidates on their status: 2 moved to interview stage (sent congrats and prep info), 1 advanced to final round (sent details), 2 are on hold pending client feedback (set expectations), and 1 was not selected (sent a thoughtful rejection with encouragement to apply for future roles). All messages personalized.',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 6 },
      },
      {
        time: '1:00 PM',
        title: 'LinkedIn Outreach Campaign',
        description: 'AI identifies and reaches out to passive candidates who match the Senior Developer profile.',
        aiResponse: 'LinkedIn outreach for TechCorp\'s Senior Developer role: I\'ve identified 15 passive candidates with strong Kubernetes and Go backgrounds. Sent personalized connection requests to 10 with tailored messages referencing their recent projects. Last week\'s campaign had a 34% response rate — expecting 3–4 replies by tomorrow.',
        channel: 'system',
        capability: 'leads',
        tier: 'manager',
        stat: { key: 'messages', increment: 10 },
      },
      {
        time: '2:15 PM',
        title: 'Salary Negotiation Question',
        description: 'A candidate asks about salary range and benefits for a role they\'re considering.',
        aiResponse: 'Hi James — great question. The Account Manager role at Bright Media offers $75–85K base plus 10–15% bonus. Benefits include full health coverage, 401k match, 20 PTO days, and remote flexibility. Based on your 6 years of experience, I\'d position you at the higher end. Want to discuss negotiation strategy before your final interview?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Onboarding Document Coordination',
        description: 'A candidate has accepted an offer. AI coordinates all pre-employment paperwork and start-date logistics.',
        aiResponse: 'Arun accepted the TechCorp offer! I\'ve sent the offer letter for e-signature, initiated the background check, emailed the onboarding packet (tax forms, direct deposit, NDA), and notified the client\'s HR team. Start date confirmed: March 24th. I\'ll follow up on any unsigned documents in 48 hours.',
        channel: 'email',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'savings', increment: 3500 },
      },
      {
        time: '4:30 PM',
        title: 'Placement Anniversary Check-In',
        description: 'AI checks in with candidates placed 90 days ago to ensure retention and client satisfaction.',
        aiResponse: 'Sent 90-day check-in messages to 3 placed candidates. Emily at DataFlow says she loves the role and her manager gave a glowing review — great for a testimonial. Marcus at Bright Media mentioned some onboarding friction — I\'ve flagged it for you to discuss with the client. Retention rate this quarter: 94%.',
        channel: 'sms',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '5:30 PM',
        title: 'Market Rate Report',
        description: 'AI compiles salary benchmarking data for a client who\'s struggling to attract candidates.',
        aiResponse: 'Salary benchmark report for Cascade Solutions\' Project Manager role: Current offer of $90K is 12% below market median ($102K) in your metro area. Competitors are offering $95–115K with signing bonuses. I\'ve prepared a recommendation to increase the range to $100–112K with a $5K signing bonus. Attached as a PDF for your client call.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:00 PM',
        title: 'End-of-Day Pipeline Summary',
        description: 'AI generates a full summary of the day\'s recruiting activity across all clients and roles.',
        aiResponse: 'Today\'s recap: 28 resumes screened, 6 shortlisted, 3 interviews scheduled, 1 offer accepted (Arun — TechCorp), 1 new job order (Cascade PM). Pipeline health: 42 active candidates across 14 roles. Revenue this month: $18,500 in placement fees. Pending: Lisa Park\'s final reference for the $28K CFO placement fee.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to candidate questions across SMS, WhatsApp, email, and LinkedIn with full context on roles and application status',
      memory: 'Remembers every candidate\'s skills, preferences, salary expectations, interview history, and placement outcomes',
      proactive: 'Morning pipeline briefings, aging listing alerts, and retention check-in reminders at key milestones',
      bookings: 'Coordinates multi-party interview scheduling across candidates, clients, and panel members',
      leads: 'Sources passive candidates on LinkedIn, nurtures talent pools, and re-engages past applicants for new roles',
      revenue: 'Tracks placement fees, chases outstanding invoices, and identifies upsell opportunities with existing clients',
      reputation: 'Sends candidate satisfaction surveys and requests Google reviews after successful placements',
      content: 'Creates job postings, LinkedIn thought leadership content, and employer branding materials',
      reporting: 'Daily pipeline summaries, weekly client reports, and quarterly market benchmarking analysis',
      browser: 'Scans job boards, researches company profiles, and monitors competitor postings',
      team: 'Recruiters query AI for candidate status, client preferences, and role requirements',
      workflow: 'Syncs ATS with calendar, email, and onboarding systems for seamless candidate tracking',
      voice: 'Handles intake calls from clients, collects job requirements, and pre-screens candidates by phone',
      multiagent: 'Runs parallel candidate sourcing across multiple platforms and roles simultaneously',
      environment: 'Controls presentation screens for client pitch meetings and candidate showcases',
    },
    stats: {
      messagesPerDay: 55,
      bookingsPerWeek: 18,
      monthlySavings: 7200,
      responseTime: '< 3 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Staffing agencies need phone-based intake, automated resume screening, and cross-platform candidate sourcing that require executive-tier capabilities.',
  },

  /* ================================================================
     8. PROPERTY MANAGEMENT
     ================================================================ */
  {
    id: 'property-management',
    label: 'Property Management',
    emoji: '🏘️',
    category: 'Professional Services',
    tagline: 'Manage every property, tenant, and vendor from one AI that never sleeps — even for after-hours emergencies',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Maintenance Request from Tenant',
        description: 'A tenant submits a maintenance request through the portal reporting a leaking faucet in unit 4B.',
        aiResponse: 'New maintenance request from Unit 4B (Sarah Mitchell): kitchen faucet leaking. I\'ve categorized it as non-emergency plumbing, logged it in the system, and sent Sarah a confirmation: "We\'ve received your request and a plumber will be scheduled within 24 hours." I\'m contacting Mike\'s Plumbing now for availability.',
        channel: 'system',
        capability: 'workflow',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Rent Payment Reminder',
        description: 'AI sends friendly rent reminders to tenants whose payments are due in 3 days.',
        aiResponse: 'Rent reminders sent to 12 tenants with payments due on the 15th. Personalized messages include payment portal link and current balance. 3 tenants have autopay set up (no reminder needed). Last month, reminders reduced late payments by 40%. I\'ll flag any non-payments on the 16th.',
        channel: 'sms',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'messages', increment: 12 },
      },
      {
        time: '8:30 AM',
        title: 'Property Showing Scheduling',
        description: 'Two prospective tenants reach out to schedule viewings for the vacant unit at 742 Elm Street.',
        aiResponse: 'Two showing requests for 742 Elm Street (2BR, $1,850/mo). I\'ve scheduled: David R. — today at 4 PM, Maria L. — tomorrow at 11 AM. Both received confirmation emails with unit photos, floor plan, lease terms, and parking info. I\'ve also sent them the pre-qualification form to complete before the showing.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 2 },
      },
      {
        time: '9:45 AM',
        title: 'Lease Renewal Notification',
        description: 'Three leases expire in 60 days. AI proactively sends renewal offers with updated terms.',
        aiResponse: 'Lease renewal notices sent to 3 tenants (Units 2A, 3C, 5D) expiring May 15th. Each received a personalized offer: 2A and 3C at 3% increase (market-aligned), 5D at current rate (long-term tenant incentive). All include the digital renewal link. I\'ll follow up in 7 days if unsigned.',
        channel: 'email',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '11:00 AM',
        title: 'Vendor Coordination (Plumber)',
        description: 'AI coordinates with the plumber to schedule the Unit 4B faucet repair and notifies the tenant.',
        aiResponse: 'Mike\'s Plumbing confirmed for Unit 4B tomorrow at 10 AM. I\'ve notified Sarah: "Your faucet repair is scheduled for tomorrow, March 13th at 10 AM. Mike from Mike\'s Plumbing will need access to the kitchen. Please confirm if this time works." Sarah confirmed. Entry instructions sent to the plumber.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:30 PM',
        title: 'Tenant Complaint Resolution',
        description: 'A tenant in Unit 3A complains about noise from the unit above during evening hours.',
        aiResponse: 'Noise complaint from Unit 3A (Tom Wheeler) about Unit 4A. I\'ve logged the complaint, reviewed the lease quiet hours clause (10 PM–7 AM), and sent a diplomatic notice to Unit 4A: "We\'ve received feedback about evening noise levels. As a reminder, quiet hours are 10 PM–7 AM per your lease agreement. Thank you for your consideration." Tom received confirmation that we\'re addressing it.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 2 },
      },
      {
        time: '1:30 PM',
        title: 'Vacancy Listing Posting',
        description: 'AI creates and posts listings for a newly vacant unit across multiple platforms.',
        aiResponse: 'New listing posted for Unit 6A (1BR, $1,450/mo, available April 1st). Published on Zillow, Apartments.com, Facebook Marketplace, and Craigslist with professional photos, virtual tour link, and key amenities. SEO-optimized description highlights in-unit laundry and walkability. I\'ll track views and inquiries daily.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:30 PM',
        title: 'HOA Communication',
        description: 'The HOA sends a notice about upcoming parking lot resurfacing that affects multiple properties.',
        aiResponse: 'HOA notice received: parking lot resurfacing at Maple Ridge complex, March 20–22. I\'ve drafted tenant notifications for all 18 affected units with alternate parking instructions and dates. Also updated the maintenance calendar and notified the landscaping crew to reschedule Thursday\'s service. Ready for your review before sending.',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'Inspection Scheduling',
        description: 'Annual property inspections are due next month. AI coordinates schedules with tenants.',
        aiResponse: 'Annual inspection scheduling started for Oakwood Apartments (24 units). I\'ve sent scheduling requests to all tenants with 3 available time slots each over the March 25–28 window. 8 tenants have already confirmed. I\'ll send reminders to non-responders in 48 hours. Inspector confirmed availability for all 4 days.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 8 },
      },
      {
        time: '4:30 PM',
        title: 'Late Payment Follow-Up',
        description: 'Two tenants are 5 days past due on rent. AI sends firm but professional follow-up notices.',
        aiResponse: 'Late payment follow-ups sent to Units 1B and 7C (both 5 days overdue). Messages include outstanding balance, late fee notice per lease terms ($50), and a direct payment link. Unit 1B (Jason) has been late twice before — I\'ve flagged this for your review. Unit 7C (Patricia) is first-time late — I used a gentler tone.',
        channel: 'sms',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 3700 },
      },
      {
        time: '6:00 PM',
        title: 'Monthly Owner Report',
        description: 'AI compiles the monthly financial and operational report for the property owner.',
        aiResponse: 'March owner report ready for Oakwood Apartments: 96% occupancy (1 vacant unit, showing scheduled). Rent collected: $38,200 of $39,850 (96%). Maintenance spend: $2,340 (within budget). 2 lease renewals pending. Net operating income: $28,400. Attached with full P&L, maintenance log, and tenant roster. Ready for your review.',
        channel: 'email',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '11:00 PM',
        title: 'Emergency After-Hours Call',
        description: 'A tenant calls about a burst pipe flooding their apartment late at night.',
        aiResponse: 'EMERGENCY: Burst pipe reported in Unit 2B (Carlos Reyes). I\'ve instructed Carlos to shut off the water valve under the sink and place towels. Emergency plumber dispatched — ETA 35 minutes. I\'ve also notified Unit 1B below about potential water damage. Logging this as an emergency maintenance event. I\'ll update you with the plumber\'s report.',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles tenant inquiries, complaints, and notices across SMS, email, phone, and portal messages',
      memory: 'Tracks every tenant\'s lease terms, payment history, maintenance requests, and communication preferences',
      proactive: 'Lease renewal alerts 60 days out, payment reminders before due dates, and inspection scheduling automation',
      bookings: 'Schedules property showings, maintenance visits, inspections, and vendor appointments',
      leads: 'Captures prospective tenant inquiries from listing sites and nurtures them through the application process',
      revenue: 'Sends rent reminders, chases late payments with escalating notices, and tracks collection rates',
      reputation: 'Responds to property reviews on Google and Apartments.com and requests reviews from satisfied tenants',
      content: 'Creates property listings with optimized descriptions, photos, and virtual tour links across platforms',
      reporting: 'Monthly owner reports with P&L, occupancy rates, maintenance spending, and tenant roster updates',
      browser: 'Monitors comparable rental rates, checks permit statuses, and researches vendor reviews',
      team: 'Maintenance staff and leasing agents query AI for tenant info, work orders, and showing schedules',
      workflow: 'Syncs property management software with accounting, maintenance tracking, and tenant portals',
      voice: 'Handles after-hours emergency calls, dispatches vendors, and provides tenant instructions',
      multiagent: 'Manages parallel maintenance coordination across multiple properties and vendors',
      environment: 'Controls smart building systems for common area lighting, HVAC scheduling, and access control',
    },
    stats: {
      messagesPerDay: 50,
      bookingsPerWeek: 15,
      monthlySavings: 6500,
      responseTime: '< 4 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Property management requires after-hours emergency call handling, vendor dispatch, and multi-system workflow automation that demand executive-tier capabilities.',
  },
];
