import type { Industry } from '../experience-data';

export const retailIndustries: Industry[] = [
  /* ------------------------------------------------------------------ */
  /* 1. CLOTHING / BOUTIQUE                                              */
  /* ------------------------------------------------------------------ */
  {
    id: 'clothing',
    label: 'Clothing / Boutique',
    emoji: '\u{1F457}',
    category: 'Retail & E-Commerce',
    tagline: 'Every customer styled, every fitting room booked, every comeback automatic.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Daily trend report compiled',
        description: 'AI scans fashion blogs, TikTok trends, and competitor Instagram feeds to surface today\'s trending styles relevant to your inventory.',
        aiResponse: 'Good morning! Oversized linen blazers are trending heavily today (+340% search volume). You have 12 units in stock \u2014 I\'d recommend featuring them in your window display and posting a styling reel.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '7:30 AM',
        title: 'Morning briefing sent to owner',
        description: 'Summary of yesterday\'s sales, pending online orders to pack, and today\'s private shopping appointments.',
        aiResponse: 'Yesterday: $2,840 in sales (14 transactions). 6 online orders need packing before noon. You have 2 private styling appointments today at 11 AM and 3 PM. One VIP client, Megan R., is coming \u2014 she prefers earth tones and size 6.',
        channel: 'whatsapp',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:15 AM',
        title: 'Customer asks about dress availability',
        description: 'A customer sends a photo of a dress she saw on Instagram and asks if you carry it or something similar.',
        aiResponse: 'Hi Priya! That\'s a beautiful piece. We don\'t carry that exact dress, but we have two very similar styles in stock \u2014 a wrap midi in sage green ($128) and a pleated version in dusty rose ($145). Want me to set them aside so you can try them on? We\'re open until 7 PM today.',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'New collection drop announced',
        description: 'AI drafts and schedules social media posts for the new spring arrivals that just came in.',
        aiResponse: 'I\'ve drafted 4 posts for the spring collection launch: a carousel showcasing key pieces, a behind-the-scenes unboxing reel, a "first look" story series, and a styled flat-lay. Everything\'s scheduled across Instagram and Facebook for peak engagement times this week.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '11:30 AM',
        title: 'Private styling appointment reminder',
        description: 'AI sends a personalized reminder to the VIP client with outfit suggestions pre-selected based on her purchase history.',
        aiResponse: 'Hi Megan! Just a reminder about your styling session today at 3 PM. Based on your wardrobe with us, I\'ve pulled some pieces you\'ll love \u2014 including a camel cashmere knit that pairs perfectly with the wide-leg trousers you bought last month. See you soon!',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:45 PM',
        title: 'Online return request handled',
        description: 'Customer emails about returning a top that didn\'t fit. AI processes the return and suggests an exchange.',
        aiResponse: 'Hi Dana, I\'m sorry the top didn\'t fit! I\'ve initiated your return \u2014 you\'ll receive a prepaid shipping label by email within the hour. Based on your measurements, I\'d recommend trying the same style in a size down. Want me to hold one for you, or would you prefer a store credit of $89?',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Slow afternoon detected \u2014 flash sale triggered',
        description: 'Foot traffic is low. AI sends a limited-time offer to nearby customers who\'ve opted in to SMS alerts.',
        aiResponse: 'Slow afternoon detected \u2014 only 3 walk-ins since noon. I\'ve sent a "2-hour flash sale: 20% off all denim" SMS to 245 local subscribers. Last time this generated 11 additional visits within 90 minutes.',
        channel: 'sms',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 320 },
      },
      {
        time: '2:30 PM',
        title: 'Supplier restock reminder',
        description: 'AI notices best-selling items are running low and drafts a reorder to the supplier.',
        aiResponse: 'Your best-selling ribbed tank ($34) is down to 3 units across all sizes. Based on the current sell-through rate, you\'ll be out of stock by Friday. I\'ve drafted a reorder of 48 units to your supplier. Shall I send it?',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 200 },
      },
      {
        time: '4:00 PM',
        title: 'Google review response',
        description: 'A customer left a 5-star review praising the personal styling service. AI responds warmly.',
        aiResponse: 'Thank you so much, Rachel! We\'re thrilled you loved your styling session. It was a pleasure helping you find the perfect outfit for your anniversary dinner. We can\'t wait to see you again \u2014 new arrivals dropping next week that are right up your alley!',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '5:30 PM',
        title: 'Abandoned cart follow-up',
        description: 'Three online shoppers left items in their carts. AI sends personalized nudge messages.',
        aiResponse: 'Hi Jess! You left a gorgeous floral maxi dress in your cart. Just a heads up \u2014 it\'s one of our most popular pieces and we\'re down to the last 2 in your size. Want me to hold it for 24 hours? Free shipping if you complete your order today.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '7:00 PM',
        title: 'End-of-day sales summary',
        description: 'AI compiles the full day\'s performance: sales, foot traffic, online orders, and social engagement.',
        aiResponse: 'Today\'s wrap-up: $4,120 total sales (22 in-store + 8 online). Flash sale drove $640 in incremental revenue. Instagram gained 47 new followers. Top seller: linen blazer (5 units). Tomorrow you have 3 appointments and a shipment arriving at 10 AM.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:30 PM',
        title: 'Late-night Instagram DM handled',
        description: 'A potential customer asks about sizing and store hours after close.',
        aiResponse: 'Hey Taylor! Great question \u2014 our Everyday Blazer runs true to size, so your usual Medium should be perfect. If you\'re between sizes, I\'d suggest sizing up for a relaxed fit. We\'re open tomorrow 10 AM\u20137 PM. Want me to put one aside for you to try on?',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Responds to DMs about sizing, availability, and style advice across Instagram, WhatsApp, and email with full product knowledge.',
      memory: 'Remembers every customer\'s size, color preferences, past purchases, and style profile for personalized recommendations.',
      proactive: 'Sends morning briefings with sales data, appointments, and shipments. Detects slow periods and triggers promotions.',
      bookings: 'Manages private styling appointments, hold requests, and fitting room reservations.',
      leads: 'Captures interest from social media, follows up on abandoned carts, and nurtures first-time visitors into repeat customers.',
      revenue: 'Triggers flash sales during slow periods, chases unpaid invoices for wholesale accounts, re-engages lapsed customers.',
      reputation: 'Responds to Google and Facebook reviews within the hour with personalized, on-brand replies.',
      content: 'Creates styled flat-lays, outfit-of-the-day posts, and new-arrival announcements across all social platforms.',
      reporting: 'Daily sales summaries, weekly sell-through reports, and inventory velocity analysis.',
      browser: 'Browses supplier catalogs, compares wholesale prices, and drafts restock orders when inventory runs low.',
    },
    stats: {
      messagesPerDay: 65,
      bookingsPerWeek: 18,
      monthlySavings: 3200,
      responseTime: '< 2 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Boutiques thrive on personal relationships and visual marketing. The Manager tier handles reputation, content creation, and revenue recovery \u2014 turning browsers into loyal repeat customers.',
  },

  /* ------------------------------------------------------------------ */
  /* 2. ELECTRONICS STORE                                                */
  /* ------------------------------------------------------------------ */
  {
    id: 'electronics',
    label: 'Electronics Store',
    emoji: '\u{1F4BB}',
    category: 'Retail & E-Commerce',
    tagline: 'Every spec question answered, every warranty tracked, every price matched instantly.',
    dayEvents: [
      {
        time: '6:30 AM',
        title: 'Competitor price scan completed',
        description: 'AI browses Amazon, Best Buy, and Newegg to check prices on your top 50 SKUs and flags any items where you\'re undercut.',
        aiResponse: 'Morning price check complete. 3 items need attention: your Sony WH-1000XM5 is $18 above Amazon, the Samsung 65" OLED is $40 above Best Buy, and your iPad Air is price-matched. I\'ve prepared adjustment recommendations.',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
      },
      {
        time: '8:00 AM',
        title: 'Morning briefing with repair queue',
        description: 'Summary of today\'s agenda: repairs to complete, deliveries incoming, and trade-in appointments.',
        aiResponse: 'Good morning! Today: 4 repairs due (2 screen replacements, 1 laptop keyboard, 1 data transfer). UPS delivery at 11 AM \u2014 20 units of the new iPhone cases. 2 trade-in appointments (10:30 AM and 2 PM). Yesterday\'s revenue: $6,420 across 31 transactions.',
        channel: 'whatsapp',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:15 AM',
        title: 'Customer asks for laptop recommendation',
        description: 'A customer on WhatsApp describes their needs: video editing, budget around $1,200, portable.',
        aiResponse: 'Hi Marcus! For video editing at that budget, I\'d recommend the MacBook Air M3 ($1,199) or the ASUS ProArt StudioBook ($1,149). The MacBook gives you better battery life and ecosystem, while the ASUS has a dedicated GPU for heavier renders. Both are in stock. Want to come test them side by side? I can reserve a demo station for you.',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'Trade-in evaluation assisted',
        description: 'Customer arrives for a phone trade-in. AI pulls current market values and generates an instant offer.',
        aiResponse: 'Trade-in assessment for iPhone 14 Pro (128GB, Space Black, Good condition): Current market value $420\u2013$480. I\'d recommend offering $440 cash or $510 in store credit. The customer\'s battery health is at 87%, which supports the "Good" rating. Offer generated and ready on the POS screen.',
        channel: 'system',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '11:45 AM',
        title: 'Warranty claim follow-up',
        description: 'A customer who bought a TV 8 months ago reports a dead pixel issue. AI checks warranty status and initiates the claim.',
        aiResponse: 'Hi Sandra, I\'ve looked into your Samsung 55" QN85B purchase from July 14th. You\'re covered under the manufacturer\'s 1-year warranty for dead pixels. I\'ve initiated a claim with Samsung \u2014 reference #SM-882441. They\'ll contact you within 48 hours to schedule a technician visit at no charge.',
        channel: 'email',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:00 PM',
        title: 'Facebook product question answered',
        description: 'Someone comments on your Facebook post asking if a gaming monitor is compatible with their PS5.',
        aiResponse: 'Great question, Derek! Yes, the ASUS VG28UQL1A is fully compatible with PS5 \u2014 it supports HDMI 2.1 for 4K at 120Hz gaming. It\'s one of our top-selling gaming monitors. We have 3 in stock at $549. Want me to set one aside for you?',
        channel: 'facebook',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:15 PM',
        title: 'Repair status update sent automatically',
        description: 'A laptop screen replacement is complete. AI notifies the customer with pickup details.',
        aiResponse: 'Hi Kevin! Great news \u2014 your Dell XPS 15 screen replacement is complete and tested. Everything looks perfect. You can pick it up anytime today before 8 PM or tomorrow 9 AM\u20138 PM. Total: $189 (parts + labor). We accept card, cash, or Apple Pay.',
        channel: 'sms',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:30 PM',
        title: 'New product launch post created',
        description: 'AI creates social media content for a newly arrived product, including specs comparison and pricing.',
        aiResponse: 'I\'ve created a launch post for the new Sony A7C II: a spec comparison carousel vs. Canon R8 and Nikon Z6 III, a short demo video script, and an Instagram story with "Now In Stock" sticker. All scheduled for peak engagement windows this week.',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '4:45 PM',
        title: 'Bulk order inquiry from business client',
        description: 'A local office manager emails asking for a quote on 15 laptops with specific configurations.',
        aiResponse: 'Hi Patricia, thank you for the inquiry! I\'ve prepared a bulk quote for 15x Lenovo ThinkPad L14 Gen 4 (i5, 16GB, 512GB SSD) at $849 each \u2014 that\'s $12,735 total with a 7% bulk discount applied. Includes 3-year on-site warranty. Delivery within 5\u20137 business days. I\'ve attached the formal quote as a PDF. Shall I schedule a call to finalize?',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '6:00 PM',
        title: 'Weekly review performance audit',
        description: 'AI analyzes this week\'s Google and Facebook reviews, identifies patterns, and suggests improvements.',
        aiResponse: 'This week: 8 new Google reviews (avg 4.6 stars). Positive themes: knowledgeable staff, fair pricing. One 3-star review mentioned long wait times on Saturday \u2014 I\'ve responded and flagged it. Suggestion: consider adding a Saturday afternoon staff member. Your overall rating is now 4.7 (up from 4.6 last month).',
        channel: 'system',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '7:30 PM',
        title: 'End-of-day financial summary',
        description: 'AI compiles daily revenue, margin analysis, and outstanding invoices.',
        aiResponse: 'Today\'s totals: $8,210 revenue across 38 transactions. Gross margin: 22.4%. Top category: laptops ($3,600). 2 trade-ins processed ($880 in credit issued). Outstanding B2B invoices: $4,200 (Patricia\'s quote pending). Tomorrow: 3 repairs queued, shipment of accessories arriving.',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'After-hours phone call intercepted',
        description: 'Customer calls asking if a specific GPU is in stock. AI answers the call with full inventory knowledge.',
        aiResponse: 'Thank you for calling TechHub Electronics! I can help you with that. We currently have 2 units of the RTX 4070 Ti Super in stock at $799. We\'re open tomorrow from 9 AM to 8 PM. Would you like me to reserve one for you? I\'ll just need your name and I\'ll hold it until noon tomorrow.',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Answers detailed spec questions across WhatsApp, Facebook, email, and phone with complete product knowledge and comparison data.',
      memory: 'Tracks every customer\'s purchase history, warranty dates, trade-in records, and device preferences for personalized service.',
      proactive: 'Morning briefings with repair queue, deliveries, and appointments. Alerts when high-demand items are running low.',
      bookings: 'Manages repair appointments, trade-in slots, and product demo reservations with automatic status updates.',
      leads: 'Captures interest from social media and website, qualifies business inquiries, and generates bulk quotes automatically.',
      revenue: 'Price-match alerts, bulk discount calculations, and trade-in value optimization to maximize both margins and customer satisfaction.',
      reputation: 'Monitors and responds to reviews highlighting product expertise, flags negative feedback about wait times or service gaps.',
      content: 'Creates product launch posts, spec comparison carousels, and unboxing content for new arrivals.',
      reporting: 'Daily revenue and margin reports, weekly category analysis, and monthly inventory turnover metrics.',
      browser: 'Scans competitor pricing daily, researches wholesale suppliers, and monitors stock availability on distributor sites.',
      voice: 'Answers after-hours calls with inventory info, reserve requests, and store hours.',
    },
    stats: {
      messagesPerDay: 85,
      bookingsPerWeek: 22,
      monthlySavings: 4800,
      responseTime: '< 1 min',
    },
    recommendedTier: 'executive',
    recommendationReason: 'Electronics retail demands real-time price monitoring, deep product knowledge, and after-hours support. The Executive tier adds competitor browsing, voice call handling, and autonomous supplier research.',
  },

  /* ------------------------------------------------------------------ */
  /* 3. E-COMMERCE / ONLINE STORE                                        */
  /* ------------------------------------------------------------------ */
  {
    id: 'ecommerce',
    label: 'E-commerce / Online Store',
    emoji: '\u{1F6CD}\u{FE0F}',
    category: 'Retail & E-Commerce',
    tagline: 'Every cart recovered, every question answered, every review managed \u2014 24/7.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Overnight order digest',
        description: 'AI compiles all orders placed overnight, flags any issues (payment failures, out-of-stock items, suspicious orders).',
        aiResponse: 'Overnight summary: 23 new orders ($3,870 total). 2 payment failures (retries scheduled). 1 order flagged for review \u2014 different billing/shipping addresses + high-value item ($489). All other orders are ready for fulfillment. Top seller overnight: Organic Cotton Tote (7 units).',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:00 AM',
        title: 'Abandoned cart recovery campaign',
        description: 'AI identifies 18 carts abandoned in the last 24 hours and sends personalized recovery emails with dynamic incentives.',
        aiResponse: 'I\'ve sent 18 abandoned cart emails. Segmented by value: 6 high-value carts ($150+) got free shipping offers, 8 mid-range got 10% discount codes, and 4 first-time visitors got a "Welcome 15%" code. Last week\'s recovery rate was 12.3% \u2014 targeting 14% this week.',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 2 },
      },
      {
        time: '8:30 AM',
        title: 'Customer asks about order status',
        description: 'A customer messages on WhatsApp asking where their package is. AI pulls tracking info instantly.',
        aiResponse: 'Hi Natalie! Your order #EC-4892 shipped yesterday via USPS Priority. Tracking: 9400111899223847561. It\'s currently in transit from our warehouse in Austin and estimated to arrive Thursday by 6 PM. I\'ll send you an update when it\'s out for delivery!',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:45 AM',
        title: 'Product Q&A handled on Instagram',
        description: 'Multiple DMs asking about a viral product \u2014 sizing, materials, shipping time.',
        aiResponse: 'Hi! Our Cloud Sneakers run half a size large \u2014 I\'d recommend going down half a size from your usual. They\'re made with recycled mesh upper and memory foam insole. Ships within 24 hours, delivery in 3\u20135 business days. We have all sizes in white, black, and sage green. Want to grab a pair?',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 3 },
      },
      {
        time: '11:00 AM',
        title: 'Weekly email newsletter drafted',
        description: 'AI creates the weekly newsletter featuring new arrivals, bestsellers, and a curated collection.',
        aiResponse: 'Newsletter draft ready: "This Week\'s Edit" featuring 3 new arrivals, top 5 bestsellers with social proof ("542 sold this month"), and a curated "Weekend Essentials" collection. Subject line A/B test: "Your Weekend Edit Is Here" vs "Selling Fast \u2014 Don\'t Miss These." Scheduled for Thursday 10 AM (your highest open-rate window).',
        channel: 'system',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '12:30 PM',
        title: 'Return and exchange processed',
        description: 'Customer wants to exchange a jacket for a different color. AI handles the entire process.',
        aiResponse: 'Hi Alex! No problem at all. I\'ve created a prepaid return label for the navy jacket (attached to this email). Once we receive it, I\'ll immediately ship the olive version in the same size. Your exchange reference is #RET-1147. You won\'t be charged again \u2014 the swap is free. Is there anything else I can help with?',
        channel: 'email',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '2:00 PM',
        title: 'Influencer collaboration managed',
        description: 'An influencer DMs about a potential collab. AI qualifies them and responds with the partnership process.',
        aiResponse: 'Hi @SarahStyles! Thanks for reaching out. I checked out your profile \u2014 love your aesthetic! You have 45K engaged followers with a 4.2% engagement rate, which is great. Here\'s how our collab program works: we send you 3 pieces of your choice, you create 2 posts + 3 stories. We also offer a unique 15% discount code for your audience with 10% commission on sales. Want me to send over the full partnership brief?',
        channel: 'instagram',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:15 PM',
        title: 'Inventory alert and auto-reorder',
        description: 'Bestselling item hits reorder threshold. AI drafts a purchase order to the supplier.',
        aiResponse: 'Alert: Cloud Sneakers (White, sizes 7\u201310) are below reorder point \u2014 only 8 units left across sizes. At current velocity (6/day), you\'ll be out in 32 hours. I\'ve drafted a PO for 200 units to your manufacturer at $22/unit. Lead time: 12 days. Approve to send?',
        channel: 'system',
        capability: 'browser',
        tier: 'executive',
        stat: { key: 'savings', increment: 500 },
      },
      {
        time: '4:30 PM',
        title: 'Negative review response and recovery',
        description: 'A 2-star review complains about shipping delay. AI responds publicly and reaches out privately to resolve.',
        aiResponse: 'Public response: "Hi Jordan, I\'m truly sorry about the delay. That\'s not the experience we want for you. I\'m looking into this personally and will reach out directly." Private DM: "Hi Jordan, I\'ve tracked your order and it looks like there was a carrier delay in the Memphis hub. I\'m sending a replacement via express shipping today, plus a $20 credit for the inconvenience. Again, deeply sorry."',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
        stat: { key: 'savings', increment: 100 },
      },
      {
        time: '6:00 PM',
        title: 'Flash sale performance tracked',
        description: 'A 4-hour flash sale ends. AI compiles real-time results and ROI analysis.',
        aiResponse: 'Flash sale results: $8,420 revenue in 4 hours (142 orders). Conversion rate: 6.8% (vs 2.1% baseline). Email drove 52% of traffic, Instagram 31%, direct 17%. Best performer: Cloud Sneakers bundle ($89, 47 units). Customer acquisition cost: $4.20. Net margin after discounts: 38%.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'savings', increment: 800 },
      },
      {
        time: '8:00 PM',
        title: 'International customer helped in Spanish',
        description: 'A customer from Mexico messages in Spanish asking about international shipping and customs.',
        aiResponse: 'Hola Maria! Si hacemos env\u00edos a M\u00e9xico. El costo es $18 USD por env\u00edo est\u00e1ndar (10\u201314 d\u00edas) o $35 por express (4\u20136 d\u00edas). Los impuestos de importaci\u00f3n son responsabilidad del comprador, generalmente 16% IVA. Aceptamos pago en USD. \u00bfTe gustar\u00eda hacer tu pedido?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 PM',
        title: 'Daily P&L and marketing spend report',
        description: 'AI generates a complete daily profit and loss statement with ad spend breakdown.',
        aiResponse: 'Daily P&L: Revenue $14,290 | COGS $5,716 | Gross profit $8,574 (60%). Ad spend: $420 (Meta $280, Google $140). ROAS: 34x. Shipping costs: $890. Net operating profit: $7,264. Compared to same day last week: +18% revenue, +22% profit. Top acquisition channel: Instagram (38% of new customers).',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'savings', increment: 350 },
      },
    ],
    capabilityExamples: {
      communication: 'Handles product questions, order status, returns, and multilingual support across all channels 24/7.',
      memory: 'Tracks every customer\'s order history, size preferences, and browsing behavior for personalized recommendations.',
      proactive: 'Overnight order digests, stock alerts, payment failure notifications, and suspicious order flagging.',
      bookings: 'Manages return pickups, delivery scheduling, and influencer collaboration timelines.',
      leads: 'Recovers abandoned carts with personalized incentives, qualifies influencer partnerships, and nurtures first-time buyers.',
      revenue: 'Dynamic pricing, flash sale execution, and lapsed customer re-engagement campaigns.',
      reputation: 'Responds to reviews across Google, Trustpilot, and social media. Resolves complaints privately while responding publicly.',
      content: 'Creates email newsletters, social media campaigns, product descriptions, and ad copy with A/B testing.',
      reporting: 'Real-time sales dashboards, daily P&L, ad spend ROI, and customer acquisition cost tracking.',
      browser: 'Monitors competitor pricing, manages supplier portals, and places restock orders when inventory hits thresholds.',
    },
    stats: {
      messagesPerDay: 120,
      bookingsPerWeek: 35,
      monthlySavings: 8500,
      responseTime: '< 30 sec',
    },
    recommendedTier: 'manager',
    recommendationReason: 'E-commerce runs 24/7 and lives on content, reviews, and cart recovery. The Manager tier handles the marketing engine, reputation, and revenue analytics that drive online growth.',
  },

  /* ------------------------------------------------------------------ */
  /* 4. FLORIST                                                          */
  /* ------------------------------------------------------------------ */
  {
    id: 'florist',
    label: 'Florist',
    emoji: '\u{1F338}',
    category: 'Retail & E-Commerce',
    tagline: 'Every arrangement perfect, every delivery on time, every occasion remembered.',
    dayEvents: [
      {
        time: '6:00 AM',
        title: 'Fresh inventory and delivery schedule',
        description: 'AI reviews today\'s flower shipment from the wholesaler and maps out the delivery route for 8 arrangements.',
        aiResponse: 'Good morning! Your Dutch auction shipment arrives at 7 AM: 200 roses (red, pink, white), 80 peonies, 60 ranunculus, and 40 eucalyptus bunches. Today\'s deliveries: 8 arrangements mapped on an optimized route \u2014 first stop at 9:30 AM (birthday bouquet to 245 Oak St), last at 4 PM (corporate lobby at Meridian Tower).',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '7:30 AM',
        title: 'Wedding consultation request',
        description: 'A bride-to-be fills out the inquiry form on your website for a September wedding. AI responds with availability and next steps.',
        aiResponse: 'Hi Emily! Congratulations on your engagement! I\'d love to help with your September 20th wedding at The Oaks Estate. We\'re available that date! For a wedding of 120 guests with the garden aesthetic you described, I\'d estimate $3,500\u2013$5,200 for ceremony + reception florals. Let\'s schedule a free consultation \u2014 are you available this Saturday at 11 AM or next Tuesday at 2 PM?',
        channel: 'email',
        capability: 'leads',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '8:45 AM',
        title: 'Same-day delivery order via WhatsApp',
        description: 'A customer wants to send flowers to their mom for her birthday today. Needs it delivered by noon.',
        aiResponse: 'Happy birthday to your mom! I can absolutely arrange same-day delivery by noon. Here are three options: Classic Rose Bouquet (24 red roses, $75), Garden Mix (seasonal flowers in pinks and whites, $65), or Luxury Peony Arrangement (vase included, $110). All come with a complimentary card \u2014 what would you like it to say?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:00 AM',
        title: 'Anniversary reminder sent to past customer',
        description: 'AI remembers that a customer ordered anniversary flowers last year and sends a thoughtful reminder.',
        aiResponse: 'Hi David! Just a heads up \u2014 your wedding anniversary is coming up next Friday (March 20th). Last year you sent Sarah a stunning arrangement of white peonies and pink garden roses, and she absolutely loved them. Shall I create something similar this year, or would you like to try something new? I can also include her favorite chocolates for $25 extra.',
        channel: 'sms',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '11:30 AM',
        title: 'Corporate account weekly standing order',
        description: 'AI prepares the weekly lobby arrangement for a corporate client and confirms delivery details.',
        aiResponse: 'Hi Laura! Your weekly lobby arrangement for Meridian Tower is ready \u2014 this week I\'ve done a spring-inspired design with white hydrangeas, green viburnum, and trailing ivy per your seasonal preference. Delivery scheduled for 2 PM today. Your monthly invoice ($680, 4 arrangements) will be sent Friday. Everything look good?',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '12:15 PM',
        title: 'Instagram story: behind-the-scenes arranging',
        description: 'AI posts a time-lapse story of a wedding centerpiece being created, with trending audio and hashtags.',
        aiResponse: 'Posted! Behind-the-scenes story of the bridal centerpiece build \u2014 time-lapse from stems to stunning. Used trending audio "Flowers" by Miley Cyrus. Added hashtags: #WeddingFlowers #FloristLife #BridalBouquet #SpringWedding. Also shared to Reels for broader reach. Last BTS reel got 2,400 views.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '1:30 PM',
        title: 'Delivery confirmation with photo',
        description: 'Driver delivers the birthday bouquet. AI sends the customer a photo confirmation.',
        aiResponse: 'Great news! Your mom\'s birthday bouquet has been delivered to 245 Oak Street at 12:47 PM. Here\'s a photo of the arrangement at her door. The delivery was received by "Linda" who said she\'d make sure your mom gets it. Happy birthday to her! Would you like to set up automatic anniversary or birthday reminders for other loved ones?',
        channel: 'whatsapp',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Mother\'s Day pre-order campaign launched',
        description: 'AI creates and sends an early-bird pre-order campaign for Mother\'s Day, still 6 weeks away.',
        aiResponse: 'Mother\'s Day campaign launched! Email blast sent to 1,240 past customers: "Pre-order by April 15th and save 15%." 3 curated packages: Classic ($55), Deluxe ($85), Showstopper ($135). Added an "Add Delivery Date" feature so orders auto-schedule for May 11th. Also posted the collection on Instagram and Facebook.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 450 },
      },
      {
        time: '4:00 PM',
        title: 'Sympathy arrangement request handled with care',
        description: 'A customer calls, emotional, needing funeral flowers delivered tomorrow. AI handles with empathy and care.',
        aiResponse: 'I\'m so sorry for your loss. I\'ll take care of everything. For the service tomorrow at St. Mary\'s at 10 AM, I\'d suggest a standing spray arrangement in white lilies and roses \u2014 it\'s elegant and peaceful. We offer that at $180 with a ribbon and personalized message. I\'ll have it delivered by 9 AM. What would you like the card to say? Take your time.',
        channel: 'phone',
        capability: 'voice',
        tier: 'executive',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '5:30 PM',
        title: 'Google review responded to',
        description: 'A happy wedding client left a glowing review with photos. AI responds and thanks them.',
        aiResponse: 'Thank you so much, Emily and James! It was an absolute honor to be part of your wedding day. Your garden ceremony was breathtaking, and we\'re so glad the florals matched your vision perfectly. Wishing you a lifetime of happiness! And thank you for the gorgeous photos \u2014 they made our day.',
        channel: 'google',
        capability: 'reputation',
        tier: 'manager',
      },
      {
        time: '7:00 PM',
        title: 'End-of-day wrap-up and waste tracking',
        description: 'AI summarizes the day and logs any flowers that need to be used tomorrow or composted.',
        aiResponse: 'Today\'s totals: $1,890 revenue (12 arrangements, 3 walk-ins). All 8 deliveries completed successfully. Flower waste: minimal \u2014 15 roses and 8 carnations past peak, will incorporate into $25 "surprise bouquets" for tomorrow\'s walk-in display. Wedding consultation booked for Saturday. Mother\'s Day pre-orders: 14 already!',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:00 PM',
        title: 'Late Valentine\'s Day style planning',
        description: 'AI starts analyzing last year\'s Valentine\'s data to optimize next year\'s ordering and staffing.',
        aiResponse: 'Valentine\'s analysis started. Last year: $12,400 in revenue (highest day), 89 arrangements delivered. Pain points: ran out of red roses by 11 AM, delivery backed up 2 hours. Recommendations for next year: order 40% more red roses, hire 2 temp delivery drivers, close walk-ins after 2 PM to focus on deliveries. Building a full playbook now.',
        channel: 'system',
        capability: 'multiagent',
        tier: 'executive',
      },
    ],
    capabilityExamples: {
      communication: 'Handles flower orders with empathy and detail \u2014 from joyful birthdays to sensitive sympathy arrangements.',
      memory: 'Remembers anniversaries, birthdays, favorite flowers, past orders, and card messages for every customer.',
      proactive: 'Morning delivery route optimization, inventory checks, and occasion-based reminders for repeat customers.',
      bookings: 'Manages wedding consultations, corporate standing orders, delivery scheduling, and event timelines.',
      leads: 'Captures wedding inquiries, qualifies event leads, and follows up with proposals automatically.',
      revenue: 'Seasonal pre-order campaigns, surprise bouquet upsells, and corporate account invoicing.',
      reputation: 'Responds to reviews with genuine warmth, requests reviews after every delivery, tracks rating trends.',
      content: 'Creates behind-the-scenes arranging videos, seasonal collection showcases, and wedding portfolio posts.',
      reporting: 'Daily sales and waste tracking, seasonal demand forecasting, and event profitability analysis.',
      voice: 'Handles emotional calls with empathy \u2014 especially sympathy orders \u2014 and takes complex custom requests by phone.',
      multiagent: 'Analyzes historical data across peak seasons to optimize ordering, staffing, and delivery logistics.',
    },
    stats: {
      messagesPerDay: 45,
      bookingsPerWeek: 30,
      monthlySavings: 2800,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Florists depend on emotional connection, seasonal marketing, and reputation. The Manager tier handles occasion reminders, content that showcases artistry, and review management that builds trust.',
  },

  /* ------------------------------------------------------------------ */
  /* 5. BOOKSTORE                                                        */
  /* ------------------------------------------------------------------ */
  {
    id: 'bookstore',
    label: 'Bookstore',
    emoji: '\u{1F4DA}',
    category: 'Retail & E-Commerce',
    tagline: 'Every reader matched, every event packed, every recommendation on point.',
    dayEvents: [
      {
        time: '6:30 AM',
        title: 'New release and bestseller digest',
        description: 'AI compiles today\'s new releases, trending titles on BookTok, and upcoming author events in the region.',
        aiResponse: 'Morning digest: 3 notable releases today \u2014 new Colleen Hoover drops at midnight (pre-orders: 34), a debut thriller from local author Maria Santos, and the paperback edition of last year\'s Booker winner. BookTok trending: "Intermezzo" by Sally Rooney is surging again. You have 6 copies in stock.',
        channel: 'system',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '8:00 AM',
        title: 'Morning briefing with event prep',
        description: 'Today\'s agenda: author signing at 6 PM, book club discussion at 2 PM, and a school field trip at 10 AM.',
        aiResponse: 'Good morning! Big day: School field trip (3rd graders, 25 kids) at 10 AM \u2014 I\'ve prepared a reading nook with age-appropriate picks and a 10% educator discount code. Book club at 2 PM discussing "Demon Copperhead" (8 RSVPs). Author signing at 6 PM \u2014 Maria Santos (45 RSVPs, 60 chairs set up). Coffee bar stocked and ready.',
        channel: 'whatsapp',
        capability: 'proactive',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '9:15 AM',
        title: 'Customer asks for recommendation',
        description: 'A regular customer messages asking for a book similar to one they loved. AI uses their reading history.',
        aiResponse: 'Hi Claire! Since you loved "The Seven Husbands of Evelyn Hugo," I think you\'d absolutely devour "Malibu Rising" by the same author, or "The Great Alone" by Kristin Hannah for that epic emotional sweep. If you\'re in the mood for something more literary, try "Circe" by Madeline Miller. All three are in stock \u2014 want me to hold any for you?',
        channel: 'whatsapp',
        capability: 'memory',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '10:30 AM',
        title: 'School field trip welcome and activity',
        description: 'AI helps manage the field trip: sends welcome materials to the teacher, tracks which kids bought books, and processes the group discount.',
        aiResponse: 'Welcome, Ms. Patterson\'s class! I\'ve sent you the digital scavenger hunt worksheet \u2014 kids find books by genre clues. Each student gets a $5 voucher toward any book. The 10% educator bulk discount applies if the school orders 20+ copies. Today\'s group story time is in the children\'s corner at 10:45 AM with our picture book selection.',
        channel: 'email',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '12:00 PM',
        title: 'Online order with gift wrapping',
        description: 'Customer places an online order for a birthday gift and requests wrapping and a handwritten note.',
        aiResponse: 'Hi Thomas! Your order is confirmed: "Lessons in Chemistry" (hardcover, $28) with our signature gift wrapping in navy and gold. Your card message: "Happy Birthday, Grandma! Here\'s to another year of great reads. Love, Tommy." We\'ll ship it today for delivery by Thursday. Total with gift wrap: $34. Anything else?',
        channel: 'instagram',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '1:30 PM',
        title: 'Book club prep and discussion guide',
        description: 'AI sends the book club members a reminder with discussion questions and a special offer.',
        aiResponse: 'Reminder: Book Club meets today at 2 PM! We\'re discussing "Demon Copperhead" by Barbara Kingsolver. I\'ve attached 8 discussion questions covering themes of Appalachian identity and modern parallels to Dickens. Book club members get 15% off their next purchase today. Refreshments will be served. See you there!',
        channel: 'sms',
        capability: 'communication',
        tier: 'operator',
        stat: { key: 'messages', increment: 1 },
      },
      {
        time: '3:00 PM',
        title: 'Staff pick of the week posted',
        description: 'AI creates a "Staff Pick" social media post featuring a team member\'s favorite current read.',
        aiResponse: 'Posted! This week\'s Staff Pick from Jake: "Tomorrow, and Tomorrow, and Tomorrow" by Gabrielle Zevin \u2014 "If you\'ve ever loved video games, friendship, or stories about creative partnership, this will wreck you (in the best way)." Carousel with cover photo, quote graphic, and shelf location. Scheduled cross-post to Facebook at 5 PM.',
        channel: 'instagram',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '4:00 PM',
        title: 'Publisher rep meeting prep',
        description: 'AI compiles sell-through data and wish list for tomorrow\'s meeting with the Penguin Random House rep.',
        aiResponse: 'Prep for tomorrow\'s PRH meeting: Your top 10 PRH titles this quarter with sell-through rates. Bestseller: "Intermezzo" (92% sell-through). Underperformers: 2 titles at <30%. Wish list: 3 upcoming titles for signed editions, request for co-op marketing funds for the summer reading program. I\'ve compiled it all into a one-page brief.',
        channel: 'system',
        capability: 'reporting',
        tier: 'manager',
      },
      {
        time: '5:30 PM',
        title: 'Author signing event prep \u2014 final check',
        description: 'AI sends final reminders to RSVPs, confirms author logistics, and prepares the social media live stream.',
        aiResponse: 'Event check: 45 RSVPs confirmed, 60 chairs set, PA system tested. Author Maria Santos confirmed arrival at 5:45 PM. Her 50 signed copies are stacked at the event table. I\'ve sent a final reminder to all RSVPs with parking info. Instagram Live starts at 6:15 PM \u2014 I\'ll handle the stream intro and Q&A prompts.',
        channel: 'system',
        capability: 'bookings',
        tier: 'operator',
        stat: { key: 'bookings', increment: 1 },
      },
      {
        time: '7:00 PM',
        title: 'Post-event social media coverage',
        description: 'AI creates a recap post from the author signing with photos and highlights.',
        aiResponse: 'Event recap posted! Carousel with 6 photos: Maria Santos reading, audience reaction, signed books, the Q&A moment, a fan selfie (with permission), and the packed house shot. Caption highlights the 43 books sold and announces Maria\'s next book date. Tagged the author, publisher, and local press. Already at 180 likes.',
        channel: 'facebook',
        capability: 'content',
        tier: 'manager',
      },
      {
        time: '8:30 PM',
        title: 'Lapsed customer re-engagement',
        description: 'AI identifies 35 customers who haven\'t visited in 90+ days and sends a personalized "We miss you" campaign.',
        aiResponse: 'Re-engagement batch sent to 35 customers. Each email includes their last purchase and a "Because you loved [X], you\'ll love [Y]" recommendation. Included a $5 "Welcome Back" coupon valid for 2 weeks. Last quarter\'s re-engagement campaign brought back 22% of lapsed customers.',
        channel: 'email',
        capability: 'revenue',
        tier: 'manager',
        stat: { key: 'savings', increment: 280 },
      },
      {
        time: '9:30 PM',
        title: 'End-of-day summary and inventory flag',
        description: 'AI wraps up the day with sales data and flags titles that need reordering.',
        aiResponse: 'Today\'s wrap-up: $3,240 revenue (highest this month!). Author event drove 43 book sales alone. School visit: 18 books sold + $50 in vouchers redeemed. Reorder alert: "Intermezzo" down to 2 copies, new Colleen Hoover down to 5 (from 34 pre-orders \u2014 all fulfilled). Book club generated $120 in add-on sales. Great day!',
        channel: 'whatsapp',
        capability: 'reporting',
        tier: 'manager',
        stat: { key: 'messages', increment: 1 },
      },
    ],
    capabilityExamples: {
      communication: 'Provides personalized book recommendations, handles gift orders with custom messages, and answers inventory questions.',
      memory: 'Tracks every customer\'s reading history, genre preferences, book club participation, and wish lists.',
      proactive: 'Morning digests with new releases, trending titles, and event prep. Alerts when popular titles run low.',
      bookings: 'Manages author signings, book club meetings, school visits, story times, and reading group reservations.',
      leads: 'Captures interest from social media, converts event attendees into regulars, and builds email lists from in-store interactions.',
      revenue: 'Re-engages lapsed readers, runs seasonal campaigns (summer reading, holiday gifts), and manages gift card programs.',
      reputation: 'Responds to reviews highlighting the community atmosphere, curated selection, and knowledgeable staff.',
      content: 'Creates staff picks, event recaps, BookTok-style reels, and themed reading list carousels.',
      reporting: 'Daily sales summaries, sell-through analysis by publisher, event ROI tracking, and seasonal trend reports.',
    },
    stats: {
      messagesPerDay: 40,
      bookingsPerWeek: 12,
      monthlySavings: 2100,
      responseTime: '< 3 min',
    },
    recommendedTier: 'manager',
    recommendationReason: 'Bookstores are community hubs. The Manager tier manages events, content that drives foot traffic, reputation management, and the revenue campaigns that keep readers coming back.',
  },
];
